### ISSUE TITLE
Visibility of the examples is poor

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#133]
### Expected behavior

The examples should be more visible in the readme

**edit:**

Maybe change the link https://github.com/cprogrammer1994/ModernGL/tree/master/examples to https://github.com/cprogrammer1994/ModernGL/tree/master/examples#examples (target the readme)

**Comment by Korijn** [comment]
Can I also recommend to refer to examples from the API docs. E.g.on the page where the Texture class is described, link to a few examples that showcase its usage.
