### ISSUE TITLE
Add numpy record array support

### ISSUE THREAD

**Issue by NeilGirdhar** [moderngl/moderngl#204]
It would be nice to automatically calculate `VertexArray.bind`'s `offset` and `stride` from a `numpy` record array given a `path`.   E.g., given

```
dtype = np.dtype([('key', np.float64),
                  ('time', np.float32),
                  ('value', np.int)])
a = np.zeros(100, dtype=dtype)
```
we can calculate offset and strides for the path`['time']`  (I think 8 and 20).

We can fold in [my code from here](https://github.com/NeilGirdhar/glx/blob/master/glx/shader_program/bound_attribute.py).

**Comment by cprogrammer1994** [comment]
Inhomogenous dtypes should be supported. I really like the idea.
