### ISSUE TITLE
Expose glBlendEquation?

### ISSUE THREAD

**Issue by NeilGirdhar** [moderngl/moderngl#208]
How do I port this to `moderngl`?
```
gl.glBlendEquationi(framebuffer, gl.GL_FUNC_ADD)
gl.glBlendFunc(gl.GL_SRC_ALPHA, gl.GL_ONE_MINUS_SRC_ALPHA)
gl.glEnable(gl.GL_BLEND)
```

**Comment by cprogrammer1994** [comment]
`glBlendEquationi` and `glBlendFunc` should be exposed.
Can you also describe a use case / example where these settings are used?

**Comment by NeilGirdhar** [comment]
I use them here https://github.com/NeilGirdhar/glx/blob/master/demonstration/text.py.  Feel free to try that program out; it should display some text.  I am trying to port this to ModernGL.

**Comment by cprogrammer1994** [comment]
We can implement this in `5.x` too. I had no time to finish my experiments on this topic.

Currently we have `Context.blend_func`.

**Comment by mduser** [comment]
Will there be any progress in that in the near future?

**Comment by cprogrammer1994** [comment]
Yes it will be part of the next major version.

There is a prototype that allows the "Scope" object to have `blending=...`.
The context can create blending objects.

Blending objects support:

- glBlendFunc
- glBlendFunci
- glBlendFuncSeparate
- glBlendFuncSeparatei

- glBlendEquation
- glBlendEquationi
- glBlendEquationSeparate
- glBlendEquationSeparatei

The default blending (currently hardcoded + configurable from context) will be provided by a blending object too.

**Comment by cprogrammer1994** [comment]
I am really happy finally finding a good way supporting blending parameters.

Since I already have a working prototype I am closing it...

Thank you for the feature request.

**Comment by einarf** [comment]
FYI : I ninjaed in `glBlendFuncSeparate` and `glBlendEquationSeparate` in 5.5.4.
