### ISSUE TITLE
The buffer and vertex array design might need to be examined

### ISSUE THREAD

**Issue by NeilGirdhar** [moderngl/moderngl#216]
I noticed that the code works like this:
```
        self.vbo = self.ctx.buffer(vertices.astype('f4').tobytes())
        self.ibo = self.ctx.buffer(indecies.astype('i4').tobytes())

        vao_content = [
            # 2 floats are assigned to the 'in' variable named 'in_vert' in the shader code
            (self.vbo, '2f', 'in_vert')
        ]

        self.vao = self.ctx.vertex_array(self.prog, vao_content, self.ibo)
```
There are a number of problems.  First, `buffer` always allocates *and* sends the buffer.  It's more efficient to create the buffer and specify its vertex arrays apart from the draw code.  [Also, you want to interleave the data where possible for efficiency's sake. ](https://stackoverflow.com/questions/18853713/does-interleaving-in-vbos-speed-up-performance-when-using-vaos)  Finally, you should be able to send the data without making a copy using `vertices.buffer`.

You want something like
```
dtype = [('vertices', 'f4'), ('indices', 'i4')]
buffer = context.declare_buffer()
# Then declare the vertex arrays.
```
Also, declare your data
```
data = np.array(100, dtype=dtype)
other_data = np.array(100, dtype=dtype)
```
At every draw time, you would bind the buffer, you might bind more vertex arrays, and then you would pass the data in using `data.buffer` and `data.nbytes` (or `other_data`, etc.) to `glBufferData`.

**Comment by NeilGirdhar** [comment]
Okay, that's pretty close to what I have.  Why not pass a record dtype in for the second argument?

**Comment by einarf** [comment]
I'm guessing because the format string can contain other things as well such as padding info and instance info.

Skipping ``in_normal`` from the first example:

```python
(interleaved_vbo, '3f 3x4 2f`, ['in_position', 'in_uv0'])
```

Per instance data
 
```python
(interleaved_vbo, '3f/i', 'in_pos_distort')
```

**Comment by NeilGirdhar** [comment]
The numpy dtype can also contain padding information.  I don't see the point of having a string representation of records when there is already a structured Python type for that.

**Comment by cprogrammer1994** [comment]
> It's more efficient to create the buffer and specify its vertex arrays apart from the draw code

It is possible that the I want to draw using the same buffer with a different layout.

Let say I have a buffer with some attribs: (x, y, z, normal x, normal y, normal z, texture u, texture v, texture w)

I want to render all of them.
I want to render using x, y, z, and texture u, texture v.
I want to render with (x, y) passed to an attribute and z passed to a different attribute.

To extend @einarf 's comment:

we can also pass x, y to `in_position` and expect the z component to be `0.0`

```
(interleaved_vbo, '2f 4x4 2f`, ['in_position', 'in_uv0'])
                   ^^^^^^
```

On the experimental branch it is possible to map buffers with a dtype (when numpy is installed)

**Comment by NeilGirdhar** [comment]
> It is possible that the I want to draw using the same buffer with a different layout.

Yes, I understand that, but it's also possible to want to draw a different buffer with the same layout.  Or, the same buffer multiple times (each time with the same layout).  This is why you should be able to specify the vertex arrays and buffer once, and then bind and send the buffer at draw time.

Also, how are you setting array attributes?

> On the experimental branch it is possible to map buffers with a dtype (when numpy is installed)

Awesome!

**Comment by cprogrammer1994** [comment]
> Also, how are you setting array attributes?

There used to be some tests covering this.

ModernGL thinks vaos change rarely (or never), when you want to render the same buffer multiple times, it expects to have multiple vaos created and bound to that buffer. (vaos are "cheap", you can have a lot of them)

ModernGL thinks buffers are holding binary data, the layout of the buffer is not something the buffer must know. However every ModernGL object have a slot called **extra**, this field can contain user defined objects.

**Comment by NeilGirdhar** [comment]
> ModernGL thinks vaos change rarely (or never), when you want to render the same buffer multiple times, it expects to have multiple vaos created and bound to that buffer. (vaos are "cheap", you can have a lot of them)

I don't understand why on the one hand you're replacing `isinstance(…)` checks with `type(…) is` checks to save iteration over `__mro__` and on the other hand you're forcing recreation of vertex arrays every single time draw is called.  Creation of vertex arrays is not cheap (compared with `isinstance`).  It requires calling into ModernGL, parsing your vertex specification, which can be a complicated string, and then calling the OpenGL driver.  And it's totally unnecessary.  I don't think this is good design.

> ModernGL thinks buffers are holding binary data, the layout of the buffer is not something the buffer must know.

I agree with you there, and that's not what I'm proposing.

I think ModernGL has some really good ideas, but in this case, `glx` has a cleaner [buffer description interface](https://github.com/NeilGirdhar/glx/tree/master/glx/shader_program).

**Comment by cprogrammer1994** [comment]
For two different types of drawing you have to create 2 vaos, not 2 / frame.
Any `type()` check in python code can be replaced with an `isinstance` but this will not help the C++ implementation to accept the subclasses. It will still report a type mismatch.

We can make a prototype of what you want and compare it to the current solution.

**Comment by NeilGirdhar** [comment]
> We can make a prototype of what you want and compare it to the current solution.

Sounds good.  I will try to come up with a demo of `glx`'s interface to compare.

> For two different types of drawing you have to create 2 vaos, not 2 / frame.

The problem is if the buffer data is different every frame, the current implementation of ModernGL forces you to create a new buffer index every frame, and therefore bind new vertex arrays every frame.

> Any type() check in python code can be replaced with an isinstance but this will not help the C++ implementation to accept the subclasses.

Well, you can just call [PyObject_IsInstance](https://docs.python.org/3/c-api/object.html#c.PyObject_IsInstance) in C++.

**Comment by einarf** [comment]
> The problem is if the buffer data is different every frame, the current implementation of ModernGL forces you to create a new buffer index every frame, and therefore bind new vertex arrays every frame.

You can use ``Buffer.write(..)`` to change the buffer data. That's what I do in my text writer at least. It certainly don't happen every frame, but there is no need to change the vao.

Maybe your case is just different and I don't understand it. Got a more specific example?

**Comment by NeilGirdhar** [comment]
I draw graphs every frame.  The graph data is produced on another thread by a simulation.  There is an every increasing amount of data, so I can't get away with `glBufferSubData` calls.  I need to `BufferData`.  However, most of the vertex arrays should only be created once.

Also, there is no need to have data at the time that I set up the vertex arrays.  I should be able to `BindBuffer`, and set up the vertex arrays at initialization time.  If some uniforms changes, I should be able to update those too.  All of this should happen without actually having any data.

Only at draw time should I have to call `BufferData`.
