### ISSUE TITLE
Api for writing to image2D texture in compute shader

### ISSUE THREAD

**Issue by pocdn** [moderngl/moderngl#220]
**A simple use-case of the new feature**

In a compute shader it is often necessary to be able to write to a texture via an image2D uniform. A compute shader example for modifying an image2D texture is

```glsl
#version 430
layout (local_size_x = 16, local_size_y = 16) in;
layout(rg32f,location=0) writeonly uniform image2D destTex;
uniform float time;
void main() {
    ivec2 ij = ivec2(gl_GlobalInvocationID.xy);
    float localCoef = length(vec2(ivec2(gl_LocalInvocationID.xy)-8)/8.0);
    float globalCoef = sin(float(gl_WorkGroupID.x+gl_WorkGroupID.y)*0.1 + time)*0.5;
    imageStore(destTex, ij, vec4(1.0-globalCoef*localCoef, 0.0, 0.0, 0.0));
}
```

Note that this requires on initialization an explicit call to bind the image texture in addition to the setting of it's uniform to 0

> glGenTextures(1, &texHandle);
> glBindImageTexture(0, texHandle, 0, GL_FALSE, 0, GL_WRITE_ONLY, GL_R32F);
> glUniform1i(glGetUniformLocation(progHandle, "destTex"), 0);

when trying the equivalent of glUniform1i

> self.destTex= self.computeprog['destTex']
> self.destTex.value = 0

the getter is works fine but an error is thrown on the setter 

```
  File "foo.py", line 204, in foo_execute()
    self.destTex.value = 0
  File "C:/msys64/mingw64/lib/python3.6/site-packages\moderngl\program_members\uniform.py", line 163, in value
    self.mglo.value = value
mgl.Error: cannot detect uniform type
```

This seems to be a bug where a uniform image2D type is not correctly handled when trying to set the uniform integer.

**Describe the solution you'd like**

Assuming the uniform image2D is corrected, there seems to be a larger missing API piece. Presently, the moderngl interface seems to be missing a way to do the equivalent of
> glBindImageTexture(0, texHandle, 0, GL_FALSE, 0, GL_WRITE_ONLY, GL_R32F);

How does one bind the image texture to be writeonly with a format of GL_R32F? Note, this is required in addition to the standard texture glBindTexture(GL_TEXTURE_2D, texHandle). For example, when one inits the texture a complete working c-code is

```cpp
GLuint genTexture() {
    GLuint texHandle;
    glGenTextures(1, &texHandle);

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, texHandle);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_R32F, 512, 512, 0, GL_RED, GL_FLOAT, NULL);

    // Because we're also using this tex as an image (in order to write to it),
    // we bind it to an image unit as well
    glBindImageTexture(0, texHandle, 0, GL_FALSE, 0, GL_WRITE_ONLY, GL_R32F);
    return texHandle;
}
```

The goal is to  have an animated texture with compute shader like
![goal_mixed_vertexshader_computeshader](https://user-images.githubusercontent.com/6920644/43265288-2c877e4c-909d-11e8-9b75-93bc97da2e43.png)

Here's a an python-moderngl coding attempt at that goal but doesn't work, possibly due to missing API feature as described above. Note this is a slight change example 04.
[mixed_vertexshader_computeshader.py,txt](https://github.com/cprogrammer1994/ModernGL/files/2232197/mixed_vertexshader_computeshader.py.txt)

**Version info**

moderngl 5.3.0
--------------
vendor: NVIDIA Corporation
renderer: Quadro M1200/PCIe/SSE2
version: 4.6.0 NVIDIA 388.16
python: 3.6.4 (default, Jan 23 2018, 13:17:37)  [GCC 7.2.0 64 bit (AMD64)]
platform: win32
code: 460

```



```

**Comment by cprogrammer1994** [comment]
There used to be a method for that. We lost it in the last major update.

**Comment by fbertola** [comment]
Any updates on this? I love ModernGL and I used it to implement a fast fluid simulation entirely on compute shaders. The only drawback now is that I need to read back the buffer for the pixel shader.
You mentioned a previous commit where the function was present; if you can point it out, I would love to help!

**Comment by cprogrammer1994** [comment]
Hi! What we need is to bind a texture to an image unit.
I will add this functionality later this day, so we can test.

**Comment by cprogrammer1994** [comment]
https://github.com/cprogrammer1994/ModernGL/commit/71ab30cf3fd59bd50bddeefec0e9404f196adfa2

**Comment by pocdn** [comment]
The experimental branch with added ability to binda a texture unit didn't seem to cover the entire problem.

There seems to be two parts to the problem;
1) need to set the sampler e.g. self.computeprog['destTex'].value = 0 but since 'destTex' is a sampler and not a uniform then moderngl throws an error
2) need to bind the texture e.g.  self.texture.bind_to_image(0,GL_WRITE_ONLY, GL_R32F) but the newly added bind_to_image requires some GL constants GL_WRITE_ONLY, GL_R32F but those don't seem to be exposed or available in the moderngl API?

I tried modifying the above original test code "mixed_vertexshader_computeshader.py,txt" with this new API. It seemed the only affected code was in the 

`    ... ...
       ...

     def animate_billboard_image(self):
        self.time.value = self.wnd.time

        w, h = self.texture.size
        gw, gh = 16, 16
        nx, ny, nz = int(w/gw), int(h/gh), 1
        
        #In moderngl, how to change to compute shader from vertex shader?
        #glUseProgram(computeHandle);

        self.texture.use(0)

        #self.destTex.value = 0 # In moderngl, presently throws error
        #self.computeprog['destTex'].value = 0 # In moderngl, presently throws error
        
        #Because we're also using self.texture as an image 
        #(in order to write to it in compute shader),
        #it must be bound to an image unit layout(location=0) as well
        #What's equivalent to following c-code in moderngl API?
        #glBindImageTexture(0, texHandle, 0, GL_FALSE, 0, GL_WRITE_ONLY, GL_R32F);

        # GL_R32F ---> dtype='f4'
        # GL_WRITE_ONLY 0x88B9 ----> what is equavalent in moderngl?
        self.texture.bind_to_image(0,GL_WRITE_ONLY, GL_R32F)

        self.computeprog.run(nx, ny, nz)
`

**Comment by cprogrammer1994** [comment]
I have pushed some changes to support image__ uniforms better.
`bind_to_image` takes the parameters and passes as-is to opengl.

To make this method convenient and pythonic. I have to see it working first. I have exposed 3 parameters.

To get:

`glBindImageTexture(0, texHandle, 0, GL_FALSE, 0, GL_WRITE_ONLY, GL_R32F);`

call:

```
GL_WRITE_ONLY = 0x88B9
GL_R32F = 0x822E
self.texture.bind_to_image(0,GL_WRITE_ONLY, GL_R32F)
```

Later this method will change to have the proper number of parameters with proper types that is easy to understand, but covers most/all of the use cases.

**Comment by cprogrammer1994** [comment]
I have added an example for next having the compute shader you wrote above.

**Comment by cprogrammer1994** [comment]
https://github.com/moderngl/moderngl/blob/ad636aa19e1c1c270ed53d1ad61a57f99f72e9cc/examples/next/render_texture_compute_shader.py

**Comment by pocdn** [comment]
Thanks for adding a modified example to match next API. It's looking like a nice improvement in the API. Unfortunately I wasn't able to actually run the example. Maybe it was due to not having the correct branch to match. Were you able to run this successfully?

Without running it but reading thru the code, one thing is that the compute shader is expecting a 4-byte value, rg32f -->
`layout(rg32f,location=0) writeonly uniform image2D destTex;`
so I would expect the image to match with RBGA not RGB as is now;
`img = Image.new("RGB", (512, 512))`
`self.texture = self.ctx.texture(img.size, 3, img.tobytes())`
Perhaps the following would be more appropriate?
`img = Image.new("RGBA", (512, 512))`
`self.texture = self.ctx.texture(img.size, 4, img.tobytes())`

**Comment by cprogrammer1994** [comment]
thank you for the corrections. I use the master, I get a black billboard. I will put together a simple example soon. This example was not working before the commits that added uniform support for the compute shader. They got an error as you mentioned before. take a look at the last 3-5 commits to see what was added.

**Comment by pocdn** [comment]
I was able to run and test the example with the changes accounting for required 4-byte image structure. It's getting close to working fully :)

img = Image.new("RGBA", (512, 512))
self.texture = self.ctx.texture(img.size, 4, img.tobytes())

And I did see an animating texture based on the compute shader.

![next](https://user-images.githubusercontent.com/6920644/55082977-e411d580-505f-11e9-8344-4aa59c18e10b.png)

The billboard should look like

![next01](https://user-images.githubusercontent.com/6920644/55083155-47036c80-5060-11e9-8034-d2c1c60d1ae9.png)

The two versions both have the characteristic 45degree wavefront motion. This suggests the compute shader is working fine but the image format itself is mis-initialized. I suspect the problem area is 

> img = Image.new('RGBA', (512, 512))
self.texture = self.ctx.texture(img.size, 4, img.tobytes())
 how to set format GL_R32F equivalent to 
    glTexImage2D(GL_TEXTURE_2D, 0, GL_R32F, 512, 512, 0, GL_RED, GL_FLOAT, NULL);
self.sampler = self.ctx.sampler(self.texture)
self.scope = self.ctx.scope(mgl.DEPTH_TEST, self.ctx.screen, samplers=[(self.sampler, 0)])

Is there a means to set self.texure image format to be GL_RED, GL_FLOAT as in the original c-code function glTexImage2D?

Here's the presently animating example but with the suspected incorrect intenal format (not GL_RED):

[render_texture_compute_shader.py.txt](https://github.com/moderngl/moderngl/files/3013620/render_texture_compute_shader.py.txt)

**Comment by pocdn** [comment]
A 2nd observation pointing to the image format being the remaining issue, if I change 

self.texture = self.ctx.texture(img.size, 4, img.tobytes())

to

self.texture = self.ctx.texture(img.size, 1, img.tobytes(), dtype='f4') 

I get the following animating billboard;

![next02](https://user-images.githubusercontent.com/6920644/55085796-82079f00-5064-11e9-9ad2-77606fcec19a.png)

This is closer to the expected result but not exactly right. The difference (mostly red versus expected blue-white billboard) is due to the setting of the underlying openGL glTexImage2D image format not being
internalformat = GL_R32F
format = GL_RED
type  = GL_FLOAT

**Comment by pocdn** [comment]
Actually, please ignore my previous hint. I can get the desired result

![next03](https://user-images.githubusercontent.com/6920644/55087251-0c510280-5067-11e9-9ef7-f849e71a828b.png)

without having to anything other than 

self.texture = self.ctx.texture(img.size, 1, img.tobytes(), dtype='f4')

I had a error in the program (not compute) shader that made it mostly red. Here's the complete working code

[render_texture_compute_shader.py.txt](https://github.com/moderngl/moderngl/files/3013847/render_texture_compute_shader.py.txt)

Thanks for making the changes to allow this compute shader integration with image samplers.

**Comment by cprogrammer1994** [comment]
Looks awesome. Can you please push an example with the working code?
I will take a look and think about a proper interface for this "bind_to_image" functionality.
I want to test if any of the parameters are so constrained that should come from inside. I will also expose level, layer, ... I will change the pushed example accordingly.

**Comment by pocdn** [comment]
I attempted to push the example with

git status
git add examples/next/render_texture_compute_shader.py
git commit

but once asked for my username and password I realized that wouldn't work without permission. Anyhow, I am okay if you take the following code and commit it yourself (without the py.txt extension just to get it to upload here). After all it's a modification to one of your original examples, but with the compute shader added.

[render_texture_compute_shader.py.txt](https://github.com/moderngl/moderngl/files/3018376/render_texture_compute_shader.py.txt)

That's great you will be considering how to make this API more pythonic in relation to samplers and compute shaders. The one line that was not exactly clear and could use some pythonic morphing was the 

self.texture = self.ctx.texture(img.size, 1, img.tobytes(), dtype='f4')

Coming from opengl-c-based coding, the python/moderngl parameters "1" and "f4" are somewhat cryptic compared to the equally cryptic c-counterparts; internalformat = GL_R32F, format = GL_RED, type = GL_FLOAT. I am not certain how best to make those pythonic but is well worth the effort and thought :)

**Comment by cprogrammer1994** [comment]
Can I place this file in the example folder?

**Comment by pocdn** [comment]
Yes, please place it anywhere that you deem most appropriate.

**Comment by einarf** [comment]
This is also something that has be requested multiple times for 5.*.
There is enough useful info here that I could add this in 5.6 or 5.7.

**Comment by einarf** [comment]
Commited a working version if this in 5.6 (master). I re-write the example to make it as simple as possible. It just displays the texture generated by the compute shader as a fullscreen quad for now.

The remaining part is 

* What about the additional paramters to `glBindImageTexture`
* Some basic sanity checking of parameters
* Should moderngl handle the constants for `access` and `format`

**Comment by einarf** [comment]
We might as well also add image support for other texture types while we're at it after figuring out the list above. Worst case add a notice about this being an experimental feature subject to change in 5.x

**Comment by einarf** [comment]
> When a texture is bound to an image unit, the format parameter for the image unit need not exactly match the texture internal format as long as the formats are considered compatible as defined in the OpenGL Specification. The matching criterion used for a given texture may be determined by calling glGetTexParameter with value set to `GL_IMAGE_FORMAT_COMPATIBILITY_TYPE`, with return values of `GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE` and `GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS`, specifying matches by size and class, respectively. 

What looks reasonable for now is:
```python
def bind_to_image(self, read=True, write=True, format=None, level=0):
    pass
```

The `format` is just the raw opengl enum. If no format is specified, the texture's format is used.

**Comment by einarf** [comment]
Publish docstrings : https://moderngl.readthedocs.io/en/latest/reference/texture.html#moderngl.Texture.bind_to_image

Remaining is to add the method to all texture methods. For layered textures we also need to support the `layers` and ``layered`` parameter. Adding examples using these texture formats might also be a good idea.

**Comment by einarf** [comment]
Considering this done. We can expand support for other textures in 5.6.x
