### ISSUE TITLE
Undocumented texture filter mode switch in build_mipmaps()

### ISSUE THREAD

**Issue by toaarnio** [moderngl/moderngl#221]
**Description**

Calling build_mipmaps() on a Texture changes the filter mode to (LINEAR_MIPMAP_LINEAR, LINEAR). This is an unexpected and undocumented side-effect. Note that the corresponding OpenGL function, glGenerateMipmap, is not changing the sampler mode.

**Proof of code**

Texture.cpp, lines 651-652:
```
gl.TexParameteri(texture_target, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
gl.TexParameteri(texture_target, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
```

**Version info**

```
moderngl 5.3.0
--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
version: 4.5 (Core Profile) Mesa 18.0.5
python: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
platform: linux
code: 450
```

**Comment by cprogrammer1994** [comment]
I think the `gl.TexParameteri` calls should be removed. Examples will need an upgrade since some of them expect `build_mipmaps` to set the filters.
The current behavior can be inconvenient for those who want to call `build_mipmaps` multiple times having a custom texture filter set already.
The current behavior is based on the fact that developers may forget to set the texture filter and see that "build_mipmaps" had no effect on the rendering.

**Comment by einarf** [comment]
I think it should be removed as well. It caused some confusion for me when using alternative ``NEAREST``  mipmap filters.

**Comment by cprogrammer1994** [comment]
Removing the `gl.TexParameteri` calls is a non-backward compatible change.

Adding a parameter that defaults to the current functionality would be great. (this is a bit hacky but backward compatibility is important for minor versions)

I want to remove these `gl.TexParameteri` in the next major entirely.

I am open to suggestions. What do you think?

---

Some ideas:

1. Adding a parameter to have or not to have this functionality.
2. Adding a parameter that defaults to a tuple for the new filters to set. (None for no filter change)
3. Keep track if the filters were changed, if not, change the filters.

**Comment by toaarnio** [comment]
Breaking backwards compatibility of a feature that was undocumented to begin with does not sound like a big deal to me, so I'd personally like to see it gone in the next minor release. That said, documenting the sampler mode switch and dropping it in the next major release would be fine as well. Changing the method signature sounds less appealing.

**Comment by einarf** [comment]
Documented in ##225
