### ISSUE TITLE
Discussion on: How to properly build .whl files

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#229]
As of 2018-07-30 we build the wheel files as follows:

wheel|building with
-|-
cp35-cp35m-win32|Windows 10 x64 (msvc)
cp36-cp36m-win32|Windows 10 x64 (msvc)
cp37-cp37m-win32|Windows 10 x64 (msvc)
cp35-cp35m-win_amd64|Windows 10 x64 (msvc)
cp36-cp36m-win_amd64|Windows 10 x64 (msvc)
cp37-cp37m-win_amd64|Windows 10 x64 (msvc)
cp35-cp35m-manylinux1_i686|Ubuntu 16.04 x86 (gcc)
cp36-cp36m-manylinux1_i686|Ubuntu 16.04 x86 (gcc)
cp35-cp35m-manylinux1_x86_64|Ubuntu 16.04 x64 (gcc)
cp36-cp36m-manylinux1_x86_64|Ubuntu 16.04 x64 (gcc)
cp34-cp34m-macosx_10_6_intel|Mac OSX x64 (clang)
cp35-cp35m-macosx_10_6_intel|Mac OSX x64 (clang)
cp36-cp36m-macosx_10_6_intel|Mac OSX x64 (clang)

Not sure if we should use `Ubuntu 16.04` for `Python 3.7`. Is it backward compatible to compile the wheels on the `18.04`? Is it forward compatible?

Please feel free to share knowledge or experience on this topic.

**Comment by cprogrammer1994** [comment]
Does anyone know if cross compiling works fine between `Ubuntu 16.04 x64` and `Ubuntu 16.04 x86`?
Windows and Mac builds fine for x86 from x64.

**Comment by QuLogic** [comment]
There are (very old, in order to support everything) dockers images for manylinux1: https://github.com/pypa/manylinux#docker-images Not sure if it would have all the C++/GL stuff you need though.
