### ISSUE TITLE
create_context should clear the native GL error flag

### ISSUE THREAD

**Issue by toaarnio** [moderngl/moderngl#251]
**Description**

`create_context` is not clearing the native GL error state, at least not when the GL context has been created by Pyglet. Any subsequent Pyglet operation that accesses the native GL context then raises an exception.

A simple workaround is to read the `error` member variable of the newly created context. Reading the variable triggers a `glGetError` call to the native GL context, which causes the error flag to be reset to `GL_NO_ERROR`.

**Proof of code**

```py
import moderngl
import pyglet

w = pyglet.window.Window()
ctx = moderngl.create_context()
print(ctx.error)
```

**Expected behavior**

Expected to print `GL_NO_ERROR`. Instead prints `GL_INVALID_ENUM`.

**Version info**

```
moderngl 5.4.2
--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
version: 4.5 (Core Profile) Mesa 18.0.5
python: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
platform: linux
code: 450
```

**Comment by cprogrammer1994** [comment]
I think some of the `glGet` calls generate this error.
I have managed not to have this error in the next major version, I call glGet for parameters supported by the core version + clear error when the glGetIntegerv fails for the version:

https://github.com/cprogrammer1994/ModernGL/blob/79ff9a80ee7f3f15f7356302710ddd116f6567fc/moderngl/mgl/context.cpp#L59-L66

I will put a glGetError at the end of the initialization.

**Comment by cprogrammer1994** [comment]
Thank you for the report :)

I hope this will fix it for now: https://github.com/cprogrammer1994/ModernGL/commit/fbad70fa9db09edbf9e98b4ac8855efc60c642a3

It would be great to know if we can avoid getting an error at the first place.
Do you know what gl call caused the error? do you have any traces?

**Comment by cprogrammer1994** [comment]
As I understood it happens because of pyglet. It is possible that moderngl cause an error too.

**Comment by tartley** [comment]
FWIW I'm using latest pyglet (1.4.0b1) and HEAD of moderngl, and requesting opengl v3.3, I get a context version of: `4.5 (Core Profile) Mesa 18.2.2`.

Does the "Core" in here pyglet is giving me a core context?

**Comment by einarf** [comment]
> Does the "Core" in here mean pyglet is giving me a core context?

Definitely, yes. I know they have been experimenting with context creation in 1.4, but it seems their main focus now is Pyglet 2.0 using OpenGL 3.3 and core profiles (forward compat). I'm in the pyglet discord server to follow up on this and will help them test the release when the branch is published. 

Especially on OS X because I want to use pyglet as the default for https://github.com/moderngl/moderngl_window.

(Still, on OS X with pyglet 1.4.0b1 even with shadow window disabled it doesn't work with ModernGL currently. I havn't had time to take a closer look, but their context creation seems to do the right thing)

**Comment by einarf** [comment]
All issues related to errors on window creation in the future: https://github.com/moderngl/moderngl_window/issues/22
