### ISSUE TITLE
Support GL_PROGRAM_POINT_SIZE

### ISSUE THREAD

**Issue by TheGreatRambler** [moderngl/moderngl#253]
**A simple use-case of the new feature**

Allow for the usage of GL_PROGRAM_POINT_SIZE in our shaders.

**Describe the solution you'd like**

Support this enable flag so that point sizes can be changed in shaders.

**Version info**

```
moderngl 5.4.2
--------------
vendor: NVIDIA Corporation
renderer: GeForce MX150/PCIe/SSE2
version: 4.6.0 NVIDIA 411.63
python: 3.7.1rc2 (v3.7.1rc2:6c06ef7dc3, Oct 13 2018, 15:44:37) [MSC v.1914 64 bit (AMD64)]
platform: win32
code: 460
```

**Comment by einarf** [comment]
I'll jump on this when I'm done with example window revamp unless someone grabs it before me.

**Comment by cprogrammer1994** [comment]
@cprogrammer1994

**Comment by einarf** [comment]
This may also be a good candidate for 5.6. Temporarily changed the milestone.

**Comment by einarf** [comment]
Thinking this can just be a flag in 5.6. That way we can support it in scopes as well.

**Comment by einarf** [comment]
Considered adding state for `GL_POINT_SPRITE_COORD_ORIGIN`, but it's easy enough to convert the coordinates in the fragment shader these days. It's just about flipping the y coordinate. It was probably more important in the fixed pipeline days.

**Comment by einarf** [comment]
Workig like a charm
```python
ctx.enable_only(ctx.PROGRAM_POINT_SIZE)
or
ctx.enable_only(moderngl.PROGRAM_POINT_SIZE)
```

New eample rendering points with dyamic sizes. Also using `gl_PointCoord`:
https://github.com/moderngl/moderngl/blob/master/examples/points_varaible_size.py
