### ISSUE TITLE
Providing Uniform type information

### ISSUE THREAD

**Issue by einsweniger** [moderngl/moderngl#258]
I'd like to have access to the type information for uniforms.
It should be simple to extend them with a `shape` member, like they are already implemented on `Attribute.cpp`:
https://github.com/cprogrammer1994/ModernGL/blob/8eb9b18e313c092b717950fd49ac0db1813108af/src/Attribute.cpp#L70-L81

I'd be happy to do a PR, but I'd need to know what other files I'd have to touch once `Uniform.cpp` is extended accordingly.

Thank you!

**Comment by einsweniger** [comment]
Oh, well. 
I just realized, the simple solution (`uniform.shape`) would not work for the various texture/image types.
So, I guess we'd have to use an `Enum` or 'str' which would make it complicated for compatibility across python versions.

I'll leave this here as an idea/feature request.

**Comment by cprogrammer1994** [comment]
Uniforms will have their type returned by glGetActiveUniform, this will be an undocumented feature, moderngl uses this under the hood, closing...
