### ISSUE TITLE
Build targets

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#265]

**Comment by cprogrammer1994** [comment]
@einarf can you please build moderngl for mac?

**Comment by cprogrammer1994** [comment]
Should we build for Linux x86? I see that the latest LTS ubuntu only supports x64
We could use Ubuntu 16.04 for the x86 builds.

**Comment by einarf** [comment]
> Should we build for Linux x86? I see that the latest LTS ubuntu only supports x64
> We could use Ubuntu 16.04 for the x86 builds.
Probably a good idea. It's the same deal on osx 10.14 where x86 is deprecated and we're building both.

**Comment by cprogrammer1994** [comment]
I got my Mac running again. :)
How do you test moderngl? I plan to add mac support for the experimental features recently added to the master.

**Comment by einarf** [comment]
Nice.

I just do basic testing by:

* Running pytest
* Run all examples (one liner running all py scripts in the directory. Why I added ESC to close the window)
* Run all examples i demosys-py

**Comment by einarf** [comment]
Linux wheels are still missing from the 5.5.0 release in case you forgot about that. Travisci is not particilarly happy about this and I suspect it might cause some confusion for new users of ModernGL.

**Comment by cprogrammer1994** [comment]
I have uploaded the missing wheels
