### ISSUE TITLE
reading depth buffer

### ISSUE THREAD

**Issue by yscoffee** [moderngl/moderngl#267]
Hi,
I am wondering that is there an example of reading depth buffer?.  My attempt is provided below.
but the size is incorrect. seems that i got a depth image with 1 byte depth per-pixel.

```
        w=self.ctx.viewport[2]
        h=self.ctx.viewport[3]

        rbo_rgba = self.ctx.renderbuffer((w, h))
        rbo_depth = self.ctx.depth_renderbuffer((w, h))
        fbo = self.ctx.framebuffer(rbo_rgba, rbo_depth) 
        fbo.use()
        fbo.clear(0.0, 0.0, 0.0, 1.0,depth=1.0)
        
        self.ctx.enable(moderngl.DEPTH_TEST)    
        
        self.my_vao.render()
        
        img = Image.frombytes('RGB', fbo.size, fbo.read(), 'raw', 'RGB', 0, -1)
        img = np.asarray(img)
        depth = np.frombuffer(fbo.read(attachment=-1), dtype=np.dtype('f4'))
        
```

**Comment by einarf** [comment]
#199 might be helpful

**Comment by cprogrammer1994** [comment]
not sure if https://github.com/cprogrammer1994/ModernGL/tree/quick-fix-reading-depth-values was merged

**Comment by yscoffee** [comment]
it looks I need to use depth_texture instead of depth_renderbuffer in the current version in order to get correct depth image. 
(my moderngl version: 5.4.2)

        depth_tex = self.ctx.depth_texture((w, h), alignment=1)
        fbo = self.ctx.framebuffer(color_attachments=(rbo_rgba), depth_attachment=depth_tex ) 
        ...
        depth = np.frombuffer(rbo_depth.read( ), dtype=np.dtype('f4'))

**Comment by cprogrammer1994** [comment]
> `depth_tex = self.ctx.depth_texture((w, h), alignment=1)`

`alignment` is ignored on texture creation if no data is given.
you can set the alignment in the read function (by default it is `4`)

**Comment by cprogrammer1994** [comment]
Is the value correct if you read the `fbo` directly?

**Comment by einarf** [comment]
We should probably make sure reading depth buffer is documented when this is resolved :)

**Comment by yscoffee** [comment]
> Is the value correct if you read the `fbo` directly?

not sure how to check value in this case
I count total number of bytes from `fbo.read(attachment-1)` to check but the length is incorrect. 

`
        print('depth read=', len(fbo.read(attachment=-1)))
`

will get depth read= w x h instead of w x h x 4

**Comment by cprogrammer1994** [comment]
Try this `fbo.read(attachment-1, dtype='f4')`

**Comment by yscoffee** [comment]
looks it works!
```
w,h= (1333, 2000)
fbo.read(attachment=-1)= 2666000
fbo.read(attachment=-1, dtype="f4")= 10664000
```

**Comment by cprogrammer1994** [comment]
The problem was that the default dtype was 'f1' (1 byte / pixel)
We will need to improve the docs and examples on this topic.
