### ISSUE TITLE
Nvida EGL context without X

### ISSUE THREAD

**Issue by bhack** [moderngl/moderngl#279]
Is it possible to create an EGL context without X?
https://devblogs.nvidia.com/egl-eye-opengl-visualization-without-x-server/

**Comment by cprogrammer1994** [comment]
There was an experiment to support EGL. Unfortunately none of my computers supported EGL with OpennGL 3.3 core so I was not able to test it.
I am willing to restore EGL support if you manage to get EGL with at least OpenGL 3.3 core available.

Currently you can do headless rendering with xvfb

**Comment by bhack** [comment]
@cprogrammer1994 There are some server/cloud contexts where GLX is not available.
See https://github.com/nvidia/nvidia-docker/wiki/Frequently-Asked-Questions#is-opengl-supported

**Comment by waleedka** [comment]
I second that. EGL support would be great. It's a more elegant solution for headless rendering, and also xvfb does not work in all situations.

**Comment by cprogrammer1994** [comment]
A simple modified EGL hello world example with a vertex shader having:

```
#version 330
...
```

gives an error:

```
shader info: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.00 ES, and 3.00 ES
```

In case you can get moderngl working with EGL by replacing the current context loading than we can add a configuration and organize the code to support both glx and egl.

Pull requests are welcome, I cannot progress with EGL since It is not working from my virtual machines.

**Comment by cprogrammer1994** [comment]
Got it working with moderngl 6.
OpenGL backends are provided by a simple module [glcontext](https://github.com/moderngl/glcontext)

We will add support for moderngl 5.x soon

**Comment by christopherhesse** [comment]
@cprogrammer1994 thanks for working on this!  Was this added to moderngl 5?  I was unable to get it working when I tried.

**Comment by einarf** [comment]
master branch is 5.6 using the glcontext package. I would play with with glcontext project. That is relevant from 5.6 and later.

**Comment by christopherhesse** [comment]
Thanks!  Here's what I see when running the master version of moderngl:

```In [1]: import glcontext

In [2]: from glcontext import egl

In [3]: egl.create_context()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-3-d1a25279a001> in <module>
----> 1 egl.create_context()

Exception: eglInitialize failed (0x3001)
```

I wrote a test program based on the nvidia link that enumerates EGL devices and this seems to work fine:

https://gist.github.com/christopherhesse/5ece3c4e7ac2cf2d9c8b3f93b100d580

```
$ ./a.out
success 1
Detected 8 devices
```

Any ideas?

**Comment by christopherhesse** [comment]
That looks to be `#define EGL_NOT_INITIALIZED               0x3001` though I don't see the difference between my test program and what glcontext is doing: https://github.com/moderngl/glcontext/blob/master/glcontext/egl.cpp#L173

**Comment by einarf** [comment]
It might just be something simple/stupid. I don't think the egl backend in glcontext was ever tested. It was just moved over from one of the moderngl experimental branches were it worked at some point on someones computer. 😄  I do see that `EGL_DEFAULT_DISPLAY` might be a whole range of different thing depending on the platform after taking a quick glance at `egl.h`?

The main reason for creating the separate glcontext package (https://github.com/moderngl/glcontext) was to make it easier for people to extend/improve context creation without having to deal with moderngl directly. We kind of rely on the community to make PRs to this project at least until moderngl 5.6 is out the door (and possibly 6).

**Comment by christopherhesse** [comment]
Using glcontext master seems to be creating a context now, I was presumably using some pypi version before.

It's not clear to me how to call glcontext through moderngl.  I see there's a settings dict but I don't see where it is used: https://github.com/moderngl/moderngl/blob/master/moderngl/context.py#L1301

**Comment by einarf** [comment]
Ah yes. We need to add a path for that.
https://github.com/moderngl/moderngl/blob/b4fe7f403574234ac4bb40c4a88a18ad4feb44ea/moderngl/old/ModernGL.cpp#L106-L136

Probably just a `backend(target: str)` in `glcontext.__init__`.

**Comment by einarf** [comment]
I'll see if I can get that sorted shortly as I have a couple of other fixes for glcontext I'm working on right now. Then we could get new glcontext out on pypi an potentially a `5.6.dev1` of moderngl.

**Comment by christopherhesse** [comment]
I think this would be a nice addition to moderngl, in the meantime, I wanted this to work for a C program, so I made a fork of GLFW that supports this: https://github.com/cshesse/glfw

In theory you should be able to have moderngl use the context created by this custom glfw and get software (OSMesa) or hardware (EGL) rendering on a linux server without running X.

**Comment by einarf** [comment]
FYI: Getting close to wrapping up things now including egl support.

**Comment by einarf** [comment]
Working example using headless EGL in a VM

```python
import numpy as np
from PIL import Image
import moderngl

ctx = moderngl.create_context(standalone=True, backend='egl')
fbo = ctx.simple_framebuffer((512, 512), components=4)
fbo.use()

vertices = np.array([
    -1.0,  -1.0,   1.0, 0.0, 0.0,
     1.0,  -1.0,   0.0, 1.0, 0.0,
     0.0,   1.0,   0.0, 0.0, 1.0],
    dtype='f4',
)

prog = ctx.program(vertex_shader="""
#version 330
in vec2 in_vert;
in vec3 in_color;
out vec3 color;
void main() {
    gl_Position = vec4(in_vert, 0.0, 1.0);
    color = in_color;
}
""",
fragment_shader="""
#version 330
out vec4 fragColor;
in vec3 color;
void main() {
    fragColor = vec4(color, 1.0);
}
""",
)
vao = ctx.simple_vertex_array(prog, ctx.buffer(vertices), 'in_vert', 'in_color')
vao.render(mode=moderngl.TRIANGLES)

image = Image.frombytes('RGBA', (512, 512), fbo.read(components=4))
image = image.transpose(Image.FLIP_TOP_BOTTOM)
image.save('triangle.png', format='png')
```

Output 

![Capture](https://user-images.githubusercontent.com/5418180/73141945-b0da1180-4089-11ea-8450-7220ee86cec1.PNG)

**Comment by einarf** [comment]
Added to examples `examples/headless_egl.py`

**Comment by einarf** [comment]
@christopherhesse Improvements to context creation can be done in the glcontext package. People can contribute and hack around there. From next release (very soon) this package is used for context creation / detection.

https://github.com/moderngl/glcontext

**Comment by christopherhesse** [comment]
Thanks @einarf!  Would you guys be open to a libosmesa backend in glcontext at some future point?

**Comment by einarf** [comment]
@christopherhesse Never played with OSMesa, but it sounds like something that could be mocked up fairly quickly using ctypes with the `empty.py` backend template.

Make an issue here : https://github.com/moderngl/glcontext/issues
(And ideally share as much info as possible)
