### ISSUE TITLE
release next

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#291]
Creating this issue early for planning purposes.

**Comment by cprogrammer1994** [comment]
A lot of features are still missing, most of them just need to be picked from moderngl 5.x and refactored to use the proper classes and their slots.

**Comment by einarf** [comment]
I can move demosys-py to ModernGL 6.0 testing things and help out with improving docs.

How would I get started with this as early as possble?

**Comment by cprogrammer1994** [comment]
I have tried to do that and I realized a lot of things are not yet working.
I usually just replace the import:

`import moderngl.next as moderngl`

There are a few examples in the `examples\next` folder.
I try to do minimal touch on the original examples to get them working with the `next`.

**Comment by einarf** [comment]
I'll complete the first working version of `moderngl_window` and apply them to experimental examples and the current ones (unless experimental is bumped to the main version very soon)

Then I will make a branch of `demosys-py` testing out things.

**Comment by cprogrammer1994** [comment]
I will apply the changes to the experimental examples. I am now creating a few sampler examples to test the sampler implementation. the next one will be the missing depth texture.

the basic experimental examples are just a copy paste the original + the minimum changes required to get them running.

**Comment by cprogrammer1994** [comment]
> How would I get started with this as early as possble?

we still have no docs for the 6.x but most of the things should match the old api

if you diff the current and the experimental examples, you will see what was changed.

Here are a few notes:

the context object is mostly for creating new object
the textures are just data, samplers are required to use them
the viewport can be set  for each fbo (even for the ctx.screen or the ctx.fbo) (( the latter is the currently bound fbo ))
there is no enable disable enable_only in the context, scopes are required to do enabling
most of the ctx.info was moved to ctx.limits *(Limits have properties not dict keys)
the hwinfo contains the GL_VERSION GL_RENDERER ...

**Comment by cprogrammer1994** [comment]
I want to release a version 5.x.x where this "next" is available too

**Comment by einarf** [comment]
ah. I see, so `next` is 6.x.x and will be available in the `5.x.x` package as well just like the project is structured now. I'm guessing that is actually not a bad way to do the transition. Should we also try to get docs up (just a skeleton) so it will be easy to contribute to that over time?

> the context object is mostly for creating new object
> the textures are just data, samplers are required to use them
> the viewport can be set for each fbo (even for the ctx.screen or the ctx.fbo) (( the latter is the currently bound fbo ))
> there is no enable disable enable_only in the context, scopes are required to do enabling
most of the ctx.info was moved to ctx.limits *(Limits have properties not dict keys)
the moderngl.next.hwinfo(ctx) contains the GL_VERSION GL_RENDERER ...

Thanks. This is a good start.

I thought about also attempting to clean up the examples a bit more. It would be nice if they were organized better and combined used most of the ModernGL features so it can also be used for basic (visual) feature testing and be a better reference for users. Maybe extend the standard `NN_something.py` examples and clearly separate the more fun examples with a different prefix. This is probably better to do in `next`.
