### ISSUE TITLE
document format string used by 'content' arg of vertex array constructor

### ISSUE THREAD

**Issue by tartley** [moderngl/moderngl#306]
I plan to contribute this documentation. I hijacked another existing issue discussing it. I'll discuss it here instead.

**Comment by tartley** [comment]
I would like to contribute some documentation.

I am trying to figure out the format strings passed to `Context.vertex_array`, and when I've figured it out, I'd be happy to add a doc PR explaining my findings. :-)

For example, I'm talking about the '2f' in:

```
ctx.vertex_array(
            self.shader,
            [
                (self.ctx.buffer(verts), '2f', 'vert'),
                (self.ctx.buffer(colors), '3u', 'color_in'),
            ],
            self.ctx.buffer(indices),
            index_element_size=1,
        )
```

I don't know whether these format strings are using a syntax from elsewhere, eg that maybe is part of OpenGL? If so, then the docs could link to those docs. Or if it is just made up for moderngl, then the docs could describe the format.

At first I assumed that it was the same type of format strings that I pass to `struct.pack(...)` to create my buffers, because '3f' does the same thing in each. But this doesn't seem to be the case. In particular, I'm trying to create a buffer of colors made up of three unsigned bytes. I create these using `struct.pack('3B', *data)`, but vertex_array constructor does not accept '3B' as a valid format string.

Just ten minutes ago, I found the source that reads these format strings, here:
https://github.com/cprogrammer1994/ModernGL/blob/master/src/BufferFormat.cpp

So now I can see what sequences of values are allowed. At the very least, I could try to lay out this information in a readable manner for the documentation. Would this be useful? If you have strong opinions about how it should look, let me know.

---

In my specific case, to pass in vertex color attributes using unsigned bytes, and receive them as floats from 0.0 to 1.0 in my vertex shader.  I think it's important for me to get `node.normalize` set to true. From the source of Bufferformat.cpp, it appears the only way to do this is to use a format like '3f1'. So I'm puzzled about why 'f' is used here for unsigned bytes. I've been assuming 'f' is shorthand for 'float'. Any clues welcome. **Update:** yay using f1 works.

**Comment by tartley** [comment]
One option would be to use BNF, eg. a hurried version:

```
<nodes> ::= <node> | <node> " " <nodes>
<node> ::= <opt-count><type-size><opt-post>
<opt-count> ::= <integer> | ""
<type-size> ::= ( "f" <size8> ) | ( "i" <size4> ) | ( "u" <size4> ) | ( "x" <size8> )
<post> ::= "/" <per-type>
<per-type> ::= "i" | "r" | "v"
```

With extra notes describing things like 'normalize' is true for "f1", divisor values for per-types, etc.

But this lacks some intuitive readability. Maybe back it up with examples. Or maybe there's a better way. I'll try again tomorrow...

**Comment by tartley** [comment]
cprogrammer1994 commented:

These buffer formats are specific to moderngl. I have tried to represent a wide range of vertex attribute formats. It would be really helpful to get this part documented.

`f1` is a special format representing a float on one byte, (a normalized unsigned integer on one byte).
`f1` was introduced exactly for the purpose of passing colors.

In `next`, it is also allowed to pass `3f1` to a vertex attribute with vec4 type (in case we want to pass the RGB values, but not the alpha).

>  At the very least, I could try to lay out this information in a readable manner for the documentation. Would this be useful?

It would be useful.

> One option would be to use BNF, eg. a hurried version:

BNF format seems to be okay

---

There is a method in VertexArray called `bind`.
bind was exposed to manually configure the underlying opengl calls. This bind was added to remove the limitation of the formats discussed above. I don't recommend using bind. Formats above seems to be enough for all kind of projects)

**Comment by tartley** [comment]
I wonder if  something less formal than BNF might have better readability. Going to try it out here, see which we prefer:

---

A buffer format is a short string, describing the layout of data in the buffer. For example, "3f" indicates the buffer contains three floats.

By default, floats occupy 4 bytes, but this can be modified with an optional trailing size, such as "3f2", indicating three two-byte half-floats.

A final optional slash and character indicates the divisor size (I don't understand what this is yet)
* `/i` divisor = 1
* `/r` divisor = 0x7fffffff
* `/v` divisor = 0

So the resulting overall form of the format string is:

    `[count] type [size] [/usage]`

Where:
* count is an optional integer, defaulting to `1`.
* type is a single character indicating data type (`f` float, `i` int, `u` unsigned int, `x` padding)
  * `f` (float)
  * `i` (int)
  * `u` (unsigned int)
  * `x` (padding)
* size is an optional number of bytes used to store the type, defaulting to 4 for numeric types, or to 1 for padding bytes.
* usage is (copy best character list format from above)

**Comment by einarf** [comment]
I've had this in my metal TODO list for a long time. Getting this properly documented would be fantastic.

**Comment by tartley** [comment]
Opinions about the above grateful received, even if they are highly critical.

**Comment by einarf** [comment]
Maybe also include dtypes for textures and supply some examples. I imagine this as a separate "Buffer Formats" page that can be linked from the documentation from the various types and create functiond.

**Comment by tartley** [comment]
Separate page makes perfect sense. Thanks.

Is that 'dtypes' as in numpy.dtype?

I'm unclear about the role of 'next'. Should I be aiming to add a doc page to the 'next' docs, or to both that and the regular docs? Will it be identical in each?

**Comment by einarf** [comment]
Was referring to the parameter you can supply in the texture function.

https://github.com/moderngl/moderngl/blob/master/moderngl/context.py#L564

If you are unsure about that I would just skip it for now.

I'd say document it for moderngl 5 (current docs) and we can move it over to moderngl 6 docs and revise it if needed. I'm sure moderngl 5 will be used for a long time anyway.

**Comment by cprogrammer1994** [comment]
I have a hint on the last format item the one that starts with `/`.

There are 3 options:

- `/v` - read it as per vertex -
- `/i` - read it as per instance -
- `/r` - read it as per render - think of it as it was something similar to uniforms -

The default is `/v` and the first vbo bound to the vao must be per vertex. (*please ignore the restriction now, I will try to explain it later)

Let's say we want to render a dozen cubes with instanced rendering where we have the vertices and normals of the cube in `vbo1` in a proper format. We have some origins and rotations in `vbo2` and we have a single color = (0.0, 0.0, 1.0) blue in `vbo3`

Our program will take all the attributes above as attributes, none of them are uniforms.
We also use this program to render some objects with vertex paint (where the color is a per vertex attribute) -> to be able to reuse this program we turned everything into attributes.

We can do the instanced rendering binding `vbo1` and `vbo2`:

```py
(vbo1, '3f 3f /v', 'in_vert', 'in_norm'),
(vbo2, '3f 9f /i', 'in_position', 'in_rotation'),
```

Okay, but what about the color?

If we don't bind it it will default to (0, 0, 0, 1) -> black cubes
If we bind it with `/i` we will store the color a dozen times.
We can bind it with `/r` the first item will be used for every instance.

I know there are default values for attributes the OpenGL API can set, but I have seen them working improperly on more than one device -> it made me think this feature is probably not used. I have seen problems with rare types like 2x3 matrices, doubles and similar.

I had the idea to use `/d` and not `/r` but I like to read the line as per render attributes.

@einarf Do you have an opinion on this?

**Comment by cprogrammer1994** [comment]
I think the description and the table is accurate. Can you prepare it in an rst format. Please try to build the docs with `python setup.py build_sphinx`

**Comment by cprogrammer1994** [comment]
Some info about dtypes:

- dtypes were the replacement for the earlier `floats=True` textures :)

Sometimes we need better precision for textures. Float textures are great for building a heightmap or similar. Sometimes we need integer textures to implement some sort of picking.
This led me to extend the list of types the textures support.

I found the final set sharing a lot of elements with the dtypes numpy introduces.
These dtypes are not the same, but most of them define the same format and size for a single item.

`f4` is a float on 4 bytes both in numpy and in moderngl.

There are special dtypes in moderngl 6 for depth textures `d2` `d3` and `d4` were choosen not to have matching pairs in numpy.
for example `d3` is a float on 3 bytes or 24 bits (most of the devices support 24bit depth by default)
When a texture is created with the `dtype=d3` it will be possible to read it as it was an `f4`. this is why these dtypes are special.

Another special dtype is `f1` (float on one byte)
Please think of it as 0-255 integer range is mapped to the 0.0 1.0 float range.

**Comment by tartley** [comment]
Fantastic. Thanks for all the info. I'll work it into a branch and push it for review. I've been crazy busy at work recently, but it'll happen soon. (I'm delaying work on my hobby project using moderngl until I can merge this & feel like I've been a bit useful)
