### ISSUE TITLE
compile error: converting void pointers in buffer.cpp

### ISSUE THREAD

**Issue by tartley** [moderngl/moderngl#307]
**Description**

I get a cpp compile error on 'pip install .' of the git repo:

```
  moderngl/next/mgl/buffer.cpp:457:1: error: invalid conversion from ‘void (*)(MGLBuffer*)’ to ‘void*’ [-fpermissive]
   };
   ^
  error: command 'gcc' failed with exit status 1
```

Bisecting shows it was introduced at commit:
```
 * d3b285a 2019-03-05 18:34:13 Szabolcs Dombi (HEAD, refs/bisect/bad)
 | implement tp_dealloc
```

I'm on

LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch
Description:	Ubuntu 18.10

**Comment by cprogrammer1994** [comment]
fixing it

**Comment by cprogrammer1994** [comment]
fixed: https://travis-ci.org/moderngl/moderngl/builds/505170380
travis integration will be fixed soon too.
