### ISSUE TITLE
vertex_array: partial render uses incorrect offset when index_element_size is not 4

### ISSUE THREAD

**Issue by atomizer** [moderngl/moderngl#310]
**Description**

When rendering a vertex array with non-zero offset (`first` parameter), there is incorrect assumption that index element size is 4: [render](https://github.com/moderngl/moderngl/blob/3d7b1eee3475842a038b716b1de7ff7ec13cd0af/src/VertexArray.cpp#L273), [render_indirect](https://github.com/moderngl/moderngl/blob/3d7b1eee3475842a038b716b1de7ff7ec13cd0af/src/VertexArray.cpp#L374). This leads to empty draws or garbage.

**Proof of code**

```py
import moderngl
from array import array
from PIL import Image

ctx = moderngl.create_standalone_context()

prog = ctx.program(
    vertex_shader='''
        #version 330

        in vec2 in_pos;

        void main() {
            gl_Position = vec4(in_pos, 0.0, 1.0);
        }
    ''',
    fragment_shader='''
        #version 330

        out vec3 f_color;

        void main() {
            f_color = vec3(0.0, 1.0, 0.0);
        }
    ''',
)

# 4 points
vbuf = ctx.buffer(array('f', [-1, -1, -1, 1, 1, -1, 1, 1]))
# 2 triangles
ibuf = ctx.buffer(array('b', [0, 2, 1, 1, 2, 3]))

vao = ctx.vertex_array(
    program=prog,
    content=[(vbuf, '2f', 'in_pos')],
    index_buffer=ibuf, index_element_size=1)

fbo = ctx.simple_framebuffer((100, 100))
fbo.use()

# draw only the second triangle
vao.render(first=3)

Image.frombytes('RGB', fbo.size, fbo.read(), 'raw', 'RGB', 0, -1).show()
```

**Expected behavior**

A black square with green top right half.

**Version info**

moderngl 5.5.0, but also related to #299

**Comment by einarf** [comment]
Think I forgot to multiply with `index_element_size` here so the pointer is wrong:
https://github.com/moderngl/moderngl/blob/540567f5f4c821001e70f06fa58695a48483dc10/src/VertexArray.cpp#L273

**Comment by einarf** [comment]
#312

Result with the change applied:
![result](https://user-images.githubusercontent.com/5418180/54378785-61187480-4688-11e9-96b5-3b06f0849e50.png)

**Comment by einarf** [comment]
Merged to master. Might be a good idea to let this issue hang around until new version is released.
