### ISSUE TITLE
pypy compatibility

### ISSUE THREAD

**Issue by atomizer** [moderngl/moderngl#311]
[Pypy](https://pypy.org) is an alternative Python implementation with JIT.

Curretnly moderngl doesn't compile due to non-existence of following in pypy C API:
- `5.5.0`:
  - `PyException_HEAD` macro
  - `PyUnicode_Append`
- `next`:
  - `ob_base` inside PyObject

**Comment by cprogrammer1994** [comment]
Thank you for the issue.
Most of the ob_base are used to access values that can be accessed with macros
I will replace those so `next` will be compatible with pypy

**Comment by cprogrammer1994** [comment]
I don't know a quick solution to get rid of `PyException_HEAD` for the 5.x compatibility

**Comment by cprogrammer1994** [comment]
please build moderngl 5.5 from the master
I have removed `PyException_HEAD` and `PyUnicode_Append`
I hope it works. I have not yet tested it.

https://github.com/moderngl/moderngl/commit/540567f5f4c821001e70f06fa58695a48483dc10

**Comment by cprogrammer1994** [comment]
I am not able to build with pypy:

```
 error: Microsoft Visual C++ 14.1 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
```

Can you please test:

```
./pypy3.exe -m pip install https://github.com/moderngl/moderngl/archive/master.zip
```

**Comment by atomizer** [comment]
In `GLMethods.cpp` there's one mention of `PyUnicde_Append` left in (now unused) `AddToLog`. Removing the function makes it compile and work (tests pass).

**Comment by cprogrammer1994** [comment]
Super!

**Comment by atomizer** [comment]
I'm building it manually with `setup.py build_ext --inplace` since `next` still fails.

**Comment by cprogrammer1994** [comment]
I will fix next too. It will take more time doe to a lot of `ob_bases` I guess

**Comment by cprogrammer1994** [comment]
I think it is done. Can you please check if both `5.x` and `next` are building.

**Comment by cprogrammer1994** [comment]
https://travis-ci.org/moderngl/moderngl/jobs/506619895

**Comment by einarf** [comment]
Awesome stuff. This opens up for a lot of interesting experimentation. I wonder myself what kind of performance boost can be gained in some of my projects.

**Comment by atomizer** [comment]
Yes, it compiles. Creating a context using `next` causes instant crash. I'm not an expert on either engine's internals, but I think your direct object memory access/manipulation tricks (memsets, `SLOT` macro etc.) are CPython-only. It's really difficult (for me at least?) to find concrete info on what those differences are exactly, so I'm not quite sure how to debug this.

**Comment by cprogrammer1994** [comment]
I was not able to run pypy locally at all. I cannot get the msvc compiler installed for pypy. Probably the `SLOT` macro needs to be changes into something that supports `PyObject_SetAttrString` internally when needed.

**Comment by cprogrammer1994** [comment]
I will probably try to run pypy on Ubuntu soon.
