### ISSUE TITLE
release 5.5.2

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#313]
I will need to fix pypy compatibility for next or I will need to exclude next from the next release.

**Comment by einarf** [comment]
Would it be a good idea to release a version without pypy support first? There's a few very important bug fixes and I would guess the vast majority of users are currently on 5.x.

**Comment by cprogrammer1994** [comment]
yes sure, let us do a release.

**Comment by cprogrammer1994** [comment]
do you consider the current master stable?

**Comment by einarf** [comment]
Good point. I can run some tests today and report back here again.

**Comment by einarf** [comment]
Did quite a bit of testing and looking at commit history. Things do look very stable, so think a new releases is good. I guess `5.5.1` because there are mainly bug fixes.

**Comment by einarf** [comment]
Forgot about: https://moderngl.readthedocs.io/en/5.5.1/reference/buffer_format.html :)

**Comment by cprogrammer1994** [comment]
we will fix the changelog later, I just added at least one entry not to look too bad. I also found that i have wip changes on master, these will be part of the repo only after the release

**Comment by cprogrammer1994** [comment]
uploaded:

- source dist
- linux 3.5 -> 3.7 wheels
- windows 3.6, 3.7 wheels

cannot build 3.5 wheels on windows anymore .. :(

**Comment by einarf** [comment]
Can upload osx release when I get home today if needed

**Comment by cprogrammer1994** [comment]
Thank you

**Comment by cprogrammer1994** [comment]
linking https://github.com/moderngl/moderngl/issues/326

**Comment by einarf** [comment]
I think next time I do testing I should build a wheel locally and install it. I will take part of the blame for 5.5.1 😄

**Comment by cprogrammer1994** [comment]
me too

**Comment by einarf** [comment]
Wheels for OS X uploaded. I'm sticking to 10_9 wheels for now. If you think there is a reason to also do 10_6 wheels I can look into this.

**Comment by cprogrammer1994** [comment]
According to [this](http://gs.statcounter.com/macos-version-market-share/desktop/worldwide), there is a tiny chance having a request for 10_6 in the future, they still could build it on their own. I don't see why should we spend time on those wheels now.
