### ISSUE TITLE
Behavior of example.mouse_position_event(self, x, y)

### ISSUE THREAD

**Issue by charlesloop** [moderngl/moderngl#316]
Shouldn't example.mouse_position_event(self, x, y) get called regardless of mouse button state? Running python examples/00_empty_window.py --window pyglet, and looking at the terminal output shows that example.mouse_position_event(self, x, y) is not called when a mouse button is in the pressed state. This makes it difficult to implement click and drag behaviors. Thanks!

**Comment by einarf** [comment]
We're working on a separate package for window support at the moment. I'm not sure if the same issue is present there. (example windows in this repo will be removed)

https://github.com/moderngl/moderngl_window

**Comment by einarf** [comment]
Fixed in `moderngl_window` project now. This was a bug specific to Pyglet windows.

https://github.com/moderngl/moderngl_window/commit/e961ea5f6b9405a22e08539a4e51a948c95b050c
