### ISSUE TITLE
How to get screen resolution in fragment shader

### ISSUE THREAD

**Issue by matcool** [moderngl/moderngl#319]
I'm trying to convert a shadertoy shader to moderngl and theres a function that needs to know the screen height.
```
vec3 rayDirection(float fieldOfView, vec2 fragCoord) {
    vec2 xy = fragCoord - iResolution.xy / 2.0;
    float z = iResolution.y / tan(radians(fieldOfView) / 2.0);
    return normalize(vec3(xy, -z));
}
```
So far I've gotten it to be this, but the main problem is what to replace iResolution with
```
vec3 rayDirection(float fieldOfView) {
    vec2 xy = v_uv;
    float z = ???? / tan(radians(fieldOfView) / 2.0);
    return normalize(vec3(xy, -z));
}
```

**Comment by auxiliary** [comment]
If not mistaken, that is provided as an input to the shader and doesn't belong to the shader language. You'd have to calculate it outside and send it in. See https://stackoverflow.com/questions/27888323/what-does-iresolution-mean-in-a-shader. 
If you are setting the viewport or screen size somewhere in your code, that would be what you'd want to send as a uniform variable to the shader.

**Comment by einarf** [comment]
They are uniforms or injected in the source code before compile/link. You can however use `textureSize` to query size of samplers. It confuses me as well at times.
