### ISSUE TITLE
Extended Error Handling

### ISSUE THREAD

**Issue by THofstee** [moderngl/moderngl#320]
**A simple use-case of the new feature**

For example, when you call a shader without writing uniforms yet.

**Describe the solution you'd like**

It would be neat if attempting to call a shader without having written uniforms yet resulted in an error/exception. I imagine there are also more cases in the API where you could check for these general classes of expected use errors.

**Version info**

```
moderngl 5.5.0
--------------
vendor: VMware, Inc.
renderer: Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits)
version: 3.3 (Core Profile) Mesa 13.0.6
python: 3.7.1 (default, Nov 16 2018, 07:46:36) 
[GCC 6.3.0 20170516]
platform: linux
code: 330
```

**Comment by yoyonel** [comment]
Could you write a unit test to expose this issue ?

**Comment by THofstee** [comment]
Sure, I modified the line drawing example:

```python
import moderngl
import numpy as np

from PIL import Image

ctx = moderngl.create_standalone_context()

prog = ctx.program(
    vertex_shader='''
        #version 330
        uniform vec3 in_color;
        in vec2 in_vert;
        out vec3 v_color;

        void main() {
            v_color = in_color;
            gl_Position = vec4(in_vert, 0.0, 1.0);
        }
    ''',
    fragment_shader='''
        #version 330

        in vec3 v_color;

        out vec3 f_color;

        void main() {
            f_color = v_color;
        }
    ''',
)

x = np.linspace(-1.0, 1.0, 50)
y = np.random.rand(50) - 0.5
rgb = np.array([1.0, 1.0, 0.0])

vertices = np.dstack([x, y])

vbo = ctx.buffer(vertices.astype('f4').tobytes())
vao = ctx.simple_vertex_array(prog, vbo, 'in_vert')

fbo = ctx.simple_framebuffer((512, 512))
fbo.use()
fbo.clear(0.0, 0.0, 0.0, 1.0)

# prog['in_color'].write(rgb.astype('f4').tobytes())
vao.render(moderngl.LINE_STRIP)

Image.frombytes('RGB', fbo.size, fbo.read(), 'raw', 'RGB', 0, -1).show()
```

**Comment by einarf** [comment]
Not setting a uniform is sometimes perfectly valid, so I'm not sure if this is a good idea. Sampler for example by default use texture channel 0 unless set.

A differernt approach is to extend the Program class adding this functionality specific for the project. I do this myself to for example support shader reloading runtime.

My main worry is how this will affect performance and I'm not entirely sure how this will apply to Uniform Buffer Objects.
