### ISSUE TITLE
Rendering dependency on vertex_array

### ISSUE THREAD

**Issue by charlesloop** [moderngl/moderngl#321]
I have been using moderngl for a while and have come to appreciate how simple it is to get things done. However, it seems that all rendering is done through the vertex_array Render call, and there is an expectation that the vertex buffer be non-zero in length. This is very different from OpenGL in C where you don't even need a vertex buffer to be bound prior to a draw call. You can call glDrawArrays(GL_POINTS, 0, numVerts), with an empty vertex shader, and the geometry shader will get invoked numVerts times, with a unique value of gl_PrimitiveIDIn. This is useful for creating geometry on the fly. I have not been able to replicate this functionality using moderngl. Is this a design flaw, or a gap in the example code?

Thanks.

**Comment by cprogrammer1994** [comment]
I will think of a solution.
Let's see if I understand it exactly.

We can create an empty vertex array in C
```c
GLuint vertex_array_obj;
glGenVertexArrays(1, &vertex_array_obj);
```

We can bind it
```c
glBindVertexArray(vertex_array_obj);
```

No call to `glVertexAttribPointer` or friends.

But enabling a vertex attribute:
```c
glEnableVertexAttribArray(location)
```

When calling `glDrawArrays` it is not an error to have a vertex attribute enabled but not bound to a vbo or a local buffer.
Can you please provide some opengl specs/docs to see if this is a valid call?

If the above code is correct, I suggest extending the `vertex_array(...)` to support enabled but non-bound vertex attributes.

Sketch 1:

```py
ctx.vertex_array(prog, [
    (None, None, 'in_vert'),
])
```

Sketch 2:

```py
vao = ctx.vertex_array(prog, []) # empty is allowed
vao.bind(...)  # can a bind call do it? (with glVertexAttribPointer and glEnableVertexAttribArray?)
```

**Comment by cprogrammer1994** [comment]
@einarf do you have any thoughts on this feature?

**Comment by einarf** [comment]
Personally I have not worked with this method before, but if this is in fact valid in OpenGL 3.3 and higher it's definitely a nice addition. I can imagine it can transform feedback step for many things.

@charlesloop Do you have a sample snippet and some reference somewhere that this is valid OpenGL 3.3+?

**Comment by charlesloop** [comment]
Sorry for the delay. 

The issue is: you don't need a vertex buffer at all to do rendering in opengl (in recent versions). My use case that I put a large amount of data into a shader storage buffer (SSBO), bind it and set other state, then call

	glDrawArrays(GL_POINTS, 0, NUM);

Where NUM is the number of geometry invocations I want. My vertex shader is empty:

#version 430
void main(void){}

Then my geometry shader accesses the SSBO using gl_PrimitiveIDIn, and emits triangles based on what my shader does with this data.

I can't do this use case using ModernGL.

**Comment by einarf** [comment]
I think this could be great to support. The tight restrictions on how VAOs are created are one of the things a lot of people don't like with moderngl, so anything to soften this has my support. Maybe even `content` can be `None` when no attributes should bound.

**Comment by einarf** [comment]
From Nicol Bolas, someone I definitely trust regarding OpenGL.
https://computergraphics.stackexchange.com/questions/5402/do-i-have-to-have-a-buffer-bound-before-making-a-draw-call

> There is nothing in the OpenGL specification that requires you to have enabled attribute arrays in the bound VAO when you render. All of the user-defined vertex attributes will have undefined values, but since you're not reading any of them, that won't be a problem.

> What may be a problem is driver bugs. Rendering with an empty VAO is not exactly the most common thing in the world, so it's possible that some drivers won't do the right thing. But the implementation should allow this.

By skipping the vertex attribute bind (`glEnableVertexArrayAttrib`) and not providing a buffer (`glVertexArrayVertexBuffer`) it should work.

**Comment by cprogrammer1994** [comment]
Thank you @charlesloop an @einarf for helping me understand this issue.

I have managed to implement it for the next major version of moderngl.
Here is an already working sample code:

https://github.com/moderngl/moderngl/blob/97bb7eff46b47e0c902416b005535904d5484cdd/examples/geometry_genertion.py

It produces the following image:

![image](https://user-images.githubusercontent.com/11232402/62945283-20638980-bde7-11e9-8c2e-d645118a62d8.png)

This example uses the bare minimum required to see if empty vaos can render.

**Comment by einarf** [comment]
Yay. A lot of people will be happy for this one.

**Comment by cprogrammer1994** [comment]
> The tight restrictions on how VAOs are created are one of the things a lot of people don't like with moderngl, so anything to soften this has my support. Maybe even content can be None when no attributes should bound. This also means users can defer buffer binds and use vao.bind later. This is definitely an advantage because it adds flexibility.

Even empty vaos are possible in the next major. (empty: the program can be set later, buffers can be bound to locations directly, programs can be replaced at runtime)

**Comment by einarf** [comment]
Even better. This will certainly simplify things a lot for people who are doing more fancy stuff!

**Comment by Cazadorro** [comment]
Is there a work around in the meant time for this (not being able to render with out a vertex array buffer)?  I ran into this exact same problem today, completely screws any kind of competent voxel rendering or points with out it, and completely halts the project I'm working on.   My project cannot afford to have a dependency on next or any new sub-module we don't control.

**Comment by einarf** [comment]
The simplest solution might be to just use PyOpenGL for those specific cases until an official release is out.

**Comment by cprogrammer1994** [comment]
Please fork the repository and comment out the following lines:

https://github.com/moderngl/moderngl/blob/f9e0047e6a01439d62b242c44e36b1d66c3b8af9/moderngl/old/VertexArray.cpp#L42-L45

This will allow `ctx.vertex_array(prog, [])` to create an empty vao.

If this change is helpful, please let me know and I will add this to the list of "forward compatibilities" an release it under 5.6.x

**Comment by einarf** [comment]
I got this working in 5.5.x actually. I think this is such an imporant change we should support it in 5.5.x and 5.6.

**Comment by einarf** [comment]
I enabled this in 5.5.x and master (5.6)

master : f1b04b8916247674dbfe2efd903147f39d2f6001
5.5.x : f6bcf0bb34884af5c112c21376291c2ca6bc2dda

**Comment by einarf** [comment]
5,5,4 is out, so you should be able to render with empty Vertexbuffer now.
