### ISSUE TITLE
How to do multisample anti-aliasing with Xvfb?

### ISSUE THREAD

**Issue by airalcorn2** [moderngl/moderngl#322]
When following the example [here](https://github.com/cprogrammer1994/ubuntu-headless-ModernGL), the maximum number of samples (i.e., `ctx.max_samples`) is one, so multisample anti-aliasing isn't possible and render quality suffers. Is there a way to increase the maximum number of samples to enable MSAA when using Xvfb?

**Comment by cprogrammer1994** [comment]
render with the 2x size and scale down the image with LANCZOS for example. PIL can do that :)

**Comment by airalcorn2** [comment]
Ah, of course! Thanks!
