### ISSUE TITLE
Support for Stencil Buffers

### ISSUE THREAD

**Issue by auxiliary** [moderngl/moderngl#323]
Is there currently any support for stencil buffers or a way to fake it? If not, do you all have any suggestions on where I can start adding in the functionality?

**Comment by cprogrammer1994** [comment]
Hi,
create a framebuffer(color_attachments=texture1), render the stencil part
bind the texture1 to some texture unit and render the scene. in the fragment shader use texture1 to decide if you want to discard a pixel or not.

hint: texture1 can be a texture with a single component (components=1)

**Comment by auxiliary** [comment]
Thank you for the explanation. Although, one part that I really need is the ability to accumulate values in the stencil buffer for each pixel (which I think is done with GL_INCR for the operation and GL_ALWAYS for the stencil test function). Would that still be somehow possible?

**Comment by einarf** [comment]
Could use additive blending to accumulate the values? (`GL_ONE`, `GL_ONE`)

**Comment by auxiliary** [comment]
Great idea. I'll give it a try.

**Comment by auxiliary** [comment]
Worked. Thank you.
