### ISSUE TITLE
Additional dtypes

### ISSUE THREAD

**Issue by SliMM** [moderngl/moderngl#324]
Hello,

In the current implementation only a limited number of texture/renderbuffer data types are exposed to the user. For example, I can’t find a data type for a two-channel texture stored as a pair of normalised unsigned shorts.

I’m going to hack the data types I need quickly, but I thought I’d check if there is any interest in extending the current implementation, and if so discuss the preferred way of supporting additional types.

Best,
Ștefan

**Comment by cprogrammer1994** [comment]
Hi,

Datatypes were kept simple, they really miss the normalized unsigned integers. I am open to suggestions. I think the `vao.bind` could be improved a bit to be well documented+tested. the explicit bind could have no further missing features, dtypes could remain simple.

- Do you have an idea how normalized dtypes should look like?
- Did you try to use `vao.bind` directly?

Thank you,

**Comment by SliMM** [comment]
I haven’t tried `vao.bind`, I’ll take a look at it.

The available formats focused around the internal representation are relatively clear with the exception of `f1` – unlike the other `f*` formats, it is stored (and read from GPU memory) as unsigned bytes. This is probably the most common thing you’d want to do, but it’s somewhat inconsistent with the other datatypes.

As far as other combinations of formats are concerned, I guess the number of possibilities gets a bit too big for a simple string representation. What about a simple structure with the following fields:

- data representation (e.g. GL_BYTE, GL_FLOAT, GL_UNSIGNED_SHORT_5_6_5)
- number of channels
- normalisation (whether integer pixels appear as 0.0–1.0 or -1.0–1.0 floating point values in shaders, depending on integer sign)

Some representations imply a fixed number of channels, and the floating point representations do not support normalisation. You could quickly validate these in Python – this is not the kind of thing that gets called in a tight loop.

**Comment by cprogrammer1994** [comment]
I have investigated normalized types and added the missing ones. In the mext major version one will be able to use:

- `nf` normalized float
- `ni2` normalized signed short
- `nu4` normalized unsigned int

...
