### ISSUE TITLE
 elementwise multiplication should be matrix multiplication for Mvp calculation

### ISSUE THREAD

**Issue by cameronschaeffer** [moderngl/moderngl#325]
I see in many places the code uses
self.mvp.write((proj * lookat).astype('f4').tobytes())

The * operator does elementwise multiplication for both pyrr and numpy matrices. I believe this should be the @ operator which does matrix multiplication. How does this code work?

**Comment by McSinyx** [comment]
> The `*` operator does elementwise multiplication for ~both pyrr and~ numpy matrices and matrix multiplication for pyrr `Matrix*`

or more precisely, a wrapper around `numpy.dot`, and thus `A * B == B @ A`. I believe that this is to provide compatibility/consistancy with other 3D library in other language. Personally I use `@` because `MVP = M @ V @ P` makes much more sense than `P * V * M`.

**Comment by cprogrammer1994** [comment]
`proj * lookat` is from the times of Python 3.4 where there was no `@` operator.

I think the code you pasted is using `Pyrr` and the `*` operator does a `@` internally.
I was looking for `glm` like python modules. Unfortunately I found out that different projects have different dependency on how a module like `glm` should work.
In most of the cases the best option I have is to write a minimal wrapper over [glm](https://glm.g-truc.net) and use either floats or doubles, a single matrix or an array of matrices, ... I can build it directly for the project's needs. However there are a lot of similar python wrappers: pyrr, numpy, transforms3d, miniglm, pyglm.

**Comment by einarf** [comment]
The state of matrix math libraries in python is a bit messy. Especially if you want performance 🙃

What operators are supported in pyrr depends if you are using the Object Oriented or Procedural interfaces. The procedural interface return ndarrays that would indeed just do elementwise multiplication while the `Matrix*` types do have proper operators. It can be very confusing.
