### ISSUE TITLE
Scopes and framebuffer

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#329]
I think framebuffer should be optional in scopes. Using scopes is alone a great way to make efficient and compact render calls just for textures and uniform buffers alone. Consider the situation below:

```python
def render(self, time=0.0, frametime=0.0, target: moderngl.Framebuffer =None):
    with self.scope:
        self.vao.render(mode=moderngl.TRIANGLES)
```

Above we take a `target` framebuffer so I could easily switch to rendering this content in an offscreen buffer, but I would have to dynamically create a new scope for each target. Consider a more extreme example were you want to render a scene with 50 vaos to a different framebuffer.

This is why I think making all parameters to scopes optional is a better idea.

```
bind fbo
render 50 scopes
...
```

**Comment by cprogrammer1994** [comment]
I think the `new` was designed this way. I also made `enable_only` the first parameter and moved framebuffer to be the second and optional.

**Comment by cprogrammer1994** [comment]
https://github.com/moderngl/moderngl/blob/master/examples/next/crate.py#L65

**Comment by einarf** [comment]
Might be even better if all of them are optional. If a user has prepared scopes with texture and uniformbuffer bindings it could be the case they want to render that with blending separately in a different pass. A scope with no parameters could then do absolutely nothing.

**Comment by cprogrammer1994** [comment]
ModernGL 6 has this, closing
