### ISSUE TITLE
glDebugMessageCallback

### ISSUE THREAD

**Issue by alanjfs** [moderngl/moderngl#330]
Hi @moderngl!

I'm looking for this member, and can spot traces of it but aren't sure how or if that this maps to Python:

https://github.com/moderngl/moderngl/blob/517f22ad269e71ff7dbbd41fcd50507d9c65a1ae/moderngl/mgl/internal/opengl/gl_methods.cpp#L607

I've searched in the root `moderngl` namespace, as well as the Context with no luck, and I've made sure to use OpenGL 4.3 since it seems to only be available there.

Should this member be available already, and if not, is there any other way I can access it?

Thanks!

Edit: Adding to this, as I'm new to moderngl I'm not quite sure; is there a _need_ for this member from Python? I can also imagine moderngl automatically provides a callback for this internally.

**Comment by cprogrammer1994** [comment]
Hi!

ModernGL does not use `glDebugMessageCallback`

The headless context is also created without the DEBUG bit set. It cannot be parameterized from python at the moment.

ModernGL loads all the OpenGL functions available according to the OpenGL 4.6 core specification.

A filtered subset can be made with ~50 functions in use, it does not improve performance so I never made it.

---

ModernGL uses OpenGL internally.
Most of the objects expose their OpenGL objects through the `glo` property.
The `glo` is an undocumented property that lets the user implement functionality that ModernGL does not expose.

ModernGL does not expose the OpenGL functions it loaded, however one can access the context's internal state that contains the struct `GLMethods`. The property is called `glprocs`. There is an example in the travis build.

---

I will need a good example and a short description of how would you like to use `glDebugMessageCallback` through ModernGL.
We can discuss whether to add it to the list of features or not.

Any simple pure OpenGL examples helps to identify if `glDebugMessageCallback` should be part of ModernGL.

**Comment by alanjfs** [comment]
Thansk @cprogrammer1994, I think that I should have investigated better before submitting this request, as what I was looking for was warning and error messages from compiling shaders, but so far they've been great already so my original concern was unwarranted. I'll close this, it's not necessary for my purposes.
