### ISSUE TITLE
ModernGL 5 maintenance

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#332]
- moderngl5 will have a single (minor) release adding new features to allow the users to become compatible with moderngl6, these changes should be 100% backward compatible.

- moderngl5 will have some (patch) releases: bug fixes, fixes for unintended behavior, no new features.

Preventing incompatibilities:

Staying at **5.5.x** is recommended for those who will not upgrade to moderngl6:

```
pip install "moderngl<5.6.0"
```

Including releases with forward compatibility:

```
pip install "moderngl<6.0.0"
```

**Comment by einarf** [comment]
This is probably good to include in `README.md`?

**Comment by cprogrammer1994** [comment]
Prepared #337
Branch: https://github.com/moderngl/moderngl/tree/moderngl-5.5.x

**Comment by cprogrammer1994** [comment]
I will update the readme soon.

**Comment by cprogrammer1994** [comment]
5.5.3 is ready
official branch at https://github.com/moderngl/moderngl/tree/moderngl-5.5.x
README with the upgrade notes will be part of 5.6.x

**Comment by einarf** [comment]
Closing this since we're definitely adding new stuff to 5.x while trying to get 6 up and running on the side.
