### ISSUE TITLE
ModernGL 6 Release

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#333]
The first minor version of moderngl6 will have maximized backward compatibility with the compatibility features of the upcoming moderngl 5.6.x.

Some of the backward compatible features of moderngl6 will be marked as deprecated.

This release is a long plan, moderngl5 will still receive maintenance updates.

**Comment by cprogrammer1994** [comment]
more about moderngl5 maintenance https://github.com/moderngl/moderngl/issues/332

**Comment by einarf** [comment]
There is a `docs/next` directory in master branch. Is this still relevant?

Seeing that `next` has moved most of the python wrapper classes I'm not entirely sure how to generate docs with sphinx. I'm sure there is a solution 😄 

Any idea on how to approach this if I plan to start putting some docs together?

**Comment by einarf** [comment]
Made moderngl 6 project here : https://github.com/moderngl/moderngl/projects/10
