### ISSUE TITLE
Feature Requests for ModernGL 6

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#334]
I plan to add a list of features here, features I did not manage to implement for ModernGL 5.

**Comment by cprogrammer1994** [comment]
https://github.com/moderngl/moderngl/pull/247 is a must have (probably working already have to check)

**Comment by cprogrammer1994** [comment]
https://github.com/moderngl/moderngl/pull/248 will be possible to be done from Python. It will be configurable.

**Comment by cprogrammer1994** [comment]
https://github.com/moderngl/moderngl/issues/321

**Comment by cprogrammer1994** [comment]
Point size and line width should work in the [0, 1] range, most of the use cases require point size > 1 pixels. I plan to add examples for textured sprites.

Do we need https://github.com/moderngl/moderngl/issues/253 if there were examples for geometry shader powered sprites?

**Comment by cprogrammer1994** [comment]
https://github.com/moderngl/moderngl/issues/220 must have for compute shaders.

Scopes will cover image units.

**Comment by cprogrammer1994** [comment]
#208

**Comment by cprogrammer1994** [comment]
#345

**Comment by cprogrammer1994** [comment]
Do not use the glMulti calls for indirect rendering (unless needed)
#346

**Comment by einarf** [comment]
Exposing a `dict` structure of extensions in the context would also be nice (The same way we expose the `info` structure.

```python
ctx.extensions['GL_ARB_texture_storage']
```

I can just dump this out from the spec file. Easy enough to add. for 5.6 and 6.x.

**Comment by cprogrammer1994** [comment]
what should the `ctx.extensions['GL_ARB_texture_storage']` return?

**Comment by einarf** [comment]
I was thinking about just storing true, but I guess it can just be a `set()` or something.
```c++
int num_ext;
glGetIntegerv(GL_NUM_EXTENSIONS, &num_ext);
# loop i -> num_ext
glGetStringi(GL_EXTENSIONS, i)
```

Just realized the extensions are just stored as stings, so it's simply just populating a set.

**Comment by einarf** [comment]
5,5,4 has `glBlendFuncSeparate` and `glBlendEquationSeparate` #353

I think I saw moderngl using them as well, but only `glBlendFunc` and `glBlendEquation`.
Fairly easy to adapt to the `Separate` variation.

**Comment by einarf** [comment]
#341 is now also implied for moderngl 6, but is already fixed in glcontext, so it will be part of 5.6 and 6.

**Comment by einarf** [comment]
I would also check that this issue was not copied over the moderngl 6 so we revive this bug: #355

These should not be fetched in `Contex.info` as they are deprecated and raise `GL_INVALID_ENUM`
```
GL_MAX_VARYING_COMPONENTS
GL_MAX_VARYING_VECTORS
```

Small things like this causes confusion among users. Especially users mixing moderngl and pyopengl.

**Comment by einarf** [comment]
#356 scissor support. This was actually not that complicated to add.
