### ISSUE TITLE
Resize Buffer object

### ISSUE THREAD

**Issue by lordmauve** [moderngl/moderngl#335]
As far as I can tell it is not currently possible to resize a VBO using `moderngl` as of 5.5.2.

`buffer.write()` always uses `gl.BufferSubData()` which requires that writes are fully contained within a buffer.

Only `buffer.orphan()` calls `gl.BufferData()` to allocate a new buffer, but [it passes the existing size](https://github.com/moderngl/moderngl/blob/e3e8f8ea93988ed06bb4954568f8864d3e1136c9/moderngl/old/Buffer.cpp#L486).

I'd like to grow buffers without reallocating the VAO.

Given I'm not actually calculating byte sizes myself (I'm passing numpy arrays) and I created the buffer with

```vbo = ctx.buffer(vertarray)```

I'd suggest something unlike `orphan()` and closer to the constructor, eg.

```vbo.reallocate(newvertarray, reserve=0)```

**Comment by cprogrammer1994** [comment]
the major next version will use `glBufferStorage` if available, so it will be better to release + create a new buffer.
