### ISSUE TITLE
Unable to recover render context after grabbing a texture with Image(...,texture.read(),...) with PyQt5

### ISSUE THREAD

**Issue by pavelkrupala** [moderngl/moderngl#339]
Hello,
so the issue is as title says, here is min setup:
window:
```
class QModernGLWidget(QOpenGLWidget):
   def __init__(self, parent=None):
        super().__init__(parent)
        fmt = QSurfaceFormat()
        fmt.setVersion(4, 1)
        fmt.setProfile(QSurfaceFormat.CoreProfile)
        fmt.setSamples(0)
        self.setFormat(fmt)
        self.timer_update = QTimer()
        self.timer_update.timeout.connect(self.update)
        self.timer_update.start(0)
        # self.scene = Scene(self.ctx, self)
    def paintGL(self):
        self.ctx = moderngl.create_context()
        self.screen = self.ctx.detect_framebuffer()
        ... 
        self.scene.render()
    def keyPressEvent(self, event):
        if event.key() == Qt.Key_F11:
            img = Image.frombytes('RGB', self.scene.texture.size, self.scene.texture.read(), 'raw', 'RGB', 0, -1).show()
            self.ctx.detect_framebuffer().use()
```

the Scene:
```
class Scene():
    def __init__(ctx, wnd):
            size = (1024, 1024)
            self.texture = self.ctx.texture(size, components=3, dtype='f1')
            depth_attachment = self.ctx.depth_renderbuffer(size)
            self.fbo1 = self.ctx.framebuffer(self.texture, depth_attachment)
    def render(self):
        # render to texture
        self.fbo1.use()
        self.fbo1.clear(0, 0, 0, 0)
        self.vao.render()
        # render to screen
        self.wnd.screen.use()
        self.wnd.screen.clear(0,0,0,0)
        self.vao.render()
        self.ctx.finish() 
```

And here is the strange thing:
This works, and after showing & closing window, rendering resumes (1):
```
Image.frombytes('RGB', self.scene.texture.size, self.screen.read(), 'raw', 'RGB', 0, -1).show()
```
However when using (2):
```
Image.frombytes('RGB', self.scene.texture.size, self.scene.texture.read(), 'raw', 'RGB', 0, -1).show()
```
the texture is grabbed correctly, but the render to window is not working anymore

RenderDoc 1.20 win7, py36 says:
1. Texture98 is being rendered (correctly)
Colour Pass #1
    glClear
    glDrawElementsInstanced(6,1)
    glFinish()
    glFlush()
2. Texture87 is being rendered (correctly)
Colour Pass #2 
    glClear
    glDrawArrays(6)   --> **input: FS0 textureSampler** => output: FB0 Backbuffer Color
    glDrawArrays(6)
SwapBuffers()

the difference between (1) and (2) is in the **highlighted input FS0**. In the second case, when self.texture.read() has been called, the input is empty and it doesn't bind the *Texture87* - the result of Colour Pass #1. *Texture87* is rendered correctly and is the result of (as mentioned above) :
```
        self.wnd.screen.use()
        self.wnd.screen.clear(0,0,0,0)
        self.vao.render()
```

Does please anyone have a clue how to rebind the rendering result back?

Thanks for your time.

**Comment by cprogrammer1994** [comment]
Reading the default framebuffer does not work correcly.

please try this workaround:

use ctx.finish() or glFinish from some other library
use glFlush from some other library
sleep one second after the last draw you expect to be on the screen

do the `self.screen.read()`

With my integrated card I get different results with my dedicated gpu.
I usually get 1 frame from the past and I need the sleep too.

I think this can be bug in my driver too.

If you render to a framebuffer you need nothing special before the read.
The final step can be a blit from the fbo to the screen.
This is the best solution, you will also know what internal types your framebuffer have.
Blit can be done with the ctx.copy_framebuffer
