### ISSUE TITLE
Releasing standalone context

### ISSUE THREAD

**Issue by adshhzy** [moderngl/moderngl#341]
I am working in a circumstance where I need to create standalone context then release them iteratively. But I found that ctx.release() seems not releasing the context as I expect. Here is the code for a test:

    for i in range(400):
        print(i)
        ctx = moderngl.create_standalone_context()
        ctx.release()
        del ctx

Error happens when i = 360:
    ctx.mglo, ctx.version_code = mgl.create_standalone_context(settings)
    moderngl.error.Error: cannot create OpenGL context

Looks like it hits the maximum amount of context allowed, so the question here is what is the correct way to release a context.

Version: 5.5.3.
platform: MacOS

**Comment by einarf** [comment]
It seems releasing a context is not implemented at the moment.
https://github.com/moderngl/moderngl/blob/d60d9ce1212967091b049a52152b3fb5a73aa582/moderngl/old/Context.cpp#L449-L453

**Comment by cprogrammer1994** [comment]
I help to solve this issue. We will create a branch for this.

moderngl version? platform?

**Comment by einarf** [comment]
It seems @adshhzy edited the post adding:
```
Version: 5.5.3.
platform: MacOS
```

**Comment by einarf** [comment]
I can try to get this working on OS X. I'm guessing we only allow releasing standalone contexts. Maybe we could get this sorted out on all 3 platforms?

**Comment by einarf** [comment]
Experiments going on here at the moment : https://github.com/moderngl/glcontext

**Comment by cprogrammer1994** [comment]
OpenGL context creation will likely be extracted from moderngl and provided separately

**Comment by einarf** [comment]
This is now fixed in glcontext. Unittests will create and destroy 1000 contexts and inspect the memory consumption of the process before and after.

That means 5.6 and 6.x will fix this issue,
