### ISSUE TITLE
Fuse Texture and Texture3D to handle 2D, 3D (and 1D) textures

### ISSUE THREAD

**Issue by pohlt** [moderngl/moderngl#342]
When I look into texture.py and texture_3d.py I wonder why you chose to separate these two classes. IMHO their overlap is big enough to try to squeeze them into one class and - on top of that - add support for 1D textures.

I'm sure you had good reasons for taking a different approach, so I'm not even trying to come up with a PR before I understand these reasons. :-)

moderngl rocks, btw. Thanks for your hard work!

Cheers, Tom

**Comment by einarf** [comment]
moderngl6 will do exactly this, so we're on the same page :)

**Comment by pohlt** [comment]
Great minds think alike! Awesome!


________________________________

**Comment by cprogrammer1994** [comment]
nice catch, moderngl 6 supports all kind of textures from a single class called `Texture`

**Comment by einarf** [comment]
Closing this one. Be free to re-open if needed,
