### ISSUE TITLE
Doc issue: Program.uniforms no longer available

### ISSUE THREAD

**Issue by pohlt** [moderngl/moderngl#343]
The docs state that uniforms can be accessed via `Program.uniforms`:https://github.com/moderngl/moderngl/blob/b6c1e241839b0db098a7b7d560c45bb35a7e8091/moderngl/program_members/uniform.py#L9

I'm using 5.5.3 and this attribute is no longer available.

Best,
Tom

**Comment by cprogrammer1994** [comment]
thank you for the issue, it must be a bug, 5.5.x should have these uniforms accessible.

**Comment by cprogrammer1994** [comment]
you are right, the docs are not proper, moderngl 5 exposes the uniforms through `__getitem__`

**Comment by einarf** [comment]
I added these missing methods in 5.5.4 as well.
![Capture](https://user-images.githubusercontent.com/5418180/68521405-0ed43580-02a1-11ea-8f2a-567fd0307893.JPG)

**Comment by einarf** [comment]
Fixed in 5.5.x branch: 566ede7abe738a8df8b8f4e92c955577df788124

Probably need work in 5.x / 5.6 as well, so keeping this open.

**Comment by georgem3** [comment]
Am I missing something or are uniforms still inaccessible in 5.5.4?

**Comment by einarf** [comment]
@georgem3 Updates docs here should help you: https://moderngl.readthedocs.io/en/latest/reference/program.html#moderngl.Program.__iter__

**Comment by einarf** [comment]
Closing this for now. Please poke if anything is still unclear. All changes have been moved into master.

I'll stick to doc improvements in master / 5.6 from now on. These changes will show up in `latest` until 5.6 is out.
