### ISSUE TITLE
Misleading example for using textures

### ISSUE THREAD

**Issue by pohlt** [moderngl/moderngl#344]
I saw the discussion in #135 about using multiple textures.

For my application I just looked at the simpler example in
https://github.com/moderngl/moderngl/blob/master/examples/basic_colors_and_texture.py

IMHO, this example is misleading because it relies on two implicit features:
1. Texture.use() uses a default value of 0 which is the correct value only for single-texture use cases. My suggestion would be to remove the default value.
2. The uniform for the texture sampler is implicitly initialized with 0 which is also only working correctly for single-texture use cases.

To improve the example, I would replace

        self.use_texture.value = True
        self.texture.use()

        self.vao_image.render()

by something like this

        self.use_texture.value = True

        TEXTURE_ID = 0  # of course it would be nicer to move this out of the rendering method
        self.prog['Texture'] = TEXTURE_ID 
        self.texture.use(TEXTURE_ID)

        self.vao_image.render()

I know it's in the docs for `Texture.use` but still I think this example might bite some first-time users.

**Comment by einarf** [comment]
I guess this at least can be more explicit with comments like this?

```python
# Instruct the program uniform the read from texture unit 0
self.prog['Texture'] = 0
# Bind the texture to texture unit 0
self.texture.use(location=0)
```

**Comment by pohlt** [comment]
Sure, works as well.

What do you think about the default location value?
Saves you _one single character_ and only works correctly if you have zero or one texture. Chances are, if you use one texture, you most likely use multiple at some point and then you start wondering why you always see just one texture... ;-)

**Comment by cprogrammer1994** [comment]
in moderngl 6 there will be no default value for textures or samplers, they must be assigned when scopes are created, this may change before we release it.

currently it is a bad thing to allow the user to assign textures directly to texture units.
The other way is to create samplers with textures assigned, when assigning the sampler, the textures will be assigned accordingly.

Samplers were added way after textures were part of moderngl. this is why the design is not proper within the `use()`

**Comment by cprogrammer1994** [comment]
the default value was added for single texture programs where you don't have to set the value of the sampler2D, nor the location in `use()`

**Comment by cprogrammer1994** [comment]
in moderngl 6 it should look similar to this:

```py
texture = ...
sampler = ctx.sampler(texture, ...)
vao = ...
vao.scope = ctx.scope(samplers=[sampler.assign(0), ...])

# and in render:
vao.render()
```

**Comment by einarf** [comment]
I've added a note to the documentation improvement project : https://github.com/moderngl/moderngl/projects/8

**Comment by einarf** [comment]
Looks like this could fit into the redering guide or opengl introduction.

**Comment by einarf** [comment]
Updated api docs with more information about the `use(location)` method. f0529c20e0b875f9c6ff6ad1d3fa1a20001bf563

Texture units and binding will also be covered in a guide later.
