### ISSUE TITLE
Mipmaps for TextureCube

### ISSUE THREAD

**Issue by pohlt** [moderngl/moderngl#345]
Since you plane to refactor texture handling anyway, please also add a method to generare Mipmaps for `TextureCube`.

According to https://www.khronos.org/opengl/wiki/Cubemap_Texture, one should also do this

        glEnable(GL_TEXTURE_CUBE_MAP_SEAMLESS)

but it seems you are already doing this by default in `Context`.

**Comment by cprogrammer1994** [comment]
`glEnable(GL_TEXTURE_CUBE_MAP_SEAMLESS)` is called on initialization

`build_mipmaps` will be available for all kind of textures that supports it. the number of texture levels must be provided when creating the texture. -- internally we will use glTexStorage... when available and fallback to the glTexImage... when needed.

**Comment by einarf** [comment]
Added notice about this in 5.6 / master.

![Capture](https://user-images.githubusercontent.com/5418180/70867965-cda80300-1f7b-11ea-8aef-68cde31674ea.JPG)
