### ISSUE TITLE
Crash when undocking moderngl in dock widget and VAO uses index_buffer (PyQt5)

### ISSUE THREAD

**Issue by pavelkrupala** [moderngl/moderngl#348]
**Description**

PyQt5, moderngl widget in docking window -- When dockWnd is undocked, python crashes.
This happens only when VAO is using index_buffer. My guess is that when undocking, the context is changed, and data where index_buffer is pointing are lost. It looks like C++ error, because I'm trying to catch every possible exception in python.

**Proof of code**

comment out lines @51 or @54 to see the issue - you have to undock the dockWidget when app is running.

```py
import sys
import moderngl
import traceback
import numpy as np
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

def dumpException(): traceback.print_exc()

class MyScene:
    def __init__(self, ctx, wnd=None):
        self.ctx = ctx
        self.wnd = wnd
        self.init()

    def init(self):
        self.prog = self.ctx.program(
            vertex_shader='''
                        #version 330

                        in vec2 in_vert;

                        void main() {
                            gl_Position = vec4(in_vert, 0.0, 1.0);
                        }
                    ''',
            fragment_shader='''
                        #version 330

                        out vec4 f_color;

                        void main() {
                            f_color = vec4(0.3, 0.5, 1.0, 1.0);
                        }
                    ''',
        )

        vertices = np.array([
            0.0, 0.8,
            -0.6, -0.8,
            0.6, -0.8,
        ])

        indices = np.array([0,1,2])

        self.vbo = self.ctx.buffer(vertices.astype('f4').tobytes())
        self.ibo = self.ctx.buffer(indices.astype('i4').tobytes())

        # this is working
        self.vao = self.ctx.simple_vertex_array(self.prog, self.vbo, 'in_vert')

        # but this crashes when dockWnd is undocked/floating
        self.vao = self.ctx.simple_vertex_array(self.prog, self.vbo, 'in_vert', index_buffer=self.ibo)

    def render(self):
        self.ctx.clear(0,0,0,0)
        self.vao.render()


class QModernGLWidget(QOpenGLWidget):
    SceneClass = MyScene

    def __init__(self, parent=None):
        super().__init__(parent)  # fmt, None)
        fmt = QSurfaceFormat()
        fmt.setVersion(4, 1)
        fmt.setProfile(QSurfaceFormat.CoreProfile)
        fmt.setSamples(0)
        self.setFormat(fmt)

        self.timer = QElapsedTimer()
        self.timer.restart()
        self.timer_update = QTimer()
        self.timer_update.timeout.connect(self.update)
        self.timer_update.start(0)

    def initializeGL(self):
        pass

    def restart(self, w, h):
        try:
            print("Preview GL Restarting")
            self.resize(w, h)
            self.ctx.viewport = (0, 0, w, h)
            self.scene = self.__class__.SceneClass(self.ctx, self)
        except: dumpException()

    def paintGL(self):
        try:
            self.ctx = moderngl.create_context()
            self.screen = self.ctx.detect_framebuffer()
            self.init()
            self.render()
            self.paintGL = self.render
        except: dumpException()

    def init(self):
        self.resize(512, 512)
        self.ctx.viewport = (0, 0, 512, 512)
        self.scene = self.__class__.SceneClass(self.ctx, self)

    def render(self):
        try:
            self.screen.use()
            self.ctx.clear(0, 0, 0, 0)
            self.scene.render()
        except: dumpException()


class MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setGeometry(100, 100, 640, 480)
        self.setCentralWidget(QLabel("central widget"))
        self.show()

        self.dock = QDockWidget("MyDock")
        self.addDockWidget(Qt.RightDockWidgetArea, self.dock)
        self.widget = QModernGLWidget(self.dock)
        self.dock.setWidget(self.widget)
        self.dock.setMinimumWidth(300)
        self.dock.topLevelChanged.connect(self.onTopLevelChanged)

    def onTopLevelChanged(self, value):
        print("Dock is floating?", value)
        w, h = self.dock.width(), self.dock.height()
        self.widget.restart(w, h)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    wnd = MainWindow()
    sys.exit(app.exec_())


```

**Expected behavior**

Expecting python not to crash

**Version info**

Running on woe7 OS (windows)

```
moderngl 5.5.3
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 970/PCIe/SSE2
version: 4.6.0 NVIDIA 436.02
python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
platform: win32
code: 460
```

**Comment by einarf** [comment]
Not entirely sure what is happening here because I'm not familiar with the `QOpenGLWidget` yet.

When debugging on windows I see that things are working until you undock it. `initializeGL` is called and it crashes on the next `render`, so I assume there is something you need to do in `initializeGL`.

Also, on Linux and OS X the widget doesn't display anything.

**Comment by einarf** [comment]
Isn't this more reasonable? `initializeGL` I guess is called on context initialization / re-creation, but there are no framebuffer created yet, so we'll query for it in `render` instead. This fixes the issue for me on windows at least. The only crash I have is when I dock the window back in the top in hidden mode. I don't know why.

```python
    def initializeGL(self):
        self.ctx = moderngl.create_context(require=330)
        self.init()

    def paintGL(self):
        self.screen = self.ctx.detect_framebuffer()
        self.screen.use()
        self.scene.render()
```

**Comment by einarf** [comment]
I think the other problem might related to using timers to call `self.update` because this triggers `paintGL` when the window is not in a state to actually render anything? (Fully hidden framebuffer)

Might be wrong, but this is entirely dependent on what you are trying to render.

**Comment by pavelkrupala** [comment]
Damn... it looks like it is working and not loosing any contexts/framebuffers. I was just using code from moderngl-window and yes, you're right with using those initializeGL and paintGL much simpler way it looks it's working now... I'll still do some tests.

Thank you very much for help

**Comment by pavelkrupala** [comment]
Okay, so the issue still remains, however I've cleaned up the widget class code:
```py
class QModernGLWidget(QOpenGLWidget):
    SceneClass = MyScene

    def __init__(self, parent=None):
        super().__init__(parent)  # fmt, None)
        fmt = QSurfaceFormat()
        fmt.setVersion(4, 1)
        fmt.setProfile(QSurfaceFormat.CoreProfile)
        fmt.setSamples(0)
        self.setFormat(fmt)

        self.scene = None

        self.timer = QElapsedTimer()
        self.timer.restart()
        self.timer_update = QTimer()
        self.timer_update.timeout.connect(self.update)
        self.timer_update.start(0)

    def initializeGL(self):
        print("\nInitGL called")
        self.timer_update.stop()
        if self.scene is None:
            print("  for the first time... init Ctx,Screen,..")
            self.ctx = moderngl.create_context()
            self.screen = self.ctx.detect_framebuffer()

        self.init()
        self.dump()
        print("Default FBO:", self.defaultFramebufferObject())

        self.timer_update.start(0)

    def init(self):
        if self.scene is None:
            # if you do this always, it won't crash
            self.scene = self.__class__.SceneClass(self.ctx, self)
            print("created scene", self.scene)

    def resizeGL(self, w, h):
        self.ctx.viewport = (0, 0, w, h)
        self.update()
        print("Preview GL resized:", w, h)

    def dump(self):
        print("CTX:", self.ctx, hex(id(self.ctx)))
        print("SCREEN:", self.screen, hex(id(self.screen)))
        print("SCENE:", self.scene)

    def paintGL(self):
        self.screen = self.ctx.detect_framebuffer()
        self.screen.use()
        self.render()

    def render(self):
        self.ctx.clear(0, 0, 0, 0)
        self.scene.render()
```

the topLevelChanged connection is not necessary and here lies the problem:
- if you dock/undock initializeGL is being called
- that calls QModernGLWidget.init():
1) if you recreate the Scene() object entirely you are good to go, nothing crashes, window updates even after undocking
2) if you **don't** create new instance of Scene(), then you are in troubles. 
This will leave you with black screen when you undock
```py
        # this is working
        self.vao = self.ctx.simple_vertex_array(self.prog, self.vbo, 'in_vert')
```
and this will cause you an crash
```py
        # but this crashes when dockWnd is undocked/floating
        self.vao = self.ctx.simple_vertex_array(self.prog, self.vbo, 'in_vert', index_buffer=self.ibo)
```

However few important notes:
- now you never re-create Context object
- self.screen -- 
at the beginning is 
SCREEN: <Framebuffer: 0> 0x479e5f8
after undocking:
SCREEN: <Framebuffer: 1> 0x479e660
interesting fact: when you print out `screen` in renderGL function it will be Framebuffer: 1, oscilating between two different obj ids (double buffering) which is correct

But sill I believe this is an issue because all objects in MyScene (if I'm correct) should be bound onto a single instance of Context, which doesn't change... 
Question is: why does it even work, if you just re-create MyScene instance, with the same Context?
What happened?

**Comment by einarf** [comment]
One theory without testing out things : 
I'm suspecting the vao crash is related to the fact that empty VAOs are legal to render. VAOs with empty index buffer is not allowed and will cause a crash. This describes exactly what you are seeing.

This indicates the gl context is indeed destroyed and one should assume a new one is always created before `initializeGL` is called. All moderngl objects must be discarded when the context is destroyed.

**Comment by pavelkrupala** [comment]
yup I guess that's probably happening...
I put print in paintGL of id(Context), Context.mglo and Context.error and I got:
```
...
self.ctx.error GL_NO_ERROR
71304912 <mgl.Context object at 0x0000000021869620>
self.ctx.error GL_NO_ERROR
71304912 <mgl.Context object at 0x0000000021869620>

InitGL called
CTX: <Context> 0x44006d0
SCREEN: <Framebuffer: 1> 0x43ce5f8
SCENE: <__main__.MyScene object at 0x0000000004AE4A90>
Default FBO: 0
Preview GL resized: 300 480
self.ctx.error GL_NO_ERROR
71304912 <mgl.Context object at 0x0000000021869620>

Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by pavelkrupala** [comment]
So I was fiddling around many hours with this and find out:
- yes, context can be switched / destroyed
- the crashes are happening due to missing/invalid context
- plain OpenGL functions we're handling this exception/error saying error at: bind vertex array (for IBO) invalid Operation and also returning the ID number of the vertex buffer -- modernGL is **NOT** saying a thing (that could possibly change)
- reading more about the docs of QOpenGLWidget:
```Your widget’s OpenGL rendering context is made current when paintGL() , resizeGL() , or initializeGL() is called. If you need to call the standard OpenGL API functions from other places (e.g. in your widget’s constructor or in your own paint functions), you must call makeCurrent() first.
```
so all can be fixed when recreating (usually from un/docking) or any other place by adding **makeCurrent()** call, too these functions first.

I guess we can close it now :) but good to know about this.

**Comment by einarf** [comment]
Awesome. I'll let this hang around a bit as I might use some of the info here to make a standard widget for moderngl-window (for both pyside and pytq5). It has definitely been useful.

**Comment by pavelkrupala** [comment]
yeah it will, that could go to some wiki or knowledge base. Thanks for your help again too :)

**Comment by einarf** [comment]
Closing this. We already reference this issue from moderngl-window as it contains useful information.
