### ISSUE TITLE
Document memory management / object discard

### ISSUE THREAD

**Issue by pootle** [moderngl/moderngl#349]
There's nothing in the docs about how to discard buffers, vertex arrays, programs etc. If the app drops all references to them, do they just get closed down as part of garbage collection?

Or should I call release explicitly when I'm finished with something?

Is there an order in which release should be called? - e.g. vertex array, then the buffers used in the array?

**Comment by einarf** [comment]
In 5.x you need to call `release()` to destroy the allocated OpenGL resource.

For vertex array the release order doesn't really matter as long as you release the vertexarray object and the necessary buffers (They can be reused in multiple vertexarrays).

I've added this issue to the documentation improvement project.

**Comment by einarf** [comment]
This is now in docs
