### ISSUE TITLE
Document rendering with xvfb

### ISSUE THREAD

**Issue by francoisruty** [moderngl/moderngl#350]
**Description**

Currently on moderngl 5.5.2 it's not possible to create a standalone context.

**Proof of code**

```py
import moderngl
ctx = moderngl.create_standalone_context()


```

**Expected behavior**

I expected the ctx object to be created. Instead, I get this:
>>> import moderngl
>>> ctx = moderngl.create_standalone_context()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/moderngl/context.py", line 1234, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_standalone_context(settings)
NameError: name 'mgl' is not defined

**Version info**

This command does not work, I get:

root@9daaf49c2017:/app/fruty# python -m moderngl
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/moderngl/__main__.py", line 50, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/moderngl/__main__.py", line 33, in main
    ctx = moderngl.create_standalone_context()
  File "/opt/conda/lib/python3.7/site-packages/moderngl/context.py", line 1234, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_standalone_context(settings)
NameError: name 'mgl' is not defined

Version is 5.5.2.
I installed pip via conda, and then pip install moderngl

**Comment by einarf** [comment]
What about 5.5.3?

**Comment by francoisruty** [comment]
So what I pasted above was for:
install pip via conda
pip install moderngl

Now if I try with the "classic" pip (installed via apt-get install python3-pip):
import moderngl
ctx = moderngl.create_standalone_context()

>>> ctx = moderngl.create_standalone_context()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/moderngl/context.py", line 1173, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_standalone_context(settings)
moderngl.error.Error: cannot detect the display


So it seems there are 2 issues with moderngl 5.5.2:

- install via pip does not work when pip itself was installed via conda
- install via classic pip: moderngl.create_standalone_context() does not work, the whole point of create_standalone_context is to work without display so we shouldn't get this "cannot detect display" error

**Comment by francoisruty** [comment]
by the way it's really weird I used 5.5.2 2 or 3 months ago and I didn't have any of those problems, was the released version changed after its initial release?

**Comment by francoisruty** [comment]
OK so I got news
I was missing this lib: libgl1-mesa-glx

now that I installed it,
ctx = moderngl.create_standalone_context()
yields:
>>> ctx = moderngl.create_standalone_context()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/moderngl/context.py", line 1234, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_standalone_context(settings)
moderngl.error.Error: cannot detect the display

whatever the way pip was installed (via conda or via apt-get)

**Comment by cprogrammer1994** [comment]
> cannot detect the display

Please make sure `glxinfo` works.

glxinfo is available in the `mesa-utils` apt package.

**Comment by francoisruty** [comment]
thanks for the intel, I installed xvfb and now it works, but I'm interested in other alternatives, what do you mean by "glxinfo works", once I installed it, do I have to run a binary or something?

thanks

**Comment by cprogrammer1994** [comment]
> what do you mean by "glxinfo works"

Here is an example:

```shell
root@droplet:~# glxinfo | grep version
Error: unable to open display

root@droplet:~# python3 -m moderngl
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/moderngl/__main__.py", line 50, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/moderngl/__main__.py", line 33, in main
    ctx = moderngl.create_standalone_context()
  File "/usr/local/lib/python3.6/dist-packages/moderngl/context.py", line 1173, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_standalone_context(settings)
moderngl.error.Error: cannot detect the display

root@droplet:~# xvfb-run glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.0.8
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.1 Mesa 19.0.8
OpenGL shading language version string: 1.40
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

root@droplet:~# xvfb-run python3 -m moderngl
libGL error: failed to create drawable
libGL error: failed to create drawable
moderngl 5.5.3
--------------
vendor: VMware, Inc.
renderer: llvmpipe (LLVM 8.0, 256 bits)
version: 3.3 (Core Profile) Mesa 19.0.8
python: 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0]
platform: linux
code: 330
```

I usually mention `glxinfo` because the internet is full of help on how to get it working.

When glxinfo returns no error, moderngl will likely to work as well.

**Comment by francoisruty** [comment]
ok thx for the precision

**Comment by einarf** [comment]
The repo people usually go to:
https://github.com/cprogrammer1994/ubuntu-headless-ModernGL/blob/master/README.md

**Comment by einarf** [comment]
Docs now have ubunut 18 example : https://moderngl.readthedocs.io/en/latest/the_guide/headless_ubunut18_server.html
