### ISSUE TITLE
Build wheels for python 3.8

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#351]
Python 3.8 is out. We should probably build wheel for this soon. I suggest adding 3.8 wheels for 5.5.x, 5.6 and 6 (pre-release). Might give it a week or two at least to make dependecies catch up considerig libs like numpy and Pillow are not out yet.

moderngl master builds just fine with python 3.8 in windows.

**Comment by einarf** [comment]
py38 wheel check list
- [x] numpy : https://pypi.org/project/numpy/#files
- [ ] pillow : https://pypi.org/project/Pillow/#files
- [ ] matplotlib : https://pypi.org/project/matplotlib/#files
- [x] PyQt5 :  https://pypi.org/project/PyQt5/#files
- [x] PySide2 : https://pypi.org/project/PySide2/#files

**Comment by hugovk** [comment]
Pillow 6.2.1 has now been released with wheels for Python 3.8.

**Comment by einarf** [comment]
matplotlib now as pre-release (3.2.0rc1) with 3.8 wheels. Getting closer. Hopefully we'll get new wheels out this week.

**Comment by einarf** [comment]
Looks like it's going to take quite some time for dependecies to sort out 3.8 wheels, but these are not crucual for moderngl and are mostly used by examples. We can add a version guard in `examples/requirements.txt` for now.

**Comment by sol-prog** [comment]
@einarf Hello, SciPy 1.3.2 was just released, wheels for Python 3.8 are available.

**Comment by einarf** [comment]
Great! I have built 3.8 wheels for moderngl today. Just need to verify the linux wheels are properly working.

**Comment by einarf** [comment]
5.5.4 is on pypi with python 3.8 wheels for all platforms
