### ISSUE TITLE
Support glScissor

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#356]
It would be practical to support `glScissor` in 5.6 and 6.x.

We could support it globally in the context in framebuffer:
```python
# Will enable GL_SCISSOR_TEST in active fbo
ctx.scissor = 200, 200, 200, 200
# Set directly in fbo
fbo.scissor = 200, 200, 200, 200
```

We can also add an optional `scissor` parameter to `Scope`. Still we should probably ensure this can be compatible with moderngl 6.

**Comment by einarf** [comment]
I noticed how how awkward missing this feature is when making the imgui integration for moderngl.
I had to use `ctx.viewport` and calculate a new projection matrix for each draw call, something that is not every efficient and will degrade performance as the number of draw groups increases.

**Comment by fekga** [comment]
There is no glScissor yet? That's good to know, I was just about to use that.
Is there any workaround for this as I would like to make a shader render only in a RoI of the screen and the shader would take a long time if I would render the whole screen?

**Comment by einarf** [comment]
You can use `ctx.viewport` instead and adjust your projection matrix to render the correct geometry.

**Comment by einarf** [comment]
Adding some notes here to keep sanity:

* I don't really want to add more enable flags when possible
* The `Framebuffer` class uses scissor internally for `clear`, so it would be impractical having to `glIsEnabled` that state.
* Viewport is per framebuffer, and so should scissor
* When a framebuffer is created the default scissor value should be `(0, 0, width, height)`

What seems to be the most sane idea so far is:

We check if the scissor box set in the framebuffer matches the buffer size exactly.
```
(scissor_x, scissor_y, scissor_width, scissor_height) == (0, 0, width, height)
```

If this is not the case we enable `GL_SCISSOR_TEST` internally. 

Users can reset the scissor box by setting `scissor` to the framebuffer size or `None` can be assigned to reset the scissor values back to default.

```python
fb = ctx.framebuffer((100, 100), ...)
# Enable scissor
framebuffer.scissor =10, 10, 80, 80
# Disable (option 1)
framebuffer.scissor =0, 0, 100, 100
# Disable (option 2)
framebuffer.scissor =None
```

This makes the most sense after reading docs:
>  When a GL context is first attached to a window, width and height are set to the dimensions of that window. 
> When the scissor test is disabled, it is as though the scissor box includes the entire window. 


In moderngl 6 we can look into adding support for ` glScissorIndexed` when GL 4.1+ is detected.

**Comment by einarf** [comment]
Commit : 18d139c73ab795d88d80375517af85ff7ac9fac5

Looks like everything is working fine after a lot of testing.

Remaining:
* Support for `scissor = None` reset
* Unittests

**Comment by einarf** [comment]
All done, tested and with unit tests.
