### ISSUE TITLE
Better Error handling

### ISSUE THREAD

**Issue by pavelkrupala** [moderngl/moderngl#357]
**A simple use-case of the new feature**

currently when anything goes wrong and GL commands ends up with error (wrong IBO, lost context due Qt Black box magic) python results in crash.

When you write with PyOpenGL you will end up with an exception describing to you what is wrong.

**Describe the solution you'd like**

It's not an easy issue to tackle, however, what I want to say is, that something like a debug mode throwing exceptions, so python can catch them, would be really helpful. Especially helpfull will this be for new ppl or not-so-experienced-ppl-yet to help understand what are they doing wrong.

I mention Debug mode because of performance. Still less code = faster code...

**Version info**

All versions

**Comment by einarf** [comment]
We do actually have a `gltraces` package that could be used for this.
https://github.com/moderngl/moderngl/projects/9

Making that more available could actually be useful. 

Moved this into future ideas project for now : https://github.com/moderngl/moderngl/projects/9

It's not a high priority, but definitely an idea to pick up in the future! Thanks for making this issue.
