### ISSUE TITLE
Support transform feedback pausing and resuming

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#362]
This is an extremely simple and useful feature and helps us do things efficiently. One application is emitting new particles in a particle system. The geometry shader can discard dead particles leaving the output buffer partially filled. We can then switch shader and emit new particles filling the up remaining buffer.

https://www.khronos.org/opengl/wiki/Transform_Feedback#Feedback_pausing_and_resuming

Me and @lordmauve already talked about this on Discord.

**Comment by lordmauve** [comment]
> We can then switch shader

I don't believe it's possible to switch shader:

> To resume a paused feedback operation, you must do the following:
>
> * Bind the paused feedback object.
> * Bind the exact program or pipeline object that was used when glBeginTransformFeedback was called

However, you can bind a different input buffer, and it's *that* capability that is really useful. That allows me to use transform feedback to concatenate two buffers of particles, existing and newly emitted, where newly emitted particles are more directly under control of the CPU (eg. managing emitter objects).

**Comment by einarf** [comment]
@lordmauve Did you have any thoughts about how this could work? Just at a higher level (api) ..

**Comment by lordmauve** [comment]
I suggested that the transform operation could be a context manager. Then the input buffers could be rebound on the VertexArray inside the context (but I still haven't worked out how to do this, just because `VertexArray.bind()` doesn't take parameters that look anything like `Context.vertex_array()`).

Inside the context you would just use draw calls to transform another set of primitives and append the output to the target buffer.

So maybe

```python
with vao.transform_feedback(dest=buffer, mode=POINTS) as tf:
    tf.transform()
    vao.bind(...)
    tf.transform(...)
```

However lots of other operations are invalid during a transform feedback operation; ideally attempting these would raise.

**Comment by einarf** [comment]
Can you explain exactly what you want to do with some sample data? The devil in in the details here. There may be other ways to support this as well and I'm trying to build up a list of use cases.

**Comment by lordmauve** [comment]
I want to transform two buffers of particle data into one target buffer (with updates and expiring old particles). The first buffer will be particles from the previous frame. The second will be particles generated this frame, possibly on the GPU but more like (initially) a new buffer of data generated by the CPU.

**Comment by einarf** [comment]
Right now I'm thinking of a simpler solution. Feedback objects need `ARB_transform_feedback2` that requires OpenGL 4.0. A simpler solution in 5.6 could be:

* Support passing in a `buffer_offset` in `VertexArrray.transform` so you can output with an offset. This means you have control over offsets for both the source and destintation buffers.
* Use a `Query` object to capture the the actual number of primitives written by the geometry shader so you know where to resume.

```python
out_buffer = ctx.buffer(...)
query = ctx.query(...)

# Transform particles with geo shader discarding read ones
with query:
    vao1.transform(out_buffer)

# query.primitives should now give you an offset position you can use
# to continue filling the remaining part of the buffer
vao2.transform(out_buffer, buffer_offset=N)
```

This means you have several options:
* Fill the remaining part of the buffer using `out_buffer.write(data, offset=N)`
* Fill a new buffer and render that into the `out_buffer` using another transform feedback
* Fill the remaining part of the buffer with a shader generating the new data

This is a far more conservative approach that may fit 5.6 better and it doesn't add the complications of what is allowed to do in a context. This also fits perfectly with the 3.3 core profile.

**Comment by einarf** [comment]
I'll try to push this tomorrow. `BindBufferRange` seems to the the job being able to set offset. It remains if the offset should be in bytes or we can calcuate it from the varyings.

**Comment by einarf** [comment]
Fixed! Example here: https://github.com/moderngl/moderngl/blob/master/examples/particle_system_emit.py

It shows the simple approach writing to the end of the buffer directly, but the emit buffer variant is a lot more efficient. It really depends if you can get away with emitting a smaller slice of the buffer every frame, something that is usually the case.

Will add the 3rd variant doing gpu emitting soon.
