### ISSUE TITLE
"proj * lookat" is Hadamard (i.e., element-wise) product

### ISSUE THREAD

**Issue by yshhrknmr** [moderngl/moderngl#364]
**Description**

In most of the example codes (e.g., loading_obj_files.py), products of projection matrix P and model-view matrix M are written as P * M. However, since the pyrr.Matrix44 module returns numpy matrices, P * M is not a matrix product but an Hadamard (i.e., element-wise) product. This bug is catastrophic with some specific matrices.

**Proof of code**

```
proj = pyrr.matrix44.create_orthogonal_projection_matrix(-1., 1., -1., 1., 1., 10.)
lookat = Matrix44.look_at(
    (-4.0, 0.0, 0.0),
    (0.0, 0.0, 0.0),
    (0.0, 1.0, 0.0),
)
print('proj = \n{}'.format(proj))
print('mv = \n{}'.format(lookat))
print('mvp = \n{}'.format(proj * lookat))
```

yields

```
proj =
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.         -0.22222222  0.        ]
 [-0.         -0.         -1.22222222  1.        ]]
mv =
[[ 0.  0. -1.  0.]
 [ 0.  1. -0.  0.]
 [ 1.  0. -0.  0.]
 [-0. -0. -4.  1.]]
mvp =
[[ 0.          0.         -0.          0.        ]
 [ 0.          1.         -0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          4.88888889  1.        ]]
```

This is apparently strange because multiplication of mvp with any vectors makes their x and z coordinates zero. 

**Expected behavior**

At first I tried to replace the code "proj * lookat" with "np.matmul(proj, lookat)" before sending the product to the GPU, i.e., 

```
mvp.write(np.matmul(proj, lookat).astype('float32').tobytes())
```

but somehow it didn't work. Instead, I separately send proj and lookat to the vertex shader, and apply matrix multiplication in the shader. Now it works.

```
#version 330

//uniform mat4 Mvp;
uniform mat4 modelView;
uniform mat4 proj;

in vec3 in_vert;

void main() {
    //gl_Position = Mvp * vec4(in_vert, 1.0);
    gl_Position = proj * modelView * vec4(in_vert, 1.0);
}
```

**Version info**

```
>python -m moderngl
moderngl 5.5.4
--------------
vendor: NVIDIA Corporation
renderer: GeForce RTX 2070/PCIe/SSE2
version: 4.6.0 NVIDIA 441.12
python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
platform: win32
code: 460
```

**Comment by McSinyx** [comment]
I'd personally recommend using [PEP 465](https://www.python.org/dev/peps/pep-0465/) matrix multiplication operator, which would require the opposite order due the the difference in presentation in numpy and OpenGL, e.g. `lookat @ proj`.  I remember having similar discussion either here or on Discord about the pyrr's matmul behavior, but I think it's changed to compile with the linked PEP above.

**Comment by yshhrknmr** [comment]
Aha, it worked. Thank you very much.

**Comment by einarf** [comment]
You get in trouble because you are mixing `pyrr.matrix44` and `pyrr.Matrix44`.
`Matrix44` is the object oriented api returning the `Matrix44` (subclass of `ndarray`) while `matrix44` is the procedural api creating `ndarray`s.

In your example you multiply an `ndarray` with a `Matrix44`, so operator in the `ndarray` is used causing an element-wise multiplication instead. When mixing them use `matrix44.multiply(proj, lookat)`.

The procedural api is actually a lot faster, but the object oriented api looks better. Maybe we should update the code to use the `@` operator as suggested.

Your example only using the object oriented api:

```python
>>> from pyrr import Matrix44, matrix44
>>> proj = Matrix44.orthogonal_projection(-1., 1., -1., 1., 1., 10.)
>>> lookat = Matrix44.look_at(
...     (-4.0, 0.0, 0.0),
...     (0.0, 0.0, 0.0),
...     (0.0, 1.0, 0.0),
... )
>>> print('proj = \n{}'.format(proj))
proj = 
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.         -0.22222222  0.        ]
 [-0.         -0.         -1.22222222  1.        ]]
>>> print('mv = \n{}'.format(lookat))
mv = 
[[ 0.  0. -1.  0.]
 [ 0.  1. -0.  0.]
 [ 1.  0. -0.  0.]
 [-0. -0. -4.  1.]]
>>> print('mvp = \n{}'.format(proj * lookat))
mvp = 
[[ 0.          0.          0.22222222  0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.          0.          0.        ]
 [ 0.          0.         -0.33333333  1.        ]]
```

**Comment by einarf** [comment]
I'll look into possibly adding something in the docs about this. It's not the first time this issues has been raised.

**Comment by McSinyx** [comment]
> The procedural api is actually a lot faster, but the object oriented api looks better.

TIL, thank you for pointing out this additional information.

**Comment by einarf** [comment]
@McSinyx I've been experimenting with performance of `Matrix44` in this fork: https://github.com/einarf/pyrr-optimized

The readme has some performance comparisons.

**Comment by McSinyx** [comment]
That's interesting.  Do you have any plan for getting that merged upstream?  It's a shame pyrr does not support specifying element dtype which also leads to another conversion after creation.

**Comment by einarf** [comment]
I don't think it can be merged into pyrr. I just noticed that `Matrix44` multiplications was a lot slower. In fact, `Matrix44 * Matrix44` takes 5 times longer than muliplying `ndarray`s through the procedural api. You can specify `dtype='f4'` during creation to avoid converting with `astype` later. numpy to also support the buffer protocol, so you don't have to use `tobytes` in most cased.

**Comment by McSinyx** [comment]
> You can specify `dtype='f4'` during creation to avoid converting with `astype` later.

Thanks, I think I missed that the procedural API still supports this.

> numpy to also support the buffer protocol, so you don't have to use tobytes in most cases.

I will experiment around and see where I can omit that.
