### ISSUE TITLE
Buffer resizing

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#365]
Look into possibly supporting buffer resizing.

When making batches users desperately need to resize buffers. More and more geometry gets written into a buffer as more spites and objects are added. Recreating a new `Buffer` and `VertexArray` or `bind`ing in a new buffer manually in the `VertexArray` is not very elegant.

We could allow a buffer to grow in the `orphan()` method by adding an optional keyword argument `size` for byte size of the new array. We need to be careful because the `VertexArray` do contain a vertex count as well. This needs to be investigated.

The user would possibly have to specify how many vertices or elements to render when the buffer size is changed because the `VertexArray` is not aware of these changes unless we sanity check in `render` or `transform`. It could also be possible to provide a method to update the `VertexArray`'s internal vertex count.

I know @lordmauve needed this. A few more people have also asked for this in the past.

**Comment by lordmauve** [comment]
Yes, I would like this. I currently create new buffers, but because it's not easy to substitute one buffer for another in a VertexArray, I end up creating a new VertexArray also - even less elegant.

**Comment by einarf** [comment]
I would assume it would be acceptable to require a full buffer rewrite from the client after the resize.

**Comment by einarf** [comment]
I think getting this one into 5.6 is more than realistic. I'll put this one as high priority.

**Comment by einarf** [comment]
I have a working prototype for this now. Doing more testing.

**Comment by einarf** [comment]
Fixed in 632146f4da03b8cb9f14a0642938fbc819161be5

I also made a quick and dirty example batch drawing a growing number of points.
