### ISSUE TITLE
Share between context

### ISSUE THREAD

**Issue by DarwinSenior** [moderngl/moderngl#367]
I was wondering if it is possible to share textures between contexts

As afar I know there is no way to create a texture from an existing texture right?

**Describe the solution you'd like**

Is it possible to do something like this?

```python
# setup the first window ...
ctx1 = moderngl.create_context()
texture1 = ctx1.texture((H, W), 4)

# setup the second window ...
ctx2 = moderngl.create_context()
texture2 = ctx2.texture(texture1)
frame = ctx2.framebuffer((texture2,))
```
Where `ctx2.texture` function will check if `texture1` can be shared and create a texture that is shared between `ctx1` and `ctx2`.

**Version info**

```
moderngl 5.5.4
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 1080 Ti/PCIe/SSE2
version: 4.6.0 NVIDIA 430.64
python: 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0]
platform: linux
code: 460
```

**Comment by einarf** [comment]
Another option is to make different windows sharing the same context. That might be simpler, but I don't know about your use case. 

Some notes on this for glfw:
https://www.glfw.org/docs/latest/context_guide.html#context_sharing

**Comment by einarf** [comment]
Does your example assume object sharing between contexts? If you have any more details, that would be great.

**Comment by DarwinSenior** [comment]
I do ask if it is possible different windows sharing objects between contexts. 
So, what I had in mind is that no object is created in the new context as it is managed by the original context but can be used in the new object.

What I want to achieve is that we can create a "borrowed" object (buffer/texture/storage) by an id (GLuint), so that they can be used with the rest of the moderngl code. Basically to create same object but with a different context. As I understand it, textures, buffer objects, and render buffers are the ones can be shared between contexts.

For sharing between context, one scenario I currently have is to that I want to render the same content to two screens, where we want to output to one screen a rendered 3D scene and the other screen a tone-mapped version of the same content. In this case, it makes perfect sense to render to a buffer first and then blit this texture to one screen and process the same texture in another.

**Comment by einarf** [comment]
This is close to what I imagined as well. I assume if enabling object sharing we could test reconstructing the moderngl object in the other context. I have to look into how this works. If we object sharing means name sharing the moderngl texture instance could be reconstructed from a `GLunit`.

Currently I don't think this is possible in moderngl. We would have to come up with some solution for the next release (5.6).

There are still a couple of ways you can do this:

* If the opengl names are indeed shared between the contexts you can access them in the other context with PyOpenGL. You can simply `glBindTexture` the `GLuint` (and optionally use `glActiveTexture` to specify the texture channel.
* Simply `read()` the texture data and `write()` it into a new texture. This does not require object sharing

I can look into setting up some test in the moderngl-window project using the glfw window.

**Comment by einarf** [comment]
I saw you made a branch with some additions : https://github.com/DarwinSenior/moderngl/commit/ff34fc07406af66090cb0b84ebd46485c9921b96

Did this work out for you?

**Comment by DarwinSenior** [comment]
Yes, it does. 
Essentially, I created a function `transfer` (though the name could be more accurate)
```
texture.transfer(ctx)
```
Essentially, I added a field in the texture pointer to distinguish between a referenced texture and texture created by the context. And then it copies everything to the next context.
And it does work across contexts that share the texture.

**Comment by einarf** [comment]
Awesome! So the names are indeed shared. Good to know. If you PR this we could get it into 5.6. I think also adding a `Texture.from_name(ctx, id)` could be a good idea as a more generic solution. (I can organize that)

**Comment by einarf** [comment]
I would add a few sanity check in the transfer method, but this is also something I can fix.

* Make sure we don't transfer to the same context
* Check if the opengl id/name is actually a texture in the target context

This is of course a bit harder to test unless moderngl also supports creating shared headless context in the glcontext package.

**Comment by DarwinSenior** [comment]
I have added the PR.
However, this solution is kind of problematic when you want to modify the data in any way (changing sizes of the buffer/texture).
I want to modify the solution at some point. But it is usable as an interface right now.
But I would think it would be better if we have a reference type that we could use to indicate this "borrowed" data.

**Comment by einarf** [comment]
It's a good start. Worst case it can be added as an experimental feature in 5.6. There are still some time think this through before 5.6 is released.

Can you go into specifics of what challenges you think this solution has? I'm guessing the main issue is having two separate objects with properties getting out of sync if modified?

**Comment by DarwinSenior** [comment]
Yes, that is my concern. Basically, if you modify one object, the other is
out of sync.

**Comment by einarf** [comment]
I'm thinking this is actually ok for now. I'm assuming all the states of an opengl resource are syncronized. Textures are more or less immutable except the actual texture content and the states will not be set on `use`/bind because it just sticks to what is already in the resource.

It might be a bit more exiting for the `Buffer` type, but it should work.

I would suggest just merging this into 5.6 as a highly experimental feature with a big notice in the docs 😄 .. then the idea can possibly keep evolving.

**Comment by einarf** [comment]
Fixed context sharing in standalone contexts. That means this could be added to unit tests soon as well. Still context switching is a bit weird in moderngl 5, but it works.

```python
import moderngl
import numpy

data1 = numpy.array([1, 2, 3, 4], dtype='u1')
data2 = numpy.array([4, 3, 2, 1], dtype='u1')

ctx1 = moderngl.create_context(standalone=True)
ctx2 = moderngl.create_context(standalone=True, share=True)

with ctx1 as ctx:
    b1 = ctx.buffer(reserve=4)
    b1.write(data1)

with ctx2 as ctx:
    b2 = ctx.buffer(reserve=4)
    b2.write(data2)

print(b1.glo)
print(b2.glo)

with ctx1:
    print(b1.read())
    print(b2.read())

with ctx2:
    print(b1.read())
    print(b2.read())
```
Output
```
1
2
b'\x01\x02\x03\x04'
b'\x04\x03\x02\x01'
b'\x01\x02\x03\x04'
b'\x04\x03\x02\x01'
```
.. while without `share=True` these arrays will both have gl name `1`.

**Comment by einarf** [comment]
After playing with this for a while it looks like you **don't actually need to transfer the objects at all**. An object created in context A can be used in context B. moderngl don't currently check if you are accessing an object from a different context at all.

If your context is set up with sharing it should just work. I might be missing some corner cases, but generally I think it should work.

**Comment by DarwinSenior** [comment]
Yes, if you are checking context, then it is not needed. One case I know
comes from context.copy_buffer
So, maybe a better solution is not associate the texture and the buffer
with a context?

**Comment by einarf** [comment]
What I'm saying is that the objects in moderngl 5.x only stores a reference to the context they were created in, There are no actual checks for what context is active. You can see this in the code example I posted yesterday (3 posts up)

Worst case if you have a texture with an unknown context you can:
```python
with texture.ctx:
    # Do something with texture
```
... but this doesn't really matter if you have a shared context anyway.

This means that the transfer method is probably not needed. moderngl 5.6 will also give greater control over context switching. There might be checks / barriers in the future, but currently it's not easy to keep track of this.

**Comment by fekga** [comment]
According to the OpenGL wiki some objects cannot be shared between contexts:
https://www.khronos.org/opengl/wiki/OpenGL_Object#Object_Sharing
These objects are the ones that have reference to other objects, namely:
https://www.khronos.org/opengl/wiki/Framebuffer_Object
https://www.khronos.org/opengl/wiki/Shader_Compilation#Program_pipelines
https://www.khronos.org/opengl/wiki/Transform_Feedback
https://www.khronos.org/opengl/wiki/Vertex_Specification#Vertex_Array_Object

Some other rules also apply which are located here:
https://www.khronos.org/opengl/wiki/Memory_Model

So it is rather a complex set of rules when and how an object can be shared even for single threaded applications.

**Comment by einarf** [comment]
Yep. That I am definitly aware of. I'll link to this in the docs. Still moderngl should manage to work with basic object sharing at least in 5.6. This issue was mostly about sharing the less complex objects. (Unless that has changed)

**Comment by einarf** [comment]
Mocked up a quick docs page on contexts here:
https://moderngl.readthedocs.io/en/latest/the_guide/context.html

**Comment by einarf** [comment]
Closing this because I haven't heard anything in a while and I'm pretty sure the methods I've shared about using moderngl objects across context should work.

Be free to reopen if needed.
