### ISSUE TITLE
Clear depth buffer

### ISSUE THREAD

**Issue by MatthewScholefield** [moderngl/moderngl#368]
**A simple use-case of the new feature**

You want to render something on top of a skybox. You need to clear just the depth buffer because you still want depth test enabled, but with a new set of elements.

**Describe the solution you'd like**

```python
self.ctx.clear(None, None, None, None, 0.0)
# Or:
self.ctx.clear_depth()
```

**Version info**

```
moderngl 5.5.4
--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
version: 4.6 (Core Profile) Mesa 19.3.1
python: 3.6.9 (default, Jul  5 2019, 15:53:24) 
[GCC 8.3.1 20190320]
platform: linux
code: 460
```

**Notes**
It's possible I'm being stupid and there's an obvious way to do this. Please let me know if so :).

**Comment by einarf** [comment]
You can control what fragments are affected in rendering calls and `clear` using color and depth mask.

```python
# Protects the R, G, B, A components in the color attachment
fbo.color_mask = False, False, False, False

# Protects the depth attachment
fbo.depth_mask = False
```

Shortcut to default framebuffer is `ctx.screen` or you can use `ctx.fbo` for the currently bound framebuffer (more compatible with headless).

I think this the confusion is more about lacking documentation. This is a good opportunity to fix that.

Still I would say it might not be good practice to clear the depth buffer. In most cases you can play with `depth_mask` instead. You could render your sky box with `depth_mask = False` and still have depth culling enabled. The sky box just won't update the depth buffer. There are of course corner cases were you have to clear it.

I'll keep this one open until docs have been updated. Thanks asking this question highlighting the need for doc improvements.

**Comment by MatthewScholefield** [comment]
Thanks, this is great that there's already a way I just missed :D! And yeah, there are few corner cases like if you wanted to overlay a UI (like with some spinning coins on top of it etc.).

**Comment by einarf** [comment]
Improved docstring in moderngl 5.6 : https://moderngl.readthedocs.io/en/latest/reference/framebuffer.html

This topic should also be covered by future guides.
