### ISSUE TITLE
Could you give a 3d picking example

### ISSUE THREAD

**Issue by zhouhang95** [moderngl/moderngl#373]
I try to reproduce 3d pick, I find it hard to me.
link: http://ogldev.atspace.co.uk/www/tutorial29/tutorial29.html

**Comment by einarf** [comment]
You might want to look at https://github.com/moderngl/moderngl-window/blob/master/examples/advanced/fragment_picking.py

**Comment by zhouhang95** [comment]
Thanks a lot!
