### ISSUE TITLE
Brython support

### ISSUE THREAD

**Issue by stuaxo** [moderngl/moderngl#374]
Brython support (python implementation in the browser) would be really interesting, if not straightforward.

I ported an existing JS webgl example to Brython here
https://codepen.io/stuaxo/pen/zYxebVL

WebGL 2 is closest to OpenGL ES 2.

You can see that how you get hold of types like Float32Array, and the gl binding is a little different, but once you've got them you're into something that looks like OpenGL everywhere.

**Comment by einarf** [comment]
Are you suggesting creating a brython api similar to moderngl? I haven't really played around with brython too much, but it looks interesting.

**Comment by stuaxo** [comment]
Brython is definitely interesting, their aim is Python 3.x compatibility.

Their aim is that in the future you will be able to install python3 packages from PyPI that are compatible (e.g. no native APIs used).

A similar API is one approach (that brython-pygame) takes.

One issue with similar APIs is divergence - sharing tests may be way around this, somehow directly supporting it would be another.

In the past some APIs have been ported to other platforms and diverged leading to fragmentation, a couple of examples I can think of:

Cocos2D [python]:  
ported to all sorts of platforms and languages Cocos2D-X is the most successful, but python bindings to this will have a different API.

Gtk (Python on GObject) vs Gtk on Jython via Java bindings:  Of course these are different, but it would have been more of a benefit to Jython if they were not.

**Comment by McSinyx** [comment]
> Gtk on Jython via Java bindings: Of course these are different, but it would have been more of a benefit to Jython if they were not.

Isn't Jython dead?

**Comment by einarf** [comment]
Still not sure how this ties into moderngl and/or what path would be the right one to go to even consider this option 😄

**Comment by einarf** [comment]
Think for now I'll close this one, because I don't know where this is going. Adding to notes at least. 😄 There have been interest in the community for adding ES2 support. That is maybe the first step!
