### ISSUE TITLE
Add example to pyimgui

### ISSUE THREAD

**Issue by stuaxo** [moderngl/moderngl#375]
Pyimgui has examples showing how to integrate it into various GL bindings, it would he good if there was one for ModernGL

https://github.com/swistakm/pyimgui/tree/master/doc/examples

**Comment by zhouhang95** [comment]
https://github.com/moderngl/moderngl-window/blob/master/examples/integration_imgui.py

**Comment by einarf** [comment]
Yup made an integration already and are even working on an integration guide.
https://github.com/swistakm/pyimgui/issues/125

moderngl 5.6 is needed because it needs scissor support. Getting closer to release now..

**Comment by einarf** [comment]
Closing this when the work is done. It's good to have a reminder task here as well 😃

**Comment by stuaxo** [comment]
Fantastic :)

**Comment by einarf** [comment]
It's getting a bit more mature now after a few bug fixes. I'll hold a bit longer before PRing to pyimgui

**Comment by einarf** [comment]
The integrations is already mature and resides in moderngl-window

**Comment by stuaxo** [comment]
Really appreciate how this project and pyimgui are great examples when it comes to integrating with the wider ecosystem.

**Comment by einarf** [comment]
We even added support for it in arcade for fun : https://github.com/kfields/arcade-imgui
