### ISSUE TITLE
Add integration example to pycairo

### ISSUE THREAD

**Issue by stuaxo** [moderngl/moderngl#376]
Following pyimguis example pycairo has examples integrating pycairo with various libraries including GL bindings, but none for ModernGL yet, it would be good to have one.

https://github.com/pygobject/pycairo/blob/master/docs/integration.rst

**Comment by einarf** [comment]
Good tip! Thank you. Small tings like this is always useful. Interaction with other libraries is a good thing. This can also make bridges between communities.

**Comment by einarf** [comment]
@stuaxo If you have any other tips about integrations I'll be happy to add examples for that. I also want a separate section for that in docs. The more, the better!

**Comment by stuaxo** [comment]
All the integrations with pycairo do rendering to a texture.

The next thing on my procrastination list is to make some curvy 2d shapes with cairo and use api that makes it into straight lines then convert to 3d verts and render in moderngl.

Integrating existing libraries that output vectors and meshes is a territory that isn't as explored as it could be.

**Comment by stuaxo** [comment]
Problem is procrastination list is always completed in reverse order 😂

**Comment by McSinyx** [comment]
> Problem is procrastination list is always completed in reverse order

I'm stealing this quote of yours!

**Comment by einarf** [comment]
Added example using pycairo and moderngl : https://github.com/moderngl/moderngl/blob/master/examples/integration_pycairo.py

**Comment by einarf** [comment]
PR: https://github.com/pygobject/pycairo/pull/174

**Comment by einarf** [comment]
🍰
