### ISSUE TITLE
moderngl on Jupyter Notebook or Google Colab

### ISSUE THREAD

**Issue by AK82** [moderngl/moderngl#378]
Hi
Is moderngl working on Jupyter Notebook or Google Colab, and if so can you please post an example?
Thank you.

**Comment by einarf** [comment]
Personally I have very little knowledge about Jupyter Notebook or Google Colab, so I woudn't be able to give a concrete answer. Maybe someone else here knows?

**Comment by stuaxo** [comment]
The easiest way to get an image to appear as Jupyter cell out is by encoding it as a PNG, and passing that data to it's Image class.

```
# < insert code to get png data from ModernGL here. >
display(Image(data=png_data))
```

You can register data types so this happens automatically.

You could register types for `moderngl.Texture` and whatever else it makes sense to see in the cell.

There is some work to package this all up as an extension, this would probably be a seperate project - e.g moderngl-jupyter.

VisPy have (or had?) GL rendering in Notebooks a while ago, via their Gloo library, so if you need it now that may be an option for you.

Here's a Jupyter extension I made for cairo to display Surface and Context, I lean heavily on the PngFormatter so just need to get it png data to make this work.
https://github.com/stuaxo/cairo-jupyter/blob/master/extension/cairo_jupyter/__init__.py#L46

There is info on writing Jupyter extensions here.
https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html

**Comment by einarf** [comment]
Thank you @stuaxo for answering the question. I'll close this for now. The issue still be useful in search results in the future.

**Comment by stuaxo** [comment]
I'll also point to Vispys `GLIR` spec.   Which encodes a subset of opengl over the wire, which they use to for webgl targets.

If somebody liked `moderngl` syntax a lot more than Gloos they could target GLIR with a moderngl - like API.
http://api.vispy.org/en/latest/gloo.glir.html
