### ISSUE TITLE
uniforms: trouble with the buffer protocol implementation 

### ISSUE THREAD

**Issue by jimy-byerley** [moderngl/moderngl#379]
Hello there,

I get an issue while working with `Program['uniform'].write(...)`
I use PyGLM, that implements the buffer protocol, so I don't know exactly if this issue is from glm or moderngl.

I got the following:
```python
program['uniform'].value = (1, 1, 1)    # working
program['uniform'].write(np.array([1,1,1]))    # working

v = glm.fvec3(1,1,1)
program['uniform'].write(memoryview(v))    # working
program['uniform'].write(bytes(v))    # working
program['uniform'].write(np.array(v))    # working

program['uniform'].write(v)    #  <--------- error
```

I get the following error using moderngl 5.5.4 installed with `pip`:
```
  File "some.py", line 354, in render
    program['uniform'].write(v)
  File "/home/jimy/.local/lib/python3.7/site-packages/moderngl/program_members/uniform.py", line 178, in write
    self.mglo.data = data
SystemError: error return without exception set
Abandon
```

So it seems that the uniform assignment using the buffer protocol works with bytes, raw memory, numpy but not with pyglm. But pyglm's buffer protocol seems to work since it works with memoryview and numpy.
I'm a bit confused.

**Comment by einarf** [comment]
Thanks for the report. I was actually just going to try out pygml with moderngl. Let's try to figure this out for the 5.6 release (in a few days).

**Comment by einarf** [comment]
```
int get_buffer = PyObject_GetBuffer(value, &buffer_view, PyBUF_SIMPLE);
```
raises the following error for `glm.vec3` and `glm.mat4`
```
BufferError: This type of buffer is not supported.
```

**Comment by einarf** [comment]
Found it. The `*_getbuffer` functions in pyglm does not accept `PyBUF_SIMPLE`. I have no idea how the buffer layout actually is for pyglm types. This at least tells us why it fails.

```cpp
// line 20886
template<int C, int R, typename T>
static int
mat_getbuffer(mat<C, R, T>* self, Py_buffer* view, int flags) {
	if (view == NULL) {
		PyErr_SetString(PyExc_ValueError, "NULL view in getbuffer");
		return -1;
	}
	if ((flags & PyBUF_RECORDS_RO) != PyBUF_RECORDS_RO || (flags & PyBUF_F_CONTIGUOUS) == PyBUF_F_CONTIGUOUS || (flags & PyBUF_ANY_CONTIGUOUS) == PyBUF_ANY_CONTIGUOUS) {
		PyErr_SetString(PyExc_BufferError, "This type of buffer is not supported.");
		view->obj = NULL;
		return -1;
	}
```

**Comment by einarf** [comment]
Still, `PyBuffer_IsContiguous()` does claim the buffer is contiguous.

**Comment by einarf** [comment]
Hacking on pyglm making it accept `PyBUF_SIMPLE`
```python
matrix44 = glm.mat4(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
prog['matrix'].write(matrix44)
print(prog['matrix'].value)
```
Output
```
(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0)
```

**Comment by einarf** [comment]
Created an issue in PyGLM project. It needs to be solved there. Tweaked the uniform setter to propagate the error from the objects `getbuffer` method at least : ed4540389e602a4b38d96310aabc4f873be8ccfa

That means we get to see PyGLM's error message:
```
BufferError: This type of buffer is not supported.
```

**Comment by jimy-byerley** [comment]
Wow, I'm not that smart with the buffer protocol !
Thanks for having reported it to pyGLM :)

**Comment by einarf** [comment]
Closing this for now because no changes are needed in moderngl.

**Comment by einarf** [comment]
Should work with `pyglm==1.1.8` now

**Comment by jimy-byerley** [comment]
Yes it works ! thanks a lot !
