### ISSUE TITLE
x11: cannot choose visual - create_standalone_context()

### ISSUE THREAD

**Issue by sunweilunformatech** [moderngl/moderngl#382]
**Description**

In the blending example given in documentation:
# For both rgb and alpha
ctx.blend_func = moderngl.SRC_ALPHA, moderngl.ONE_MINUS_SRC_ALPHA

# Separate for rgb and alpha
ctx.blend_func = (
    moderngl.SRC_ALPHA, moderngl.ONE_MINUS_SRC_ALPHA,
    moderngl.ONE, moderngl.ONE
)

For both rgb and alpha mode works, while
separate for rgb and alpha mode gives:
SystemError: error return without exception set

**Comment by einarf** [comment]
In current master / 5.6 this passing in unit tests. I also tried manually

```
$ python
>>> import moderngl
>>> ctx = moderngl.create_context(standalone=True)
>>> ctx.blend_func = (
... moderngl.SRC_ALPHA, moderngl.ONE_MINUS_SRC_ALPHA,
... moderngl.ONE, moderngl.ONE
... )
>>> ctx.blend_func = moderngl.ONE, moderngl.ONE
>>>
```

Are sure you have the latest (5.6) version installed?

**Comment by sunweilunformatech** [comment]
Oh I was on 5.5.3, thanks for the response :-)

However, I got this error after upgrading to 5.6.0:
/usr/local/lib/python3.6/dist-packages/glcontext/__init__.py in create(*args, **kwargs)
     66     def create(*args, **kwargs):
     67         supported_args = ['glversion', 'mode', 'libgl', 'libx11']
---> 68         return x11.create_context(**_strip_kwargs(kwargs, supported_args))
     69     return create
     70 

Exception: cannot choose visual

When I roll back, it worked fine but I couldn't use the full blend_func.

**Comment by einarf** [comment]
Thanks. I will look at the error in 5.6.

**Comment by sunweilunformatech** [comment]
Great thanks!

**Comment by einarf** [comment]
I can't spot anything apparent. The x11 backend was pretty much copied from the 5.5.x code base. I added more details to the errors raised in the x11 backend for now.

Leaving this open for now until we figure things out.

@sunweilunformatech Can you share exactly what distro and version you are using? Could it also be that you have multiple `libGL.so*` versions and moderngl is loading the wrong one? It will dynamically load `libGL.so` if present. Otherwise context creation will fail.

**Comment by sunweilunformatech** [comment]
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.5.0 NVIDIA 440.33.01
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 440.33.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 440.33.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_group_vote, GL_EXT_shader_implicit_conversions, 

This is what I have in `glxinfo | grep 'version'`

**Comment by einarf** [comment]
Thanks. Right, It's nvidia. What's the name of the `libGL.so` for nvidia in your case? I guess you find them in `/usr/lib/libGL*`

**Comment by sunweilunformatech** [comment]
All my libGL.so* under `/usr`:

/usr/lib/i386-linux-gnu/mesa/libGL.so.1
/usr/lib/i386-linux-gnu/mesa/libGL.so.1.2.0
/usr/lib/nvidia-440/libGL.so
/usr/lib/nvidia-440/libGL.so.1
/usr/lib/nvidia-440/libGL.so.1.7.0
/usr/lib/x86_64-linux-gnu/libGL.so
/usr/lib/x86_64-linux-gnu/mesa/libGL.so
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0

So they put them in `nvidia-440/` by default it seams. Maybe also add `nvidia*/` under `/usr/lib/` while searching for libGL.so?

**Comment by einarf** [comment]
I think you can use `LD_LIBRARY_PATH` instead to promote a specific directory. You could also specifically load `libGL.so.1.7.0` and see what happens :)

**Comment by sunweilunformatech** [comment]
Cool. That worked. Thanks.

**Comment by einarf** [comment]
Nice! So you did this?:
```python
moderngl.create_context(standalone=True, libgl="libGL.so.1.7.0")
```

**Comment by sunweilunformatech** [comment]
`moderngl.create_standalone_context(libgl='libGL.so.1')`

**Comment by einarf** [comment]
Thanks a lot for testing 👍 

I'll close this after updating api docs and context guide.

**Comment by einarf** [comment]
FYI: I added env vars for controlling various parameters as well.
https://github.com/moderngl/glcontext#environment-variables

**Comment by einarf** [comment]
glcontext 2.2.0 will now locate the appropriate `.so` for GL and EGL so in the vast majority of cases everything should just work automagically.

**Comment by jmurray6** [comment]
I'm having an issue possibly related to this. I'm running some code with glcontext and moderngl on an AWS Lambda function, and I'm seeing the error: 
`"errorMessage": "libGL.so not found in /lib, /usr/lib or LD_LIBRARY_PATH"`

I've tried packaging the libGL.so file with the Lambda layer at various /lib directories, also tried the above solution with the `libgl=` flag. Do you think my issue is with packaging my layer incorrectly? Like am I just failing to put the lib in the right place for the Lambda to find it? Or is there something else going on here?

**Comment by einarf** [comment]
I have never used moderngl in AWS Lambda or similar services. I don't really know what capabilities are available there.

**Comment by jmurray6** [comment]
No worries at all. I have moved to a different configuration for the Lambda (using a container) and I'm now running into an issue with `XOpenDisplay`, thus I'm reading some of your other issue threads.

**Comment by einarf** [comment]
Yeah you need to use virtual framebuffer or healdess EGL. The latter is much better because it can be hardware accellerated even in docker containers with the right setup.

**Comment by einarf** [comment]
This is a nice test for headless egl : https://github.com/moderngl/moderngl/blob/master/examples/headless_egl.py

**Comment by jmurray6** [comment]
Wow thanks for that! That really makes me think that this will work once I get past all the dependencies! 

I was just able to identify the egl library I needed to install (it was `mesa-libEGL`) and now I'm hitting a new error:
`"errorMessage": "eglGetPlatformDisplayEXT failed (0x3000)"`

This is still originating from my context creation line, which is:
`ctx = moderngl.create_standalone_context(libgl='libGL.so.1', backend='egl')`

Any ideas on this one?

**Comment by einarf** [comment]
It returns `EGL_NO_DISPLAY` it seems. It probably means you don't have access to some underlying devices.
