### ISSUE TITLE
exposing load_* functions

### ISSUE THREAD

**Issue by fekga** [moderngl/moderngl#383]
I know that using the moderngl_window I could use the load_* functions to load my objects, shaders, textures. But using only the moderngl package I would like to use those features as well. Is there any easy way to use those without importing moderngl_window or is there a plan to expose those to be used using only moderngl?

**Comment by einarf** [comment]
moderngl itself will probably not have these features as it is meant to be a fairly lightweight binding for modern opengl.

Still, you can use moderngl-window's resource system without using any other features. You only need to provide it with your context.

```python
import moderngl_window
from moderngl_window import resources
from moderngl_window.meta import ProgramDescription
resources.register_dir("absolute/path/to/resource/root")

ctx = moderngl.create_context(...)
moderngl_window.activate_context(ctx=ctx)
program = resources.programs.load(ProgramDescription(path="test.glsl"))
```

You can look at `WindowConfig` and make your own load method wrappers if needed: https://github.com/moderngl/moderngl-window/blob/0ea845bc28437d2778fe921605c924d158afdb96/moderngl_window/context/base/window.py#L967-L1127

**Comment by fekga** [comment]
Ah thank you, this snippet is really helpful!

**Comment by einarf** [comment]
Older guide mention some of this: https://moderngl-window.readthedocs.io/en/latest/guide/window_guide.html#old-guide

Needs to be rewrittren, but most is still relevant

**Comment by einarf** [comment]
Closing this for now. There are tasks for improving docs in the moderngl-window project.
