### ISSUE TITLE
Face culling

### ISSUE THREAD

**Issue by fekga** [moderngl/moderngl#384]
**A simple use-case of the new feature**

Ability to discard front/back or both faces from the rendering.

**Describe the solution you'd like**

Exposing the glCullFace function to moderngl with the constants it is using: GL_FRONT/GL_BACK/GL_FRONT_AND_BACK.
The culling still needs to be enabled with the glEnable(GL_CULL_FACE) call but I think that is already used in the flags.
Related issue: #119
Note that winding order is a different feature, it is used only for deciding on the order of sent vertices to the primitive assembly what the facing of the primitives are. Face culling is a different feature. 

**Version info**

moderngl 5.6.0
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 1060/PCIe/SSE2
version: 3.3.0 NVIDIA 441.20
python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
platform: win32
code: 330

```



```

**Comment by einarf** [comment]
Do you have a specific rendering example were this is needed?

**Comment by fekga** [comment]
I would like to implement in opengl this method:
http://www.humus.name/index.php?page=3D&ID=88
It requires to render the scene using front and backfaces only in separate textures and then use those to get the edges in a shader.

**Comment by einarf** [comment]
It makes sense. It's definitely not practical to process your geometry to achieve this. For now you can use pyopengl to set the state.

**Comment by yoyonel** [comment]
It's already implement  in ``moderngl` => https://github.com/moderngl/moderngl/blob/b39cedd8cf216c34e43371b4aec822f6084f0f79/moderngl/context.py#L458-L478
You can use the setter of this property to trigger the OpenGL method `FrontFace`:
https://github.com/moderngl/moderngl/blob/b39cedd8cf216c34e43371b4aec822f6084f0f79/moderngl/src/Context.cpp#L756-L770
I think it's enougth to port the Humus sample (very nice website, old school but still relevant)

**Comment by einarf** [comment]
Ok. Maybe I misunderstood or some details are missing here leading to some wrong assumptions? 😄

**Comment by yoyonel** [comment]
Ahh no you're rigth, my bad, it's `CullFace` needed here not `FrontFace` :p

**Comment by einarf** [comment]
After a bit of confusion.. you can achieve what you want here by setting polygon winding along. Still, it's nice to expose `glCullFace`.

**Comment by einarf** [comment]
This was added in 5.6.1
