### ISSUE TITLE
How to run moderngl in a conda environment?

### ISSUE THREAD

**Issue by AK82** [moderngl/moderngl#385]
When I try to run moderngl in a conda environment I am getting this error:
```
 Traceback (most recent call last):
   File "/home/alex/Documents/moderngl_2.py", line 8, in <module>
     ctx = moderngl.create_context(standalone=True, headless=True, backend='egl')
   File "/home/alex/anaconda3/envs/OpenGL/lib/python3.6/site-packages/moderngl/context.py", line 1423, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
 ModuleNotFoundError: No module named 'glcontext'
```

Can anybody help me with this issue?
Thanks.

**Comment by einarf** [comment]
It seems you are missing the `glcontext` package. From 5.6 this package is responsible for context creation. How did you installed moderngl?

**Comment by AK82** [comment]
Like this:
`pip install moderngl`

**Comment by einarf** [comment]
Can you do a `pip install -I moderngl` and post the output?

**Comment by AK82** [comment]
Thank you very much. I don't get the error anymore.
Can you please let me know what` -I `from `pip install` is standing for?

**Comment by einarf** [comment]
`pip install --help`
```
-I, --ignore-installed      Ignore the installed packages (reinstalling instead).
```
Something wrong happened when you installed it the first time I guess. `-I` just force re-installs the package and its dependencies and it resolve the issues. It could be you installed it with conda because I see moderngl 5.6 is in their package index. I don't know how conda deals with dependencies.

**Comment by einarf** [comment]
If conda doesn't install glcontext I would report it here:
https://github.com/conda-forge/moderngl-feedstock

Closing this for now.
