### ISSUE TITLE
Cannot create standalone context using remote desktop

### ISSUE THREAD

**Issue by DavidWongEA** [moderngl/moderngl#389]
Hi,

I've trouble creating a standalone context when running moderngl using remote desktop.

Python 3.6.7 (default, Jul  2 2019, 02:21:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import moderngl
>>> moderngl.__version__
'5.5.2'
>>> ctx = moderngl.create_standalone_context()

It'll crash and exit python on the line above.

I read something about opengl not work with remote desktop, but running in software mode work. If that's really the case, how to run in software mode?

thanks,
David

**Comment by einarf** [comment]
Unless your system have drivers to provide hardware acceleration it will fall back to software emulation. Consumer hardware can probably do this easily today, but I'm guessing drivers are still locked to specific products.

The most common trick is probably to make a batch file that disconnects your session and starts the application using the local session. When connecting again a few seconds later it all works fine. This doesn't always work, but for long running applications it could be an option.

I really have no idea how to properly fix this issue. Could it be possible to use mesa for windows? If you upgrade to moderngl 5.6 context creation is done in a separate glcontext package you can tinker with or make your own backend for providing a context.

**Comment by einarf** [comment]
This might also be useful (from Szabolcs Dombi);
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowstationa 
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-opendesktopa

**Comment by DavidWongEA** [comment]
Thanks Einar! I'll try the suggested work around.

**Comment by einarf** [comment]
Closing this for now. It should still be around and searchable if people bump into this issue. Be freee to reopen if more information can be added.
