### ISSUE TITLE
Crash loading compute shader when too low opengl version

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#390]
Not a super critical issue, but we should at least do a sanity check during compute shader creation and give some reasonable feedback.

**Comment by einarf** [comment]
Like mentioned in the PR we should check version code AND extensions. I don't really want to add this before more research is done. We might break things.

**Comment by einarf** [comment]
This is someting we could do in the refactoring on the python side.

```py
supported = ctx.version_code >= 430 or "GL_ARB_compute_shader" in ctx.extensions
```

My only worry is that some drivers might only have the vendor specific extension.

**Comment by szabolcsdombi** [comment]
the list should be finite and I expect having a custom entry but no `GL_ARB_compute_shader` will be rare.
these will be reported, the bugfix is trivial and requires only python code changes. it even can be tested without rebuilding moderngl.

**Comment by szabolcsdombi** [comment]
This was not implemented as loading and searching the extension list is an expensive operation. load time would suffer from it.
I think we should just tie `glDispatchCompute != NULL` to having compute shaders available.
