### ISSUE TITLE
copy_framebuffer ignores 'dst' argument of a texture

### ISSUE THREAD

**Issue by sunweilunformatech** [moderngl/moderngl#394]
**Description**

Texture argument passed in copy_framebuffer is ignored. The copy is applied on the texture currently in use instead.

```
# Sorry, too lazy to write a full example for now. But I think you can get the idea.
fbo = ctx.simple_framebuffer(...
texture1 = ctx.texture(...
texture2 = ctx.texture(...
texture1.use()
ctx.copy_framebuffer(texture2, fbo)
texture1.read()  # texture1's cotent overwrite by the copy
texture2.read() # texture2's content remain unchanged
```

**Expected behavior**

texture2 is overwritten instead of texture1
There's a work around to always use the texture before the copy. But this destroys the purpose of the argument and creates confusion. So maybe best to fix it.

**Version info**

5.6.0

```



```

**Comment by einarf** [comment]
Thank you. I'll look into this.

**Comment by einarf** [comment]
FIxed. Just need to wrap this up by adding test improving docs.
