### ISSUE TITLE
Disable Framebuffer Clipping

### ISSUE THREAD

**Issue by sunweilunformatech** [moderngl/moderngl#395]
Is there a way to disable color clipping for framebuffers in floats?

```
fbo = self.ctx.simple_framebuffer(size, dtype='f4')
# render something with values > 1
raw = fbo.read(components=4)
result = np.frombuffer(raw, dtype=np.float32).reshape((*fbo.size[::-1], -1))
print(np.max(result)) # max is always <= 1 here
```
Thanks :-)

**Comment by einarf** [comment]
Play with the parameters : https://moderngl.readthedocs.io/en/latest/reference/framebuffer.html#moderngl.Framebuffer.read

It reads with `dtype='f1'` by default. I would suggest checking the contents of `ctx.error` after the read to make sure you detect any incompatible read configuration.

**Comment by sunweilunformatech** [comment]
Thanks for the reply. I actually added dtype in the code. I think it was actually also related to copy_framebuffer:

```
self.texure.use()
self.ctx.copy_framebuffer(self.texure, self.msaa_fbo)
tgt = self.fbo
raw = tgt.read(components=4, dtype='f4')
result = np.frombuffer(raw, dtype=np.float32).reshape((*tgt.size[::-1], -1))
print(np.max(result)) # this is fine, result is 2.0

tgt = self.texure
raw = tgt.read()
result = np.frombuffer(raw, dtype=np.float32).reshape((*tgt.size[::-1], -1))
print(np.max(result)) # 1.0 here
```

I checked that texture actually doesn't clip so I can actaully store and read > 1 values in texture. But some clipping probably happended in the copy. Any ideas?

**Comment by sunweilunformatech** [comment]
https://moderngl.readthedocs.io/en/4.1.2/Textures.html
Oh maybe it's the "floats" kw arg that I need to set to True?
But it doesn't seem to recognize it:
TypeError: texture() got an unexpected keyword argument 'floats'

**Comment by einarf** [comment]
That is in moderngl 4. I was assuming you used 5.x 😄 It should obey the dtype from creation.
You can try passing in a different alignment when reading the texture. 

I'll need to sit down and go though this a bit deeper later and add more docs. There might be issues as well.

Worst case you can try to poke around with pyopengl replicating some of this. `Texture.glo` should be the resource id : https://github.com/moderngl/moderngl/blob/13b0b0345051b74d82049e39e883828be122f3fd/moderngl/src/Texture.cpp#L341-L369

**Comment by sunweilunformatech** [comment]
Got it. Thanks. I'll play with it.

**Comment by einarf** [comment]
Can try to get this resolved and document this properly for once. Reading texture data is not very intuitive currently.

**Comment by einarf** [comment]
A bit late on this, but this is apparently because of `glClampColor`: https://www.khronos.org/opengl/wiki/GLAPI/glClampColor

For now it would work to disable clamping with pyopengl until we find a good way to solve this.

**Comment by einarf** [comment]
Think I will add a `clamp` parameter to `read` methods for this.

**Comment by einarf** [comment]
This is already in master
