### ISSUE TITLE
Exception on context creation in linux

### ISSUE THREAD

**Issue by HopefulFire** [moderngl/moderngl#397]
**Description**

An exception occurs when running this code/ checking the version number

**Proof of code**

```py

import moderngl

context = moderngl.create_context()

print(context.screen)

```

**Expected behavior**

I expected a context to be created and printed to the terminal, following the docs tutorial.

**Version info**

```
(output when running python3 -m moderngl
python3 -m moderngl         
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jadelynnmasker/.local/lib/python3.8/site-packages/moderngl/__main__.py", line 50, in <module>
    main()
  File "/home/jadelynnmasker/.local/lib/python3.8/site-packages/moderngl/__main__.py", line 33, in main
    ctx = moderngl.create_standalone_context()
  File "/home/jadelynnmasker/.local/lib/python3.8/site-packages/moderngl/context.py", line 1466, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/jadelynnmasker/.local/lib/python3.8/site-packages/glcontext/__init__.py", line 76, in create
    return x11.create_context(**kwargs)
Exception: libGL.so not found in /lib, /usr/lib or LD_LIBRARY_PATH

pip3 install ModernGl
Requirement already satisfied: ModernGl in /home/jadelynnmasker/.local/lib/python3.8/site-packages (5.6.0)
Requirement already satisfied: glcontext<3,>1 in /home/jadelynnmasker/.local/lib/python3.8/site-packages (from ModernGl) (2.1.0)
```
I checked and I do have libgl1 installed. In fact, I am running a freshly installed Pop! OS 20.04 LTS, so I wouldn't expect any packages to be out of date or missing.

**Comment by einarf** [comment]
Read from here : https://github.com/moderngl/moderngl/issues/382#issuecomment-582086235

It's something we have to properly document in 5.6.1. It tried to load `libGL.so` by default. If your system have another version such as `libGL.so.1` or some other variant, you need to provide this. There are also enviroment variables to override this in the glcontext library : https://github.com/moderngl/glcontext#environment-variables

**Comment by HopefulFire** [comment]
Yeah, sorry I'm a bit of a linux newbie. THANK YOU very much for your quick response and for providing this library. I'll see what I can do on my end.

**Comment by einarf** [comment]
No problem. We still have things to do on our end to make this easier for most people.

**Comment by HopefulFire** [comment]
I fixed it by creating a hard link between '/usr/lib/x86_64-linux-gnu/libGL.so.1' and '/usr/lib/x86_64-linux-gnu/libGL.1.so' which is what it's looking for. However, now I am getting a different error:
```
Traceback (most recent call last):
  File "example1.py", line 3, in <module>
    context = moderngl.create_context()
  File "/home/jadelynnmasker/.local/lib/python3.8/site-packages/moderngl/context.py", line 1423, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/jadelynnmasker/.local/lib/python3.8/site-packages/glcontext/__init__.py", line 76, in create
    return x11.create_context(**kwargs)
Exception: (detect) glXGetCurrentContext: cannot detect OpenGL context
```

**Comment by einarf** [comment]
It looks like you are creating a standalone context. By default moderngl will try to detect the active context.

```
import moderngl
moderngl.create_context(standalone=True)
```

**Comment by HopefulFire** [comment]
Thank you, that fixed my issue

**Comment by einarf** [comment]
FYI: If upgrading to glcontext 2.2.0 it will automatically find the appropriate `.so` file for you.
