### ISSUE TITLE
Unable to set usampler2D uniform.

### ISSUE THREAD

**Issue by lordmauve** [moderngl/moderngl#401]
[I have some uniforms](https://github.com/lordmauve/wasabi2d/blob/6a1f084a0658afa8e8d1bc61663e93e7e9138511/wasabi2d/glsl/tile_map.frag#L7) defined as `usampler2D`. These hold texel coordinates that are used passed to `texelFetch()`

[Trying to assign a texture unit to these](https://github.com/lordmauve/wasabi2d/blob/6a1f084a0658afa8e8d1bc61663e93e7e9138511/wasabi2d/primitives/tile_map.py#L283) causes a crash under ModernGL 5.6.0:

```
  File "/home/mauve/dev/wasabi2d/wasabi2d/primitives/tile_map.py", line 283, in render
    self.prog['tiles'] = 0
  File "/home/mauve/dev/wasabi2d/venv/lib/python3.7/site-packages/moderngl/program.py", line 90, in __setitem__
    self._members[key].value = value
  File "/home/mauve/dev/wasabi2d/venv/lib/python3.7/site-packages/moderngl/program_members/uniform.py", line 164, in value
    self.mglo.value = value
moderngl.error.Error: cannot detect uniform type
```

**Comment by einarf** [comment]
We should probably add those in 5.6.1. I don't think they are needed to read from `usampler2D` or `isampler2D` in 3.3 core+, but they are still nice to support.

**Comment by lordmauve** [comment]
I tried working around this by reading from the texture as a `sampler2D`. However, fetching values from the texel didn't work as expected.

I was writing a np byte array starting with `[2, 2, ...]` as a texture with dtype `u1` and only seeing a nonzero value in the  `.w` value of texel `(0, 0)` - and that value was `1`.

Changing the texture dtype to `f1` and adding a `* 255.0` in my shader fixed it with no other changes.

**Comment by einarf** [comment]
Fixed
