### ISSUE TITLE
pycairo example seems to be inverted y axis

### ISSUE THREAD

**Issue by jrjbertram** [moderngl/moderngl#403]
**Description**

Attempted to draw some text with pycairo example and found that it appears to have an inverted y axis.  Probably wasn't noticed because the existing example is symmetric about the x and y axes.

**Proof of code**

Change integration_pycairo.py to:

```py

    def render_cairo_to_texture(self, width, height):
        # Draw with cairo to surface
        x, y, radius = (250, 250, 200)
        surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, width, height)
        ctx = cairo.Context(surface)
        #ctx.set_line_width(15)
        #ctx.arc(x, y, radius, 0, 2.0 * math.pi)
        #ctx.set_source_rgb(0.0, 0.8, 0.0)
        #ctx.fill_preserve()
        #ctx.set_source_rgb(1, 0, 0)
        #ctx.stroke()

        ctx.move_to(20, 30)
        ctx.select_font_face("Purisa", cairo.FONT_SLANT_NORMAL,
                            cairo.FONT_WEIGHT_NORMAL)
        ctx.set_font_size(13)
        ctx.set_source_rgb(0.8, 0.8, 0.8)
        ctx.show_text("Most relationships seem so transitory")
        # Copy surface to texture
        return self.ctx.texture((width, height), 4, data=surface.get_data())

```

**Expected behavior**

I expected (perhaps incorrectly?) that the text would be rendered correctly, but found it was inverted in the y direction.  Actual output attached.

![image](https://user-images.githubusercontent.com/2137279/82152335-09ded880-9826-11ea-9b14-83968f336313.png)

**Version info**

```

C:\Users\josh\divQ\moderngl\examples>python -m moderngl
moderngl 5.6.0
--------------
vendor: NVIDIA Corporation
renderer: GeForce RTX 2080 with Max-Q Design/PCIe/SSE2
version: 3.3.0 NVIDIA 441.66
python: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
platform: win32
code: 330

```

**Comment by einarf** [comment]
Thanks for reporting. It's not a hard fix but I agree it's silly the example was upside down.

Fixed in 7842db85bb3ac634f6d3d5a9b98e5c403ae5b831

![Capture](https://user-images.githubusercontent.com/5418180/82248832-13149600-9949-11ea-8a0f-0467c2ac8366.PNG)
