### ISSUE TITLE
matplotlib_as_texture example normed parameter deprecated.

### ISSUE THREAD

**Issue by jrjbertram** [moderngl/moderngl#404]
The matplotlib_as_texture example needs to change the normed=1 parameter to density = True.  Normed was deprecated.  Switching to density=True allows the example to work.

https://github.com/moderngl/moderngl/blob/master/examples/matplotlib_as_texture.py#L26

See:
https://stackoverflow.com/a/53063337/1641102

**Comment by einarf** [comment]
Thanks for reporting. Fixed in 94d232b6c179813f6eb442d5647dd1313001193e
