### ISSUE TITLE
EGL backend fails in docker container

### ISSUE THREAD

**Issue by christopher-hesse** [moderngl/moderngl#405]
**Description**

egl backend fails to initialize in docker container:

```py
import moderngl
moderngl.create_standalone_context(backend="egl")
```

```
Traceback (most recent call last):
  File "egl_test.py", line 2, in <module>
    moderngl.create_standalone_context(backend="egl")
  File "/root/miniconda3/envs/env/lib/python3.7/site-packages/moderngl/context.py", line 1466, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/root/miniconda3/envs/env/lib/python3.7/site-packages/glcontext/__init__.py", line 99, in create
    return egl.create_context(**kwargs)
Exception: eglInitialize failed (0x3001)
```

I might just be doing something wrong, but I'm not sure what it is.  It works for my example program.

**Proof of code**

https://github.com/christopher-hesse/moderngl-issue

```
docker build . --tag egl_test
docker run -it --rm egl_test bash -c "gcc egl_test.c -lEGL -lOpenGL && ./a.out && tail out.ppm"
docker run -it --rm egl_test python egl_test.py
```
The first docker run runs a simple egl program which seems to be working because it outputs a PPM file.  The second crashes with the above error. 

**Expected behavior**

I expected it to work instead of crashing.  Could this be some sort of gl version issue?

**Version info**

```
docker run -it --rm egl_test pip show moderngl glcontext
Name: moderngl
Version: 5.6.0
Summary: ModernGL: High performance rendering for Python 3
Home-page: https://github.com/moderngl/moderngl
Author: Szabolcs Dombi
Author-email: cprogrammer1994@gmail.com
License: MIT
Location: /root/miniconda3/envs/env/lib/python3.7/site-packages
Requires: glcontext
Required-by:
---
Name: glcontext
Version: 2.1.0
Summary: Portable OpenGL Context
Home-page: https://github.com/moderngl/glcontext
Author: Szabolcs Dombi
Author-email: cprogrammer1994@gmail.com
License: MIT
Location: /root/miniconda3/envs/env/lib/python3.7/site-packages
Requires:
Required-by: moderngl
```

**Comment by einarf** [comment]
hmm. you could try to tweak the backend : https://github.com/moderngl/glcontext/blob/master/glcontext/egl.cpp

The obvious difference is that glcontext is using `GetDisplay(EGL_DEFAULT_DISPLAY)` instead of querying the devices and picking the first one with `eglGetPlatformDisplay`

**Comment by christopher-hesse** [comment]
Yeah that seems to work, thanks!  Unless there is a way for the user to select the default display, it seems like the user should at least be able to select the device index here, right?  Do you guys have any interest in adding that functionality?

**Comment by einarf** [comment]
Definitely. I'm guessing just adding another parameter to the backend should be easy enught. The hard part might be explaining what the difference between `EGL_DEFAULT_DISPLAY` and this new version. I don't really know myself 😄

**Comment by einarf** [comment]
As far as I can see ..

> Plainly using eglGetDisplay(EGL_DEFAULT_DISPLAY) can be problematic in certain setups
https://bugs.webkit.org/show_bug.cgi?id=163333
https://bugreports.qt.io/browse/QTBUG-60330
https://bugs.webkit.org/show_bug.cgi?id=163333

> Basically, eglGetDisplay does not can cannot work reliably with any value except EGL_DEFAULT_DISPLAY. Different EGL implementations will have different heuristics to try to guess what kind of platform it's dealing with, but that guessing won't always work.

So I guess this might be as simple as introducing a similar patch : https://github.com/libretro/RetroArch/pull/4826/files

There are other patches to look at. It seems no extra backend parameters are required to achieve this.

**Comment by einarf** [comment]
If you do a PR in `glcontext` I'll do some basic testing in a VM and release a new version immediately.

**Comment by christopher-hesse** [comment]
I don’t see how a version that does not let you select the device index
would work correctly in a multi gpu system, am I missing something?

**Comment by einarf** [comment]
If device index makese sense, go for it!

**Comment by christopher-hesse** [comment]
I am not particularly familiar with EGL, I just want headless rendering to work on Linux for my python scripts.

Speaking of which, how are the tests run?  I didn't see the test output in travis.

**Comment by einarf** [comment]
I'm not extremely familiar with EGL either. I just know the basics and what was uncovered in this issue is also new to me.

Tests in glcontext is very basic at the moment. Borh glcontext and moderngl currently don't run tests in travis or github actions, but that might change soon.

**Comment by christopher-hesse** [comment]
https://github.com/moderngl/glcontext/pull/13

**Comment by christopher-hesse** [comment]
Seemed to work when I tested it.  Doesn't really help people figure out which device index is which, but at least people have the option.

**Comment by einarf** [comment]
PR looks good. A bit more testing needed. Maybe try on Arch and some older debian based linux (or at least some setup having older EGL version)

**Comment by christopher-hesse** [comment]
Yeah, I'm afraid I don't have a good test setup.  I tested on GCE's debian image but it ended up adding like 2 hours to the PR (which was probably 15 minutes of local dev + testing) due to all the overhead of a one-off setup just for testing the PR.

**Comment by christopher-hesse** [comment]
Thanks for the help!

**Comment by einarf** [comment]
No, thank **you** for PRing this. Handling the fallback is the easy part 😄

**Comment by einarf** [comment]
`2.3.dev0` should now have the egl changes

**Comment by einarf** [comment]
glcontext 2.3.0 is out. We have documented context creation and have egl examples.

**Comment by christopher-hesse** [comment]
Great thanks!
