### ISSUE TITLE
program._member dose not contain all uniform variables 

### ISSUE THREAD

**Issue by MySticalWing** [moderngl/moderngl#411]
This is my test python file:
```python
vertex_shader = """
#version 330

uniform sampler2D position_texture;
uniform sampler2D normal_texture;
uniform sampler2D diffuse_texture;

uniform mat4 modelview = mat4(0.0);
uniform ivec2 texel_pos = ivec2(0);

out vec3 out_position;
out vec3 out_normal;
out float out_temperature;

void main() {
    vec3 vertex_coord_in_camera = texelFetch(position_texture, texel_pos, 0).rgb;
    if (vertex_coord_in_camera.z == 0.0) {
        // A 0.0 z value means we missed the mesh. Just write out 0.0 as the result
        out_position = vec3(0.0);
        out_normal = vec3(0.0);
        out_temperature = 0.0;
    } else {
        // Reverse translations and rotations aligning the point with the original mesh
        out_position = (inverse(modelview) * vec4(vertex_coord_in_camera, 1.0)).xyz;
        out_normal = texelFetch(normal_texture, texel_pos, 0).xyz;
        out_temperature = texelFetch(diffuse_texture, texel_pos, 0).r;
    }
}
"""

if __name__ == '__main__':
    import moderngl

    ctx = moderngl.create_standalone_context()
    program = ctx.program(vertex_shader=vertex_shader)
    print(program._members)

```
after I create a program object by `program =ctx.program(vertex_shader=vertex_shader)`, 
the program._members only contains part of the variables `{'position_texture': <Uniform: 0>, 'modelview': <Uniform: 1>, 'texel_pos': <Uniform: 2>}`.
Since I am new to shader,  all the things that I know is OpenGL will remove the unused variables in shader. 
Thanks, and sorry for my poor english.

**Comment by einarf** [comment]
Because this is a transform shader you need to register the out attributes to enable them 
```python
    program = ctx.program(
        vertex_shader=vertex_shader,
        varyings=['out_position', 'out_normal', 'out_temperature'],
    )
    print(program._members)
```
The output should be somthing like 
```python
{
    'out_position': <Varying: 0>, 
    'out_normal': <Varying: 1>, 
    'out_temperature': <Varying: 2>, 
    'diffuse_texture': <Uniform: 0>, 
    'modelview': <Uniform: 1>, 
    'normal_texture': <Uniform: 2>, 
    'position_texture': <Uniform: 3>, 
    'texel_pos': <Uniform: 4>
}
```

**Comment by MySticalWing** [comment]
it's solved my problem, thank you very much !

**Comment by einarf** [comment]
No problem. I recognize the shader from the fragment picking example. The reason we don't specify out attributes there is that moderngl-window will automatically parse out the attributes from the glsl source for you. The built in shader loader has a lot of additional features.

**Comment by MySticalWing** [comment]
Yes, I copied this shader from fragment picking example, and want to writing my picking program based on moderngl only. May be I should read the documentations more, thanks again, and sorry for my late response(I do not browse github often).

**Comment by MySticalWing** [comment]
One more question, I want to know if there exists a ProgramDescription-like class use to load shader from glsl file in the moderngl library? I do not find in the documentation.
