### ISSUE TITLE
Framebuffer: Support redering to texture array layers

### ISSUE THREAD

**Issue by nir** [moderngl/moderngl#413]
Being able to render a shadow map into a layer of a texture array would help reduce the number of required texture units.

This is the technique used in the NVIDIA document describing the cascaded shadow mapping technique:
https://developer.download.nvidia.com/SDK/10.5/opengl/src/cascaded_shadow_maps/doc/cascaded_shadow_maps.pdf

**Comment by yonibr** [comment]
Hi, are there any updates to this issue (or any workarounds)? I'm also working on implementing CSMs and would like to be able to use texture arrays. Thank you!
