### ISSUE TITLE
Multiple contexts hangs when context is created in main thread

### ISSUE THREAD

**Issue by tomfallen** [moderngl/moderngl#414]
**Description**

I'm trying to use to do some headless rendering in a function that I want to parallelize using `parmap`.  However, if I create a context in the main process, then creating a context in the child processes hangs forever.  I've created a minimal example, below.  As is, it runs, but if either of the lines that call `create_context` are un-commented, it hangs on the `create_context` calls in all the child processes.  If `pm_parallel` is set to `False`, it runs in either case.

**Proof of code**

```py
def create_context(thread_num):
    print(f"Thread {thread_num}: entered create_context.")
    ctx = mgl.create_context(require=330, standalone=True, backend='egl')
    print(f"Thread {thread_num}: created context {ctx}.")
    return


# The parmap call below hangs if this is called:
# create_context(-1)

# The parmap call below hangs if this is called, with or without release().
# ctx = mgl.create_context(require=330, standalone=True, backend='egl')
# ctx.release()

# Setting pm_parallel false makes it run with either of the above calls.
pm_parallel = True

num_threads = 3
ret = parmap.map(create_context, range(num_threads), pm_parallel=pm_parallel)
```

**Expected behavior**

I would expect the code above to run even if a context is created in the main process.

**Notes**

I also tried using a global context manager based on this example, below.
https://moderngl.readthedocs.io/en/stable/reference/context.html?highlight=**settings#contextmanager
I don't really understand why this works, as `ContextManager.ctx` cannot be pickled once a context is created, but `ContextManager` can be pickled.  However, this causes the child processes to share a context causing data from one thread to show up in other threads occasionally, which is probably expected, but means this workaround doesn't work for me.

Using `xvfb-run` before running the script above does not seem to change the behavior.

Right now I'm just going to make sure a context isn't created in the main process, but this isn't ideal.

**Version info**

```
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) UHD Graphics 630 (CFL GT2)
version: 4.6 (Core Profile) Mesa 20.0.8
python: 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
platform: linux
code: 460
```

**Comment by einarf** [comment]
In a VM I get the following (Ubuntu 20 in hyperv)
```
Thread 0: entered create_context.
Thread 1: entered create_context.
Thread 2: entered create_context.
Thread 1: created context <Context 139850424525184 version_code=330>.
Thread 0: created context <Context 139850424525184 version_code=330>.
Thread 2: created context <Context 139850424525184 version_code=330>.
```
No hangs as far as I can see. Might be driver issues?

**Comment by einarf** [comment]
With EGL you should not need to use xvfb. Just create `Framebuffer`s you render to if that is needed.

**Comment by tomfallen** [comment]
> In a VM I get the following (Ubuntu 20 in hyperv)
> 
> ```
> Thread 0: entered create_context.
> Thread 1: entered create_context.
> Thread 2: entered create_context.
> Thread 1: created context <Context 139850424525184 version_code=330>.
> Thread 0: created context <Context 139850424525184 version_code=330>.
> Thread 2: created context <Context 139850424525184 version_code=330>.
> ```
> 
> No hangs as far as I can see. Might be driver issues?

@einarf 
Did you try it with either `# create_context(-1)` or `ctx = mgl.create_context(require=330, standalone=True, backend='egl')` uncommented?  Sorry, that might not have been the clearest way to post the example.  It runs for me as is, but either of those cause it to hang.

Regarding `xvfb`, I was running that due to issues running it in a docker container, but I'm not certain if that's necessary or not right now in Docker.  I also thought it might reduce potential driver issues.

FYI: I'm on Ubuntu 18.04 and these test were not in a Docker container.

**Comment by einarf** [comment]
oh right. Yes, it does hang for me when context is also created in main thread. I'm not entirely sure why.

There is a pre-release of glcontext that should have better support in docker containers : https://pypi.org/project/glcontext/2.3.dev0/
