### ISSUE TITLE
Problems Using Two Contexts In One Process

### ISSUE THREAD

**Issue by tomfallen** [moderngl/moderngl#415]
**Description**

I'm trying to use two different ModernGL contexts to do different offscreen rendering tasks in the same script and having problems.  It seems that the contexts aren't independent, and I'm getting both variable name collisions, as well as confusion between different textures.

I've created relatively simple example below.  One problem is that setting `rot` in `mapper2` seems to overwrite `rot` in `mapper1`  This is the output I get:
```
mapper1 rot:  (1.0, 0.0, 0.0, 1.0)
mapper1 rot:  (0.0, -1.0, 1.0, 0.0)
mapper2 rot:  (0.0, -1.0, 1.0, 0.0)
```

The other issues is that strange things happen with the texture in `mapper1`.  See the attached screenshot, where `img1a` and `img1b` are both not as expected.  If I don't create or use `mapper2`, then `mapper` behaves as expected (rendering a red image).

In my full example, I'm seeing additional issues, such as setting a program value then immediately reading it and getting a different value.

I tried name-mangling the texture names as well as explicitly setting which texture I'm using, and stills see data from one texture showing up in the other rendering.

Is this expected behavior?  Am I using this incorrectly?  If I name-mangle everything, would this be expected to work?

**Proof of code**

```py
import numpy as np
import moderngl as mgl

from matplotlib import pyplot as plt

FRAGMENT_SHADER = """
  #version 330
  uniform sampler2D img_src;
  in vec2 dst_tex;
  out vec4 f_color;

  uniform mat2 rot;
  vec2 tex_rot;

  void main() {
      tex_rot = rot * dst_tex;
      f_color = texture(img_src, tex_rot);
    }
"""

VERTEX_SHADER = """
  #version 330

  in vec2 in_vert;
  out vec2 dst_tex;

  void main() {
    dst_tex = in_vert;
    gl_Position = vec4(in_vert * 2.0 - 1.0, 0.0, 1.0);
  }
"""

CANVAS_VERTS = np.array([
    [-1.0, -1.0],
    [-1.0, 1.0],
    [1.0, 1.0],
    [1.0, -1.0],
]).reshape(-1).astype('f4')


class TextureMapper(object):
    def __init__(self, height, width, offset):
        self.h = height
        self.w = width
        self.ctx = mgl.create_context(standalone=True, backend='egl')

        self.fbo = self.ctx.simple_framebuffer((self.w, self.h), components=4)
        self.fbo.use()

        self.prog = self.ctx.program(
            vertex_shader=VERTEX_SHADER,
            fragment_shader=FRAGMENT_SHADER,
        )

        self.vbo = self.ctx.buffer(CANVAS_VERTS)
        self.vao = self.ctx.simple_vertex_array(self.prog, self.vbo, 'in_vert')

        data = bytes([0]) * (self.w * self.h * 3)
        self.texture = self.ctx.texture((self.w, self.h), 3, data)
        self.texture.filter = (mgl.LINEAR, mgl.LINEAR)
        self.texture.use()

    def render(self, img):
        # self.fbo.use()  # Is this necessary?
        self.texture.write(img.tobytes())

        self.vao.render(mgl.TRIANGLE_STRIP)

        data = np.frombuffer(self.fbo.read(components=4), dtype=np.uint8)
        img_dst = data.reshape(self.w, self.h, 4).copy()
        return img_dst


if __name__ == "__main__":

    # Make the shapes slighly different.
    h1 = 512
    w1 = h1 * 2

    h2 = 720
    w2 = h2 * 3

    rot1 = np.eye(2)
    rot2 = np.array([[0.0, -1.0], [1.0, 0.0]])

    mapper1 = TextureMapper(h1, w1, offset=0)
    mapper1.prog['rot'] = tuple(rot1.flatten())

    print("mapper1 rot: ", mapper1.prog.get('rot', None).value)

    mapper2 = TextureMapper(h2, w2, offset=100)
    mapper2.prog['rot'] = tuple(rot2.flatten())

    print("mapper1 rot: ", mapper1.prog.get('rot', None).value)
    print("mapper2 rot: ", mapper2.prog.get('rot', None).value)

    img_black = np.zeros((h1, w1, 3), dtype=np.uint8)

    img_red = np.zeros((h1, w1, 3), dtype=np.uint8)
    img_red[:, :, 0] = 255

    img_green = np.zeros((h2, w2, 3), dtype=np.uint8)
    img_green[:, :, 1] = 255

    img1a = mapper1.render(img_red)
    img2a = mapper2.render(img_green)

    img1b = mapper1.render(img_red)
    img2b = mapper2.render(img_green)

plt.figure()
plt.title("img1a")
plt.imshow(img1a)

plt.figure()
plt.title("img1b")
plt.imshow(img1b)

plt.figure()
plt.title("img2a")
plt.imshow(img2a)

plt.figure()
plt.title("img2b")
plt.imshow(img2b)

plt.show()
```

**Expected behavior**

I was hoping the two contexts would be completely independent.

**Version info**

moderngl 5.6.1
--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) UHD Graphics 630 (CFL GT2)
version: 4.6 (Core Profile) Mesa 20.0.8
python: 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
platform: linux
code: 460
```
I'm on Ubuntu 18.04.
![moderngl_example_02_output](https://user-images.githubusercontent.com/9384943/93230719-d4db8780-f72c-11ea-8bc9-15556eb7774c.png)

**Comment by einarf** [comment]
I think currently you will have to switch context using `enter` and `exit` : https://moderngl.readthedocs.io/en/latest/reference/context.html#moderngl.Context.__enter__

The moderngl objects itself do reference the context they belong to, but if the context is not switched they would be acting on identical objects with the same ID/name in the wrong context.

**Comment by tomfallen** [comment]
> I think currently you will have to switch context using `enter` and `exit` : https://moderngl.readthedocs.io/en/latest/reference/context.html#moderngl.Context.__enter__
> 
> The moderngl objects itself do reference the context they belong to, but if the context is not switched they would be acting on identical objects with the same ID/name in the wrong context.

Thanks a bunch. That resolved my issues, and also saved my day.

**Comment by einarf** [comment]
This is useful when shared context are used. (mainly on linux in some situations).
We don't really have control over what context is active or when it might be destroyed, so it's better to keep it simple like this.

I'll keep this open until more info is added in docs. Working on a slight restructure.

**Comment by einarf** [comment]
This shoud be covered in Context Creation section in docs now
