### ISSUE TITLE
Make wheels for python 3.9

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#416]
Python 3.9 will be released very soon and we should have wheels for it.

Release a 5.6.3 with py39 wheels. We might also want to consider deprecating 3.5 at some point.

**Comment by McSinyx** [comment]
Moreover, recent releases are missing the source distribution, which prevent them from being installed from PyPI.

**Comment by abey79** [comment]
I won't cry for 3.5, but I'm keen with 3.9 :)

Python 3.9.1 is currently the only version that officially supports macOS Big Sur and I'd be happy to be able to move my project on 3.9.

**Comment by einarf** [comment]
I'll try to get this out in the weekend. Seeing if there are more fixes we can squeeze into the release.

Reminder : #421

**Comment by McSinyx** [comment]
Thanks!

**Comment by einarf** [comment]
5.6.3 is out with python 3.9 wheels!

**Comment by McSinyx** [comment]
I've just noticed that there isn't manylinux wheels for CPython 3.9.  Could you please upload them?

**Comment by einarf** [comment]
> I've just noticed that there isn't manylinux wheels for CPython 3.9. Could you please upload them?

Looks like the build pipline skipped that. Will look into it. What problems does this cause on your side?

**Comment by McSinyx** [comment]
Thanks, compiling requires CPython and X11 headers, which I did not
include in a CI.  That how I noticed, it was easily worked around though.
