### ISSUE TITLE
Strange behavior of TextureArray / sampler2DArray on Mac OSX

### ISSUE THREAD

**Issue by nir** [moderngl/moderngl#418]
I am using texture arrays for materials. 

On my Windows 10 laptop everything works correctly. However, on my friend's Macbook machine meshes are rendered with the wrong material. each mesh seems to be rendered with the material of the next mesh.

I was able to reproduce the effect on my Windows laptop by doing the following.

In the shader code I call: texture(N, ...)
In the python code I call: texture.use(location=N+1)

If I do that on my Windows 10 laptop I get the exact same result that my friend get on his macbook machine (without the +1)

**Comment by einarf** [comment]
https://github.com/nir/jupylet/blob/master/examples/spaceship_3d.py

**Comment by nir** [comment]
I changed my code to use the same single texture unit for all texture arrays and the problem on OSX went away.

It could be something wrong I did in the original code - though I don't see any reason why it would manifest badly on OSX but work fine on Windows 10, even if I limit my Windows setup to just 8 texture units like on the OSX machine.

I think you can close this issue - it is probably good enough that it remains as a reference in case someone else stumbles on this again.

In case you would like to investigate it, the last commit of my code that exhibits the problem on OSX is: 
https://github.com/nir/jupylet/commit/4bd870de4deb6a48fee569fd4e8760157d1d2e06

And the fix/workaround by using a single texture unit is in:
https://github.com/nir/jupylet/commit/c6c4c23658798391f611c0d6af21a7895d39164e

Thanks for all your help

**Comment by einarf** [comment]
We can make a simple example using multiple texture arrays in differernt channels and see. Should be a quick one to test!
