### ISSUE TITLE
MGL Exception needs to derive from Python's BaseException to be able to catch them

### ISSUE THREAD

**Issue by pavelkrupala** [moderngl/moderngl#419]
I've recently stumbled upon a minor issue when .use() of textures. I'm working on a texture manager. When I do release a texture and later I try to .use it I end up with uncatchable exception:

```py
from moderngl.mgl import InvalidObject
# create any texture
# release the texture in code
try: texture.use()
except InvalidObject: dumpException()
```

this will raise this error:

```
Traceback (most recent call last):
  File "D:/OpenMaterialDesigner/src/main/python/main.py", line 201, in <module>
    exit_code = appctx.app.exec_()      # 2. Invoke appctxt.app.exec_()
  File "D:\OpenMaterialDesigner\src\main\python\widgets\preview3d\render_widget.py", line 140, in paintGL
    self.gl_scene.updateUniforms()
  File "D:\OpenMaterialDesigner\src\main\python\widgets\preview3d\render_scene.py", line 161, in updateUniforms
    self.bindTextures()
  File "D:\OpenMaterialDesigner\src\main\python\scenes\base_scene.py", line 192, in bindTextures
    except InvalidObject:
TypeError: catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "D:\OpenMaterialDesigner\src\main\python\scenes\base_scene.py", line 191, in bindTextures
    try: texture.use()
  File "D:\OpenMaterialDesigner\src\main\python\gleval\texture_slot.py", line 102, in use
    self.texture.use(self.num_sampler)
  File "C:\Python37\lib\site-packages\moderngl\texture.py", line 377, in use
    self.mglo.use(location)
AttributeError: 'mgl.InvalidObject' object has no attribute 'use'
```

The issue is:
```
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Expected behavior**

`mgl.InvalidObject ` aka CPP's `struct MGLInvalidObject` doesn't inherit from Python's `BaseException` and it should. Only then will Python be able to catch those exceptions

I would love to add it myself to the code, however I'm not sure where to do that :)

**Version info**

```
moderngl 5.6.2
--------------
vendor: NVIDIA Corporation
renderer: GeForce GTX 970/PCIe/SSE2
version: 3.3.0 NVIDIA 456.71
python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
platform: win32
code: 330
```

**Comment by cprogrammer1994** [comment]
InvalidObject is not an exception is a type that was used for the following case:

buffer = ctx.buffer()
type(buffer) # Buffer
buffer.release()
type(buffer) # InvalidObject

this was an early idea that prevented invalid objects from being used, mapped, ... without any extra checking in their method.

**Comment by einarf** [comment]
This is something we can document.

**Comment by pavelkrupala** [comment]
Also I realized that there could be catched the 'AttributeError' exception when using the InvalidObject

**Comment by pavelkrupala** [comment]
a good thing is that it could be checked in python even before calling those objects method, id:
```
if type(self.texture.mglo) == moderngl.mgl.InvalidObject:
    self.print("There will be error", color='red')
```

**Comment by cprogrammer1994** [comment]
Consider this example: the user programatically released an object then calls `write()` on a `buffer` I think it is totally legit to see `Invalid object has no method write` and there is no point catching it. this invalid object was more useful before the python wrapper with classes and `.mglo` attirbutes were added.

**Comment by einarf** [comment]
Keep this issue open until I have added a section in docs. This section will also cover #409

**Comment by pavelkrupala** [comment]
yes makes sense. I thought before that I was unable to catch the error when trying to do incorrect operation, However it's catchable by AttrErr. The invalid object makes perfect sense there.

**Comment by einarf** [comment]
Documented : https://moderngl.readthedocs.io/en/latest/the_guide/gc.html
