### ISSUE TITLE
moderngl.error.Error: the value must be a list of size 6 not 12

### ISSUE THREAD

**Issue by zhangluustb** [moderngl/moderngl#422]
**Description**

ERROR INFO
moderngl.error.Error: the value must be a list of size 6 not 12

"But my shader script need 12 instead of 6"

**Proof of code**

uniform float reshapeIntensity[12]

**Expected behavior**

no error in the host machine 

**Version info**

ENV
moderngl 5.60
glsl version 330
ubuntu docker nvcr.io/nvidia/pytorch:20.03-py3 18.04.1-Ubuntu
NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0 
Xvfb :99 -screen 0 640x480x24 &

**Comment by einarf** [comment]
Code for setting the uniform?

**Comment by zhangluustb** [comment]
> Code for setting the uniform?

Yes.

**Comment by einarf** [comment]
Can you show me the python code that sets the uniform?

**Comment by zhangluustb** [comment]
> Can you show me the python code that sets the uniform?

`
self.reshape_intensitys = [0.0] * 12

shader_2.prog["cartesianPoints"].value = [(i[0], i[1]) for i in landmarks[0].tolist()]
shader_2.prog["textureWidth"].value = img.size[0]
shader_2.prog["textureHeight"].value = img.size[1]
shader_2.prog["reshapeIntensity"].value = self.reshape_intensitys
`

`
#version 330
// precision mediump float;
in vec2 v_vert;
out vec4 FragColor;
uniform sampler2D sTexture;
// face reshape render
// 图像笛卡尔坐标系的关键点，也就是纹理坐标乘以宽高得到
uniform vec2 cartesianPoints[106];
// 是否允许美型处理，存在人脸时为1，没有人脸时为0
int enableReshape=1;

#define INDEX_FACE_LIFT     0   // 瘦脸
#define INDEX_FACE_SHAVE    1   // 削脸
#define INDEX_FACE_NARROW   2   // 小脸
#define INDEX_CHIN          3   // 下巴
#define INDEX_FOREHEAD      4   // 额头
#define INDEX_EYE_ENLARGE   5   // 大眼
#define INDEX_EYE_DISTANCE  6   // 眼距
#define INDEX_EYE_CORNER    7   // 眼角
#define INDEX_NOSE_THIN     8   // 瘦鼻
#define INDEX_ALAE          9   // 鼻翼
#define INDEX_PROBOSCIS    10   // 长鼻
#define INDEX_MOUTH        11   // 嘴型
#define INDEX_SIZE 12           // 索引大小

// 美型程度参数列表
uniform float reshapeIntensity[INDEX_SIZE];
// 纹理宽度
uniform int textureWidth;
// 纹理高度
uniform int textureHeight;

// adjust render
// uniform float brightness;
// uniform int iternum;
// uniform float aaCoef; //参数
// uniform float mixCoef; //混合系数

// vec2 blurCoord1s[14];
// float mul_x = 2.0 / float(textureWidth);
// float mul_y = 2.0 / float(textureHeight);
// 曲线形变处理
vec2 curveWarp(vec2 textureCoord, vec2 originPosition, vec2 targetPosition, float radius)
{
    vec2 offset = vec2(0.0);
    vec2 result = vec2(0.0);

    vec2 direction = targetPosition - originPosition;

    float infect = distance(textureCoord, originPosition)/radius;

    infect = 1.0 - infect;
    infect = clamp(infect, 0.0, 1.0);
    offset = direction * infect;

    result = textureCoord - offset;

    return result;
}

// 大眼处理
vec2 enlargeEye(vec2 currentCoordinate, vec2 circleCenter, float radius, float intensity)
{
    float currentDistance = distance(currentCoordinate, circleCenter);
    float weight = currentDistance / radius;
    weight = 1.0 - intensity * (1.0 - weight * weight);
    weight = clamp(weight, 0.0, 1.0);
    currentCoordinate = circleCenter + (currentCoordinate - circleCenter) * weight;

    return currentCoordinate;
}

// 瘦脸
vec2 faceLift(vec2 currentCoordinate, float faceLength)
{
    vec2 coordinate = currentCoordinate;
    vec2 currentPoint = vec2(0.0);
    vec2 destPoint = vec2(0.0);
    float faceLiftScale = reshapeIntensity[INDEX_FACE_LIFT] * 0.05;
    float radius = faceLength;

    currentPoint = cartesianPoints[3];
    destPoint = currentPoint + (cartesianPoints[52] - currentPoint) * faceLiftScale;
    coordinate = curveWarp(coordinate, currentPoint, destPoint, radius);

    currentPoint = cartesianPoints[29];
    destPoint = currentPoint + (cartesianPoints[52] - currentPoint) * faceLiftScale;
    coordinate = curveWarp(coordinate, currentPoint, destPoint, radius);

    radius = faceLength * 0.8;
    currentPoint = cartesianPoints[10];
    destPoint = currentPoint + (cartesianPoints[54] - currentPoint) * (faceLiftScale * 0.6);
    coordinate = curveWarp(coordinate, currentPoint, destPoint, radius);

    currentPoint = cartesianPoints[22];
    destPoint = currentPoint + (cartesianPoints[54] - currentPoint) * (faceLiftScale * 0.6);
    coordinate = curveWarp(coordinate, currentPoint, destPoint, radius);

    return coordinate;
}

// 削脸
vec2 faceShave(vec2 currentCoordinate, float faceLength)
{
    vec2 coordinate = currentCoordinate;
    vec2 currentPoint = vec2(0.0);
    vec2 destPoint = vec2(0.0);
    float faceShaveScale = reshapeIntensity[INDEX_FACE_SHAVE] * 0.12;
    float radius = faceLength * 1.0;

    // 下巴中心
    vec2 chinCenter = (cartesianPoints[16] + cartesianPoints[85]) * 0.5;
    currentPoint = cartesianPoints[13];
    destPoint = currentPoint + (chinCenter - currentPoint) * faceShaveScale;
    coordinate = curveWarp(coordinate, currentPoint, destPoint, radius);

    currentPoint = cartesianPoints[19];
    destPoint = currentPoint + (chinCenter - currentPoint) * faceShaveScale;
    coordinate = curveWarp(coordinate, currentPoint, destPoint, radius);

    return coordinate;
}

// 处理下巴
vec2 chinChange(vec2 currentCoordinate, float faceLength)
{
    vec2 coordinate = currentCoordinate;
    vec2 currentPoint = vec2(0.0);
    vec2 destPoint = vec2(0.0);
    float chinScale = reshapeIntensity[INDEX_CHIN] * 0.08;
    float radius = faceLength * 1.25;
    currentPoint = cartesianPoints[16];
    destPoint = currentPoint + (cartesianPoints[54] - currentPoint) * chinScale;
    coordinate = curveWarp(coordinate, currentPoint, destPoint, radius);

    return coordinate;
}

void main()
{
    
        vec2 coordinate = v_vert.xy;
        // 禁用美型处理或者鼻子不在图像中，则直接绘制
        if (enableReshape == 0 || (cartesianPoints[54].x / float(textureWidth) <= 0.03)
            || (cartesianPoints[54].y / float(textureHeight)) <= 0.03) {
            FragColor = texture2D(sTexture, coordinate);
            return;
        }

        // 将坐标转成图像大小，这里是为了方便计算
        coordinate = v_vert * vec2(float(textureWidth), float(textureHeight));

        //draw point
        if(distance(coordinate,cartesianPoints[96])<2.0 ||distance(coordinate,cartesianPoints[97])<2.0 ||distance(coordinate,cartesianPoints[22])<2.0||distance(coordinate,cartesianPoints[3])<2.0||distance(coordinate,cartesianPoints[29])<2.0||distance(coordinate,cartesianPoints[10])<2.0||distance(coordinate,cartesianPoints[52])<2.0||distance(coordinate,cartesianPoints[54])<2.0||distance(coordinate,cartesianPoints[16])<2.0||distance(coordinate,cartesianPoints[13])<2.0||distance(coordinate,cartesianPoints[19])<2.0||distance(coordinate,cartesianPoints[85])<2.0){
            FragColor = vec4(1.0,1.0,1.0,1.0);
            return;
        }

        float eyeDistance = distance(cartesianPoints[96], cartesianPoints[97]); // 两个瞳孔的距离

        // 瘦脸
        coordinate = faceLift(coordinate, eyeDistance);

        // 削脸
        coordinate = faceShave(coordinate, eyeDistance);

        // 下巴
        coordinate = chinChange(coordinate, eyeDistance);

        // 大眼
        float eyeEnlarge = reshapeIntensity[INDEX_EYE_ENLARGE] * 0.12; // 放大倍数
        if (eyeEnlarge > 0.0) {
            float radius = eyeDistance * 0.33; // 眼睛放大半径
            coordinate = enlargeEye(coordinate, cartesianPoints[96] + (cartesianPoints[97] - cartesianPoints[96]) * 0.05, radius, eyeEnlarge);
            coordinate = enlargeEye(coordinate, cartesianPoints[97] + (cartesianPoints[96] - cartesianPoints[97]) * 0.05, radius, eyeEnlarge);
        }

        // 转变回原来的纹理坐标系
        coordinate = coordinate / vec2(float(textureWidth), float(textureHeight));
        // 输出图像
        FragColor = texture2D(sTexture, coordinate);
    
}
`

**Comment by zhangluustb** [comment]
Because in the local machine everything is ok. But with the same code in a docker, it has a error.

**Comment by einarf** [comment]
Weird. The only thing I can think of if ensuring you write 32 bit floats.
```python
from array import array
shader_2.prog["reshapeIntensity"].write(array("f", self.reshape_intensitys))
```
Maybe also sanity add sanity check that `len(self.reshape_intensitys) == 12`

**Comment by einarf** [comment]
When I think of it.. the reason might be that the OpenGL implementation providied in the docer container is not able to handle this much uniform data. `uniform vec2 cartesianPoints[106];` in particular will take up a lot of the available slots.

You should instead use Uniform Buffer Object or store this data in a float texture.

**Comment by zhangluustb** [comment]
> When I think of it.. the reason might be that the OpenGL implementation providied in the docker container is not able to handle this much uniform data. `uniform vec2 cartesianPoints[106];` in particular will take up a lot of the available slots.
> 
> You should instead use Uniform Buffer Object or store this data in a float texture.
> 
> The limits for the context can be inspected in `ctx.info`

Thank you for your help. I'll try.
Besides, do you have an example of deploying moderngl on a remote server? Xvfb works not good.

**Comment by zhangluustb** [comment]
> When I think of it.. the reason might be that the OpenGL implementation providied in the docker container is not able to handle this much uniform data. `uniform vec2 cartesianPoints[106];` in particular will take up a lot of the available slots.
> 
> You should instead use Uniform Buffer Object or store this data in a float texture.
> 
> The limits for the context can be inspected in `ctx.info`

```
{'GL_VENDOR': 'VMware, Inc.',
 'GL_RENDERER': 'llvmpipe (LLVM 10.0.0, 256 bits)',
 'GL_VERSION': '3.3 (Core Profile) Mesa 20.0.8',
 'GL_POINT_SIZE_RANGE': (1.0, 255.0),
 'GL_SMOOTH_LINE_WIDTH_RANGE': (1.0, 255.0),
 'GL_ALIASED_LINE_WIDTH_RANGE': (1.0, 255.0),
 'GL_POINT_FADE_THRESHOLD_SIZE': 1.0,
 'GL_POINT_SIZE_GRANULARITY': 0.10000000149011612,
 'GL_SMOOTH_LINE_WIDTH_GRANULARITY': 0.10000000149011612,
 'GL_MIN_PROGRAM_TEXEL_OFFSET': -32.0,
 'GL_MAX_PROGRAM_TEXEL_OFFSET': 31.0,
 'GL_MINOR_VERSION': 3,
 'GL_MAJOR_VERSION': 3,
 'GL_SAMPLE_BUFFERS': 0,
 'GL_SUBPIXEL_BITS': 4,
 'GL_CONTEXT_PROFILE_MASK': 1,
 
 'GL_DOUBLEBUFFER': False,
 'GL_STEREO': False,
 'GL_MAX_VIEWPORT_DIMS': (8192, 8192),
 'GL_MAX_3D_TEXTURE_SIZE': 2048,
 'GL_MAX_ARRAY_TEXTURE_LAYERS': 512,
 'GL_MAX_CLIP_DISTANCES': 8,
 'GL_MAX_COLOR_ATTACHMENTS': 8,
 'GL_MAX_COLOR_TEXTURE_SAMPLES': 1,
 
 
 'GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS': 128,
 
 
 'GL_MAX_CUBE_MAP_TEXTURE_SIZE': 8192,
 'GL_MAX_DEPTH_TEXTURE_SAMPLES': 1,
 'GL_MAX_DRAW_BUFFERS': 8,
 'GL_MAX_DUAL_SOURCE_DRAW_BUFFERS': 1,
 'GL_MAX_ELEMENTS_INDICES': 3000,
 'GL_MAX_ELEMENTS_VERTICES': 3000,
 'GL_MAX_FRAGMENT_INPUT_COMPONENTS': 128,
 
 
 
 'GL_MAX_GEOMETRY_INPUT_COMPONENTS': 128,
 'GL_MAX_GEOMETRY_OUTPUT_COMPONENTS': 128,
 'GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS': 32,
 
 
 'GL_MAX_INTEGER_SAMPLES': 1,
 'GL_MAX_SAMPLES': 1,
 'GL_MAX_RECTANGLE_TEXTURE_SIZE': 8192,
 'GL_MAX_RENDERBUFFER_SIZE': 8192,
 'GL_MAX_SAMPLE_MASK_WORDS': 1,
 'GL_MAX_SERVER_WAIT_TIMEOUT': 9223372034707292159,
 'GL_MAX_TEXTURE_BUFFER_SIZE': 65536,
 'GL_MAX_TEXTURE_IMAGE_UNITS': 32,
 'GL_MAX_TEXTURE_LOD_BIAS': 16,
 'GL_MAX_TEXTURE_SIZE': 8192,
 
 
 'GL_MAX_VARYING_VECTORS': 32,
 'GL_MAX_VERTEX_ATTRIBS': 16,
 'GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS': 32,
 
 
 'GL_MAX_VERTEX_OUTPUT_COMPONENTS': 128,
 
 'GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET': 2047,
 'GL_MAX_VERTEX_ATTRIB_BINDINGS': 16}

```

**Comment by cprogrammer1994** [comment]
you have only 6 floats in the shader after **optimization**.
you are using the `INDEX_EYE_ENLARGE` as the highest index so you have only 6 needed (the rest is optimized out.

until you start using all the values of the float array change

```
shader_2.prog["reshapeIntensity"].value = self.reshape_intensitys
```

to

```
MAX_INDEX_USED = 5
shader_2.prog["reshapeIntensity"].value = self.reshape_intensitys[:MAX_INDEX_USED + 1]
```

**Comment by zhangluustb** [comment]
> you have only 6 floats in the shader after **optimization**.
> you are using the `INDEX_EYE_ENLARGE` as the highest index so you have only 6 needed (the rest is optimized out.
> 
> until you start using all the values of the float array change
> 
> ```
> shader_2.prog["reshapeIntensity"].value = self.reshape_intensitys
> ```
> 
> to
> 
> ```
> MAX_INDEX_USED = 5
> shader_2.prog["reshapeIntensity"].value = self.reshape_intensitys[:MAX_INDEX_USED + 1]
> ```
> 
> if you do not know `MAX_INDEX_USED` you can set it to `len(shader_2.prog["reshapeIntensity"].value) -1` probably

set the uniform vec2 cartesianPoints[106] to uniform vec2 cartesianPoints[98] slove this problem.
reshape_intensitys is the little one. 0o0

but i don't know which context limit lead to this, What is the  'GL_MAX_UNIFORM_BLOCK_SIZE' meaning or where to learn about this?

**Comment by einarf** [comment]
`glcontext==2.3.dev0 ` should work in docker with acceleration if you have this available (By using the EGL backend)

**Comment by cprogrammer1994** [comment]
more simple:

you have cartesianPoints[98] because you are not using cartesianPoints[98 : 106].
you have cartesianPoints[6] because you are not using cartesianPoints[6 : 12].
