### ISSUE TITLE
add the render primitive type to vertex_array constructor

### ISSUE THREAD

**Issue by jimy-byerley** [moderngl/moderngl#423]
Hello dear maintainers

## motivation

In most of the use case, a vertex-array is used with only one primitive type (eg  `mgl.TRIANGLES`, `mgl.LINES`, `mgl.POINTS`)
However it is the only information about rendering that the vertex array doesn't store. And at contrary to buffers and programs, vertex arrays doesn't hold data but only references it, so there is not a huge cost in making 2 VAO where we usually use 1.

## proposed solution

This PR propose to add the vertex type as argument to the `Context.vertex_array` constructor.
It is of course compatible with having the primitive type as optional argument for `va.render()` so this change won't break any code.     

```python
va = ctx.vertex_array(shader, [buffers ...], indices, mgl.TRIANGLES)
va.render()
```

**Comment by jimy-byerley** [comment]
The only thing thing that is not clear for me is if the primitive type should be before or after the buffer of indices:
- if after it won't break any code
```python
va = ctx.vertex_array(shader, [buffers ...],  mode=mgl.TRIANGLES)   # keyword mendatory
```
- if after we would be able to use the primitive type without keyword even when no indices buffer is provided, also it's more intuitive since when we provide indices we already know the kind of primitives we will use 
```python
va = ctx.vertex_array(shader, [buffers ...], mgl.TRIANGLES)   # breaks existing codes
```

**Comment by einarf** [comment]
I've actually been thinking about adding this, but also remember the `render*` methods are affected. This is also one if the reasons I ended up making a wrapper class in moderngl-window.

There is another case were `moide` is redundant: When using geometry shaders the draw primitive should always be the same as the input primitive type in the geometry shader or you'll get a gl error. Right now this is not automatically set. I see this more as a bug,

**Comment by szabolcsdombi** [comment]
this was added at some point, the parameter is called `mode=` and should be used as keyword argument
