### ISSUE TITLE
Image Manipulation with GLSL shaders

### ISSUE THREAD

**Issue by Correct-Syntax** [moderngl/moderngl#425]
Hi,

I would like to use ModernGL to edit images on the GPU via GLSL shaders. I am not familiar with what the best way to go about that is and I don't have experience writing GLSL, so I am not going to pretend I do. I've heard that sometimes GPU processing isn't worth it (vs on the CPU), but I am wondering what cases it would pay, etc.

So, I technically have three questions:

1. What is the best way to do image manipulation with GLSL shaders in ModernGL?

2. **Should I do this, seriously? (Is it worth it?)**

3. Also, how exactly is that done? Is it similar to the below code (from one of the examples)? Could you point me in the right direction if this is not correct?:
```python
import moderngl
import numpy as np

from PIL import Image

ctx = moderngl.create_standalone_context()

prog = ctx.program(
    vertex_shader='''
        #version 330

        in vec2 in_vert;
        in vec3 in_color;

        out vec3 v_color;

        void main() {
            v_color = in_color;
            gl_Position = vec4(in_vert, 0.0, 1.0);
        }
    ''',
    fragment_shader='''
        #version 330

        in vec3 v_color;

        out vec3 f_color;

        void main() {
            f_color = v_color;
        }
    ''',
)

x = np.linspace(-1.0, 1.0, 50)
y = np.random.rand(50) - 0.5
r = np.ones(50)
g = np.zeros(50)
b = np.zeros(50)

vertices = np.dstack([x, y, r, g, b])

vbo = ctx.buffer(vertices.astype('f4').tobytes())
vao = ctx.simple_vertex_array(prog, vbo, 'in_vert', 'in_color')

fbo = ctx.simple_framebuffer((512, 512))
fbo.use()
fbo.clear(0.0, 0.0, 0.0, 1.0)
vao.render(moderngl.LINE_STRIP)

Image.frombytes('RGB', fbo.size, fbo.read(), 'raw', 'RGB', 0, -1).show()
```

Oh, and for integration with numpy, etc is it as simple as just doing the ``fbo.read()`` as in the above code?

Thank you for your time!

**Comment by einarf** [comment]
Doing image manipulation can definitely be done with shaders. The setup will be pretty close to the code you pasted above except that you probably also need some input image to manipulate. You can of course do this with numpy as well, but if you need speed it's probably a few orders of magnitute faster on the gpu (depending on what operations are needed). It's probably one of the simpler things you can do with opengl/moderngl.

.. and yes, you can just `fbo.read()` the data into an `Image` or numpy array. Pretty straight forward. There are also a lot of resources out there related to image manipulation with shaders.

For things like this it's probably better to join our discord server : https://discord.gg/UEMtW8D

**Comment by einarf** [comment]
Discussed on discord
