### ISSUE TITLE
How to change colour3f colour everyframe?

### ISSUE THREAD

**Issue by ShaunKulesa** [moderngl/moderngl#426]
I want to make GL.glColor3f(1.0, 1.0, 1.0) change colour every frame.

**Comment by einarf** [comment]
I don't know what this have to do with moderngl. We don't support even `glColor3f`.

**Comment by ShaunKulesa** [comment]
really?
these are the libraries i imported:
import sys, math, time
if sys.version_info[0] < 3:
    from Tkinter import Tk, YES, BOTH
else:
    from tkinter import Tk, YES, BOTH
from OpenGL import GL, GLU
from pyopengltk import OpenGLFrame

**Comment by einarf** [comment]
You are using PyOpenGL. That is not the same as moderngl 😄

**Comment by ShaunKulesa** [comment]
oh yeah, i thought i saw the import ModernGl but i miss read it. so whats the difference between moderngl and pyopengl?

**Comment by einarf** [comment]
moderngl is a simpler language binding for OpenGL 3.3+. It's a lot more low level using shaders. The opengl version you are using is probably 20 years old, but it still works of course. You can also access these featurs in pyopengl if needed.

The best way to get an impression is to look at examples and docs : https://github.com/moderngl/moderngl/tree/master/examples

**Comment by ShaunKulesa** [comment]
Pyopengl seems to be outdated, all the tutorials i find are from python 2.2, but then pyopengl is so much easier than ModernGl and allows me to use tkinter gui.  But what i dont understand about your library half of it is C and half is python Pygame.

**Comment by einarf** [comment]
moderngl is mostly written in C/C++, yes. Python supports creating extensions like this. It's the same thing pygame is doing. It can help to speed up the performance of the library a great deal.

There is nothing wrong with using PyOpenGL 😃

**Comment by ShaunKulesa** [comment]
Every tutorial i find for loading an image in pyopengl either uses either pygame or imports opengl context which is from python 2.

**Comment by ShaunKulesa** [comment]
The ones that use context are for python 2 and the pygame ones i dont know how to use in pyopengltk.

**Comment by einarf** [comment]
This place is for bugs and issues in the moderngl project. This is not the right place for talking about pyopengl or pyopengl tk. We are just spamming people who are subscribed to this repositry with off-topic stuff.

There are other places more suited for these topics. Maybe the someone on the python discord server knows?
