### ISSUE TITLE
Question: Preferred way to reload shader

### ISSUE THREAD

**Issue by eliemichel** [moderngl/moderngl#427]
I am writing [a simple viewer](https://github.com/eliemichel/Python3dViewer) for which I'd like to be able to reload all shaders.

When using raw opengl, I maintain VAOs and programs separately and the vao gets provided the program only at render time so I can just iterate over my program pool to release them and create them again.

But using moderngl it seems like I'd have to keep track of all vaos using a particular program so that I can update `vao.program` when the program changes. Is there a way to reload a program without invalidating the `Program` object onto which vaos point? Or a way to create a vao without a program?

**Comment by einarf** [comment]
The simplest way is just to create new vertex arrays. They are cheap to store and create anyway. The way I've always done this is creating a small wrapper for the `VertexArray`. It can have a `render` method that takes a program. You can cache vertex array instances internally in a dict using the program id as key.

moderngl-window has a more fancy version of this : https://moderngl-window.readthedocs.io/en/latest/reference/opengl/vao.html
There is a lot of things that can save you a lot of time in that project.

**Comment by eliemichel** [comment]
Thanks! I wasn't aware of this related project, may indeed be useful!
