### ISSUE TITLE
Simple example loading an image?

### ISSUE THREAD

**Issue by DanielArnett** [moderngl/moderngl#428]
[I write fragment shaders for modifying images](https://github.com/DanielArnett/360-VJ/releases), and I'd like to port these to moderngl. I can't find an example that does what I need. 

I just need to get an image and input uv into a fragment shader, and return the resulting image. Does anyone know of an example like this or could help me with one?

**Comment by einarf** [comment]
This was something that was recently discussed in our discord server. Probably a better place for questions like this. Some quick and dirty mockup code : https://paste.pythondiscord.com/janicujuro.py

Discord : https://discord.gg/UEMtW8D

**Comment by DanielArnett** [comment]
Okay I made a few tweaks and submitted it to the examples folder in [this PR](https://github.com/moderngl/moderngl/compare/master...DanielArnett:patch-1)

**Comment by DanielArnett** [comment]
Thanks for your help and the discord invite!
