### ISSUE TITLE
Texture.read should support viewport 

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#434]
We should be able to read a sub-section of an image in the same way ``Texture.write()` works.

**Comment by einarf** [comment]
Doesn't seem to be that simple for textures, but Framebuffer.read() supports it : https://moderngl.readthedocs.io/en/latest/reference/framebuffer.html#moderngl.Framebuffer.read

**Comment by cprogrammer1994** [comment]
the only way to get it stable is with a custom fbo in ctx for this special use case.
texture read ment to be used for debug purposes so one can test if the content matches exactly what was written in.
fbo read is the proper way.

**Comment by einarf** [comment]
Yup! I initially hoped there was something for reading sub-sections of a texture, but I realized it was not so easy 😄
