### ISSUE TITLE
Support Texture1D, Texure1DArray

### ISSUE THREAD

**Issue by mahroni-14** [moderngl/moderngl#436]
Currently texture creating is done by [this](https://moderngl.readthedocs.io/en/stable/reference/texture.html#create) function, which create 2D texture. But when 1D texture creation is needed, no such method is available.

Ref: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage1D.xhtml

**Comment by einarf** [comment]
You can also just use an Nx1 2d texture. There were plans to merge all the texture trypes into the same object so we didn't really want to introduce a new one.

**Comment by mahroni-14** [comment]
Yes currently I am creating 1D texture this way.
And from **glsl** side i am accessing texture this way.

`texture(tex, vec2(x, 0.0f));`

But does this have any performance issue? I am not sure.

**Comment by einarf** [comment]
We should probably support it, but I don't think there's anything notable related to performance between these sampler types.

**Comment by szabolcsdombi** [comment]
I am sorry, despite I know texture1d is a convenient way to pass in colormaps/ranges or just pure data, we do not plan to support Texture1D or BufferTextures.
We do not support rectangle or proxy textures.
These are rarely used and would add too much maintenance burdon to moderngl at the moment.
maybe in the future, but not for now.
