### ISSUE TITLE
How to "(render / access) one VAO's output directly as a texture" in some other shader?

### ISSUE THREAD

**Issue by Tremeschin** [moderngl/moderngl#437]
Not sure if I'm wording this right since I'm a bit inexperienced with GL and I'm in the process of understanding it. I can also be just thinking wrongly in the paradigm of GPUs, so I'd be grateful if you point better ways of acomplishing this.

<hr>

Shortly, I want to do something like this:

```python
# Set up context, program, {vertex,fragment} shader
# create xy/uv buffer to fill the whole screen, VAOs, FB...

# Main routine

# Clear stuff and use FBO
ctx.clear(0.0, 0.0, 0.0)
fbo.use()
fbo.clear()

# Render VAO1 to the FBO
vao1.render(mode = moderngl.TRIANGLE_STRIP)

# Make a texture out of the current FBO and put at location 0
texture = ctx.texture((WIDTH, HEIGHT), 3, fbo.read())
texture.use(location = 0)

# Clear since we got the texture we want
ctx.clear(0.0, 0.0, 0.0)
fbo.clear()

# Render VAO2 which uses the texture above from VAO1 internally
# eg. blur post fx that needs surrounding pixels
vao2.render(mode = moderngl.TRIANGLE_STRIP)

# Continue (get FBO data and pipe to FFmpeg for rendering video)
```

While this works as expected it's painfully slow since, as far as my understanding goes, we render on the GPU, read from the FBO (back to the CPU world) then upload the resulting texture to the GPU. This process lose a lot of efficiency and would be much faster to keep everything on the GPU side.

I'm essentially trying to layer many shaders together by "rendering them to textures", gluing everyone together (apply alpha composite, post FX, etc) in a global VAO that reads from all, so then I can get the outputs from the final FBO only for rendering to a video.

<hr>

Take for example the case of: apply gauss blur to a background, apply lens distortion into some other layer image (for example a game's HUD), merge the two then apply saturation on the center of the screen (the player was damaged or something).

This keeps every part independent from each other since the lens distortion won't be applied on the background, we won't blur the whole screen and we can apply a extra processing layer in the end.

<hr>

I know this isn't possible but in my head it says that something like `fbo1.use(location = 0)` relative to some other `fbo2` is the way it would work _"naturally"_.

I'm opening this question issue just because it's been a few hours since I lurked on the docs and issues for a fast way of doing this, and it's not really apparent for me yet how this is done in a real life scenario.

I'm using `moderngl==5.6.2` on Python 3.8 (few changes from version to version so we can communicate better also latest version).

**Comment by einarf** [comment]
This can be done purely on the gpu by using texture attachments in framebuffers. When doing multiple passes it's common to set up a source and destination texture and framebuffer with texture attachments.

```python
texture_src = ctx.texture((width, height), 4)
texture_dst= ctx.texture((width, height), 4)
fbo_src = ctx.framebuffer(color_attachments=[texture_src])
fbo_dst = ctx.framebuffer(color_attachments=[texture_dst])
```

Rendering to these fbos will render to the texture itself. Internally you can swap source and destination when doing multiple passes.

```python
texture_src, texture_dst = texture_dst, texture_src
fbo_src, fbo_dst = fbo_dst, fbo_src
```

You can also use `fbo.viewport` and `fbo.scissor` to control what parts of the fbos should be affected. This can be useful if you have have a generic setup of a source and destination supporting up (for example) 4k textures and lower.

**Comment by einarf** [comment]
We also have a discord server linked in the readme were you can ask questions.

**Comment by Tremeschin** [comment]
> We also have a discord server linked in the readme were you can ask questions.

Oh I totally missed that one, I was focused on the docs and issues tab.

I'm still digesting what you explained and will try it myself in a while, then report back otherwise join the Discord server!! ty :)

**Comment by einarf** [comment]
This should ping-pong render between two fbos. 

```python
texture_src = ctx.texture((width, height), 4)
texture_dst = ctx.texture((width, height), 4)
fbo_src = ctx.framebuffer(color_attachments=[texture_src])
fbo_dst = ctx.framebuffer(color_attachments=[texture_dst])

fbo_src.use()
<render some initial stuff we want to apply postprocessing to>

for _ in range(10):
    fbo_dst.use()
    fbo_dst.clear()  # IF needed
    texture_src.use(location=0)
    <run postprocessing pass>

    # swap source and destination
    texture_src, texture_dst = texture_dst, texture_src
    fbo_src, fbo_dst = fbo_dst, fbo_src
```

**Comment by Tremeschin** [comment]
Hey I just tested with some quick and dirty sketch code and this looks VERY promising, the image was (kind of expected) flipped vertically, got any quick way of flipping or unflipping it when rendering to the other FBO?

<hr>

I guess I don't really need to swap the buffers since my end goal is headless rendering, I get about 120 fps by reading the destination FBO on each loop for FHD canvas, more than enough to saturate a video encoder given my CPU.

And in this case I don't swap them I have the option to pipe the raw bytes array to FFplay, not ideal but works for a preview of the final video which I'm doing currently.

I'll also try to implement this other one we keep swapping the two for a real time performance mode but I have to peek at the wrapper on window creation you offer first, but small steps first :p

**Comment by einarf** [comment]
The fastest (and laziest) might is probably to add a uniform in the program that can invert the texture coordinates if needed. It can be a bool combined with an if statement or a float value that offsets the `v` coordinate. This is at least infinitely more cheaper than flipping the source data in memory first.

**Comment by Tremeschin** [comment]
Gotcha, good approach!

**Comment by einarf** [comment]
You do however need two textures and fbos if you are doing multiple passes. Just to make that clear. It doesn't matter if it's headless or not. You cannot read and write from the source at the same time.

**Comment by Tremeschin** [comment]
> You do however need two textures and fbos if you are doing multiple passes. Just to make that clear. It doesn't matter if it's headless or not. You cannot read and write from the source at the same time.

Yes I can visualize why that is the case, I'll not perform simultaneous RW on the same source, I plan on either having a few "parallel" sources being concatenated into a common destination or this 2 fbo+textures scheme but iterating over the many layers (programs, shaders), rendering them one by one and progressively alpha compositing on the common destination. 

The sources will be read only since I'll only access their contents as they are already what they should be.

If I stumble across any problem regarding these undefined behaviors I'll read more carefully here since this is unknown territory to me :)
