### ISSUE TITLE
cannot create context in linux

### ISSUE THREAD

**Issue by bolin-chen** [moderngl/moderngl#439]
Hello!
I'm trying to use moderngl on a remote server. I use Ubuntu 16.04.6 LTS and the moderngl 5.6.0.
I got the following error: 

![image](https://user-images.githubusercontent.com/7379489/105941297-11829c80-6098-11eb-87f1-6f1f0063d3e3.png)

There is too little information about how this exception is occured. How can I solve this problem?

**Comment by einarf** [comment]
It just means `glXCreateContext` could to create the context for some reason : https://github.com/moderngl/glcontext/blob/e1a1031b38e72882afce4805472872fe349e093b/glcontext/x11.cpp#L406-L409

If you look into the moderngl documenation the default context backend is x11. This does not always work well on remote servers. You probably want to use the EGL context backend for this.

**Comment by bolin-chen** [comment]
Thanks to your reply. I can create the context with EGL backend. However, I got different result using EGL with that using X11. Is this situation normal?

**Comment by einarf** [comment]
What do you mean by different results?

**Comment by bolin-chen** [comment]
I mean the rendering results are different. But I find out what the problem is. When I used X11 as backend, I wrote:

**Comment by bolin-chen** [comment]
I mean the rendering results are different. But I have found out what the problem is. 
When I used X11, I wrote:
` ctx = moderngl.create_standalone_context()`
`// some code here`
`ctx = moderngl.create_context()`

When I used EGL, I wrote:
`ctx = moderngl.create_standalone_context(backend='egl')`
`// some code here`
`ctx = moderngl.create_standalone_context(backend='egl')`
The second headless context seems to override the first one. Just remove the creation of second context and every thing is ok.
Thanks very much!

**Comment by einarf** [comment]
Yes, only one context can be active at the same time and resources are not shared between contexts by default. I would not recommend using multiple contexts unless you have a very good reason to do that. `Context` to have `__enter__` and `__exit__` methods to control what context is active.

Context creation will activate the new context.
