### ISSUE TITLE
Suggestion: improve the API of vertex_array

### ISSUE THREAD

**Issue by abey79** [moderngl/moderngl#440]
#### Issue

The current API of `ctx.vertex_array` has several shortcoming that could be addressed by a better API:
- When using [structured Numpy arrays](https://numpy.org/doc/stable/user/basics.rec.html), the field specification must be repeated both for the array's `dtype` and for the `vertex_array()`. This redundancy is error prone and unnecessarily verbose. 
- In a large majority of cases, buffer objects are not used after being passed to the vertex array object. In this context, explicitly creating them just to pass them to `vertex_array()` seems unnecessarily verbose.
- The use of `\v`, `\i`, and `\r` in type specification string to denote the context of the buffer seems unpythonic (at least to me).
- The treatment of index buffer is different from the rest: element size is specified with an additional parameter (`index_element_size`) instead of the type specifiers like other buffers.

This issue lays down a proposal to get the discussion started.

#### Proposal

To address the above, I suggest the following changes to `ctxvertex_array()` API.

```python
BufferSpec = Union[
    np.ndarray,
    Tuple[np.ndarray, str],
    Tuple[Union[bytes, moderngl.Buffer], str, ...],
]

# noinspection PyUnusedLocal
class Context:
    def vertex_array(
        self,
        program: moderngl.Program,
        vertex_buffer: Union[Sequence[BufferSpec], BufferSpec],
        index_buffer: Optional[BufferSpec] = None,
        *,
        instance_buffer: Union[None, BufferSpec, Sequence[BufferSpec]] = (),
        render_buffer: Union[None, BufferSpec, Sequence[BufferSpec]] = (),
        skip_errors:bool = False,
    ) -> moderngl.VertexArray:
        ...

class VertexArray:
    @property
    def vertex_buffers(self) -> Sequence[moderngl.Buffer]:
        ...

    @property
    def index_buffer(self) -> moderngl.Buffer:
        ...
    
    @property
    def instance_buffers(self) -> Sequence[moderngl.Buffer]:
        ...

    @property
    def render_buffers(self) -> Sequence[moderngl.Buffer]:
        ...
```

**Change overview:**
- New keyword-only parameter are used for instance and render buffers (instead of the `\i` notation).
- All buffer parameters, including `index_buffer` accept a `BufferSpec` value, and all but `index_buffer` accept a sequence of `BufferSpec` as well.
- A `BufferSpec` maybe either of:
  - A structured Numpy array (in which case the `dtype` is used to infer the data format and the variable names).
  - A tuple of Numpy array and variable name (in which case the `dtype` is used to infer the data format).
  - A tuple of `bytes` or `mgl.Buffer`, format specifier, and variable name(s) (this is the same as the current situation with the added compatibility with raw `bytes`).
- `VertexArray` objects now have a set of properties to access the various buffers attached to it.
 
Note: I'm not suggesting to create a `BufferSpec` class, I'm just referring to it as a `typing` type.

**Structure array examples:**
```python
structured_array = np.empty(N, dtype=[("vertex", "2f4"), ("color", "i1")])
ctx.vertex_array(prog, structured_array)
# ...equivalent to:
ctx.vertex_array(prog, [(structured_array.tobytes(), "2f4 i1", "vertex", "color")])
```

**Simple array example:**
```python
basic_array = np.empty((N, 2), dtype="f4")
ctx.vertex_array(prog, (basic_array, "vertex"))
# ...equivalent to:
ctx.vertex_array(prog, [(basic_array.tobytes(), "2f4", "vertex")])
```

**Multiple buffers example:**
```python
ctx.vertex_array(prog, [structured_array, (basic_array, "normals"), (bytes_buffer, "2f4", "texcoords")])
```

**Index buffer example:**
```python
structured_array = np.empty(N, dtype=[("vertex", "2f4"), ("color", "i1")])
index_array = np.empty(M, dtype="i2")
ctx.vertex_array(prog, structured_array, index_array)
```

**Instance buffer example:**
```python
structured_array = np.empty(N, dtype=[("vertex", "2f4"), ("color", "i1")])
basic_array = np.empty((N, 2), dtype="f4")
index_array = np.empty(M, dtype="i2")
ctx.vertex_array(prog, structured_array, index_array, instance_buffer=(basic_array, "instance_input"))
```

**Comment by LeMinaw** [comment]
I'm not familliar with the internal machinery of ModernGL at all, but from a user-perspective those are all pretty good points.

However, with inferred buffer format from the NumPy array's `dtype`, I wonder how to deal with alignement/padding.

Of course one obvious way would be to add a/some `np.byte` in `dtype`, but maybe it would be interesting to have some kind of "auto-align" mecanism?

**Comment by abey79** [comment]
Good point. To be honest I'm not very familiar with these issues, but I don't think my proposal changes the situation much. **If** the dtype is good enough for the buffer format, you may now have everything inferred from it as a shortcut. For special cases, then the "old" way is still available (e.g. build your `bytes` as you like and provide a mgl format string manually). Or am I missing something?

**Comment by anentropic** [comment]
I was trying to work out how to achieve something like "Instanced Arrays" as described here https://learnopengl.com/Advanced-OpenGL/Instancing with moderngl

Should I understand from the above proposal to add an `instance_buffer` arg to `vertex_array` that this is not currently supported directly?

**Comment by einarf** [comment]
There are example under `examples/instanced_*`. It has been supported for a long time.

**Comment by anentropic** [comment]
ok thank you!

I am a noob but I can see `https://github.com/moderngl/moderngl/blob/master/examples/instanced_rendering_crates.py is supplying the x,y,z for each instance as instance data via a buffer... I think I can adapt this to my use case 👍

**Comment by szabolcsdombi** [comment]
Closing this as #561 will take care of the improved vertex_array definition.
