### ISSUE TITLE
vao transform doesn't work with TRIANGLE_FAN

### ISSUE THREAD

**Issue by louwaque** [moderngl/moderngl#441]
**Description**

VAO transform method doesn't work when the mode is set to TRIANGLE_FAN.

**Proof of code**

```py
import numpy as np
import moderngl
import struct

ctx = moderngl.create_context(standalone=True, backend='egl')
fbo = ctx.simple_framebuffer((1, 1), components=4)
fbo.use()

vertices = np.array([
    1.0,  -1.0,
    2.0,  -2.0,
    3.0,  -3.0],
    dtype='f4',
)

prog = ctx.program(vertex_shader=
"""
#version 130
attribute vec4 in_vert;
void main(void) {
    gl_Position = in_vert;
}
""",
varyings=['gl_Position'],
)

vbo = ctx.buffer(vertices)
vao = ctx.vertex_array(prog, [(vbo, '2f', 'in_vert')])
N = 3
buffer = ctx.buffer(reserve=N * 4 * 4)
vao.transform(buffer, vertices=N, mode=moderngl.TRIANGLE_FAN)

data = struct.unpack('{}f'.format(N * 4), buffer.read())
np.array(data, dtype='f4')
```

**Expected behavior**

The expected result:
```
array([ 1., -1.,  0.,  1.,  2., -2.,  0.,  1.,  3., -3.,  0.,  1.], dtype=float32)
```

The actual result:
```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)
```

**Version info**

```
moderngl 5.6.2
--------------
vendor: VMware, Inc.
renderer: llvmpipe (LLVM 9.0, 256 bits)
version: 3.3 (Core Profile) Mesa 19.2.8
python: 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:27:18) [GCC 7.3.0]
platform: linux
code: 330
```

**Comment by einarf** [comment]
Thanks a lot for reporting this. There is definitely something funky happening with primitive mode. Should be easy enough to fix and properly document.

I would encourage the use of at least version 3.3 shaders

```python
prog = ctx.program(vertex_shader=
"""
#version 330
in vec2 in_vert;
out vec2 out_vert;

void main(void) {
    out_vert = in_vert;
}
""",
varyings=['out_vert'],
)
```

Also note:
> Transform feedback explicitly captures Primitives. While it does capture data for each vertex, it does so after splitting each primitive up into separate primitives. So if you're rendering using GL_TRIANGLE_STRIP, and you render with 6 vertices, that yields 4 triangles. Transform feedback will capture 4 triangles worth of data. Since each triangle has 3 vertices, TF will capture 12 vertices, not the 6 you might expect from the drawing command.

**Comment by einarf** [comment]
Reproduced while adding some unit tests for this. Fix incoming soon.

**Comment by einarf** [comment]
Half way done with a slight transform revamp. Doing proper sanity checks when geometry shaders are present. Remaining is 
translating "Render Primitive modes" to "Feedback primitiveMode" when only vertex shader is present + complete tests.

**Comment by einarf** [comment]
Quick triangle fan transform test in local branch.
We input 4 vertices and transform will output 6 vertices being the two triangles.

```py
import numpy as np
import moderngl
import struct

ctx = moderngl.create_context(standalone=True)
vertices = np.array([
    0.0,  0.0,
    1.0,  0.0,
    1.0,  1.0,
    0.0,  1.0],
    dtype='f4',
)
prog = ctx.program(vertex_shader=
"""
#version 330

in vec2 in_vert;
out vec2 out_vert;

void main(void) {
    out_vert = in_vert;
}
""",
varyings=['out_vert'],
)

vbo = ctx.buffer(vertices)
vao = ctx.vertex_array(prog, [(vbo, '2f', 'in_vert')])
N_IN = 4
N_OUT = 6
buffer = ctx.buffer(reserve=N_OUT * 4 * 2)
vao.transform(buffer, vertices=N_IN, mode=moderngl.TRIANGLE_FAN)

data = struct.unpack(f'{N_OUT * 2}f', buffer.read())
print(data)
```

Output
```py
(
    0.0, 0.0,  # First triangle
    1.0, 0.0,
    1.0, 1.0,
    0.0, 0.0,  # Second triangle
    1.0, 1.0
    0.0, 1.0
)
```

**Comment by einarf** [comment]
Fixed in master. I can do a point release for this if needed tomorrow.

**Comment by einarf** [comment]
5.6.4 released with fix: https://github.com/moderngl/moderngl/releases/tag/5.6.4
