### ISSUE TITLE
Support sampler1D uniform type

### ISSUE THREAD

**Issue by zzggbb** [moderngl/moderngl#445]
It seems like the `sampler1D` datatype isn't supported. I think `GL_SAMPLER_1D` needs to be a case in this function:

https://github.com/moderngl/moderngl/blob/530decd0aa3435ad95b8e34af2f95b7c7993f672/moderngl/src/Uniform.cpp#L116

**Comment by einarf** [comment]
We don't even have 1D texture support : https://github.com/moderngl/moderngl/issues/436

Should probably at least add `sampler1D` in 5.7. For now you can just use a 2D texture.

**Comment by einarf** [comment]
Fixed in 9d8cb1b6955b9729063e9df6f68ec0191b5a3721
