### ISSUE TITLE
[question] Creating a cellular automata simulation without extra textures

### ISSUE THREAD

**Issue by zzggbb** [moderngl/moderngl#446]
I am using this library to make a cellular-automata simulation. In order to do this, I need to "feed" the screen back into itself, so that the shader can calculate the next state based on the current state.

I think I know how to do this with two textures:
- one that reads from itself
- the other being the default framebuffer, which just reads from the other texture

Is it possible to accomplish this with a single texture? I am thinking of something like this:

```python
program['self_referential_texture_sampler'] = 0
self_referential_texture = ctx.screen.color_attachments[0]
self_referential_texture.use(location=0)
```

However, this is not working because `ctx.screen` does not have any color attachments. 

I would appreciate any and all advice, thank you for your time!

**Comment by cprogrammer1994** [comment]
Hi,
I think the logic of the simulation should not depend on the screen
the screen should be just an output.
work with a texture then blit it into the screen. (i think we have an example for this)
never use the screen content as input it may have a special format you don't expect.
blit to the screen is very fast if you have concerns about that.

**Comment by zzggbb** [comment]
Which example shows blitting a texture to the screen?

**Comment by cprogrammer1994** [comment]
you need [`ctx.copy_framebuffer`](https://moderngl.readthedocs.io/en/latest/reference/context.html#moderngl.Context.copy_framebuffer)

**Comment by einarf** [comment]
A pretty normal setup is creating two framebuffers and ping-pong render between them. blit the current result to screen or draw it to the screen using a textured triangle strip.

```python
size = 600, 600
src = ctx.framebuffer(color_attachments=[ctx.texture(size, 4)]
dst = ctx.framebuffer(color_attachments=[ctx.texture(size, 4)]

# in draw loop - render to texture with previous result
dst.use()
src.color_attachements[0] <- use this texture as input in your shader
# Show something in the screen
ctx.screen.use()
# blit or show texture as textured triangle strip

# swap fbos for next frame
src, dst = dst, src
```

**Comment by einarf** [comment]
Will close this for now. We do have a discord server linked in README. It's a great place to ask questons.
