### ISSUE TITLE
Unused attributes/uniforms lead to unexpected errors

### ISSUE THREAD

**Issue by simeonkr** [moderngl/moderngl#459]
Consider the following minimal example, where the fragment shader ignores the input attribute v_color (to draw a white triangle instead of a colored one):
```
import os

import moderngl_window as mglw
import numpy as np

        
class Example(mglw.WindowConfig):
    gl_version = (3, 3)
    aspect_ratio = 16 / 9

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.prog = self.ctx.program(
            vertex_shader='''
                #version 330
                in vec2 pos;
                in vec3 color;
                out vec3 v_color;
                
                void main() {
                    v_color = color;
                
                    gl_Position = vec4(pos, 0.0, 1.0);
                }
            ''',
            fragment_shader='''
                #version 330
                in vec3 v_color;
                
                void main() {
                    //gl_FragColor = vec4(v_color, 1.0);
                    gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);
                }
            ''',
        )

        self.vertices = np.array([
            0.0, 1.0, 1.0, 0.0, 0.0,
            -1.0, -1.0, 0.0, 1.0, 0.0,
            1.0, -1.0, 0.0, 0.0, 1.0,
        ], dtype='f4')

        self.vbo = self.ctx.buffer(self.vertices)

        self.vao = self.ctx.vertex_array(self.prog,
            [(self.vbo, '2f 3f', 'pos', 'color')],)

    def render(self, time: float, frame_time: float):
        self.ctx.clear(1.0, 1.0, 1.0)
        self.vao.render()


if __name__ == '__main__':
    Example.run()
```

This leads to the error `moderngl.error.Error: content[0][3] must be an attribute not NoneType`. This may be due to `self.prog._members` being equal to `{'pos': <Attribute: 0>}` instead of `{'pos': <Attribute: 0>, 'color': <Attribute: 1>}`, which is the case if we replace the `gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);` with `gl_FragColor = vec4(v_color, 1.0);`.

This issue (which also affects uniforms) can be quite difficult to debug in larger code, if the user is not aware of it. If this is a limitation of modengl, then an appropriate error message should be shown. But it ultimately should not be, since programs like these are otherwise valid and can arise in many situations (especially when you want to have different fragment shaders compatible with the same moderngl code).

**Comment by einarf** [comment]
This will be improved in the upcoming 5.7 release. Better error messages on `VertexArray` creation and support for optional attributes. An attribute name can contain a `?` (prefix or suffix) and will be automatically padded when it doesn't exist in the program.

For uniforms you should just catch `KeyError` if they cannot be set.

**Comment by szabolcsdombi** [comment]
Try using `#pragma optimize(off)` it should work for uniforms but not for attributes.

**Comment by its-darsh** [comment]
I'm facing the same issue, this issue should be revised!

**Comment by szabolcsdombi** [comment]
The OpenGL specification allows the implementation to optimize out unused uniforms in shaders.

This bug has nothing to do with moderngl. The opengl implementation is provided by your graphics driver which does the optimization mentioned.

**Comment by einarf** [comment]
You can make a wrapper class for VAOs. I do that in moderngl-window to solve this problem. It creates and caches VertexArrays internally compatible with the program passed into the `render()` method.

For uniforms you can just catch `KeyError` when setting them of checking if they exist in the program some other way.
