### ISSUE TITLE
Questions on instance and passing array to vertex shader

### ISSUE THREAD

**Issue by SwaySZ** [moderngl/moderngl#460]
Hi there,

I have some questions as follows:

1. Instances vs many vbas. Is there any difference? Say, I can draw many spheres by setting instance number or each vba for a single sphere.

2. Is that possible to pass an array into the vertex shader? For example, I have an array defined like "in vec3 a[4]", and can the vba content look like "(vbo, "12f4 /i", "a")"? It does not work, however.

3. How to draw rectangles in 3D using instances? Each instance/rectangle has different vertex points (at the local coordinate system), which can't be reused by simply scaling. Without using instances, I have to duplicate color, position, etc., for each rectangle.

Thanks.

Sway

**Comment by einarf** [comment]
Figured it out? I'm wondering if we should add some more examples in docs.

**Comment by SwaySZ** [comment]
Yes. It would be grateful to add more examples in docs.
Q1: Instanced technique may have better performance after googling.
Q2: Finally, it works. I forgot to use the variable a in the shader so that a will be removed after shader compilation and prompt an error something like "content [x][x] must be an attribute not NoneType".
Q3: As a workaround, I prepared an array with zeros for vertex shader, and pass the real vertices via '12f \i' to the vertex shader. Not sure if there is a better way.

sway

**Comment by einarf** [comment]
Have you looked at some of the examples? https://github.com/moderngl/moderngl/tree/master/examples

1) instancing is definitly several orders of magnutide faster than doing separate draw calls.
2) The error messages when creating a vertex array will be improved in the next release
3) Just duplicating the data is more than fine. It doesn't sound like you need to use instancing in your case (unless I missed something). I would need to see some code.

**Comment by SwaySZ** [comment]
Thank you for the guide. 

Is it better to duplicate data at the CPU side? I don't know if the data will be duplicated automatically at the GPU side when using instancing. In my case, each rectangle will move but keeping constant shape so that I will update the positions frequently. Using instances may avoid passing vertices frequently.

**Comment by einarf** [comment]
> Each instance/rectangle has different vertex points (at the local coordinate system), which can't be reused by simply scaling

It sounds like you don't need instancing here. You just need to split up the data into separate buffers.

* One buffer for static data such as vertex positions and colors (it's fine to repeat color per vertex)
* A separate buffer for positions so you can quickly re-build this

I assume the rectangle geometry and colors are static and you only update positions. To optimize the position buffer updating you can also make the GPU calculate the new positions into the position buffer using `VertexArray.transform`. This is assuming you can calculate new positions in a vertex shader.

**Comment by einarf** [comment]
Also: We do have a discord server linked in README. This is usually a better place to get help with things like this.

**Comment by SwaySZ** [comment]
> Also: We do have a discord server linked in README. This is usually a better place to get help with things like this.

Thank you! I will take a try.
