### ISSUE TITLE
Update type annotations / hits

### ISSUE THREAD

**Issue by vmario89** [moderngl/moderngl#461]
Hey,
using latest python 3.9.1 moderngl throws the following warning:

```
C:\Users\tomate\AppData\Local\Programs\Python\Python39\lib\site-packages\moderngl\context.py:467: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.mglo.fbo.viewport = tuple(value)
```

**Comment by einarf** [comment]
Thanks. I will update type annotations: https://moderngl.readthedocs.io/en/latest/reference/framebuffer.html#moderngl.Framebuffer.viewport

Viewport should definitly be passed as integers.

**Comment by einarf** [comment]
I'll convert this into a generic "update type annotations" issue.

**Comment by einarf** [comment]
Viewport type hints are already there. If you are getting this issue you are trying to set viewport using float values.
