### ISSUE TITLE
VertexArrays without index buffers render excessively slow on macOS

### ISSUE THREAD

**Issue by tpwrules** [moderngl/moderngl#462]
**Description**

When drawing triangles with unique vertices (~73K per frame in the example), a VertexArray which does not have an index buffer renders much slower than the same VertexArray with an index buffer that simply consists of `range(len(vertices))`, i.e. is equivalent to not using an index buffer.

Activity Monitor stats on the Python process:
Fast (with index buffer) case: ~60FPS, ~9% CPU usage, ~20% GPU
Slow (without index buffer) case: ~20FPS, ~98% CPU usage, ~7% GPU

Profiling says all the time is spent in the VertexArray's `render()` function. In this function, ModernGL uses `glDrawArraysInstanced` when not using index buffers and `glDrawElementsInstanced` when using index buffers. I tried using the non-instanced versions but the behavior is the same. I would expect not using index buffers to be faster, or at least the same speed, because `glDrawArraysInstanced` does not have the indirection overhead through the index buffer and the number of processed vertices and triangles is identical to `glDrawElementsInstanced` with the described index buffer.

**Proof of code**

The following code attachment demonstrates the behavior. Set `USE_INDEX_BUFFERS` on line 4 to `True` or `False` to demonstrate the fast and slow cases, respectively.

[index_slow_bug.py.gz](https://github.com/moderngl/moderngl/files/6265747/index_slow_bug.py.gz)

**Expected behavior**

I would expect not using an index buffer to be the same speed or slightly faster, as the graphics card and driver do not have to deal with the indirection and memory accesses that save nothing. However, it seems this hits a slow path in the macOS drivers as all the extra time is spent in the CPU.

Not sure if ModernGL can do anything to fix this, but it is at least worth noting for posterity. I wonder if this is the case on other graphics cards on macOS, or other platforms. I can't test Windows on the same mac, but maybe that would behave differently too.

**Version info**

```
moderngl 5.6.4
--------------
vendor: ATI Technologies Inc.
renderer: AMD Radeon Pro 460 OpenGL Engine
version: 4.1 ATI-4.2.15
python: 3.9.2 (default, Mar 15 2021, 17:37:51) 
[Clang 12.0.0 (clang-1200.0.32.29)]
platform: darwin [macOS 11.2.3]
code: 410
```

**Comment by einarf** [comment]
Note: This was discussed on discord. It's avery interesting observation. It might just be a driver thing. Will see if I can compare with my 2013 maxbook with HD4000 and Nvidia 650M.

**Comment by szabolcsdombi** [comment]
I have tested the example above on windows with an integrated graphics card.

just for safety i have checked the number of vertices renderd, it was the same (221184) with or without the index buffer.

to be sure, i even replaced the vertices in the vao render call.

visually all the tested cases were perfectly smooth and looked identical. it can be a driver issue on your side.

```py
print(self.cube.vertices)
self.cube.render(vertices=221184)
```

**Comment by einarf** [comment]
Closing this for now. I'm pretty sure this is simply due to mac drivers. Sadly OpenGL on mac is deteriorating over time. I know some things like transforms have been moved to the CPU in some instances. The performance is still OK, but not properly acellerated.
