### ISSUE TITLE
Trouble with copy_framebuffer(), and possibly rendering to framebuffers

### ISSUE THREAD

**Issue by rjbudzynski** [moderngl/moderngl#464]
**Description**

Blitting a framebuffer to the screen leads to unexpected results.
Also it seems that a fbo's viewport is initially set to an unusual value.

**Proof of code**

```py
#! /usr/bin/python3

import moderngl_window as mglw
import moderngl as gl
import numpy as np
TWOPI = 2 * np.pi


class Test(mglw.WindowConfig):
    gl_version = 3, 3
    window_size = 512, 512
    N = 36

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Initialize stuff here

        self.program = self.ctx.program(vertex_shader=vshader,
                                        fragment_shader=fshader)
        self.program['N'] = self.N
        self.vao = self.ctx.vertex_array(self.program, [])

        # framebuffer setup
        self.texture = self.ctx.texture(self.window_size, 4)
        self.fbo = self.ctx.framebuffer(color_attachments=(self.texture, ))
        #

        self.ctx.enable(gl.BLEND)
        self.ctx.point_size = 32

    def render(self, time, frametime):

        self.ctx.clear()
        self.ctx.viewport = (0, 0) + self.window_size
        # self.fbo.viewport = self.ctx.viewport
        # draw stuff here
        self.fbo.use()
        # self.fbo.clear()
        self.vao.render(gl.POINTS, self.N)
        self.ctx.copy_framebuffer(self.ctx.screen, self.fbo)


vshader = """#version 330
#define TWOPI radians(360.)
uniform float N;

void main(){
    float r = .8;
    float phi = TWOPI * float(gl_VertexID) / N;
    vec2 position = vec2(cos(phi), sin(phi));
    gl_Position = vec4(r * position, 0. , 1.);
}
"""

fshader = """#version 330
out vec4 frag_color;

void main() {
    float r = 2. * distance(gl_PointCoord, vec2(.5, .5));
    float alpha = step(-1., -r);
    float brightness = .1 + smoothstep(-1., -.2, -r);
    frag_color = vec4(vec3(1., 1., 0.) * brightness, alpha);
}
"""

Test.run()



```

**Expected behavior**
I would expect to see the same picture as is rendered when drawing directly to screen, ie. with lines 37 (`self.fbo.use()`) and 40 commented out.

**Version info**
moderngl 5.6.4
--------------
vendor: Intel Open Source Technology Center
renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
version: 4.5 (Core Profile) Mesa 20.2.6
python: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
platform: linux
code: 450

```



```

**Comment by einarf** [comment]
That is a bit weird. Think one of the culpits are https://github.com/moderngl/moderngl-window/blob/d554063faef23078225fc2e7e5ef7d79e692bd75/moderngl_window/__init__.py#L216-L219

I don't know if it's a good idea to bind the window framebuffer before calling `render()` in the first place. Seems the texture get rendered to with a different viewport in this situation OR the first frame have a different viewport/scissor.

**Comment by einarf** [comment]
This is definitely related to framebuffer binding in `WindowConfig` and viewport changing after first frame. This is issue is platform specific as well.

**Comment by einarf** [comment]
We figure out on discord. A couple of bugs was fixed in moderngl-window and the other part was related to Qt.
