### ISSUE TITLE
Rendering with empty framebuffers

### ISSUE THREAD

**Issue by 0x23** [moderngl/moderngl#467]
In opengl there is the possibility to render with framebuffers that have no images attached. The following is a cite from [https://www.khronos.org/opengl/wiki/Framebuffer_Object](https://www.khronos.org/opengl/wiki/Framebuffer_Object) that describes the usecase quite well:

> It is possible to render to a framebuffer object that has no attachments. Obviously none of the fragment shader outputs will be written to anywhere in this case, but rendering can otherwise proceed as normal. This is useful for using arbitrary reading and writing of image data from shaders, rather than writing to a bound framebuffer.

In this case we would need a framebuffer creation method in moderngl that justs takes the necessary (four) framebufer parameter but no color/depth atachments:

Internally those can be parameter can be set using `void glFramebufferParameteri(GLenum target​, GLenum pname​, GLint param​);`
wich supports:
 - GL_FRAMEBUFFER_DEFAULT_WIDTH
 - GL_FRAMEBUFFER_DEFAULT_HEIGHT
 - GL_FRAMEBUFFER_DEFAULT_LAYERS 
 - GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS 

**SUMMARY:**
a new function: `create_empty_framebuffer(width, height, layers=0, fixed_sample_locations=0)` that uses `glFramebufferParameteri` internally to set the given parameter and creates a framebuffer object without attachments.

**Comment by einarf** [comment]
> This is useful for using arbitrary reading and writing of image data from shaders, rather than writing to a bound framebuffer.

Do you have more specific example? This looks easy enough. I just want to have one clear usecase with very specific details that can be used as a unit test.

**Comment by 0x23** [comment]
My use case is to write each rendered fragment (not only the closest one) to a shader storage buffer to implement order independent transparency. As all data is soterd in this shader storage buffer (wich i can index arbitrarily) i dont need the actual framebuffer.
In my case I deal with quite large images (20-50Mpixel) so the momory savings of an empty framebuffer would be very welcome.
I am not shure if this is a good usecase for a unit test though.

The simplest example I can think of is to count the total number of rendered fragments in a scene by using atomicAdd in the fragment shader to increment a single global counter - no framebuffer needed.

**Comment by einarf** [comment]
ah right. so you just want the output in a shader storage buffer 👍 

You could also mix in pyopengl for this meanwhile. If you do, please be free to share snippets

**Comment by 0x23** [comment]
I am not eager to add another opengl dependency to my project (seems redundant) and I am quite happy with moderngl and its features :) So for the meantime I will live with the extra memory cost...

**Comment by mabl** [comment]
I ran into this feature request with the exact usecase :-) Any improvement in this area would be welcome.

**Comment by szabolcsdombi** [comment]
this will be resolved after the refactor. most of the long stalled issues are kept in mind while making the changes.

An example or tutorial link would help a lot understanding this requirement.
