### ISSUE TITLE
Python39 manylinux wheels are missing

### ISSUE THREAD

**Issue by FrankFirsching** [moderngl/moderngl#468]
**Description**

Similarly to issue [#17 of glcontext](https://github.com/moderngl/glcontext/issues/17), moderngl lacks the manylinux wheels on pypi
https://pypi.org/project/moderngl/#files

**Proof of code**

Please refer to the files listsing of pypi:
https://pypi.org/project/moderngl/#files

**Expected behavior**

pip install moderngl
shall not need to compile the module on Linux using python-3.9

Thanks in advance for looking into this.

**Comment by einarf** [comment]
Ah right. Will definitely fix this soon. Thanks for making an issue!

**Comment by encukou** [comment]
It would be nice to have wheels for 3.10 as well, now that the ABI of Python 3.10 is finalized.
See: https://www.python.org/downloads/release/python-3100rc2/

**Comment by einarf** [comment]
Yep. Working on it

**Comment by encukou** [comment]
Can I help with this?

I'm using the [PyWeek](https://pyweek.org/) game jam as an excuse to learn moderngl, and I really like it so far :)
Unfortunately, if there are no official wheels, I'll need to compile and distribute unofficial ones. I can do that, but I'd rather spend that time contributing, if possible.

**Comment by szabolcsdombi** [comment]
Hi,
Please try the newly uploaded binaries.
I have uploaded the 3.10 rc 2 binaries for x64 (manylinux_* and windows) for both moderngl and glcontext

Have a great PyWeek!

**Comment by encukou** [comment]
Thank you very much!
If it's not too much to ask: the *manylinux wheel for 3.9 is still missing. (Other platforms do have 3.9 wheels.)

**Comment by szabolcsdombi** [comment]
I did see 3.9 manylinux entries among the files on PyPI. I checked them as the original title was about those. can you pint me out exactly which one is missing?

**Comment by encukou** [comment]
A `cp39-manylinux` one.

There are manylinux wheels for other Python versions:
* 3.8: `moderngl-5.6.4-cp38-cp38-manylinux1_x86_64.whl`
* 3.10: `moderngl-5.6.4-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_27_x86_64.whl` for example

And there are `cp39` wheels for other platforms:
* macOS: `moderngl-5.6.4-cp39-cp39-macosx_10_9_x86_64.whl`
* win32: `moderngl-5.6.4-cp39-cp39-win32.whl`
* win64: `moderngl-5.6.4-cp39-cp39-win_amd64.whl`

But a Linux one for Python 3.9 is missing.

**Comment by einarf** [comment]
I'm setting up new workflows for this now using cibuildwheel. That should generate most manylinux versions. I will have to set that up in the moderngl-5.6.4 branch first and see if we can push a 5.6.5 with python 3.10 and more linux wheels.

I suspect glcontext need the same treatment.

**Comment by einarf** [comment]
Testing in 5.6.4 branch now : https://github.com/moderngl/moderngl/blob/moderngl-5.6.4/.github/workflows/publish.yml

**Comment by einarf** [comment]
First test publish: https://github.com/moderngl/moderngl/actions/runs/1272520888

**Comment by einarf** [comment]
These are the wheels produced (minus py3.10)

win
```
  moderngl-5.6.4-cp36-cp36m-win32.whl
  moderngl-5.6.4-cp36-cp36m-win_amd64.whl
  moderngl-5.6.4-cp37-cp37m-win32.whl
  moderngl-5.6.4-cp37-cp37m-win_amd64.whl
  moderngl-5.6.4-cp38-cp38-win32.whl
  moderngl-5.6.4-cp38-cp38-win_amd64.whl
  moderngl-5.6.4-cp39-cp39-win32.whl
  moderngl-5.6.4-cp39-cp39-win_amd64.whl
```

mac
```
  moderngl-5.6.4-cp36-cp36m-macosx_10_9_x86_64.whl
  moderngl-5.6.4-cp37-cp37m-macosx_10_9_x86_64.whl
  moderngl-5.6.4-cp38-cp38-macosx_10_9_x86_64.whl
  moderngl-5.6.4-cp39-cp39-macosx_10_9_x86_64.whl
```

manylinux
```
  moderngl-5.6.4-cp36-cp36m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  moderngl-5.6.4-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  moderngl-5.6.4-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  moderngl-5.6.4-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  moderngl-5.6.4-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  moderngl-5.6.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  moderngl-5.6.4-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.manylinux_2_12_i686.manylinux2010_i686.whl
  moderngl-5.6.4-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  moderngl-5.6.4-cp36-cp36m-manylinux_2_24_i686.whl
  moderngl-5.6.4-cp36-cp36m-manylinux_2_24_x86_64.whl
  moderngl-5.6.4-cp37-cp37m-manylinux_2_24_i686.whl
  moderngl-5.6.4-cp37-cp37m-manylinux_2_24_x86_64.whl
  moderngl-5.6.4-cp38-cp38-manylinux_2_24_i686.whl
  moderngl-5.6.4-cp38-cp38-manylinux_2_24_x86_64.whl
  moderngl-5.6.4-cp39-cp39-manylinux_2_24_i686.whl
  moderngl-5.6.4-cp39-cp39-manylinux_2_24_x86_64.whl
```

**Comment by einarf** [comment]
.. and these should in theory work on apple silicon according to cibuildwheels
```
  moderngl-5.6.4-cp38-cp38-macosx_10_9_universal2.whl
  moderngl-5.6.4-cp38-cp38-macosx_10_9_x86_64.whl
  moderngl-5.6.4-cp39-cp39-macosx_10_9_universal2.whl
  moderngl-5.6.4-cp39-cp39-macosx_10_9_x86_64.whl
```

**Comment by lordmauve** [comment]
What is left to do to get these on PyPI? Do you need additional testing or are the wheels tested by cibuildwheel?

**Comment by einarf** [comment]
@lordmauve Promise we'll get this sorted asap zulu. I know pyweek is very soon.

**Comment by einarf** [comment]
There should be binaries on PyPI now
