### ISSUE TITLE
Add support for Mirrored Texture Repeat

### ISSUE THREAD

**Issue by fbvims** [moderngl/moderngl#470]
**Support Mirrored Texture Repeat**

Please add support for GL_MIRRORED_REPEAT.

This is very useful in the context of image processing.

Without support for Mirrored Texture Repeated, we must either :

* Do funny arithmetic in the shader
* Hack calls to TexParameteri with third party libraries

**Texture repeat interface feels incomplete**

I really like the strong typing in the library.
The clean way to fix this is an Enum I guess.
But I wouldn't mind something like:

    texture.repeat = 0x8370

or even :

    texture.repeat = (0x8370, 0x8370)

Best Regards,

**Version info**

moderngl 5.6.4

**Comment by einarf** [comment]
I agree. There should at least be a property to set that raw filter values.

**Comment by szabolcsdombi** [comment]
there will be a new property `wrap_x`. the `repeat_x` will simply change the `wrap_x` and will be deprecated in moderngl 6.x.x,
this change is backward compatible but needs to be discussed a bit more.
