### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [moderngl/moderngl#472]
Problem
---------
On aarch64, ‘pip install moderngl’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPi.

Resolution
-----------
On aarch64, ‘pip install moderngl’ should download the wheels from PyPi

@einarf, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by einarf** [comment]
We'll move to github actions instead of travis and can probably include it there. We can keep this one open until then.

**Comment by einarf** [comment]
There should be binaries on PyPI now
