### ISSUE TITLE
Additional texture formats

### ISSUE THREAD

**Issue by tpwrules** [moderngl/moderngl#475]
**A simple use-case of the new feature**

I am working on an application which uses 16 bit integer scientific imagery. Unfortunately, there is not a texture format in moderngl which specifies normalized 16 bit unsigned integers. There is `f1` which specifies normalized 8 bit unsigned integers.

**Describe the solution you'd like**

I was able to define my own `MGLDataType` as `{float_base_format, {0, GL_R16, GL_RG16, GL_RGB16, GL_RGBA16}, GL_UNSIGNED_SHORT, 2}` but it is annoying to keep around a fork. I called it `n2`. It would be nice to add this to moderngl, or some other way of specifying the equivalent, plus normalized 8 or 16 bit signed integers. OpenGL does not support 32 bit normalization.

**Comment by einarf** [comment]
ah right. We should definitely add normalized integer support. There is a branch that started on that already. `n1`, `n2` and `n4` is exactly the `dtype` they used.

**Comment by szabolcsdombi** [comment]
it would be great to have `n1`  `n2`  `n4`
 
in one of the prototypes I had `i2!` for normalized signed 16bit integer and `u2!` for normalize unsigned 16bit integer.
I found it too cryptic back then, but I am open to it now.

also `nu2` and `ni2` looks ok too.

**Comment by einarf** [comment]
As long as we document them here we're good! : https://moderngl.readthedocs.io/en/latest/topics/texture_formats.html

I think both of those notations works.

**Comment by einarf** [comment]
Looks like `GL_RGBA32` is not a thing. They don't allow it because to allow it would mean either discarding 8 bits of that extra precision in the conversion to single-precision floats, or converting those 32-bit normalized integers to double-precision floats.

`nu1`, `nu2`, `ni1` and `nu2` however are easy to add.

**Comment by einarf** [comment]
Fixed.
