### ISSUE TITLE
Tkinter Framebuffer is slow

### ISSUE THREAD

**Issue by fekga** [moderngl/moderngl#476]
I followed the example called `window_tkinter` and using the `FramebufferImage` with all the frame buffer reading and pasting it in the Image makes my application slow in rendering time. Is there any alternative to this? 

I saw that in the moderngl-window github there is something called pyopengltk.OpenGLFrame but I don't know how to replace it.

**Comment by einarf** [comment]
The tkinter example simpy reads the framebuffer into an image in tkinter. It's not really mean for per-frame changes if you want performance. You can run moderngl with tkinter if you use moderngl-window and use the tb window backend. The simplest way to do this is just passing the `--window tk` parameter when running it. It doesn't really support mixing tkinter gui out of the box and it doesn't work on MacOS (pyopengltk limitation)
