### ISSUE TITLE
Can't create context on Apple Silicon

### ISSUE THREAD

**Issue by jesi-rgb** [moderngl/moderngl#478]
Hello there! I am using Manimgl to render some animations, and that package depends on moderngl.

As it is natural, moderngl is installed, though some devs pointed out in #472 that this installation process is not ideal.

The software simply does not work. Lemme specify my situation.

## System specs
- Mac Mini M1 16GB RAM 512GB
- macOS Big Sur 11.6
- Python 3.9

## Problem
moderngl does not work for some reason (sorry I cannot be more specific, I am not professional at this)

## Expected output
Moderngl shoud be able to create a context and thus everything should run fine

## Steps to reproduce
1. Install manimgl
1. Moderngl gets installed automatically
1. Run manimgl to render a basic scene
1. Moderngl crashes and stops

## Expected behaviour
Moderngl should run normally and thus manimgl should work as usual

# Error traceback
Here I leave an error traceback in case it is useful:

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/manimgl", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "/Users/jesi/manim/manimlib/__main__.py", line 14, in main
    scenes = manimlib.extract_scene.main(config)
  File "/Users/jesi/manim/manimlib/extract_scene.py", line 115, in main
    scenes = get_scenes_to_render(all_scene_classes, scene_config, config)
  File "/Users/jesi/manim/manimlib/extract_scene.py", line 76, in get_scenes_to_render
    scene = scene_class(**scene_config)
  File "/Users/jesi/manim/manimlib/scene/scene.py", line 46, in __init__
    self.window = Window(scene=self, **self.window_config)
  File "/Users/jesi/manim/manimlib/window.py", line 18, in __init__
    super().__init__(size=size)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moderngl_window/context/pyglet/window.py", line 78, in __init__
    self.init_mgl_context()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moderngl_window/context/base/window.py", line 165, in init_mgl_context
    self._ctx = moderngl.create_context(require=self.gl_version_code)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moderngl/context.py", line 1616, in create_context
    import moderngl.mgl as mgl
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moderngl/mgl.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moderngl/mgl.cpython-39-darwin.so: mach-o, but wrong architecture
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/moderngl/mgl.cpython-39-darwin.so: mach-o, but wrong architecture
```

As I can see looking through the traceback, the problem lies when importing the moderngl library itself when creating a context, but an image cannot be found. 

Hopefully I specified all the needed information. Please let me know if I missed something.

Any help is much appreciated. Thanks beforehand for your time.

**Comment by einarf** [comment]
I guess we need to buld wheels for that as well. I'm revamping the whole build setup currently. I thought the M1 was compatible, but I guess not.. I know very little about it right now. If you have any more input, be free to share.

**Comment by einarf** [comment]
I think these are the right wheels (setting up now build workflows now)
```
  moderngl-5.6.4-cp38-cp38-macosx_10_9_universal2.whl
  moderngl-5.6.4-cp38-cp38-macosx_10_9_x86_64.whl
  moderngl-5.6.4-cp39-cp39-macosx_10_9_universal2.whl
  moderngl-5.6.4-cp39-cp39-macosx_10_9_x86_64.whl
```

**Comment by jesi-rgb** [comment]
Does that mean that installing via pip will use those wheels or do I have to specify it myself? If so, how would I use them?

**Comment by einarf** [comment]
They should be selected automatically as far as I know. Anything else would be madness 😄 

Meanwihle you can build moderngl locally from source. That's not too hard on mac.

**Comment by einarf** [comment]
There should be binaries on PyPI now
