### ISSUE TITLE
Removing the intermediate Python layer

### ISSUE THREAD

**Issue by szabolcsdombi** [moderngl/moderngl#485]
ModernGL is implemented in C++.
However, to get linting working in the early days of vscode. We decided to use a python wrapper over the ModernGL core.
This allowed us to get rid of some C++ code that did pessimistic parsing of the user-provided parameters.

If backward compatibility is not an issue the following project layout would be preferred:

- the ModernGL core should be imported directly in Python.
- a PYI file should be used to provide type hints. this allows superior type-hinting over the auto-detected counterparts. especially for available string literals.
- helpers provided by the python wrapper should be moved to `_moderngl` and be imported from the moderngl core.

**Comment by einarf** [comment]
There are still some things that could be practical to have in python that isn't time critical? For example error formatters when shaders don't compile or link? https://github.com/moderngl/moderngl/pull/248#issuecomment-427742478
