### ISSUE TITLE
Inconsistent errors with float viewport and drawing issue with the master branch

### ISSUE THREAD

**Issue by abey79** [moderngl/moderngl#496]
**Description**

As discussed on Discord, here is my findings while transitioning [my project](https://github.com/abey79/vpype) to Python 3.10. My code would originally set the viewport with `float` values 

|  | Python 3.9 | Python 3.10 |
| --- | --- | --- |
| mgl 5.6.4 | works both with `float` and `int` | works with `int`, generate a `SystemError` with `float`  |
| mgl 7dfb1606e7d6a78b31f6ff1df7e65af953d92a14 | no error but nothing is drawn (both `int` and `float` | `moderngl.error.Error` with `float`, no error but nothing drawn with `int`  |

All of the above on M1 mac, fully updated, MacPort's Python installs.

**Proof of code**

Original code (without casting to `int`):
```py
    def initializeGL(self):
        self._ctx = mgl.create_context()
        logging.info(f"Context info: {self._ctx.info}")

        self._ctx.viewport = (0, 0, self._factor * self.width(), self._factor * self.height())
        self._screen = self._ctx.detect_framebuffer()

        self.engine.post_init(
            self._ctx, int(self._factor * self.width()), int(self._factor * self.height())
        )
        self.on_screen_changed(self.screen())
        self.engine.document = self._document
        self.engine.fit_to_viewport()
```

`SystemError`:
![image](https://user-images.githubusercontent.com/49431240/159744907-d3288218-c0e8-4fa1-959d-0ec586349231.png)

`moderngl.error.Error`:
![image](https://user-images.githubusercontent.com/49431240/159744941-dffb5c4e-f34c-4df0-b785-7d01e1e38683.png)

**Version info**

```
python -m moderngl
moderngl 5.6.4
--------------
vendor: Apple
renderer: Apple M1 Max
version: 4.1 Metal - 76.3
python: 3.10.3 (main, Mar 17 2022, 15:53:29) [Clang 13.0.0 (clang-1300.0.29.30)]
platform: darwin
code: 410
```

and

```
moderngl 5.7.0
--------------
vendor: Apple
renderer: Apple M1 Max
version: 4.1 Metal - 76.3
python: 3.9.11 (main, Mar 17 2022, 21:09:29) 
[Clang 13.0.0 (clang-1300.0.29.30)]
platform: darwin
code: 410
```

Running with PySide2 5.15.2.1.

**Comment by einarf** [comment]
No longer converts to int in 3.10
https://docs.python.org/3.10/c-api/long.html#c.PyLong_AsLong

that's only part of the problem here I think.

**Comment by einarf** [comment]
@abey79 discovered this example doesn't render anything in moderngl-window
``
python uniform_block.py --window pyside2
```
This is a good start.

**Comment by szabolcsdombi** [comment]
mgl https://github.com/moderngl/moderngl/commit/7dfb1606e7d6a78b31f6ff1df7e65af953d92a14 adds a small framebuffer when there is not default framebuffer. it is done in `create_context()`

once `detect_framebuffer()` is called the same framebuffer is returned, and this may be why there is nothing drawn. (the content is drawn to the small framebuffer) 

try to call `detect_framebuffer(0)` to see if anything gets drawn with ints.

also [fix-floats-passed-in-place-of-ints](https://github.com/moderngl/moderngl/tree/fix-floats-passed-in-place-of-ints) should solve the issue with floats.

it needs a bit more testing before merge.

**Comment by szabolcsdombi** [comment]
original issue seems to be solved, closing..
