### ISSUE TITLE
Bind fragment shader output location 

### ISSUE THREAD

**Issue by mCodingLLC** [moderngl/moderngl#497]
Vertex arrays currently support binding attribute locations for vertex shader *inputs*, as in

```python3
vao = ctx.vertex_array(program, buffer, "in_position", "in_normal")
```

This allows you flexibility in how your vertex data is stored and allows you to specify your variables by name.
Under the hood this corresponds to the [glBindAttribLocation](https://docs.gl/gl4/glBindAttribLocation) call.

However, there does not seem to be the equivalent in moderngl for fragment shader *outputs*.  I would like the same flexibility to specify outputs by feature name rather than have shaders have to know about the indices.

I would like to be able to say something like
```python3
output_locations = {"out_color": 0, "object_id": 1, "some_other_out": 4}
vao = ctx.vertex_array(program, buffer, "in_position", "in_normal", output_locations=output_locations)
# or alternatively
vao.bind_output_location("out_color", 0)
...
```
or potentially something similar on the `program` object.

```python3
output_locations = {"out_color": 0, "object_id": 1, "some_other_out": 4}
prog = ctx.program(vertex_shader=..., fragment_shader=...,  output_locations=output_locations)
# or alternatively
prog.bind_output_location("out_color", 1)
...
```

 This would allow shaders to not have to care about locations and only worry about what feature outputs they support.
Also note, gl supports this with the [glBindFragDataLocation](https://docs.gl/gl4/glBindFragDataLocation) call.

**Version info**

```
moderngl 5.6.4
--------------
vendor: VMware, Inc.
renderer: SVGA3D; build: RELEASE;  LLVM;
version: 4.1 (Core Profile) Mesa 21.0.3
python: 3.9.5 (default, Nov 18 2021, 16:00:48) 
[GCC 10.3.0]
platform: linux
code: 410
```

**Comment by einarf** [comment]
Need to look into this more, but for now you need to use layout qualifiers.

```glsl
layout(location=0) out vec4 layer_0;
layout(location=1) out vec4 layer_1;
```
The locations should always match your framebuffer attachement order.

**Comment by mCodingLLC** [comment]
Thanks for looking into this!

Yes this explicit `layout(location=0)` etc. is what I'm trying to avoid (though it is usually superior). If you are familiar with [magnum graphics](https://magnum.graphics/) they implement this on the program object rather than the vertex array, though the functionality is [deprecated](https://doc.magnum.graphics/magnum/classMagnum_1_1GL_1_1AbstractShaderProgram.html#GL-AbstractShaderProgram-attribute-location) in favor of explicit layouts. In Python though I may be able to save a buffer if none of my shaders use a certain output. Say I have some shaders supporting different subsets of {color, object id, stress, temperature}. If I'm running a certain subset of shaders that only use color and temperature, it would be nice to be able to just bind color to location 0 and temperature to location 1 instead of dynamically rewriting the shader sources or allocating unused buffers to fill the unused slots.

**Comment by einarf** [comment]
This could at least be possible assuming the name of the outs are specified during program creation. It's a varying like outs in vertex and geo shaders, but needs a different category.
```py
program["layer_0"] = 1
program["layer_0"] = 0
```
Then this information could possibly be used in `Scope` objects.

**Comment by szabolcsdombi** [comment]
setting the binding similar to uniforms would be the best way.

> Bindings may be specified at any time after program has been created

I can add the necessary code for it.

**Comment by szabolcsdombi** [comment]
to get it working we are missing functionality to list the output names.

- to write we can use [glBindFragDataLocation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindFragDataLocation.xhtml)
- to read we can use [glGetFragDataLocation](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetFragDataLocation.xhtml)
- to list we cannot use [glGetProgram](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetProgram.xhtml)

if there is no way to list them it cannot be in the program[...] subscript. it must be elsewhere.

**Comment by einarf** [comment]
They are varyings and must be specified on program creation, but they would need to be separate from the `varyings`.  I for example parse out varyings from the glsl source itself and pass them to the program on creation.

**Comment by mCodingLLC** [comment]
I would be fine explicitly specifying `fragment_data_out` or something like that in the program definition like `varyings`. I would also be fine not specifying it and just depending on the user to only try to assign out variable locations for variables that exist. Probably better to just have the user specify on construction though.

**Comment by einarf** [comment]
Specifying on program creation fits the moderngl better. Other libraries can parse the `out`s looking a the glsl source. We do a simple form of that in the program loader in moderngl-window.

**Comment by szabolcsdombi** [comment]
there is a [PR](https://github.com/moderngl/moderngl/pull/500) for this.
can you check if it is sufficient?

**Comment by einarf** [comment]
This makes sense because frag data locations have the same limitations as vertex/geo shader outputs. It must happen before the program is linked. Providing setters for those runtime is a huge can of worms. One could however argue that `Program._members` should at least contains some (readonly) member with the name and location info (when `fragment_outputs` is specified)

**Comment by einarf** [comment]
Sould be in master branch now
