### ISSUE TITLE
Invalid dtype for normalized integer textures

### ISSUE THREAD

**Issue by pohlt** [moderngl/moderngl#504]
I would like to use a texture containing normalized integers as described [here](https://moderngl.readthedocs.io/en/latest/topics/texture_formats.html?highlight=r8ui#id1).

```python
a = 6553*np.arange(9, dtype=np.uint16)
self.texture = self.ctx.texture((3, 3), 1, a.data, dtype="nu2")
```
However, I get a `moderngl.error.Error: invalid dtype`.

`dtype="u2"` works as expected, but such textures do not support linear interpolation which I need.
Normalized integer textures would support linear interpolation, right?

Thanks for your help.

> 2022-05-12 06:10:10,171 - moderngl_window.context.base.window - INFO - ModernGL: 5.6.4
> 2022-05-12 06:10:10,172 - moderngl_window.context.base.window - INFO - vendor: Intel
> 2022-05-12 06:10:10,172 - moderngl_window.context.base.window - INFO - renderer: Mesa Intel(R) Xe Graphics (TGL GT2)
> 2022-05-12 06:10:10,172 - moderngl_window.context.base.window - INFO - version: 4.6 (Core Profile) Mesa 21.3.8
> 2022-05-12 06:10:10,172 - moderngl_window.context.base.window - INFO - python: 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
> 2022-05-12 06:10:10,172 - moderngl_window.context.base.window - INFO - platform: linux
> 2022-05-12 06:10:10,172 - moderngl_window.context.base.window - INFO - code: 460

**Comment by einarf** [comment]
You need to compile up master branch for 5.7 right now. We'll release 5.7 binaries soon

**Comment by pohlt** [comment]
Works as expected with 5.7. Thanks a lot for the quick response!

Answering my own question: Textures based on normalized integers _do support_ linear interpolation (in contrast to non-normalized integers)! 🥳
