### ISSUE TITLE
Add glDispatchComputeIndirect

### ISSUE THREAD

**Issue by Rafale25** [moderngl/moderngl#505]
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDispatchComputeIndirect.xhtml

example prototype:
`ComputeShader.run_indirect(buffer, offset=0)`

**Comment by einarf** [comment]
That one is super easy to add. `omputeShader.run_indirect(buffer, offset=0)`.

**Comment by einarf** [comment]
For now you can use pyopengl for this combined with moderngl
