### ISSUE TITLE
Crash on Python 3.10

### ISSUE THREAD

**Issue by naveen521kk** [moderngl/moderngl#517]
**Description**

The below code crashes when run on `Python 3.10.8` on WSL. Not sure what actually is the issue here, but it's a minimal reproducer of the issue at https://github.com/ManimCommunity/manim/pull/2994.

Backtrace from gdb: https://gist.github.com/naveen521kk/d0069116cdb203866a5d036287b7f1cf

**Proof of code**

```py
import moderngl
ctx = moderngl.create_context(standalone=True, backend="egl")
a = ctx.info
import readline
```

**Expected behavior**

The code should run without `Segmentation Fault`.

**Version info**

```
moderngl 5.6.4
--------------
vendor: Microsoft Corporation
renderer: D3D12 (Intel(R) Iris(R) Xe Graphics)
version: 3.3 (Core Profile) Mesa 21.2.6
python: 3.10.8 (main, Oct 15 2022, 23:23:03) [GCC 9.4.0]
platform: linux
code: 330
```

**Comment by einarf** [comment]
I can also reproduce this in WSL using 3.10.8. The segmentation fault is happening on readline import and seems to be related to the `ctx.info` structure. Do we have some stack corruption going on here due to changes in python 3.10?

**Comment by einarf** [comment]
Could just be related to this : https://github.com/moderngl/moderngl/issues/496

A good idea to go through the code first looking at the 3.10 changelog.

**Comment by einarf** [comment]
This also happen on Ubuntu, so it's not a WSL-specific thing. No segfault in python 3.9.

**Comment by einarf** [comment]
5.7.1 is now on PyPI
