### ISSUE TITLE
Error when assigning values to an array uniform (regression in 5.7.1)

### ISSUE THREAD

**Issue by abey79** [moderngl/moderngl#525]
**Description**

A regression appears to have been introduced in 5.7.1 (still here in 5.7.2) related to uniform arrays.

Error traceback:

```
Traceback (most recent call last):
  File "/Users/hhip/src/vpype/vpype_viewer/qtviewer/viewer.py", line 161, in paintGL
    self.engine.render()
  File "/Users/hhip/src/vpype/vpype_viewer/engine.py", line 435, in render
    self._rulers_painter.render(self, proj)
  File "/Users/hhip/src/vpype/vpype_viewer/_painters.py", line 442, in render
    self._ticks_prog["divisions"] = spec.divisions
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/hhip/Library/Caches/pypoetry/virtualenvs/vpype-l5n3HO8W-py3.11/lib/python3.11/site-packages/moderngl/program.py", line 114, in __setitem__
    self._members[key].value = value
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hhip/Library/Caches/pypoetry/virtualenvs/vpype-l5n3HO8W-py3.11/lib/python3.11/site-packages/_moderngl.py", line 344, in value
    data = b''.join(struct.pack(self._fmt, *row) for row in value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hhip/Library/Caches/pypoetry/virtualenvs/vpype-l5n3HO8W-py3.11/lib/python3.11/site-packages/_moderngl.py", line 344, in <genexpr>
    data = b''.join(struct.pack(self._fmt, *row) for row in value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Value after * must be an iterable, not int
```

The breaking code has been introduced in #522

Here is an "impression" of the code involved:

```python
self._ticks_prog = load_program("ruler_ticks", ctx)
self._ticks_prog["color"] = (0.2, 0.2, 0.2, 1.0)
self._ticks_prog["scale"] = spec.scale_px * engine.scale
self._ticks_prog["divisions"] = list(spec.divisions)   # this fails, spec.divisions is a 3-tuple of int
self._ticks_prog["delta_number"] = spec.scale
```

The actually breaking line in my code is [here](https://github.com/abey79/vpype/blob/73468c7594b9d61c8506d8d4c9ba18e12e24fca1/vpype_viewer/_painters.py#L442).

[This](https://github.com/abey79/vpype/blob/master/vpype_viewer/shaders/ruler_ticks_geometry.glsl) is the relevant shader.

In particular, `division` is defined as follows:
```glsl
uniform int divisions[3];
```
It's the only array like this in my GL code.

This is the code which appears to break:

![image](https://user-images.githubusercontent.com/49431240/201470102-099871dd-f226-414a-8bbc-0423535425c9.png)

This line is strange, it expends the *content* of `value`, instead of `value` itself. In this context is feels wrong (chances are high that I'm missing something though).

FWIW, here is what the same code looked like in 5.7.0:

![image](https://user-images.githubusercontent.com/49431240/201470139-9b838444-faa1-4372-b2aa-9179bc1414b5.png)

**Version info**

```
moderngl 5.7.2
--------------
vendor: Apple
renderer: Apple M1 Max
version: 4.1 Metal - 76.3
python: 3.11.0 (main, Oct 25 2022, 16:26:04) [Clang 13.0.0 (clang-1300.0.29.30)]
platform: darwin
code: 410
```

**Comment by szabolcsdombi** [comment]
Hi thank you for the report.

There is a missing branch here:

https://github.com/moderngl/moderngl/blob/8cdd0227dcd6e3b7b1ae35139414c507dada1154/_moderngl.py#L331-L339

**Comment by abey79** [comment]
This is the getter right? My issue is in the setter.

**Comment by szabolcsdombi** [comment]
Yes you are right. I was very short on time, there should be a setter equivalent of the above. Both of them miss a branch.

**Comment by einarf** [comment]
We should try to get this covered in unit tests. I guess we're not covering arrays properly.

**Comment by szabolcsdombi** [comment]
Here is a hotfix: https://github.com/moderngl/moderngl/commit/4b9c9cf9dfae37bcf82b496120369e0ed2424301

To test it you can install from master directly with:

```
pip install -U https://github.com/moderngl/moderngl/archive/refs/heads/master.zip
```

I will be able to take a second look and invest more time next week.

**Comment by abey79** [comment]
Great! I'll test this tomorrow first thing.

**Comment by abey79** [comment]
This works on my side, thanks 👍🏻

**Comment by abey79** [comment]
Is it yet known when the fix will be released?

**Comment by szabolcsdombi** [comment]
it should be available on pypi soon
https://github.com/moderngl/moderngl/releases/tag/5.7.3

**Comment by abey79** [comment]
Great thanks! 🎉
