### ISSUE TITLE
Using pyOpenGL with moderngl pointed to a non-default libgl

### ISSUE THREAD

**Issue by mabl** [moderngl/moderngl#527]
I am currently trying to get a test-runner for continuous integration to run. The Windows-based runner does not have a GPU, so I am trying to use mesa llvmpipe. Creating a context works fine, using `GLCONTEXT_WIN_LIBGL` and `GALLIUM_DRIVER=llvmpipe` pointed to a binary built from https://github.com/pal1000/mesa-dist-win. Unfortunately, my application has a few `pyOpenGL` calls, among them is the use of the `GL_ARB_shading_language_include` extension. While this extension is present in the context exposed via `moderngl` it is not available from `pyOpenGL`:

```python
from pprint import pprint

import moderngl


import OpenGL.GL as GL
import OpenGL.GL.ARB.shader_draw_parameters
import OpenGL.GL.ARB.shading_language_include


def main():
    ctx = moderngl.create_context(standalone=True, require=430)
    print(f"Using the following GL context:")
    print(f"\tvendor: {ctx.info['GL_VENDOR']}")
    print(f"\trenderer: {ctx.info['GL_RENDERER']}")
    print(f"\tversion: {ctx.info['GL_VERSION']}")
    print(f"\tcode: {ctx.version_code}")

    assert 'GL_ARB_shading_language_include' in ctx.extensions
    assert OpenGL.GL.ARB.shading_language_include.glInitShadingLanguageIncludeARB()



if __name__ == '__main__':
    main()
```

Returning the following result:

```
Using the following GL context:
	vendor: Mesa/X.org
	renderer: llvmpipe (LLVM 15.0.5, 256 bits)
	version: 4.5 (Core Profile) Mesa 22.2.4 (git-a21e3efe21)
	code: 450
Traceback (most recent call last):
  File "C:\Users\IEUser\PycharmProjects\tryout_opengl\main.py", line 25, in <module>
    main()
  File "C:\Users\IEUser\PycharmProjects\tryout_opengl\main.py", line 20, in main
    assert OpenGL.GL.ARB.shading_language_include.glInitShadingLanguageIncludeARB()
AssertionError
```

Is there an obvious way to point `pyOpenGL` to using the same DLL as the `moderngl` context, or to call these functions manually? I think that the internal `glcontext` `load` function would help - but it seems that one is hidden behind a compiled context object in `moderngl`.

**Comment by szabolcsdombi** [comment]
at the moment the `glcontext` `load` returns the function pointer as a python int, which in fact is only good for the moderngl core.
you should be able to use ctypes to make a C function from that value and call it similarly as the moderngl core does.
If my time allows i make an example with one of the gl functions.

**Comment by mabl** [comment]
Thanks, that is what I gathered. It is a bit unfortunate, that the `glcontext` context is not accessible from `moderngl`. So I guess one would need to create a new "dll" context using `glcontext` and then get the function pointers. I think that in theory this mechanism could be plugged into an `pyOpenGL` platform plugin, see https://github.com/mcfletch/pyopengl/blob/master/OpenGL/platform/__init__.py#L1. 

Would it be possible to add a `MGLContext_get_ctx` function to `moderngl` that will return `context->ctx`, such that the `glcontext` context becomes accessible from python?

**Comment by szabolcsdombi** [comment]
```py
import ctypes

import glcontext
import pyglet

pyglet.options['shadow_window'] = False
pyglet.options['debug_gl'] = False


class PygletWindow(pyglet.window.Window):
    def __init__(self, width, height):
        self.alive = True
        config = pyglet.gl.Config(major_version=3, minor_version=3, forward_compatible=True, double_buffer=True)
        super().__init__(width=width, height=height, config=config, vsync=True)

    def on_resize(self, width, height):
        pass

    def on_draw(self):
        pass

    def on_close(self):
        self.alive = False

    def update(self):
        self.flip()
        self.dispatch_events()
        return self.alive


wnd = PygletWindow(1280, 720)

backend = glcontext.default_backend()
ctx = backend()

glClearColorPtr = ctx.load('glClearColor')
glClearPtr = ctx.load('glClear')

assert glClearColorPtr
assert glClearPtr

glClearColor = ctypes.cast(glClearColorPtr, ctypes.CFUNCTYPE(None, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float))
glClear = ctypes.cast(glClearPtr, ctypes.CFUNCTYPE(None, ctypes.c_uint32))

while wnd.update():
    GL_COLOR_BUFFER_BIT = 0x00004000
    glClearColor(0.2, 1.0, 0.2, 1.0)
    glClear(GL_COLOR_BUFFER_BIT)
```

**Comment by szabolcsdombi** [comment]
> Would it be possible to add a MGLContext_get_ctx function to moderngl that will return context->ctx, such that the glcontext context becomes accessible from python?

yes

---

right now a very dirty workaround would be to:

```py

backend = glcontext.default_backend()
ctx = backend()

glcontext.default_backend = lambda: lambda glversion, mode: ctx

moderngl_ctx = moderngl.create_context()  # context->ctx will be the context created above
```

**Comment by szabolcsdombi** [comment]
please reopen this issue if needed
