### ISSUE TITLE
 cannot create context on centos 7.6.1810(core)

### ISSUE THREAD

**Issue by zhao-yiqun** [moderngl/moderngl#529]
**Description**
Hi, I use pip to install moderngl 5.7.3 on centos 7.6.1810(core), with python 3.8.6

However, after I installed it. and use the sample usage I got the erro as followings:

>>> import moderngl
>>> ctx = moderngl.create_standalone_context()
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/zhaoyq/anaconda3/envs/atiss/lib/python3.8/site-packages/moderngl/context.py", line 2020, in create_standalone_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/public/home/zhaoyq/anaconda3/envs/atiss/lib/python3.8/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) cannot create context

The openGL version I use is 

OpenGL version string: 1.4 (4.6.0 - Build 27.20.100.9749)

How can I solved this bugs?

Thanks  in advance.

**Version info**

```
moderngl 5.7.3


```

**Comment by einarf** [comment]
This is with `LIBGL_DEBUG=verbose`?

There's some info here as well : https://github.com/openai/gym/issues/509

**Comment by zhao-yiqun** [comment]
Hi,

With LIBGL_DEBUG=verbose. the output results is as followings:

```
LIBGL_DEBUG=verbose python -m moderngl
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/moderngl/__main__.py", line 44, in <module>        
    main()
  File "/usr/local/lib/python3.8/dist-packages/moderngl/__main__.py", line 27, in main
    ctx = moderngl.create_standalone_context()
  File "/usr/local/lib/python3.8/dist-packages/moderngl/context.py", line 2022, in create_standalo
ne_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)     
  File "/usr/local/lib/python3.8/dist-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) cannot create context
```
Unfortunately, I need work on Slurm, Therefore, I need the use of singularity for apt install. This is the log in my singularity container for ubuntu. I will appreciate if you can give me more hints or reference.

**Comment by zhao-yiqun** [comment]
Following the link you provided here [gym](https://github.com/openai/gym/issues/509). I run the command it mentioned.

```
LIBGL_DEBUG=verbose glxgears
```

I can successfully output the results 

![image](https://user-images.githubusercontent.com/91787021/207837204-c42eba84-e584-4104-a095-8405ddbb54ab.png)

but still with the LibGL errors, 
the logs is here:

```
libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
54503 frames in 9.2 seconds = 5927.263 FPS
17921 frames in 9.7 seconds = 1847.774 FPS
17925 frames in 8.5 seconds = 2110.685 FPS
17145 frames in 9.1 seconds = 1880.866 FPS
15847 frames in 8.8 seconds = 1800.107 FPS
17405 frames in 8.8 seconds = 1976.646 FPS
```

Sorry for that, but I don't know why moderngl may occur this error. Could you please give more hints or reference?

Regards.

**Comment by szabolcsdombi** [comment]
I guess the gears run on OpenGL 1.1 or 2.0.

> "OpenGL version string: 1.4 (4.6.0 - Build 27.20.100.9749)"

Try `glxinfo | grep [Vv]ersion`

Loading OpenGL is actually a responsibility of glcontext. You can try to get it working first.

```
import glcontext
backend = glcontext.default_backend(mode='standalone')
ctx = backend()
```

if you render to  window then:

```
import glcontext
window = ...
backend = glcontext.default_backend()
ctx = backend()
```

**Comment by zhao-yiqun** [comment]
Hi @szabolcsdombi , I try the command 
glxinfo | grep version

and got the results 

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 1.4 (4.6.0 - Build 27.20.100.9749)
```

Also, the glcontext didn‘t work, here is the logs, How should I make it work?

```
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import glcontext
>>> backend = glcontext.default_backend()
>>> ctx = backend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/zhaoyq/anaconda3/envs/atiss/lib/python3.8/site-packages/glcontext/__init__.py
", line 90, in create
    return x11.create_context(**kwargs)
Exception: (detect) glXGetCurrentContext: cannot detect OpenGL context
```

Regards.

**Comment by szabolcsdombi** [comment]
my bad,

```py
import glcontext
backend = glcontext.default_backend()
ctx = backend(mode='standalone')
print(ctx)
print(ctx.load('glBegin'))
print(ctx.load('glGenSamplers'))
```

**Comment by szabolcsdombi** [comment]
This looks related to your problem: https://community.khronos.org/t/opengl-version-is-forced-to-1-4-but-card-can-support-4-6-0/104868

**Comment by zhao-yiqun** [comment]
> my bad,
> 
> ```python
> import glcontext
> backend = glcontext.default_backend()
> ctx = backend(mode='standalone')
> print(ctx)
> print(ctx.load('glBegin'))
> print(ctx.load('glGenSamplers'))
> ```

I use this updated. Errors still :

```
>>> import glcontext
>>> backend = glcontext.default_backend()
>>> ctx = backend(mode='standalone')
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/zhaoyq/anaconda3/envs/atiss/lib/python3.8/site-packages/glcontext/__init__.py
", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) cannot create context
```

I am tring to see the link you provided for the misconfigured drivers.

Thanks.

**Comment by zhao-yiqun** [comment]
Thanks for your reply and instructions, with an updated correct OpenGL version, the issue can be addressed.
