### ISSUE TITLE
Add SPIR-V shader support

### ISSUE THREAD

**Issue by XEN486** [moderngl/moderngl#531]
**A simple use-case of the new feature**

Using SPIR-V, you may be able to use other languages then glsl, eg. HLSL. It should only be enabled if you have OpenGL 4.6 or higher. SPIR-V is also cross-api, meaning you can write a shader once and use it for all sorts of APIs (eg one can have moderngl support with other apis).

**Describe the solution you'd like**

Add SPIR-V shader support with preferably a similar way to load them. (eg. instead of ctx.program you could have ctx.spirv_program).

**Version info**

```
moderngl 5.7.3
--------------
vendor: Intel
renderer: Intel(R) UHD Graphics 600
version: 3.3.0 - Build 27.20.100.8681
python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
platform: win32
code: 330
```

**Comment by szabolcsdombi** [comment]
https://www.khronos.org/opengl/wiki/SPIR-V#Example

**Comment by szabolcsdombi** [comment]
Hi, passing bytes in the place of the string source code of the shader uses shader binary loading if appropiate.
If the source code is encoded as bytes it still works as expected.
This will be part of the next release.
