### ISSUE TITLE
list of program inputs and outputs

### ISSUE THREAD

**Issue by dibenedetto** [moderngl/moderngl#539]
i need to have some sort of list of (name, type) tuples for both inputs and outputs of a program (e.g., uniforms*, buffers, ...), being it from the graphics or the compute pipeline, such that i can setup some programming interface to expose them to a developer.

usually i did this using pure opengl functions (e.g., glGetActiveUniform, glGetActiveAttrib, glGetFragDataLocation, ...) to have reflection on programs and build up the interface.

i really like moderngl implementation, and i'd like to do the same without breaking its whole interface.
but, afaik, i didn't see such kind on information on modengl programs, neither a way/hack to call pure opengl functions to bend the interface towards my needs.

can you please instruct me if there is an existing way of doing this (e.g., "just use this method", or obtaining the native opengl context and doing it by hands, or ...) ?

as of now, i am working on compute shaders, but soon i'll probably need this for graphics (vert/frag) ones.

thank you so much,
m.

**Comment by einarf** [comment]
You can obtain all the members from the program like this

https://moderngl.readthedocs.io/en/latest/reference/program.html#moderngl.Program.__iter__
```py
members = [m for m in program]
```

Then each member contains introspected data from program creation.
https://moderngl.readthedocs.io/en/latest/reference/uniform.html

For buffers you have full control of this. The same for fragdata locations.

**Comment by einarf** [comment]
If you want to do hacky things with pyopengl directly it should detect the active context in most cases. Import and just start using it.

**Comment by dibenedetto** [comment]
> ```python
> members = [m for m in program]
> ```

I've tried this, but since I had only buffers as in/out variables, i didn't see anything. But now I can confirm i see uniforms listed. In this case, just spotted out that I can actually get the type of that uniform only by scavenging in object private members (e.g., _fmt) : is this correct?

> For buffers you have full control of this. The same for fragdata locations and varyings.

Can you please give me an example on how to list buffers?

Thank you above all.
M.

**Comment by einarf** [comment]
The program itself is not aware of any buffers. It's the vertex array that sets up the attribute bindings.

```py
# Interlaved positions and velocities
vbo1 = ctx.buffer(...)
# Colors
vbo2 = ctx.buffer(...)

vao = ctx.vertex_array(
    program,
    [
        (vbo1, '2f 2f', 'in_pos', 'in_vel'),
        (vbo2, '4f', 'in_col'),
    ],
)
```

**Comment by dibenedetto** [comment]
> The program itself is not aware of any buffers. It's the vertex array that sets up the attribute bindings.
> 
> ```python
> # Interlaved positions and velocities
> vbo1 = ctx.buffer(...)
> # Colors
> vbo2 = ctx.buffer(...)
> 
> vao = ctx.vertex_array(
>     program,
>     [
>         (vbo1, '2f 2f', 'in_pos', 'in_vel'),
>         (vbo2, '4f', 'in_col'),
>     ],
> )
> ```
> 
> Just like in plain OpenGL the vertex array hold the buffer bindings for a program. The program is passed in on creation for additional sanity checking.

actually i intended shader storage buffer objects for compute shaders, not for vertex shader inputs.
my first attempt was to run the very first compute shader example in the moderngl/examples folder (
[https://github.com/moderngl/moderngl/blob/master/examples/compute_shader.py](here)).

in that case, is there a way to obtain information from the program?

**Comment by einarf** [comment]
You can ontain the `binding` from the `UniformBlock` in the program at least. You create the buffers so you would know the binding points of your buffers : https://moderngl.readthedocs.io/en/latest/reference/buffer.html#moderngl.Buffer.bind_to_storage_buffer

**Comment by dibenedetto** [comment]
finally found a working mode by hacking with pyopengl:

```python
from moderngl_window.context.headless import Window as Mglwh
import OpenGL.GL as gl

source = '''
	#version 430

	layout(local_size_x=1, local_size_y=1, local_size_z=1) in;

	layout (std430, binding = 3) readonly buffer in0
	{
		vec4 inBuffer[];
	};

	layout (std430, binding = 2) writeonly buffer out0
	{
		vec4 outBuffer[];
	};

	void main(void)
	{
		uint index = gl_GlobalInvocationID.x;
		outBuffer[index] = inBuffer[index] * 2.0;
	}
'''

ctx = Mglwh().ctx

compute_shader = ctx.compute_shader(source)

resCount = gl.glGetProgramInterfaceiv(compute_shader.glo, gl.GL_SHADER_STORAGE_BLOCK, gl.GL_ACTIVE_RESOURCES)
nameLen  = gl.glGetProgramInterfaceiv(compute_shader.glo, gl.GL_SHADER_STORAGE_BLOCK, gl.GL_MAX_NAME_LENGTH )

for i in range(resCount):
	info = gl.glGetProgramResourceName(compute_shader.glo, gl.GL_SHADER_STORAGE_BLOCK, i, nameLen)
	name = info[1][:info[0]].tobytes().decode('ascii')

	info = gl.glGetProgramResourceiv(compute_shader.glo, gl.GL_SHADER_STORAGE_BLOCK, i, 1, [gl.GL_BUFFER_BINDING], 1)
	bind = info[1]

	print(name, bind)
```

thanks anyway.

**Comment by einarf** [comment]
Actually I see that we don't introspect SSBOs. I do that in my own project so got confused. I would have asked more specific questions here since it wasn't immediately clear what you wanted here.

Issue: https://github.com/moderngl/moderngl/issues/540
