### ISSUE TITLE
Independent buffer for fragment shader

### ISSUE THREAD

**Issue by danchitnis** [moderngl/moderngl#546]
First, I wanted to thank you for developing and maintaining this amazing library, especially since coding OpenGL in python is very confusing. I am working and expanding on the example that you have provided [here](https://moderngl.readthedocs.io/en/latest/the_guide/rendering.html)

However, I am very confused about why we cannot create independent fragment shader buffers like in classic OpenGL? in ModernGL it seems that we can only create a vertex buffer and pass the colour data via a proxy variable to the fragment shader

```python
prog = ctx.program(
    vertex_shader='''
        #version 330

        in vec2 in_vert;
        in vec3 in_color;

        out vec3 v_color;

        void main() {
            v_color = in_color;
            gl_Position = vec4(in_vert, 0.0, 1.0);
        }
    ''',
    fragment_shader='''
        #version 330

        in vec3 v_color;

        out vec3 f_color;

        void main() {
            f_color = v_color;
        }
    ''',
)
```

In this case, every `position`  has a separate `color` data. In some cases, this is unnecessary, and groups of `position` data can have the same color. This severely bloats the memory and slows computing in these cases because we cannot directly bind the buffer to the fragment shader. Hence in your example, you have the following:

```python
x = np.linspace(-1.0, 1.0, 50)
y = np.random.rand(50) - 0.5
r = np.ones(50)
g = np.zeros(50)
b = np.zeros(50)
```

The arrays `r, g, b` are redundant if everything has the same color!

Is there a technical reason why binding to the fragment shader hasn't been implemented? There is no technical difference in classic OpenGL between binding to vertex or fragment shaders, so I don't see any barrier to implementing it.

**Comment by einarf** [comment]
Are you talking about shader storage buffers here? If not, some more details are probably needed?

**Comment by danchitnis** [comment]
maybe I got the terminology wrong. The code could be something like this:

```python

prog = ctx.program(
    vertex_shader='''
        #version 330
        
        uniform vec4 transform
        attribute vec2 in_vert;

        void main() {
            vec2 coordinate = transform * invert
            gl_Position = vec4(coordinate, 0.0, 1.0);
        }
    ''',
    fragment_shader='''
        #version 330

        uniform vec3 v_color;

        void main() {
            gl_FragColor = vec4(v_color, 1);
        }
    ''',
)

x = np.linspace(-1.0, 1.0, 50)
y = np.random.rand(50) - 0.5

vertices = np.dstack([x, y])

vbo = ctx.buffer(vertices.astype('f4').tobytes())
vao = ctx.simple_vertex_array(prog, vbo, 'in_vert')

transform = np.array([1, 0.0, 0.0, 1.0])
ctx.setUniform(prog, transfrom)

color = np.array([0.5, 0,5, 0.5]) ## for gray color
ctx.setUniform(prog, color)


prog.render(moderngl.LINE_STRP)
```

The pesudo opengl code for the above python code would be:

```cpp
fragCode = gl.createShader(gl.FRAGMENT_SHADER);
gl.shaderSource(fragment_shader, fragCode);
gl.compileShader(fragment_shader);
prog = gl.createProgram();
gl.attachShader(prog, vertex_shader);
gl.attachShader(prog, fragment_shader);
gl.linkProgram(prog);
gl.useProgram(prog)
```

```cpp
vbuf = gl.createBuffer()
gl.bindBuffer(gl.ARRAY_BUFFER, vbuf);


in_vec  = gl.getAttribLocation(prog, "in_vec");
gl.vertexAttribPointer(in_vec, 2, gl.FLOAT, false, 0, 0);
gl.enableVertexAttribArray(in_vec);

transform = gl.getUniformLocation(prog, 'transform');
gl.programUniform2fv(transform, np.array([1.0,  0.0, 0.0, 1.0]))


v_color = gl.getUniformLocation(prog, 'v_color');
gl.programUniform2fv(v_color, np.array([0.5, 0.5, 0.5, 1]))

gl.bufferData(gl.ARRAY_BUFFER, [...vertex_data...], gl.STATIC_DRAW)
gl.drawArrays(gl.LINE_STRIP, 0, number_of_points)

```

I transcribe the code above from my javascript experiments, and I am happy to make an example if that helps. I am using `uniform` for the variables which are not point data and are not updated with every point. (e.g. like linear transform constants, etc)

**Comment by einarf** [comment]
As far as I can read that code you are talking about setting uniforms. Did you have any problems achieving this?
```py
prog = ctx.program(
    vertex_shader='''
        #version 330
        
        uniform vec4 transform
        in vec2 in_vert;

        void main() {
            vec2 coordinate = transform * invert
            gl_Position = vec4(coordinate, 0.0, 1.0);
        }
    ''',
    fragment_shader='''
        #version 330

        uniform vec3 v_color;
        out vec4 fragColor;

        void main() {
            fragColor = vec4(v_color, 1);
        }
    ''',
)

# Make vertex data and vao
....
vbo = ctx.buffer(vertices.astype('f4'))
vao = ctx.simple_vertex_array(prog, vbo, 'in_vert')
# Set uniforms
prog["transform"] = 1, 0.0, 0.0, 1.0  # Optionally .write(data)
prog["v_color"] = 0.5, 0,5, 0.5

prog.render(moderngl.LINE_STRP)
```

**Comment by einarf** [comment]
But you are right that the old style uniforms is kind of a buffer under the hood. It's a shared buffer for the program of at  that can contain uniform data.

**Comment by einarf** [comment]
And yes. We introspect pretty much everything related to the program. Uniforms are global for the program itself. They can be created in an shader stage or even exist in multiple ones.

**Comment by danchitnis** [comment]
Many thanks. Again great library. Further examples in the documents would help better.
