### ISSUE TITLE
Bindless Textures

### ISSUE THREAD

**Issue by sivansh11** [moderngl/moderngl#550]
**A simple use-case of the new feature**

Opengl Bindless texture extension would be nice to have. Would need to add a way to query if this particular extension is available in current hardware. 

**Describe the solution you'd like**

Texture class will get a function to make the texture resilient and will return the handle.

**Version info**

```
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
version: 3.3.0 NVIDIA 520.61.05
python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
platform: linux
code: 330
```

I can go into more detail of how this would be implemented, do let me know if its required

**Comment by szabolcsdombi** [comment]
I am interesed in having bindless textures working with moderngl.

https://www.khronos.org/opengl/wiki/Bindless_Texture

To get a clear view of what we need first let us have an example with moderngl + pyopengl mixed.
A simple one would do.

I am not yet sure but what we need is just:

- get_handle() for Texture objects
- program['MyTextureHandle'].value = ... (this one could definitely use the DSA variant)

To have proper support maybe we want to support the array version.
Maybe we do not need the get_handle to support specifiv layers or mipmap levels. (? - only if code remains simple)
Maybe we want to support passing a sampler to the get_handle().

**Comment by sivansh11** [comment]
from my understanding for bindless textures you only need to get the texture handle.
Getting the handle causes the texture states to be immutable 
so
I propose not enabling bindless by default and require the user to first call a make_texture_bindless()
then get_handle()
calling make_texture_bindless would cause all the state setter properties to be overwritten to some function throwing a custom exception (example BindlessTextureStateChangeException)

Also the texture can be made resilient which I have no idea about, the ogl docs dont have much info on this, if I were to guess, making a bindless texture resilient just makes the reads (also writes ?) faster
so make_texture_resilent() (and also make_texture_non_resilient())

I have never used a texture array ever for any of my projects so I wont be able to make the best call on it

also I have mostly been using c++ and have not tried pyopengl as from my knowledge it is only supporting opengl 3.3 ?
What do you want in the example ? if you can clarify a bit I can probably just create a small demo program show casing it :)

Also is there any community discord server I can join for following the development of this project?

**Comment by sivansh11** [comment]
Hey, I made a mistake, the texture needs to be resilient to be bindless, not doing so will cause undefined behaviour (which in my case just worked, but may not work on other GPUs, drivers)

**Comment by szabolcsdombi** [comment]
https://github.com/moderngl/moderngl/blob/6075f74fca130878fbf4426f9a970659df5344ee/examples/bindless_textures.py

**Comment by szabolcsdombi** [comment]
> I propose not enabling bindless by default and require the user to first call a make_texture_bindless()
then get_handle()

calling `get_handle` is explicit enough to have its consequences. Docs will re-state the side-effects, using disposable texture content like in orphaning (calling glTexImage2D for the same texture) is not supported in moderngl anyways.

> would cause all the state setter properties to be overwritten to some function throwing a custom exception (example BindlessTextureStateChangeException)

I do not yet understand why we need it, i first must see this is really needed. It may be so, in that case we can drop the idea to support samplers as there is no use having non mutable samplers set for a texture.

> Also the texture can be made resilient which I have no idea about, the ogl docs dont have much info on this, if I were to guess, making a bindless texture resilient just makes the reads (also writes ?) faster
so make_texture_resilent() (and also make_texture_non_resilient())

Without binding the texture in my example above I get a black cube, without setting the residency I get a black screen. I now see it having this call within the get_handle would make it more robust. it is a must have as you stated.

> I have never used a texture array ever for any of my projects so I wont be able to make the best call on it

I meant `uniform sampler2D MyIndexableTextures[80];` - these are very handy.

> Also is there any community discord server I can join for following the development of this project?

yes there is a Discord server in the readme.

**Comment by sivansh11** [comment]
```
Without binding the texture in my example above I get a black cube, without setting the residency I get a black screen.```
Yeah, I was wrong, I sent a correction message later on, not doing so is undefined behaviour, it may or may not be automatically resident depending on the GPU/driver.

The correct process is 
1) get the handle, 
2) make the texture resident.
3) use in shaders 

But we shouldnt mix get_handle with make_resident as from my research, older GPUs have a limited amount of vram and may require a explicit loading and unloading.

https://stackoverflow.com/questions/22588726/use-case-for-resident-textures

**Comment by szabolcsdombi** [comment]
To avoid users getting black screens as described above `Texture.get_handle()` makes the texture resident.
For users with extra care for this setting it is possible to call with:

```py
# init time
handle = mytexture.get_handle(resident=False)

# before render using my_texture
my_other_texture.get_handle(resident=False)
my_texture.get_handle(resident=True)
# before render using my_other_texture
my_other_texture.get_handle(resident=True)
my_texture.get_handle(resident=False)
...
```

Tis is mostly not needed, the default arguments should work well. this is why only `get_handle` implements the logic for make resident.
