### ISSUE TITLE
Examples about use Image Texture.

### ISSUE THREAD

**Issue by chenerg** [moderngl/moderngl#551]
I'm confused about moderngl_window.load_texture_2d function. I want to use ctx.texture to load texture from image and render. Would you please share one example?

I have coded something like this'

```
img = Image.open("path to image“).convert("RGB")
texture = ctx.texture(img.size(), 3, img.tobytes())
texture.use()

vao.render()
```

but the result is not right.

**Comment by einarf** [comment]
This is very vague and may involve several issue. Can you share a minimal runnable example of what you are doing?

**Comment by chenerg** [comment]
Sorry for the vague question, and the real problem should be how to use index buffer for triangle's vertex position and vertex texture. In many examples, "vx vy vz" is associated with "tx ty" by one-to-one. But for obj files the same vertex may have different texture positions for different triangles, which means the number of vts is not the same as that of verts. Is there anyway to specify texture index for different triangle index?

**Comment by einarf** [comment]
This is very off topic for moderngl github issues. Seek out help in communities related to graphics programming. moderngl also have a discord server linked in the readme.

Just to nudge you in the right direction:
* The `v` (vertex) entries are all the unique vertex positions in the object
* The `n` (normal) entries are all the unique normals in the object
* The `vt` (texcoord) entreis are all the unique texture coordiantes in the object

You need to use the `p` (polygon) data to build a buffer the the data it points to. It will probably repeat the same data a few times, but that's fine. There don't need to be an index buffer invovled here.

You can of course try to use an index buffer to save space, but that only works for even unique `v n vt`.

moderngl-window also have examples loading obj : https://github.com/moderngl/moderngl-window/tree/master/examples
