### ISSUE TITLE
Using with imgui and pygame

### ISSUE THREAD

**Issue by ProfAndreaPollini** [moderngl/moderngl#553]
Hi all,
 I'm a teacher and I'm using pygame along with modengl in some animations. I want to include imgui in order to have a nice looking ui for my demos. I see pygame + imgui integration, moderngl + imgui integration and I use myself moderngl along with pygame. How can I use pygame, moderngl and imgui all together?

**Comment by szabolcsdombi** [comment]
Hi,
Please provide a link to a **pygame + imgui** example and I initialize the moderng code in it.

**Comment by einarf** [comment]
I think moderngl-window might be references here. I believe you can run imgui example of of the box with the pygame2 window backend.
