### ISSUE TITLE
some wrong signatures in moderngl and contextgl binary modules

### ISSUE THREAD

**Issue by pmp-p** [moderngl/moderngl#556]
while porting to wasm i've already encountered some of them like shown here https://github.com/moderngl/moderngl/pull/555

why does it work but in fact does not ?
https://blog.pyodide.org/posts/function-pointer-cast-handling/

https://docs.python.org/3/c-api/structures.html#METH_NOARGS

**Comment by szabolcsdombi** [comment]
thank you for reporting this, added some notes on the PR
