### ISSUE TITLE
Implement Framebuffer.clear_attachment() using glClearBuffer*

### ISSUE THREAD

**Issue by chenerg** [moderngl/moderngl#557]
If I create a framebuffer using `Context.framebuffer` with two attachments, how can I clear them respectively? When I use `self.ctx.clear(r, g, b)`, both attachments are refreshed with the same rgb value.

**Comment by einarf** [comment]
I think you can set an array of color masks on the frambuffer to block clearing. Give that a try. If that works I will update the docstring.

**Comment by einarf** [comment]
Another way would be attaching the texture you want to clear on some dummy framebuffer and clear that instead. framebuffers can share attachments. This is of course a bit more hacky than what originally suggested.

**Comment by szabolcsdombi** [comment]
Actually we should implement it using `glClearBuffer*`

if it is not possible in a backward compatible way with the clear method, then Framebuffers should have a `clear_attachment` method.

**Comment by szabolcsdombi** [comment]
for now use color_mask or create dedicated framebuffers with a single attachment for clearing.
