### ISSUE TITLE
Render to a specific mipmap level

### ISSUE THREAD

**Issue by AlexRoss-WHS** [moderngl/moderngl#570]
Hi, I was wondering if it is possible to render to a specific level of a mipmap texture? As far as I can see there is no way of specifying the level when attaching the texture to a framebuffer. I am very new to opengl but there seems to be a way of doing this with glFramebufferTexture2D in regular opengl.

**Comment by szabolcsdombi** [comment]
Hi, ModernGL cannot render at the moment to a specific layer or level. This is part of the upcomming features that were not possible to make in a backward compatible way.

I am not sure if there is another issue here with a workaround, but you can do the following to have moderngl for the rest of your code: create a framebuffer with PyOpenGL you can take the mytexture.glo (it is the opengl texture object) and use fbo = ctx.detect_framebuffer(...) to make a moderngl framebuffer from the one created with pyopengl.

**Comment by AlexRoss-WHS** [comment]
Thanks @szabolcsdombi for the quick answer and the suggestion! Do you already know when the new version will be released?

**Comment by AlexRoss-WHS** [comment]
> Well we tried for moderngl 6 like five times: https://github.com/moderngl/moderngl-prototypes/branches 

That link doesn't work for me.

**Comment by szabolcsdombi** [comment]
Indeed it was private by mistake

**Comment by AlexRoss-WHS** [comment]
> I am not sure if there is another issue here with a workaround, but you can do the following to have moderngl for the rest of your code: create a framebuffer with PyOpenGL you can take the mytexture.glo (it is the opengl texture object) and use fbo = ctx.detect_framebuffer(...) to make a moderngl framebuffer from the one created with pyopengl.

This works very well, thanks @szabolcsdombi. I have not encountered any issues with this so far. Here is how I implemented it for anyone coming across this:
```python
import moderngl
from OpenGL.GL import *

def get_mipmap_framebuffer(ctx, textures, level):
    attachement_points = [GL_COLOR_ATTACHMENT0, GL_COLOR_ATTACHMENT1, GL_COLOR_ATTACHMENT2, GL_COLOR_ATTACHMENT3,
                          GL_COLOR_ATTACHMENT4, GL_COLOR_ATTACHMENT5, GL_COLOR_ATTACHMENT6, GL_COLOR_ATTACHMENT7,
                          GL_COLOR_ATTACHMENT8, GL_COLOR_ATTACHMENT9]
    fbo = GLuint()
    glGenFramebuffers(1, fbo)
    glBindFramebuffer(GL_FRAMEBUFFER, fbo)
    width, height = textures[0].size
    for i, texture in enumerate(textures):
        glFramebufferTexture2D(GL_FRAMEBUFFER, attachement_points[i], GL_TEXTURE_2D,
                               texture.glo, level)

    mgl_fbo = ctx.detect_framebuffer(fbo.value)
    mgl_fbo.viewport = (0, 0, width // (2 ** level), height // (2 ** level))
    return mgl_fbo
```
