### ISSUE TITLE
Query uniform block members / layout / format

### ISSUE THREAD

**Issue by mCodingLLC** [moderngl/moderngl#572]
Just as we can query what members a Program has, it would be nice if we could query the members (and their properties) of a UniformBlock.

This would be useful e.g. to make struct types like we would do in C++ that match the type represented in the UniformBlock and can be written in a single write call. Currently we could do this manually by using knowledge of how OpenGL lays out data (e.g. std140), but querying member information would make it easy (easier?) to let users automatically generate these struct types (e.g. the Matrices dataclass below) instead of manually doing it or requiring users to know about layouts. This also makes it easier to automatically keep Python struct types in sync with definitions in the GLSL.

```glsl
#version 330 core
layout (location = 0) in vec3 aPos;

layout (std140) uniform Matrices
{
    mat4 projection;
    mat4 view;
};

uniform mat4 model;

void main()
{
    gl_Position = projection * view * model * vec4(aPos, 1.0);
}  
```

```python
vert_src = ...
frag_src = ...
program = ctx.program(vertex_shader=vert_src, fragment_shader=frag_src)
matrices_block = program["Matrices"]
matrices_buffer = ctx.buffer(reserve=matrices_block.size)

# Currently manual process to create this type
@dataclass
class Matrices:
    projection: np.ndarray
    view: np.ndarray
    _fmt: str = "16f 16f"

    def pack(self) -> bytes:
        # pack according to fmt, similar to Uniform.value setter
        return ...

# Alternative that queries block properties to automatically make the type
Matrices = my_lib.create_uniform_buffer_struct_type(matrices_block)

matrices = Matrices(...)
matrices_buffer.write(matrices.pack())
```

This can be achieved at the C++ level similarly to this post https://stackoverflow.com/questions/71506455/get-names-of-uniforms-in-uniform-block using `glGetProgramResourceiv` and `glGetProgramResourceName` although it does require OpenGL 4 or OpenGL ES 3 and I'm not sure if there are more compatible OpenGL 3 ways to achieve this. At worst we could just skip the functionality if the OpenGL version doesn't support it.

**Describe the solution you'd like**

The UniformBlock type is augmented with a `_members` dict just like Program that stores name -> UniformBlockMember (new type). The UniformBlockMember would contain information similar to what a Uniform stores like type, fmt, location, array_len, elem size, dimension, name, and some additional info specific to uniform blocks like byte offset within block and whether the member is active. However, UniformBlockMembers are not readable/writable like Uniforms are.

**Version info**

```
moderngl 5.7.2
--------------
vendor: VMware, Inc.
renderer: SVGA3D; build: RELEASE;  LLVM;
version: 4.1 (Core Profile) Mesa 22.2.5
python: 3.8.15 (default, Oct 14 2022, 12:10:07) 
[GCC 11.2.0]
platform: linux
code: 410
```

What would be your thoughts on this idea?

**Comment by mCodingLLC** [comment]
Update: The data I'm interested in can be retrieved in OpenGL 3 using `glGetProgramiv(program_glo, gl.GL_ACTIVE_UNIFORMS)` `glGetUniformLocation`, `glGetActiveUniformName`, and `glGetActiveUniformsiv`. For reference, the docs for these functions and explanation for what attributes can be retrieved by `glGetActiveUniformsiv` can be found here: https://www.khronos.org/opengl/wiki/Program_Introspection

**Comment by mabl** [comment]
I just came across this issue, having to create arays of nested structures passed to a compute shader - and it was super painful. Having the proposed ability to generate the structure definitions on the fly, would have saved me a lot of pain.

**Comment by szabolcsdombi** [comment]
This will be implemented as a standalone module. It will most likely use the program interface query (seems to be available all the time but actually it is part of OpenGL 4.3+)

I have some local code for it. I just realized I did not push anything yet to https://github.com/szabolcsdombi/ubo

**Comment by mabl** [comment]
> I have some local code for it. I just realized I did not push anything yet to https://github.com/szabolcsdombi/ubo

I just came across this issue again. Could you kindly consider pushing your prototype code? Thay would be a real help in getting such complicated ctype definitions right.

**Comment by szabolcsdombi** [comment]
Here is a minimum working code for getting all the information needed to construct the layout:

```py

import ctypes
from OpenGL import GL
program = zengl.inspect(pipeline)['program']
num_blocks = GL.glGetProgramiv(program, GL.GL_ACTIVE_UNIFORM_BLOCKS)
uniform_blocks = {}
for i in range(num_blocks):
    name = (ctypes.c_byte * 100)()
    length = ctypes.c_long()
    GL.glGetActiveUniformBlockName(program, i, 100, ctypes.byref(length), ctypes.byref(name))
    size = ctypes.c_long()
    GL.glGetActiveUniformBlockiv(program, i, GL.GL_UNIFORM_BLOCK_DATA_SIZE, ctypes.byref(size))
    name = bytes(name)[:length.value].decode()
    uniform_blocks[i] = {'name': name, 'size': size.value, 'members': {}}

num_uniforms = GL.glGetProgramiv(program, GL.GL_ACTIVE_UNIFORMS)
uniforms = {}
for i in range(num_uniforms):
    name = (ctypes.c_byte * 100)()
    length = ctypes.c_long()
    GL.glGetActiveUniformName(program, i, 100, ctypes.byref(length), ctypes.byref(name))
    name = bytes(name)[:length.value].decode()
    uniforms[i] = {'name': name}

uniform_indices = (ctypes.c_long * num_uniforms)()
for i in range(num_uniforms):
    uniform_indices[i] = i

info = [
    ('gltype', GL.GL_UNIFORM_TYPE),
    ('block', GL.GL_UNIFORM_BLOCK_INDEX),
    ('offset', GL.GL_UNIFORM_OFFSET),
    ('array_size', GL.GL_UNIFORM_SIZE),
    ('array_stride', GL.GL_UNIFORM_ARRAY_STRIDE),
    ('matrix_stride', GL.GL_UNIFORM_MATRIX_STRIDE),
    ('row_major', GL.GL_UNIFORM_IS_ROW_MAJOR),
]

for key, pname in info:
    params = (ctypes.c_long * num_uniforms)()
    GL.glGetActiveUniformsiv(program, num_uniforms, ctypes.byref(uniform_indices), pname, ctypes.byref(params))
    for i in range(num_uniforms):
        uniforms[i][key] = params[i]

for i in range(num_uniforms):
    if uniforms[i]['block'] != -1:
        uniform_blocks[uniforms[i]['block']]['members'][uniforms[i]['name']] = uniforms[i]

print(uniform_blocks)
```

I did not continue work on this after I found out it takes a tremendous amount of effort to actually parse the output for arrays.
Please see [Program_Introspection#Arrays](https://www.khronos.org/opengl/wiki/Program_Introspection#Arrays).

```glsl
struct Aggregate
{
  vec2 main;
  vec2 sec[3];
};

uniform Aggregate unifArray[5];
```

> There is no uniform named unifArray. However, there is a uniform named unifArray[0].main. There is one named unifArray[2].sec[0], which is an array of basic types. There are five of each of these. As before, the bottom-level array can be clipped off: unifArray[2].sec is equivalent to unifArray[2].sec[0].
> These rules are applied recursively up the hierarchy.

---

PS: replace `program = zengl.inspect(pipeline)['program']` with `program = my_moderngl_program.glo`

**Comment by szabolcsdombi** [comment]
This should be a separate module so I am closing this here.
