### ISSUE TITLE
_moderngl.Error: wrong shader source type on str subclass

### ISSUE THREAD

**Issue by mCodingLLC** [moderngl/moderngl#573]
It seems moderngl 5.8.1 raises an error when a subclass of str is passed as a shader source. I believe it's due to this line, which uses `PyUnicode_CheckExact`.

https://github.com/moderngl/moderngl/blob/1053efd545febba0c46440ee63316cb85dc8f415/src/moderngl.cpp#L2944

I believe this can be fixed by using `PyUnicode_Check` instead.

The same goes as well for bytes (though I'm not affected by this one), this line

https://github.com/moderngl/moderngl/blob/1053efd545febba0c46440ee63316cb85dc8f415/src/moderngl.cpp#L2948

uses `PyBytes_CheckExact` when `PyBytes_Check` would suffice.

**Comment by szabolcsdombi** [comment]
The bytes support is new, previously it caused a fault.

Can you provide an example when would you use a string subclass?

Whan I can think of as a fix is to add a third path converting anything else to string similar to python `str(...)`.
Despite it may work I do not want to pass arbitrary types to PyUnicode_AsUTF8 or similar.

**Comment by mCodingLLC** [comment]
Sure thing, here's my use case. One of the projects I'm working on makes use of internals of the garbage collector (dangerous, we know!), and it only works with objects that are tracked by the gc. Moreover, the objects are often sources of shaders, so we have defined
```
class ShaderSource(str):
    pass
```
This ensures that ShaderSource objects are tracked, which allows us to hook them into our system without requiring the use of a wrapper type where you have to access the string through a `.data`, `.as_str()` or similar.

`PyUnicode_AsUTF8` checks its own arguments using `PyUnicode_Check` so I think it is "safe" to pass anything that passes the `PyUnicode_Check` check in the sense that it won't segfault, although it may cause unexpected behavior as it walks the internal representation of the unicode part of the object, ignoring any special functionality the user may have defined (similar to having a defaultdict raise a KeyError for a missing key instead of inserting it in a function that walks the dict memory directly).

With that said, an opt-in approach is also very reasonable and easy on mgl users, and it would allow supporting even more types such as user-defined wrappers of strings (e.g. ShaderSource if ShaderSource inherited from collections.UserStr instead). After thinking about it I think that this is probably the right way to go.

Here's a few names to get the brainstorm going for the conversion function:

- `as_str`
- `as_shader_str`
- `shader_source` (property)
- `source_str` (property)
- `shader_str` (property)
- `get_source`
- `get_source_str`
- `get_shader_source`
- `get_shader_str`
- `to_str`

Any favorites stick out to you?

**Comment by szabolcsdombi** [comment]
Thank you for the clear explanation.

> `PyUnicode_AsUTF8` checks its own arguments using `PyUnicode_Check` so I think it is "safe" to pass anything that passes the `PyUnicode_Check` check in the sense that it won't segfault.

Thank you for looking that up.
This is very interesting for me as it looks "thin ice". What I mean here, is that you can create arbitrary C structs with the [`Py_TPFLAGS_UNICODE_SUBCLASS`](https://docs.python.org/3/c-api/typeobj.html#Py_TPFLAGS_UNICODE_SUBCLASS) flag set and you get passed the check.

I think it is ok to use `PyUnicode_Check` then.

> With that said, an opt-in approach is also very reasonable and easy on mgl users,

for the fallback path I can think of `to_shader_source(self) -> str`.
Naming is similar to numpy's tolist or Python int's to_bytes().

PS: I have to update the compute shader too (note for me)

**Comment by szabolcsdombi** [comment]
I think that too thats why i finally wrote "I think it is ok to use `PyUnicode_Check` then."

**Comment by szabolcsdombi** [comment]
You can install the master branch with `pip install https://github.com/moderngl/moderngl/archive/refs/heads/master.zip`

Please check if it works, we can release it afterwards.
Thank you for the report.

**Comment by mCodingLLC** [comment]
Works perfectly for me! I tested using a str subclass as well as a `to_shader_source` wrapper and both worked. My IDE complains expected type str | bytes so perhaps type stubs/hints need to be updated to include a 
```python
class ConvertibleToShaderSource(Protocol):
    def to_shader_source(self) -> str:
        ...
```

and shader args in `program` hinted as `str | bytes | ConvertibleToShaderSource | None`. Other than that works great!

**Comment by szabolcsdombi** [comment]
updated stubs too

**Comment by mCodingLLC** [comment]
For `.py` files A | B was introduced in 3.10 so if you want to use it in 3.7  you need to put `from __future__ import annotations` at the top. But for stubs I don't know if this is required.

**Comment by szabolcsdombi** [comment]
For stubs, your text editor's python's version matter, it can happen that it is parsed manually independently from what Python X.Y supports. I can add the `from __future__ import annotations` on the top it might help.
The .py file won't be updated as it will soon be removed entirely in #568

**Comment by mCodingLLC** [comment]
Sounds good to me! Thanks for your help and closing as fixed.

**Comment by szabolcsdombi** [comment]
added `from __future__ import annotations` to the top of the pyi file thank you for recommending it.
