### ISSUE TITLE
typing issue: int expected but Constant found

### ISSUE THREAD

**Issue by cgloeckner** [moderngl/moderngl#582]
I'm using PyCharm as an IDE and it complains about the following:

```py
context = moderngl.create_context()
context.enable(moderngl.BLEND)
```

because:
> Expected type 'int', got 'Constant' instead 

but `enable()` expects an `int` and `moderngl.BLEND` is just `1` (and it's type is int indeed). Over here
https://github.com/moderngl/moderngl/blob/1f058c16945ab5bbfa4526cf69394ea515deb6a8/moderngl-stubs/__init__.pyi#LL11C7-L11C15
they seem to be typed as Constants.

Same for rendering a `vertex_array` with `mode=moderngl.POINTS` for example.
It's not a bit issue, but annoying to see those typing warnings appear.

Greetings
glocke

**Comment by szabolcsdombi** [comment]
** must edit the pyi files for `def enable()` and similar
or just revert the flag types to int

**Comment by szabolcsdombi** [comment]
fixed
