### ISSUE TITLE
Simple doc tests

### ISSUE THREAD

**Issue by einarf** [moderngl/moderngl#583]
After the refactor we lost the doc tests and I discovered from mission methods (ref https://github.com/moderngl/moderngl/commit/9a0562a833c800b5a9e4f7729e738e4b30698698)

It shouldn't be that hard to write a new unit test for this so we don't miss things in the future. Just do module and class members.

Another lazy option is to just use `automodule` and `autoclass`, but I think this will make the API docs worse. The hand crafted structure we have now is very nice.

**Comment by szabolcsdombi** [comment]
Recently I have refactored the docs build. I have a really bad experience using anything that autodetects docs from code.
Sometimes we want to support **kwargs, but we probably should never add this as-is to the docs.
Not to intimidate newcommers, function layout can be simple in the docs, extra parameters can be documented at the end of the section.

I do not think we should test the docs anymore the way we did before.
We can best detect and correct issues from bugreports. The api won't change much so it should converge to the correct form anyways.
