### ISSUE TITLE
Extracting Albedo

### ISSUE THREAD

**Issue by mbanani** [moderngl/moderngl#591]
Hi everyone!  I have a rendering pipeline built on moderngl but I am trying to extract the albedo as well. Does anyone have any suggestions or pointers on how to do that? I wasn't able to find anything in the documentation.

**Comment by einarf** [comment]
What do you mean by extract here?

**Comment by mbanani** [comment]
Thanks a lot for the very quick response! 

I meant I want the rendered to output the albedo on its own instead of generating the rendered image. Basically, I have a colored mesh, and I am trying to render it where the pixel value depicting a point on the mesh is exactly the same as the color for the respective triangle.

**Comment by einarf** [comment]
Unless I'm reading this wrong I think you are looking for framebuffers with multiple attachments. At least that's a pretty straight forward way. Create a framebuffer with multiple texture attachements and write to these separate attachments in the fragment shader.

You can define several outs in the frag shader and the location is the attachment index in the framebuffer.

```glsl
layout(location=0) out vec4 first_layer;
layout(location=1) out vec4 second_layer;
```

**Comment by mbanani** [comment]
Thanks a lot for the response. I was able to find the relevant part in the renderer and change it appropriately.
