### ISSUE TITLE
[xcb] Extra reply data still left in queue

### ISSUE THREAD

**Issue by zerolfq** [moderngl/moderngl#599]
this is my code 
 `    scene = Scene(size=args.window_size)
    if args.with_orthographic_projection:
        scene.camera_matrix = pyrr.Matrix44.orthogonal_projection(
            left=-3.1, right=3.1, bottom=-3.1, top=3.1, near=0.1, far=1000
        )
    scene.light = args.camera_position`

this error in ` scene = Scene(size=args.window_size)` form `self._ctx = moderngl.create_standalone_context()`
The error is
 `[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:577: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.`

**Comment by szabolcsdombi** [comment]
cannot reproduce it, please use the latest mesa driver it should be fine.
