### ISSUE TITLE
How to use Moderngl.ext.obj.Obj

### ISSUE THREAD

**Issue by shorttrack789** [moderngl/moderngl#600]
How to use Moderngl.ext.obj.Obj
Everytime I try to use Moderngl.ext.obj.Obj
it raises error that python cannot find moderngl.ext

how can I sove this problem?

**Comment by szabolcsdombi** [comment]
```
pip install objloader
```

and replace the import as follows

https://github.com/moderngl/moderngl/blob/8b5ecd86b073b97bce90633a39132c7052b8cc90/examples/ported/hello_crate.py#L3C1-L3C1
