### ISSUE TITLE
ModernGL can't find OpenGL on my computer or shows error with the mode.

### ISSUE THREAD

**Issue by LittleBread69** [moderngl/moderngl#605]
# My code doesn't work on my computer. Can someone help ?
## My specs:
Apple MacBook Pro M1
MacOS X Sonoma 14.0
Apple M1 (8C-8G)
ModernGL 5.8.2

## The code:
```py
#Coded on MacOS X Sonoma 14
from pprint import pprint
import moderngl as mgl
import multiprocessing as mpr
import glfw
import time as t

# vars
width, height = 1280, 700
TUS = 0.0 #TUS means TimedUpdateSpeed
HzTUS = 0.0

def Update(ctx, window, GLFW_CLOSE_WINDOW):
    glfw.make_context_current(window)
    
    while not GLFW_CLOSE_WINDOW.value:
        ctx.clear(0.0, 0.0, 0.0)
        #Update Loop

        glfw.swap_buffers(window)
        glfw.poll_events()

def TimedUpdate(ctx, TUS, HzTUS, GLFW_CLOSE_WINDOW):
    if TUS < 1.0 or HzTUS <= 0.0:
        glfw.terminate()
        raise ValueError(f"Problem with TUS: {TUS} or with HzTUS: {HzTUS}.")
    while not GLFW_CLOSE_WINDOW.value:
        st = t.time()
        #TimedUpdate Loop

        if (t.time() - st) < HzTUS:
            t.sleep(abs(HzTUS - t.time()))

def Quit(UpdateProcess, TimedUpdateProcess):
    UpdateProcess.terminate()
    TimedUpdateProcess.terminate()
    UpdateProcess.join()
    TimedUpdateProcess.join()
    glfw.terminate()

def GlobalCheck(window, GLFW_CLOSE_WINDOW):
    while not GLFW_CLOSE_WINDOW.value:
        if glfw.window_should_close(window):
            GLFW_CLOSE_WINDOW.value = True

if __name__ == '__main__':
    # Preload Section
    TUS = 60.0 #TUS means TimeUpdateSpeed
    HzTUS = 1.0 / TUS
    
    glfw.init()
    if not glfw.init():
        raise Exception("GLFW initialization failed")
    
    window = glfw.create_window(width, height, "ModernGL Window", None, None)
    if not window:
        glfw.terminate()
        raise Exception("Window Creation Failed")

    # Create a shared ModernGL context
    with mpr.Manager() as manager:
        GLFW_CLOSE_WINDOW = manager.Value('b', False)
        shared_ctx = mgl.create_context(standalone=True, require=410, share=True)

        UpdateProcess = mpr.Process(target=Update, args=(shared_ctx, window, GLFW_CLOSE_WINDOW))
        TimedUpdateProcess = mpr.Process(target=TimedUpdate, args=(shared_ctx, TUS, HzTUS, GLFW_CLOSE_WINDOW))
        CheckProcess = mpr.Process(target=GlobalCheck, args=(window, GLFW_CLOSE_WINDOW))
        # End of Preload Section
        UpdateProcess.start()
        TimedUpdateProcess.start()
        CheckProcess.start()
```

## The error:

```
Traceback (most recent call last):
  File "/Users/adamkudelas/Projects/Game Engine/ForgeWings-Engine/main.py", line 63, in <module>
    shared_ctx = mgl.create_context(standalone=True, require=410, share=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pypy/lib/pypy3.10/site-packages/moderngl/__init__.py", line 2174, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pypy/lib/pypy3.10/site-packages/glcontext/__init__.py", line 100, in create
    return darwin.create_context(**_strip_kwargs(kwargs, ['mode']))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: unknown mode
```

I'm trying to make a small game from scratch using Python and ModernGL. Though I stumble on this error constantly and when I do anything else it tells me:

`Exception: cannot detect OpenGL context`

**Comment by einarf** [comment]
There several problems here. You're not configuring the glfw window. On MacOS your window will be created using legacy opengl. See https://github.com/moderngl/moderngl-window/blob/200f2b9ea8b350b0ac9bb6a2d24310c0d8227794/moderngl_window/context/glfw/window.py#L33-L45

The second problem is the `share` option (I don't think macos backend even support that) and the processes. Just drop all that for now unless you deeply know what you are doing.

**Comment by LittleBread69** [comment]
I checked and the Share option seems to be unsupported. 

You linked ModernGL-window but I use pyGLFW, should I transition to ModernGL-window ?

**Comment by einarf** [comment]
You don't have to use moderngl-window, but it's a good reference.

Anyway. That's a diversions from the original issue. Did you get things working?

**Comment by LittleBread69** [comment]
Now it's telling me that the problem comes from GLFW, though I have to say, I knew it would be complicated. 
I'll write if I find a solution or a fix but it seems like it's a limitation of Python.

**Comment by einarf** [comment]
> Now it's telling me that the problem comes from GLFW, though I have to say, I knew it would be complicated.
> I'll write if I find a solution or a fix but it seems like it's a limitation of Python.

It should not be that complicated to set up GLFW if you set the right window hints.

A friendly tip: When you create/comment in issues be sure you include as much information as possible. Issues are not chat messages. Most developers would just close this issues because there is nothing else I can follow up with here. You would normally share a new minimal example and the exact error message.
