### ISSUE TITLE
How to use glDepthMask() function with moderngl?

### ISSUE THREAD

**Issue by caol64** [moderngl/moderngl#606]
I searched the docs and only found https://moderngl.readthedocs.io/en/latest/reference/framebuffer.html?highlight=Depth%20Mask#moderngl.Framebuffer.depth_mask . Is it only possible to use glDepthMask() when using the Framebuffer?

Thanks.

**Comment by szabolcsdombi** [comment]
Try setting this propery on the default framebuffer: `ctx.screen`
