### ISSUE TITLE
Add an optimization hint/flag to ctx.texture() to support texture render targets without sampling

### ISSUE THREAD

**Issue by szabolcsdombi** [moderngl/moderngl#615]
On modern hardware there is often no difference in rendering to texture or to a renderbuffer. ModernGL implements renderbuffers as a separate object and it confuses users. I suggest allowing textures to be created with an extra flag "sampled=False" or similar to actually create a Texture object backed up with a renderbuffer object. This works wonderful in zengl.
Docs can be simplified many places to mention just texture and renderbuffers could be deprecated and should suggest to use ctx.texture().
Renderbuffers wont be removed and will work as before without noticable change.

**Comment by compik710** [comment]
Can these MSAA `Textures` be inserted into `Framebuffer` and use several of them in one `Framebuffer`?
I remember earlier I tried to use MSAA myself, but I would have to rewrite too much because the code was too tied to regular textures.

**Comment by szabolcsdombi** [comment]
the idea was to just support the texture() function to return a renderbuffer instance, the same way ZenGL does it.
Basically a renderbuffer is a texture without the ability to attach it to a shader as a texture.
This allows (or allowed in the past) OpenGL to be more efficient using these images as render targets.

The texture is a very wrong wording here, but renaming to image is way too complicated at this stage of development.
