### ISSUE TITLE
Support Enable GL_CLIP_DISTANCE<n>

### ISSUE THREAD

**Issue by Caue-Aron** [moderngl/moderngl#620]
Howdy! I would like to know if there are any ways of using glClipPlane from raw opengl or anything similar to it. I couldnt find anything in the docs about it, my intentions with this feature is to make water refraction and reflection, like in this tutorial:
https://www.youtube.com/watch?v=0NH9k4zTAqk&ab_channel=ThinMatrix

i tried my way if

**Comment by einarf** [comment]
`glClipPlane` is deprecated and is part of the old fixed pipeline. You probably need to use `gl_ClipDistance` (set in the shader itself).

**Comment by einarf** [comment]
Closing for now. Be free to comment if you need anything else.

**Comment by Caue-Aron** [comment]
Much sorry, lost account for a while. I didnt knew gl_ClipDistance was usable in moderngl, much thanks!

**Comment by einarf** [comment]
I don't think we support enabling clip distance (`glEnable(GL_CLIP_DISTANCE<N>`) directly, but you can use `enable_direct` using the enum value(s). In a perfect world we would make a wrapper method for it in the context.

**Comment by szabolcsdombi** [comment]
closing this as it requires enable_direct and that is likely require to define the constants from above.

I am still not sure what this feature does.
We can implement in a more pythonic way. Something better than enable_direct. I just need an example to understand the use-case first.

Feel free to reopen with an article/example about `GL_CLIP_DISTANCE*`
