### ISSUE TITLE
Exception: (standalone) glXChooseVisual: cannot choose visual

### ISSUE THREAD

**Issue by Boltzmachine** [moderngl/moderngl#621]
**Description**
Command I executed
```python
ctx = moderngl.create_context(standalone=True)
```
I got error
```
     88 _apply_env_var(kwargs, 'libx11', 'GLCONTEXT_LINUX_LIBX11')
     89 kwargs = _strip_kwargs(kwargs, ['glversion', 'mode', 'libgl', 'libx11'])
---> 90 return x11.create_context(**kwargs)

Exception: (standalone) glXChooseVisual: cannot choose visual
```

**Version info**

```
moderngl 5.8.2
--------------
vendor: NVIDIA Corporation
renderer: NVIDIA A100-SXM4-40GB/PCIe/SSE2
version: 3.3.0 NVIDIA 535.104.05
python: 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0]
platform: linux
code: 330

```

**Comment by Boltzmachine** [comment]
I also refer to https://github.com/moderngl/moderngl/issues/382. But it does not help

**Comment by szabolcsdombi** [comment]
Is there any chance you are using either:

- a remote ssh connection
- x11forwarding or similar
- through vnc connection
- some very new or very old platform
- wayland
- ubuntu server or similar non gui system

Its not a problem if you cannot answer all of them, please provide some system details like what OS are you using.

PS: It is possible to run moderngl without a GUI, you either need EGL or Xvfb run.

**Comment by Boltzmachine** [comment]
Just found it because I am using MacOS for X11forwarding while the openGL I used is the Nvidia one. Switching to a Windows machine with a Nvidia card solves this issue. Thanks for your reply!
