### ISSUE TITLE
How to use Freetype with ModernGL to render text?

### ISSUE THREAD

**Issue by caol64** [moderngl/moderngl#622]

**Comment by alexandrepv** [comment]
I get a texture from Freetype, which is uploaded to the GPU, then I use a geometry shader to generate the textures for each each of the characters on the string. The values fort the size, position and UV are uploaded in VBOs. I'm not aware of already-built functions for rendering text, but it would be a great good-to-have :)

**Comment by einarf** [comment]
The moderngl discord server is probably a better place for dicussing this. It's just too complex to cover in an issue on github. It's a feature that probably needs to be broken down into many parts. The empty description in the OP also doesn't really help. We don't know anything about your experience level or what you have tried already.

Like already mentioned you can get pixel data for the glyphs using freetype-py including other properties related to correctly positioning the glyph. Ideally you want to write the glyphs into a texture atlas or a texture array to make batch redering possible. That pretty much breaks the problem down into parts.

**Comment by alexandrepv** [comment]
I didn't actually realise there was a discord server :D Nice!

**Comment by caol64** [comment]
> FreeType is just amazing to load any type of fonts. You might want to consider using something more lightweight (like only truetype). For C/C++ we have [stb_truetype](https://github.com/nothings/stb/blob/master/stb_truetype.h).
> 
> I have interfaced it for python as `font-atlas`. It is brand new so use it with a grain of salt.
> 
> This is actually just a function from my all-in-one window library that is not yet finished.
> 
> Here is a sample code:
> 
> https://github.com/szabolcsdombi/font-atlas/blob/main/examples/example_moderngl.py

@szabolcsdombi Thank you for your advice. I am a beginner in `FreeType` and `TrueType`. I would like to implement the following functionality, as shown in the attached image. I believe the challenge might be handling `CJK` characters. I think for now, it's a good idea to gather more reference materials.

![](https://babyno.top/imgs/posts/2023-10-04-parsing-ps2-3d-icon/1.jpg)

**Comment by szabolcsdombi** [comment]
![image](https://github.com/moderngl/moderngl/assets/11232402/f71248ea-a6fe-4308-af82-3a22901b935f)

I have added `NotoSansTC-Regular.ttf` and it seems to work fine.
instead of string.printable I had to add the required characters, but works as expected.

**Comment by caol64** [comment]
@szabolcsdombi Looks fantastic! This seems to be exactly the effect I was looking for.
