### ISSUE TITLE
does not install with build tools 143 on win11

### ISSUE THREAD

**Issue by goofyseeker311** [moderngl/moderngl#628]
latest python 3.12.0 with "pip install moderngl" is missing io.h include in default install, no configuration attempts anywhere.
I only installled the 143 build tools from the build tools installer by microsoft visual studio. does not work directly.

ps. any instructions how to install should work directly. why you dont provide a pre-compiled wheel if its required? the install fails because of some additional compile tasks on windows, which is highly un-usual, more like trying to do things in the linux way. even better if you provide a python native version of whatever the functionality of the wheel on windows should be. no outside python compile tasks that way. no wheel required?

**Comment by goofyseeker311** [comment]
it does install after removing the build tools only (seems to be missing the libraries/headers or some configuration related to them), and installing the full visual studio 2022 IDE, with all the build tools from 140 to 143.

**Comment by szabolcsdombi** [comment]
Hello, can you please check if any other Python library can be installed with your setup?

```
pip wheel numpy --no-binary=:all:
```

If the above code does not run, your build tools setup might be flawed.

**Comment by goofyseeker311** [comment]
all other non-compiling pip libraries install fine, like numpy.

**Comment by szabolcsdombi** [comment]
oh i see, we miss the python 3.12 wheels.
I just made a release for 5.9.0 and it will be up soon. including the python 3.12 wheels for windows

**Comment by szabolcsdombi** [comment]
should be up and install without building.

**Comment by goofyseeker311** [comment]
should be fine.
