### ISSUE TITLE
Vertex Array 'skip_errors' option is no longer valid

### ISSUE THREAD

**Issue by franklin567** [moderngl/moderngl#630]
This happened with the release of version 5.9.0. Previously when creating VAO 'skip_errors=True' ignored the use of input attributes in shaders, but now errors are caused. I had to go back to version 5.8.2

**Comment by szabolcsdombi** [comment]
thank you for reporting this, indeed skip_errors is unused here:

https://github.com/moderngl/moderngl/blob/4c6c488553e48b38d57fc0d0e699054e81b4848f/src/moderngl.cpp#L6587-L6607

i think the use of this flag needs to be restored from 5.8.2 then.

**Comment by jimy-byerley** [comment]
Yes please restore it !
This flag is very convenient for creating vertex arrays using buffer containing more data than actually used in the shader. And this is often the case when I share the same buffer between several shaders

**Comment by szabolcsdombi** [comment]
restored in #709f9611
