### ISSUE TITLE
Release notes for 5.9.0 missing, pylint shows false-positive errors for constants

### ISSUE THREAD

**Issue by manuel-koch** [moderngl/moderngl#646]
I upgraded `moderngl` from 5.8.2 to 5.9.0 and now I see strange errors from `pylint==3.0.3` like

```
my_code.py:69:41: E1101: Module 'moderngl' has no 'NEAREST' member (no-member)
my_code:73:35: E1101: Module 'moderngl' has no 'ONE' member (no-member)
my_code:73:49: E1101: Module 'moderngl' has no 'ZERO' member (no-member)
```

I guess pylint fails to find those constants due to the way `moderngl._resolve_module_constants` works ?
The code works at runtime though and constants can be accessed.

Additionally the github repo doesn't show any release info for 5.9.0 although this version seems to be the latest on PyPi.

**Comment by compik710** [comment]
According to the [new documentation](https://moderngl.readthedocs.io/en/latest/reference/moderngl.html#context-flags), all ModernGL constants have been moved to Context, so they are now accessible through the ModernGL module only as intentionally hidden from parsing.

The current version of ModernGL 5.9.0 is a preparation for the release of ModernGL 6 and is not a full version. Therefore, there was no official release on GitHub.

There are big changes coming to ModernGL and moving constants to Context is one of them.

**Comment by manuel-koch** [comment]
Thanks @compik710 for this hint - although this particular hint, that constants have been moved to `Context` is a very useful topic for a release notes of the repo.

**Comment by szabolcsdombi** [comment]
keep this open I have to double check but the intention is the following:

new code should use the ctx for all purposes.
removing typehints helps the users find this out.
removing the constant won't happen so old code can run unchanged.

**Comment by manuel-koch** [comment]
As stated above the constants have not been "moved" yet ( my code still works ), rather the "old" way using the package scope is deprecated ( and pylint fails to understand that or is ignorant of that deprecation ) and users should switch to the "Context" scope to access those constants instead.
