### ISSUE TITLE
Framebuffer python object leak

### ISSUE THREAD

**Issue by mabl** [moderngl/moderngl#647]
I am currently debugging a memory leak that occurs in my rendering code. I think I have it narrowed down to the MGLO framebuffer object (`sizeof(fbo.mglo) == 104`), which does not get released.  

The following example code illustrates the problem:

```python
import gc
import tracemalloc

import moderngl

context = moderngl.create_standalone_context(require=430)

nr_pixels_xy = (42, 42)

tracemalloc.start()
snapshot_before = tracemalloc.take_snapshot()

while True:
    for i in range(10000):
        fbo: moderngl.Framebuffer = context.empty_framebuffer(nr_pixels_xy)
        fbo.release()
        del fbo
    gc.collect()

    snapshot = tracemalloc.take_snapshot()
    top_stats = snapshot.compare_to(snapshot_before, 'lineno')
    for stat in top_stats[:1]:
        print(stat)
    snapshot_before = snapshot
```

which results in a reported steady increase in objects proportional to the created framebuffers at exactly the 104 bytes per object:

```
...debugging_env\lib\site-packages\moderngl\__init__.py:1812: size=12.9 MiB (+1016 KiB), count=130000 (+10000), average=104 B
...debugging_env\lib\site-packages\moderngl\__init__.py:1812: size=13.9 MiB (+1016 KiB), count=140000 (+10000), average=104 B
...debugging_env\lib\site-packages\moderngl\__init__.py:1812: size=14.9 MiB (+1016 KiB), count=150000 (+10000), average=104 B
```

I am not familiar with the CPython API, but I do suspect some shenanigans with the reference count of that object. Some of the CPP [includes `Py_DECREF(framebuffer);` on error condition ](https://github.com/moderngl/moderngl/blob/e9e7cd3c8040a7e24876ab4a4cb13180ec292118/src/moderngl.cpp#L1605C9-L1605C32), but not all (see [here](https://github.com/moderngl/moderngl/blob/main/src/moderngl.cpp#L1477) or [here](https://github.com/moderngl/moderngl/blob/main/src/moderngl.cpp#L1666))

What do you think? Am I doing something wrong here? Is this behavior expected?

**Comment by mabl** [comment]
Github has problems, so I accidentally created two issues. Sorry for that.

**Comment by szabolcsdombi** [comment]
https://github.com/moderngl/moderngl/issues/648
