### ISSUE TITLE
eglinitialize failed (0x3001)

### ISSUE THREAD

**Issue by smoothumut** [moderngl/moderngl#652]
Hi,
I have this testing code and it cant initialize the context

        import moderngl
        moderngl.create_standalone_context(backend="egl")

I am on ubuntu and I am using 5.10.0 version. I have checked previous versions and having the same error
probably it is not about moderngl code, but some hints what would cause this help me solve the problem
thanks thanks in advance

**Comment by compik710** [comment]
Hello, judging by the indentation, this code is embedded in something. Did any other imported module create an OpenGL context? Two OpenGL contexts cannot run simultaneously in one thread.

**Comment by smoothumut** [comment]
thanks for the reply @compik710 , 
the code is all. just two lines. I extracted from different source to test it.
Could the problem be about cuda?

**Comment by compik710** [comment]
Does the regular code work for you?
```py
import moderngl
moderngl.create_context(standalone=True)
```

**Comment by smoothumut** [comment]
yes, this one is working
but not this one 
      import moderngl
      moderngl.create_context(standalone=True,backend='egl')
this one gives the same error

**Comment by smoothumut** [comment]
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/.vscode/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/xxx/.vscode/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/xxx/.vscode/extensions/ms-python.python-2022.8.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/xxx/miniconda3/envs/yyy/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/Documents/Deeps/yyyz/test-egl.py", line 2, in <module>
    moderngl.create_context(standalone=True,backend='egl')
  File "/home/xxx/.local/lib/python3.8/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/home/xxx/.local/lib/python3.8/site-packages/glcontext/__init__.py", line 120, in create
    return egl.create_context(**kwargs)
Exception: eglInitialize failed (0x3001)

this is the log

**Comment by smoothumut** [comment]
the ubuntu's version is 20.04.5 LTS
please dont ask me the cuda version, I have messed up that part little.
I really couldnt understand what is going on there, and just caused me troubles because of conflicts :(
here is the final result

here is nvidia-smi result

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:42:00.0  On |                  N/A |
|  0%   53C    P8    15W / 260W |    356MiB / 11264MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1732      G   /usr/lib/xorg/Xorg                 35MiB |
|    0   N/A  N/A      2286      G   /usr/lib/xorg/Xorg                169MiB |
|    0   N/A  N/A      2415      G   /usr/bin/gnome-shell               34MiB |
|    0   N/A  N/A      9266      G   ...RendererForSitePerProcess       67MiB |
|    0   N/A  N/A     10225      G   ...900162502749941877,131072       35MiB |
+-----------------------------------------------------------------------------+


and here is the nvcc --version result

Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**Comment by compik710** [comment]
Your Nvidia drivers, as well as CUDA drivers, have not been updated for a long time, this may be a likely cause of this problem.

The modern version of Ubuntu 23.10 prefers to use Xwayland instead of Xorg, a lot could have changed during this time.

My advice is to update everything or just not use `backend="egl"`, there is no difference in the functionality of the backends.

**Comment by szabolcsdombi** [comment]
In case further investigation is needed:

the backend="egl" code leads to this file: https://github.com/moderngl/glcontext/blob/master/glcontext/egl.cpp

**Comment by smoothumut** [comment]
upgrading ubuntu to 22.04 and installing cuda carefully solved the problem. 
sorry for the wrong alarm 
thank you all for your time and energy 🙇
