### ISSUE TITLE
Auto garbage collection not working as expected

### ISSUE THREAD

**Issue by coz-eduardo-hernandez** [moderngl/moderngl#659]
The app I've been writing has been having MemoryError exceptions, and I tracked it down to me creating buffers quite often. If I call buffer.release() all is well; however I have set Context.gc_mode = "auto"

I'm not sure it is relevant, but I'm using two contexts in GTK4, and one of them was created with share=True. I'm sure both have the issue, but the context where I first detected it (because it uses the most memory) is the one that does not have share=True

I'm also sure that orphaning would prevent this issue; initially I chose not to use orphaning and relied on garbage collection because you can't create a buffer with zero size

I modified the GTK4 example in the other thread to easily show the issue. If you grab the corner of the window and continuously resize it, you can see the memory usage steadily climbing:
```Python
import os, psutil, sys
import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Gdk', '4.0')  # Optional, only for typehints

from gi.repository import Gtk, Gdk
from typing import Optional
import moderngl
import struct

class ModernGLArea(Gtk.GLArea):

    def __init__(self):
        super().__init__()
        self.ctx: Optional[moderngl.Context] = None

    def do_realize(self):
        Gtk.GLArea.do_realize(self)
        self.ctx = moderngl.create_context()
        self.ctx.gc_mode="auto"

    def do_resize(self, width: int, height: int):
        Gtk.GLArea.do_resize(self, width, height)
        self.ctx.detect_framebuffer().use()

    def do_unrealize(self):
        self.ctx = None
        Gtk.GLArea.do_unrealize(self)

def on_render(area: ModernGLArea, context: Gdk.GLContext) -> bool:
    ctx = area.ctx
    if ctx is None:
        print("ctx is None!")
        return True

    global checkbox
    if checkbox is not None and checkbox.props.active:
        ctx.clear(0, 1, 0, 1)
    else:
        ctx.clear(0.25, 0, 0, 1)
    print(ctx.viewport, ctx.fbo.glo)

    global shader
    if shader is None:
        shader = ctx.program(
            vertex_shader='''
#version 330
in vec2 in_vert;
in vec3 in_color;
out vec3 v_color;
void main() {
    gl_Position = vec4(in_vert, 0.0, 1.0);
    v_color = in_color;
}
            ''',
            fragment_shader='''
#version 330
in vec3 v_color;
out vec4 f_color;
void main() {
    f_color = vec4(v_color, 1.0);
}
            ''')

    global vbo
    if vbo is None:
        vbo = ctx.buffer(struct.pack("@" + "fffff" * 3, *[
            # x, y, red, green, blue
             0.0,  0.9, 1.0, 0.0, 0.0,
            -0.9, -0.9, 0.0, 1.0, 0.0,
             0.9, -0.9, 0.0, 0.0, 1.0,
            # Note: (0, 0) is center, +Y is up, +x is right, from -1 to +1
        ]))

    global vao
    if vao is None:
        vao = ctx.vertex_array(shader, vbo, 'in_vert', 'in_color')
    vao.render()

    print(psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024)
    return False

checkbox: Optional[Gtk.CheckButton] = None
shader: Optional[moderngl.Program] = None
vbo: Optional[moderngl.Buffer] = None
vao: Optional[moderngl.VertexArray] = None

def on_activate(app: Gtk.Application):
    win = Gtk.ApplicationWindow(application=app)
    box = Gtk.Box.new(Gtk.Orientation.VERTICAL, 0)
    area = ModernGLArea()
    area.connect('render', on_render)
    area.props.hexpand = True
    area.props.vexpand = True
    area.set_size_request(100,100)
    box.append(area)
    global checkbox
    checkbox = Gtk.CheckButton.new_with_label("Some example widget")
    checkbox.connect('notify::active', lambda obj, prop: area.queue_draw())
    box.append(checkbox)
    win.set_child(box)
    win.present()

app = Gtk.Application()
app.connect('activate', on_activate)
app.run(sys.argv)
```

In this example the only object that actually gets remade is the framebuffer, but if you call release before detecting the framebuffer the screen will go blank on resize, likely because it's actually the same framebuffer on GTK4

**Comment by compik710** [comment]
This issue is not related to ModernGL because framebuffer creation and resizing is done by GTK-4, not ModernGL.
The memory leak occurs inside GTK-4, so there is nothing we can do on our end.
The memory leak is controversial since it is minor and it is possible that GTK-4 deliberately expands its memory to create a huge texture from which it cuts smaller ones (thus reducing the number of destructions and creations of new buffers, which increases performance).

In previous discussions we have already mentioned the correct creation of context for GTK-4 - through `moderngl.get_context()`, do not deviate from the recommendations.
<details>

<summary>Corrected code</summary>

```py
import os, psutil, sys
import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Gdk', '4.0')  # Optional, only for typehints

from gi.repository import Gtk, Gdk
from typing import Optional
import moderngl
import struct

class ModernGLArea(Gtk.GLArea):

    def __init__(self):
        super().__init__()
        self.ctx: Optional[moderngl.Context] = None

    def do_realize(self):
        Gtk.GLArea.do_realize(self)
        self.ctx = moderngl.get_context()
        self.ctx.gc_mode="auto"

    def do_resize(self, width: int, height: int):
        Gtk.GLArea.do_resize(self, width, height)
        self.ctx.detect_framebuffer().use()

    def do_unrealize(self):
        self.ctx = None
        Gtk.GLArea.do_unrealize(self)

def on_render(area: ModernGLArea, context: Gdk.GLContext) -> bool:
    ctx = area.ctx
    if ctx is None:
        print("ctx is None!")
        return True

    global checkbox
    if checkbox is not None and checkbox.props.active:
        ctx.clear(0, 1, 0, 1)
    else:
        ctx.clear(0.25, 0, 0, 1)
    print(ctx.viewport, ctx.fbo.glo)

    global shader
    if shader is None:
        shader = ctx.program(
            vertex_shader='''
#version 330
in vec2 in_vert;
in vec3 in_color;
out vec3 v_color;
void main() {
    gl_Position = vec4(in_vert, 0.0, 1.0);
    v_color = in_color;
}
            ''',
            fragment_shader='''
#version 330
in vec3 v_color;
out vec4 f_color;
void main() {
    f_color = vec4(v_color, 1.0);
}
            ''')

    global vbo
    if vbo is None:
        vbo = ctx.buffer(struct.pack("@" + "fffff" * 3, *[
            # x, y, red, green, blue
             0.0,  0.9, 1.0, 0.0, 0.0,
            -0.9, -0.9, 0.0, 1.0, 0.0,
             0.9, -0.9, 0.0, 0.0, 1.0,
            # Note: (0, 0) is center, +Y is up, +x is right, from -1 to +1
        ]))

    global vao
    if vao is None:
        vao = ctx.vertex_array(shader, vbo, 'in_vert', 'in_color')
    vao.render()

    print('Memory:', psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024)
    return False

checkbox: Optional[Gtk.CheckButton] = None
shader: Optional[moderngl.Program] = None
vbo: Optional[moderngl.Buffer] = None
vao: Optional[moderngl.VertexArray] = None

def on_activate(app: Gtk.Application):
    win = Gtk.ApplicationWindow(application=app)
    box = Gtk.Box.new(Gtk.Orientation.VERTICAL, 0)
    area = ModernGLArea()
    area.connect('render', on_render)
    area.props.hexpand = True
    area.props.vexpand = True
    area.set_size_request(100,100)
    box.append(area)
    global checkbox
    checkbox = Gtk.CheckButton.new_with_label("Some example widget")
    checkbox.connect('notify::active', lambda obj, prop: area.queue_draw())
    box.append(checkbox)
    win.set_child(box)
    win.present()

app = Gtk.Application()
app.connect('activate', on_activate)
app.run(sys.argv)
```

</details>

**Comment by szabolcsdombi** [comment]
The gc is a convenient way to get things cleaned up for you, however you should never rely on it because it uses `__del__` and that one is absolutely not reliable, you can even get segmentation faults because of them.

- You should consider manually calling `.release()` on every object allocated that you wish **to destroy at runtime**.
- You should **NOT** release any objects before the windows is destroyed or before the program exists.

I did not yet manage to run your code, I will do that soon.

We are probably leaking CPU side python objects especially for the `detect_framebuffer` because earlier that was expected to be called at most a few times on startup.

Can I add your GTK code to the repo? You can also PR any simple version of it. or even multiple ones if it makes sense. just drop it in I merge it right after.

---

For the GC I plan a minor update which was not possible earlier due to backward compatibility.
We are going to have a gc object set by the user, moderngl will add/remove objects to it as if it was a list (has a append, remove methods) or push, pop, we'll see.

**Comment by coz-eduardo-hernandez** [comment]
> This issue is not related to ModernGL because framebuffer creation and resizing is done by GTK-4, not ModernGL. The memory leak occurs inside GTK-4, so there is nothing we can do on our end

Agreed
 

> The memory leak is controversial since it is minor

A memory leak shouldn't happen even if it's a single block, but like you said, it's not done by moderngl 5.10 and GTK4 probably eventually limits or frees the memory
 

> In previous discussions we have already mentioned the correct creation of context for GTK-4 - through `moderngl.get_context()`

Thanks for pointing that out. I was running v5.9.0 and there get_context() doesn't work for me, but it does with 5.10.0
 

> The gc is a convenient way to get things cleaned up for you, however you should never rely on it because it uses __del__

Ah. I was aware of not relying on __del__, but I had to read a bit to become aware of the lack of guarantees of memory release in Python and variations between implementations
 

> You should **NOT** release any objects before the windows is destroyed or before the program exists

I'm talking about releasing objects I won't be using anymore, ever. Is there are reason not to release those?
 

> We are probably leaking CPU side python objects especially for the `detect_framebuffer` because earlier that was expected to be called at most a few times on startup.

To be honest I think @compik710 is correct and there's no issue with detect_framebuffer (at least on my platform), because even when I remove all moderngl code memory usage goes up on resize and it follows the same pattern, at first it seems to happen on every resize in small amounts but after a while it's done in larger amounts but only every couple resizes
 

> Can I add your GTK code to the repo? You can also PR any simple version of it. or even multiple ones if it makes sense. just drop it in I merge it right after 

Of course. I might make the PR in the next couple days if I can find the time

I think using @compik710's example with some modifications is best. The modifications would be removing some of the prints (no harm in leaving them in though), adding 'self.make_current()' to do_realize() as suggested at https://github.com/moderngl/moderngl/issues/644#issuecomment-1906455479 and adding a comment over why return False from the on_render() callback of the render signal, as I found that confusing but usually will be what you want.

<details><summary>Code with the changes</summary>
``` Python
import os, sys
/import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Gdk', '4.0')  # Optional, only for typehints

from gi.repository import Gtk, Gdk
from typing import Optional
import moderngl
import struct

class ModernGLArea(Gtk.GLArea):

    def __init__(self):
        super().__init__()
        self.ctx: Optional[moderngl.Context] = None

    def do_realize(self):
        Gtk.GLArea.do_realize(self)
        self.make_current()
        self.ctx = moderngl.get_context()

    def do_resize(self, width: int, height: int):
        Gtk.GLArea.do_resize(self, width, height)
        self.ctx.detect_framebuffer().use()

    def do_unrealize(self):
        self.ctx = None
        Gtk.GLArea.do_unrealize(self)

def on_render(area: ModernGLArea, context: Gdk.GLContext) -> bool:
    ctx = area.ctx
    if ctx is None:
        print("ctx is None!")
        return True

    global checkbox
    if checkbox is not None and checkbox.props.active:
        ctx.clear(0, 1, 0, 1)
    else:
        ctx.clear(0.25, 0, 0, 1)

    global shader
    if shader is None:
        shader = ctx.program(
            vertex_shader='''
#version 330
in vec2 in_vert;
in vec3 in_color;
out vec3 v_color;
void main() {
    gl_Position = vec4(in_vert, 0.0, 1.0);
    v_color = in_color;
}
            ''',
            fragment_shader='''
#version 330
in vec3 v_color;
out vec4 f_color;
void main() {
    f_color = vec4(v_color, 1.0);
}
            ''')

    global vbo
    if vbo is None:
        vbo = ctx.buffer(struct.Struct("@" + "fffff" * 3).pack( *[
            # x, y, red, green, blue
             0.0,  0.9, 1.0, 0.0, 0.0,
            -0.9, -0.9, 0.0, 1.0, 0.0,
             0.9, -0.9, 0.0, 0.0, 1.0,
            # Note: (0, 0) is center, +Y is up, +x is right, from -1 to +1
        ]))

    global vao
    if vao is None:
        vao = ctx.vertex_array(shader, vbo, 'in_vert', 'in_color')
    vao.render()

    # True stops propagating the signal
    return False

checkbox: Optional[Gtk.CheckButton] = None
shader: Optional[moderngl.Program] = None
vbo: Optional[moderngl.Buffer] = None
vao: Optional[moderngl.VertexArray] = None

def on_activate(app: Gtk.Application):
    win = Gtk.ApplicationWindow(application=app)
    box = Gtk.Box.new(Gtk.Orientation.VERTICAL, 0)
    area = ModernGLArea()
    area.connect('render', on_render)
    area.props.hexpand = True
    area.props.vexpand = True
    area.set_size_request(100,100)
    box.append(area)
    global checkbox
    checkbox = Gtk.CheckButton.new_with_label("Some example widget")
    checkbox.connect('notify::active', lambda obj, prop: area.queue_draw())
    box.append(checkbox)
    win.set_child(box)
    win.present()

app = Gtk.Application()
app.connect('activate', on_activate)
app.run(sys.argv)
```
</details>

> For the GC I plan a minor update which was not possible earlier due to backward compatibility. We are going to have a gc object set by the user, moderngl will add/remove objects to it as if it was a list (has a append, remove methods) or push, pop, we'll see.

Sounds good. I'll be testing my code further to see if I have any more thoughts about the GC or if I can just close this issue as is. The only thing I'd change right now is in the docs for Context.gc_mode it reads 'Please see documentation for the appropriate configuration'; I'd just link directly to the topic 'The Lifecycle of a ModernGL Object'

**Comment by szabolcsdombi** [comment]
Great to know we have no leaks 👍 
I was expecting some as you are using a rarely used code path with the detect_framebuffer.
Good to hear there is none.

There are two strong reasons for not releasing anything before the program ends:

- First it takes time, and adds no value, the OS will clean everything up for you at process termination.
- There is a risk of actually causing a fault, if the window is closed, so is the OpenGL context destroyed, and chances are high GL calls will end up in access violation.

At runtime you are safe to call release on temporary objects you no longer need.
It is even possible to create+destroy resources per frame.
It is clearly a case when you still have an OpenGL context, and manually releasing the resources is independent of the Python object's lifecycle. A Buffer object may be collected by the gc later, and it won't invoke any GL function calls. This is why we have explicit release.

I hope it helps.

**Comment by coz-eduardo-hernandez** [comment]
> In previous discussions we have already mentioned the correct creation of context for GTK-4 - through `moderngl.get_context()`, do not deviate from the recommendations.

I have two GLAreas, and I switched the first one to get_context(), everything works fine. With the second one, when I switch to get_context() I get a curious artifact: only the GLArea with focus gets drawn

So I modified the GTK4 example to use three Gtk.GLArea, then separated all resources (vbo, vao, etc. ). I also added and offset to make changes obvious. The first time the areas get drawn, it works; however when you click the checkboxes it shows that get_context() is just returning the last created context and mixes them up:

<details><summary>Testing code</summary>

```Python
import os, sys
import gi

gi.require_version('Gtk', '4.0')
gi.require_version('Gdk', '4.0')  # Optional, only for typehints

from gi.repository import Gtk, Gdk
from typing import Optional
import moderngl
import struct

class ModernGLArea(Gtk.GLArea):

    def __init__(self, offset):
        super().__init__()
        self.offset = offset
        self.ctx: Optional[moderngl.Context] = None
        self.shader: Optional[moderngl.Program] = None
        self.vbo: Optional[moderngl.Buffer] = None
        self.vao: Optional[moderngl.VertexArray] = None
        self.checkbox: Optional[Gtk.CheckButton] = None

    def do_realize(self):
        Gtk.GLArea.do_realize(self)
        self.make_current()
        self.ctx = moderngl.get_context()
        #self.ctx = moderngl.create_context()

    def do_resize(self, width: int, height: int):
        Gtk.GLArea.do_resize(self, width, height)
        self.ctx.detect_framebuffer().use()

    def do_unrealize(self):
        self.ctx = None
        Gtk.GLArea.do_unrealize(self)

    def do_render(self, context: Gdk.GLContext) -> bool:
        print(self.ctx, self.ctx.viewport, self.ctx.fbo.glo)
        print(context)

        if self.checkbox is not None and self.checkbox.props.active:
            self.ctx.clear(0, 1, 0, 1)
        else:
            self.ctx.clear(0.25, 0, 0, 1)

        if self.shader is None:
            self.shader = self.ctx.program(
                vertex_shader='''
                    #version 330
                    in vec2 in_vert;
                    in vec3 in_color;
                    out vec3 v_color;
                    void main() {
                        gl_Position = vec4(in_vert, 0.0, 1.0);
                        v_color = in_color;
                    }
                ''',
                fragment_shader='''
                    #version 330
                    in vec3 v_color;
                    out vec4 f_color;
                    void main() {
                        f_color = vec4(v_color, 1.0);
                    }
                ''')

        if self.vbo is None:
            self.vbo = self.ctx.buffer(struct.Struct("@" + "fffff" * 3).pack( *[
                # x, y, red, green, blue
                 self.offset,      0.9, 1.0, 0.0, 0.0,
                 self.offset-0.9, -0.9, 0.0, 1.0, 0.0,
                 self.offset+0.9, -0.9, 0.0, 0.0, 1.0,
                # Note: (0, 0) is center, +Y is up, +x is right, from -1 to +1
            ]))

        if self.vao is None:
            self.vao = self.ctx.vertex_array(self.shader, self.vbo, 'in_vert', 'in_color')

        self.vao.render()

        return False

def on_activate(app: Gtk.Application):
    win = Gtk.ApplicationWindow(application=app)
    box = Gtk.Box.new(Gtk.Orientation.VERTICAL, 0)

    area1 = ModernGLArea(-.5)
    area1.props.hexpand = True
    area1.props.vexpand = True
    area1.set_size_request(100,100)
    box.append(area1)

    checkbox1 = Gtk.CheckButton.new_with_label("Some example widget 1")
    checkbox1.connect('notify::active', lambda obj, prop: area1.queue_draw())
    box.append(checkbox1)
    area1.checkbox = checkbox1

    area2 = ModernGLArea(0)
    area2.props.hexpand = True
    area2.props.vexpand = True
    area2.set_size_request(100,100)
    box.append(area2)

    checkbox2 = Gtk.CheckButton.new_with_label("Some example widget 2")
    checkbox2.connect('notify::active', lambda obj, prop: area2.queue_draw())
    box.append(checkbox2)
    area2.checkbox = checkbox2

    area3 = ModernGLArea(.5)
    area3.props.hexpand = True
    area3.props.vexpand = True
    area3.set_size_request(100,100)
    box.append(area3)

    checkbox3 = Gtk.CheckButton.new_with_label("Some example widget 3")
    checkbox3.connect('notify::active', lambda obj, prop: area3.queue_draw())
    box.append(checkbox3)
    area3.checkbox = checkbox3

    win.set_child(box)
    win.present()

app = Gtk.Application()
app.connect('activate', on_activate)
app.run(sys.argv)
```
</details>

**Comment by compik710** [comment]
@coz-eduardo-hernandez Ok, add `moderngl.init_context()` before `moderngl.get_context()`. I completely forgot about the need to switch.

**Comment by coz-eduardo-hernandez** [comment]
> @coz-eduardo-hernandez Ok, add `moderngl.init_context()` before `ctx = moderngl.get_context()`. I completely forgot about the need to switch.

Perfect, thank you so much. I guess that's something else to add to the docs

I haven't really checked specifically the GC but I have not gotten any memory issues recently. I'm just freeing some objects I create per frame, but the way GTK4 works it only renders when requested or the screen gets dirty. Either way, since you can always manage memory yourself and it's expected that there are cases the GC won't cover I'm satisfied

So I'll just close this issue

**Comment by coz-eduardo-hernandez** [comment]
> @coz-eduardo-hernandez Ok, add `moderngl.init_context()` before `ctx = moderngl.get_context()`. I completely forgot about the need to switch.

Perfect, thank you so much. I guess that's something else to add to the docs

I haven't really checked specifically the GC but I have not gotten any memory issues recently. I'm just freeing some objects I create per frame, but the way GTK4 works it only renders when requested or the screen gets dirty. Either way, since you can always manage memory yourself and it's expected that there are cases the GC won't cover I'm satisfied

So I'll just close this issue
