### ISSUE TITLE
moderngl with pygame-ce fps drop

### ISSUE THREAD

**Issue by solaymanehimite** [moderngl/moderngl#688]
i'am running a game using pygame-ce and moderngl for shaders, it works fine at 60 fps but after around 30-40 seconds it drops to 20 fps
removing the shaders dosen't help.

specs:
HP probook 4520s
cpu: intel i3
gpu: ATI mobility radeon hd 4500 series

https://github.com/moderngl/moderngl/assets/144042052/f4921ca4-1aff-45da-ada6-5912e969f59a

**Comment by solaymanehimite** [comment]
nevermind frogot frame_texture.release()

**Comment by einarf** [comment]
> nevermind frogot frame_texture.release()

Why don't you just make the texture once and `.write()` in the new contents pre frame? Making opengl resoruces per frame is an anti-pattern and should be avoided.

**Comment by szabolcsdombi** [comment]
They follow this tutorial: https://www.youtube.com/watch?v=LFbePt8i0DI
Which is correct. Create and Release allows the GPU to discard the previous frame's texture anytime.
Write needs to check if the texture is being used. I think there is no performance benefits of using either method. Imgui does this trick for the buffers.
