### ISSUE TITLE
Release 5.11.0 broken

### ISSUE THREAD

**Issue by debug-richard** [moderngl/moderngl#700]
Version 5.11.0 was released on pypi.org on August 10:   
https://pypi.org/project/moderngl/#history

Since an import failed, I tried to check the changelog/release page, but couldn't find anything.

Is this an "accidental" release?

**Comment by szabolcsdombi** [comment]
if you are using moderngl headlessly please `pip install moderngl[headless]` instead
or `pip install glwindow` independently

**Comment by debug-richard** [comment]
The error is `ModuleNotFoundError: No module named 'glcontext'`.  
I just saw that 5.11.1 fixed it.  
Thank you!
