### ISSUE TITLE
Add support for Other Python GUI toolkits

### ISSUE THREAD

**Issue by belalmedhat** [moderngl/moderngl#84]
Hi, 
Can the development team please add support for Python GUI toolkits like 
Tkinter
Wxwidgets

These two toolkits work well on Linux osx, Mac osx, Windows.
So if ModernGL supports tk and wxpython, I can develop a scientific app like molecular viewer using Python 3.4 and ModernGL for OpenGL 4.5 rendering.

Thank you for your efforts in this project

**Comment by cprogrammer1994** [comment]
The `Tkinter` have a `togl` and instead of using `OpenGL` one could use `ModernGL`
The `wxwidgets` for python is called `wxPython` and it is not properly uploaded to [PyPI](https://pypi.python.org/pypi/wxPython/2.9.1.1).

On what OS should be tested?

**Comment by belalmedhat** [comment]
Hi,
First Thank you for replying, 

The Tkinter has TOGL so ModernGL can easily add support for Tkinter, The Wxpython Project has a canvas for OpenGL called wx.glcanvas which worked very well with PyOpenGL. but if you entered their website you will find that they are inactive since 2014, however there is a new implementation of WxPython which is called WxPython/Phoniex https://github.com/wxWidgets/Phoenix
https://wxpython.org/Phoenix/docs/html/index.html
and they also have made a canvas for OpenGL with the same name wx.glcanvas 
https://wxpython.org/Phoenix/docs/html/wx.glcanvas.1moduleindex.html
If you added support for the new WxPython Implementation it will work on Windows/Mac OSX/ Linux  

Why you should add support for Tkinter and WxPython/Phoniex? 
Because PyQT and PySide has two software Licences, So If I want to Write a Cross Platform Molecular viewer Using Python + PyQT I will have to Pay Money for a license or publish the source code. On the Other hand using WxPython and Tkinter for development is For Free. You can publish the source code of your software and offer support or extra features for sale.

WxPython/Phoniex and Tkinter Works very well on all operating systems 

Look at the PyOpenGL 
PyOpenGL is interoperable with a large number of external GUI libraries for Python including (but not limited to):

    wxPython
    PyGame
    PyQt and PySide
    PyGTK
    Raw XLib
    OSMesa
    Raspberry Pi BCM
    Tkinter (if you have installed the Togl widget for Tk)

PyOpenGL doesn't support OpenGL 4.5 OpenGL ES 3.2 3.3 Like ModernGL 

So to attract More users to ModernGL and to Replace PyOpenGL Please Add Support for Wxwidgets and Tkinter 

Look at what is Built on PyOpenGL 
http://gr-framework.org/
http://docs.enthought.com/mayavi/mayavi/index.html
http://www.vtk.org/

mayavi works on WxPython
VTK works on Tkinter WxPython and PyQT

ModernGL should work on PyQT Tkinter WxPython/Phoniex on Windows 7 8 8.1 10  Mac os X > 10.5  and Linux distros 

You can test on Windows 8.1, Ubuntu 16.04, Mac os X el Captian

Sorry for the long answer 
I hope to help you ModernGL is so important to the Python Scientific Stack and to Python Games.

**Comment by belalmedhat** [comment]
I can Help In testing
Just give me Hello ModernGL .py Program and I can test it on Ubuntu 15.10/16.04 and on Windows 8.1 Pro and on Windows 7 Pro. Sadly I don't have a MAC.
Give me ModernGL Hello.py and I can test it on the above OS using Tkinter WxPython/Phoniex  after you add the support for them.

**Comment by cprogrammer1994** [comment]
```
d:\Programming\Phoenix>git submodule init
Submodule 'ext/wxWidgets' (https://github.com/wxWidgets/wxWidgets.git) registered for path 'ext/wxWidgets'

d:\Programming\Phoenix>git submodule update
Cloning into 'D:/Programming/Phoenix/ext/wxWidgets'...
fatal: index-pack failed
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?
```

I will raise an issue maybe the link is broken.

---

The **togl** seems to be deprecated:
> Note that Togl support is deprecated, it's there for legacy code (once you compile Togl), but you should choose a GUI library that has OpenGL support built-in for any new development.  Togl support has been dropped due to the complexity of compilation and the headache of maintenance.  There are projects which attempt to provide Togl support, feel free to install those into your Python's Tk installation if you need Togl under Python.

But I will try to solve this. What I did so far:
- Installed **PyOpenGL** and  **[glglue](https://pypi.python.org/pypi/glglue)**
- Placed the binaries in the proper folder.
- Run the example from the **glglue** docs
- Got an error on both 32 and 64 bit (tested on Windows)
```
_tkinter.TclError: couldn't load library "c:/.../Python35-.../tcl/Togl2.0/Togl20.dll": invalid argument
```

---

Do you have a working OpenGL example using **tkinter** and **togl**?

---

**Side Note:**
> You may try to replace the `gl` calls with ModernGL calls. It should work fine.
> The `ModernGL.Init()` method should be called within a valid OpenGL context. _(where you can call `gl` methods)_

**Comment by cprogrammer1994** [comment]
I prepared an [example](https://gist.github.com/cprogrammer1994/e76d6ef1132d1190fa9c09a0f0cf6f08) for `wx`.
Sorry I was not able to test it.
I will when I will get my `wx` properly installed.

**Comment by belalmedhat** [comment]
I'm Sorry, I feel that I'm stupid to request support for wxpython and tkinter. 
In fact i found that togl is deprecated, the last commit was made in 2008.
wxphoniex didn't decide when they will publish the next release.
Pyside is not maintained since QT 4.8

The only stable python gui is PyQT5  
I'm sorry you were right from the first. 
ModernGL support for PyQT5 is amazing.

The future GUI toolkits of Python are 
Pyqt5
Pyside2 which is built on qt5 with free license 
WxPhoniex

I don't know why great open source projects like wxwidgets phoniex tkinter pyopengl  gte deprecated and are not maintained. Even glglue is not maintained since 2013

You are a tough Developer you tried tkinter and wx.  Thank you for your effort and time. 
You can install Vmware free player on Windows and download/install Ubuntu linux / windows 7 / 8 / 8.1 / 10  for testing. 


I will test your wx example and i will try to find a fix for togl error. 
Thank you

**Comment by cprogrammer1994** [comment]
`wx` is not lost yet, I cannot properly clone the repo now due to a broken link in the `git submodules`.
Theoretically `ModernGL` can be used anywhere where `PyOpenGL` is capable of rendering.
The only difference is that, one have to call the `ModernGL.Init()` before any `ModernGL` calls.

**Comment by cprogrammer1994** [comment]
I just googled up **[Kivy](https://kivy.org)**. There will be at least one example for Kivy in the next week.

**Comment by cprogrammer1994** [comment]
b0e68b2 [Kivy Example](https://github.com/cprogrammer1994/ModernGL/blob/master/Examples/Kivy/01_HelloWorld.py)

**Comment by yxdragon** [comment]
@belalmedhat I wrote a toolkit like mayavi, using moderngl and wxphoenix, [Myvi](https://github.com/yxdragon/myvi)

**Comment by RenaKunisaki** [comment]
I've adapted the example to GTK (using pygobject), but all I get is a black window:

```python
#!/usr/bin/env python
import gi
gi.require_version('Gtk', '3.0'); from gi.repository import Gtk, Gdk, GLib
import moderngl
import numpy as np

vertex_shader='''
    #version 330
    in vec2 in_vert;
    in vec3 in_color;
    out vec3 v_color;    // Goes to the fragment shader
    void main() {
        gl_Position = vec4(in_vert, 0.0, 1.0);
        v_color = in_color;
    }
'''
fragment_shader='''
    #version 330
    in vec3 v_color;
    out vec4 f_color;
    void main() {
        // We're not interested in changing the alpha value
        f_color = vec4(v_color, 1.0);
    }
'''

vertices = np.array([
    # x, y, red, green, blue
     0.0,  0.8, 1.0, 0.0, 0.0,
    -0.6, -0.8, 0.0, 1.0, 0.0,
     0.6, -0.8, 0.0, 0.0, 1.0,
])

class MyGLArea(Gtk.GLArea):
    def __init__(self):
        self.ctx = None
        Gtk.GLArea.__init__(self)
        self.connect("realize", self.on_realize)
        self.connect("render",  self.on_render)

    def on_realize(self, area):
        ctx = self.get_context()
        self.make_current()
        self.ctx = moderngl.create_context(require=420)
        print("realized", ctx, "created", self.ctx)
        for k, v in self.ctx.info.items():
            print(k, v)
        print("version", self.ctx.version_code)

        self.ctx.viewport = (0, 0, 640, 480)

        self.prog = self.ctx.program(
            vertex_shader=vertex_shader,
            fragment_shader=fragment_shader)
        self.vbo = self.ctx.buffer(vertices.astype('f4').tobytes())

        # We control the 'in_vert' and `in_color' variables
        self.vao = self.ctx.simple_vertex_array(
            self.prog, self.vbo, 'in_vert', 'in_color')

        #self.fbo = self.ctx.simple_framebuffer((512, 512))
        #self.fbo.use()
        #self.fbo.clear(0.0, 0.5, 0.0, 1.0)
        print("init", self.get_error())

    def on_render(self, area, ctx):
        if not self.ctx:
            print("Render but no ctx")
            return
        #self.fbo.use()
        self.ctx.clear(0.0, 0.5, 0.0, 1.0)
        self.vao.render()
        print("rendered", self.get_error())
        return True

win = Gtk.Window()
win.connect('delete-event', Gtk.main_quit)
widget = MyGLArea()
win.add(widget)
GLib.timeout_add(50, lambda: widget.queue_draw())
win.show_all()
Gtk.main()
```

I might just be doing something wrong? GTK wants to create its own context.

**Comment by einarf** [comment]
Tried printing context info?

https://github.com/cprogrammer1994/ModernGL/blob/5278e0427d5b0b6101016da4289ab5ff2f0c7f8a/examples/window/base.py#L191-L198

I would also request at least a 3.3 context. Not sure what platform and drivers you are testing with.

**Comment by RenaKunisaki** [comment]
The output from those is:

```
GL_VENDOR Intel Open Source Technology Center
GL_RENDERER Mesa DRI Intel(R) Ivybridge Mobile 
GL_VERSION 4.2 (Core Profile) Mesa 18.3.4
GL_POINT_SIZE_RANGE (1.0, 255.0)
GL_SMOOTH_LINE_WIDTH_RANGE (1.0, 7.375)
GL_ALIASED_LINE_WIDTH_RANGE (1.0, 7.375)
GL_POINT_FADE_THRESHOLD_SIZE 1.0
GL_POINT_SIZE_GRANULARITY 1.0
GL_SMOOTH_LINE_WIDTH_GRANULARITY 0.125
GL_MIN_PROGRAM_TEXEL_OFFSET -8.0
GL_MAX_PROGRAM_TEXEL_OFFSET 7.0
GL_MINOR_VERSION 2
GL_MAJOR_VERSION 4
GL_SAMPLE_BUFFERS 0
GL_SUBPIXEL_BITS 4
GL_CONTEXT_PROFILE_MASK 1
GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT 32
GL_DOUBLEBUFFER True
GL_STEREO False
GL_MAX_VIEWPORT_DIMS (32768, 32768)
GL_MAX_3D_TEXTURE_SIZE 2048
GL_MAX_ARRAY_TEXTURE_LAYERS 2048
GL_MAX_CLIP_DISTANCES 8
GL_MAX_COLOR_ATTACHMENTS 8
GL_MAX_COLOR_TEXTURE_SAMPLES 8
GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS 245760
GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS 245760
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 96
GL_MAX_COMBINED_UNIFORM_BLOCKS 84
GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS 245760
GL_MAX_CUBE_MAP_TEXTURE_SIZE 16384
GL_MAX_DEPTH_TEXTURE_SAMPLES 8
GL_MAX_DRAW_BUFFERS 8
GL_MAX_DUAL_SOURCE_DRAW_BUFFERS 1
GL_MAX_ELEMENTS_INDICES 3000
GL_MAX_ELEMENTS_VERTICES 3000
GL_MAX_FRAGMENT_INPUT_COMPONENTS 128
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS 16384
GL_MAX_FRAGMENT_UNIFORM_VECTORS 4096
GL_MAX_FRAGMENT_UNIFORM_BLOCKS 14
GL_MAX_GEOMETRY_INPUT_COMPONENTS 64
GL_MAX_GEOMETRY_OUTPUT_COMPONENTS 128
GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS 16
GL_MAX_GEOMETRY_UNIFORM_BLOCKS 14
GL_MAX_GEOMETRY_UNIFORM_COMPONENTS 16384
GL_MAX_INTEGER_SAMPLES 8
GL_MAX_SAMPLES 8
GL_MAX_RECTANGLE_TEXTURE_SIZE 16384
GL_MAX_RENDERBUFFER_SIZE 16384
GL_MAX_SAMPLE_MASK_WORDS 1
GL_MAX_SERVER_WAIT_TIMEOUT 9223372034707292159
GL_MAX_TEXTURE_BUFFER_SIZE 134217728
GL_MAX_TEXTURE_IMAGE_UNITS 16
GL_MAX_TEXTURE_LOD_BIAS 15
GL_MAX_TEXTURE_SIZE 16384
GL_MAX_UNIFORM_BUFFER_BINDINGS 84
GL_MAX_UNIFORM_BLOCK_SIZE 65536
GL_MAX_VARYING_COMPONENTS 128
GL_MAX_VARYING_VECTORS 32
GL_MAX_VARYING_FLOATS 128
GL_MAX_VERTEX_ATTRIBS 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 16
GL_MAX_VERTEX_UNIFORM_COMPONENTS 16384
GL_MAX_VERTEX_UNIFORM_VECTORS 4096
GL_MAX_VERTEX_OUTPUT_COMPONENTS 128
GL_MAX_VERTEX_UNIFORM_BLOCKS 14
GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET 2047
GL_MAX_VERTEX_ATTRIB_BINDINGS 16
GL_VIEWPORT_BOUNDS_RANGE (-32768, 32768)
GL_VIEWPORT_SUBPIXEL_BITS 8
GL_MAX_VIEWPORTS 16
GL_MIN_MAP_BUFFER_ALIGNMENT 64
GL_MAX_COMBINED_ATOMIC_COUNTERS 4096
GL_MAX_FRAGMENT_ATOMIC_COUNTERS 4096
GL_MAX_GEOMETRY_ATOMIC_COUNTERS 4096
GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS 4096
GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS 4096
GL_MAX_VERTEX_ATOMIC_COUNTERS 4096
```

`self.get_context()` is `gtk_gl_area_get_context()`, I can't be certain what happens in there, but I think it just returns a `GdkGLContext` member from the class.

420 seems to be the highest supported version on my system. 330 doesn't make any difference.

Should I open a separate issue for this?

**Comment by einarf** [comment]
Looks like ModernGL finds a context just fine. The `code` parameter is just for checking for a minimum gl version, so the 4.2 context you are getting is all fine.

Maybe some more digging in gtk docs and here?: https://github.com/cprogrammer1994/ModernGL/blob/master/src/GLContext.cpp

**Comment by RenaKunisaki** [comment]
Well I found I can use the `create-context` event to request a version, and if I ask for one that's not supported I do get errors, so that's working at least. Still, no errors but no display with the current code.

This is on Linux, if that matters.

```python
#!/usr/bin/env python
import gi
gi.require_version('Gtk', '3.0'); from gi.repository import Gtk, Gdk, GLib
import moderngl
import numpy as np

vertex_shader='''
    #version 330
    in vec2 in_vert;
    in vec3 in_color;
    out vec3 v_color;
    void main() {
        gl_Position = vec4(in_vert, 0.0, 1.0);
        v_color = in_color;
    }
'''
fragment_shader='''
    #version 330
    in vec3 v_color;
    out vec4 f_color;
    void main() {
        f_color = vec4(v_color, 1.0);
    }
'''

vertices = np.array([
    # x, y, red, green, blue
     0.0,  0.8, 1.0, 0.0, 0.0,
    -0.6, -0.8, 0.0, 1.0, 0.0,
     0.6, -0.8, 0.0, 0.0, 1.0,
])

class MyGLArea(Gtk.GLArea):
    def __init__(self):
        self.ctx = None
        Gtk.GLArea.__init__(self)
        self.connect("create-context", self.on_create_context)
        self.connect("realize", self.on_realize)
        self.connect("render",  self.on_render)

    def on_create_context(self, area):
        ctx = self.get_window().create_gl_context()
        # this is weird. requesting version (3, 20) fails,
        # but (4, 0) succeeds. (3, 0) fails because it's less
        # than the minimum version for GdkGl.
        # I think it treats (3, 2) as the same as 3.20, which
        # is wrong for version numbers...
        ctx.set_required_version(4, 0)
        ctx.set_debug_enabled(True)
        #ctx.set_use_es(1) # 1=yes 0=no -1=auto
        print("ctx realize:", ctx.realize())
        return ctx

    def on_realize(self, area):
        self.make_current()
        self.ctx = moderngl.create_context()
        for k, v in self.ctx.info.items():
            print(k, v)
        print("version", self.ctx.version_code)

        self.ctx.viewport = (0, 0, 640, 480)
        self.prog = self.ctx.program(
            vertex_shader=vertex_shader,
            fragment_shader=fragment_shader)
        self.vbo = self.ctx.buffer(vertices.astype('f4').tobytes())

        # We control the 'in_vert' and `in_color' variables
        self.vao = self.ctx.simple_vertex_array(
            self.prog, self.vbo, 'in_vert', 'in_color')

        #self.fbo = self.ctx.simple_framebuffer((512, 512))
        #self.fbo.use()
        #self.fbo.clear(0.0, 0.5, 0.0, 1.0)
        print("init error:", self.get_error())

    def on_render(self, area, ctx):
        if not self.ctx:
            print("Render but no ctx")
            return
        #self.fbo.use()
        self.ctx.clear(0.0, 0.5, 0.0, 1.0)
        self.vao.render()
        print("render error:", self.get_error())
        return True

win = Gtk.Window()
win.connect('delete-event', Gtk.main_quit)
widget = MyGLArea()
win.add(widget)
GLib.timeout_add(50, lambda: widget.queue_draw())
win.show_all()
Gtk.main()
```

**Comment by einarf** [comment]
There are a things I find odd with your current class:
* `Gtk.GLArea.__init__(self)` .. shoudn't this be `super().__init__()?
* I would assume `GLArea` creates it's own context already, so maybe you end up creating an additional one that is not really displayed by the widget?
* Does calling `make_current` make a difference if called in the beginning of `on_render`.

Not sure about this because the docs are a bit vague and there are so many different and weird examples out there.

Do to also have four working window example now: https://github.com/cprogrammer1994/ModernGL/tree/master/examples/window

**Comment by RenaKunisaki** [comment]
I'm not sure why Gobject examples use that style instead of just `super().__init__()`. I think it's because they were made when `super` didn't have the same behaviour with composite classes. I've changed that, and it doesn't seem to have made any difference. The initializer indeed takes no arguments; GTK tends to use properties instead.

The `create-context` signal is supposed to be responsible for setting up the context. (https://developer.gnome.org/gtk3/stable/GtkGLArea.html#GtkGLArea-create-context) I don't doubt there's something funny happening with the distinction between GL context, `GdkGLContext`, and ModernGL context.

`make_current` is supposed to make that context the active one. It's already called for you before `on_render`. I added a call just in case, but no difference.

If there is a way to swap buffers, I haven't seen it. The examples I've found only call `glFlush()` when finished rendering.

**Comment by RenaKunisaki** [comment]
Maybe the problem has to do with https://developer.gnome.org/gtk3/stable/GtkGLArea.html#GtkGLArea.description :

> GtkGLArea sets up its own GdkGLContext for the window it creates, and creates a custom GL framebuffer that the widget will do GL rendering onto. It also ensures that this framebuffer is the default GL rendering target when rendering.

I'm not sure how to go about switching ModernGL to use that framebuffer (or GTK to another framebuffer).

(I did also add `self.ctx.finish()` to the end of `on_render`, with no effect.)

**Comment by einarf** [comment]
ModernGL should pick up the context that was last set to current by `glXMakeCurrent` at least. That's maybe something to look at.

https://github.com/cprogrammer1994/ModernGL/blob/5278e0427d5b0b6101016da4289ab5ff2f0c7f8a/src/GLContext.cpp#L571-L601

the context is the inspected... 

https://github.com/cprogrammer1994/ModernGL/blob/fbad70fa9db09edbf9e98b4ac8855efc60c642a3/src/Context.cpp#L1329-L1433

and a framebuffer is detected..

https://github.com/cprogrammer1994/ModernGL/blob/fbad70fa9db09edbf9e98b4ac8855efc60c642a3/src/Context.cpp#L277-L400

**Comment by RenaKunisaki** [comment]
Well, the solution seems to be to simply, albeit counterintuitively, not use GtkGlArea; instead just use GtkDrawingArea which doesn't create its own framebuffer.

```python
#!/usr/bin/env python
import gi
gi.require_version('Gtk', '3.0'); from gi.repository import Gtk, Gdk, GLib
import moderngl
import numpy as np
import OpenGL
from OpenGL.GL import *

vertex_shader='''
    #version 330
    in vec2 in_vert;
    in vec3 in_color;
    out vec3 v_color;
    void main() {
        gl_Position = vec4(in_vert, 0.0, 1.0);
        v_color = in_color;
    }
'''
fragment_shader='''
    #version 330
    in vec3 v_color;
    out vec4 f_color;
    void main() {
        f_color = vec4(v_color, 1.0);
    }
'''

vertices = np.array([
    # x, y, red, green, blue
     0.0,  0.8, 1.0, 0.0, 0.0,
    -0.6, -0.8, 0.0, 1.0, 0.0,
     0.6, -0.8, 0.0, 0.0, 1.0,
])

class MyGLArea(Gtk.DrawingArea):
    def __init__(self):
        self.ctx = None
        super().__init__()
        self.connect("realize", self.on_realize)
        self.connect("draw",    self.on_draw)

    def on_realize(self, area):
        ctx = self.get_window().create_gl_context()
        ctx.set_required_version(4, 0)
        ctx.set_debug_enabled(True)
        ctx.set_use_es(0) # 1=yes 0=no -1=auto
        print("ctx realize:", ctx.realize())
        ctx.make_current()
        # keep a reference to this so that it isn't garbage collected,
        # or else we segfault.
        self._gtk_ctx = ctx

        self.ctx = moderngl.create_context()
        for k, v in self.ctx.info.items(): # dump info
            print(k, v)
        print("version", self.ctx.version_code)

        # set up viewport and program
        self.ctx.viewport = (0, 0, 640, 480)
        self.prog = self.ctx.program(
            vertex_shader=vertex_shader,
            fragment_shader=fragment_shader)
        self.vbo = self.ctx.buffer(vertices.astype('f4').tobytes())

        # We control the 'in_vert' and `in_color' variables
        self.vao = self.ctx.simple_vertex_array(
            self.prog, self.vbo, 'in_vert', 'in_color')

        #self.fbo = self.ctx.simple_framebuffer((512, 512))
        #self.fbo.use()
        #self.fbo.clear(0.0, 0.5, 0.0, 1.0)

    def on_draw(self, area, cr):
        if not self.ctx:
            print("Render but no ctx")
            return
        self.ctx.clear(0.0, 0.5, 0.5, 1.0)
        self.vao.render()
        #self.ctx.finish()
        return True

win = Gtk.Window()
win.connect('delete-event', Gtk.main_quit)
widget = MyGLArea()
win.add(widget)
GLib.timeout_add(50, lambda: widget.queue_draw())
win.show_all()
Gtk.main()
```

I'm not sure this is exactly how it should look, but I see colours now: 
![2019-03-02-162029_209x205_scrot](https://user-images.githubusercontent.com/1185585/53687793-de49fe00-3d06-11e9-9efb-c723ee9072d2.png)

**Comment by Harvie** [comment]
We have Tkiner app (https://github.com/vlachoudis/bCNC/issues/591), which is slow, because it manualy updates Tkinter Canvas. Once it draws hundreds of lines, it gets almost unusable.

I would really like to have some way of speeding it up using moderngl... Idealy if it was possible to just load 3D lines to moderngl and let it handle pan, zoom, tilt, 3D rotation, etc. Because using python loops is very slow. Also i need displayed objects to be clickable.

Do you think this is possible?

**Comment by yxdragon** [comment]
@Harvie dose this fit you? [myvi](https://github.com/yxdragon/myvi), Now it is OK under linux, mac, windows. (Thanks for @cprogrammer1994 's advice, add the glcanvas.WX_GL_CORE_PROFILE to attr list) Myvi has a core manager, an util to generate geometry model, a wx canvas treat the interaction (right key drag to adjust view, right key adjust to adjust light direction, and we can set background color, light force, scatter light, set every object's color and mesh/frame). If it fits you, you can write a tk/qt ui to implement the manager's interface.
