### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#99]
- ModernGL by itself
- ModernGL compared to PyOpenGL

**Comment by einarf** [comment]
I'm done rewriting `demosys-py` to ModernGL now and I can report a pretty nice performance increase of my test scene (gltf buggy scene). The speed increase in OS X was 2.5x (compared to pyopengl) just drawing the scene (~200 nodes) the naive way setting every single uniform for each mesh and calling render. This is with a 2013 macbook pro 2.7Ghz 650M.

Will test on windows in a bit.

**Comment by einarf** [comment]
Performance increase was 3x for the same scene on windows bringing the performance much closer to OS X and Linux. Moved from 15 fps around 48.

**Comment by einarf** [comment]
Another observation about performance:

Matrix math in python is not fast enough for real time rendering when you traverse a scene graph drawing lots of nodes. Using the buggy GLTF scene I was around ~50 FPS when moving to ModernGL (from ~15 with PyOpenGL).

I tried to optimize in a few steps:

1) Pre-calculate node matrices from the root and down storing ``f4`` byte data ready for uniforms. This means one matrix multiplication less per node.
2) Send in a separate camera matrix in the ``draw`` method passing it to the shader
3) calculate MVP in vertex shader ``camera_matrix * view_matrix``
4) Ensure the projection matrix is ready as ``bytes``

Most of this is mainly to reduce memory allocations. Every matrix operation creates one or multiple new ``ndarrays`` and is further converted to ``bytes``.

This boosted the FPS from ~50 to ~175 on my 5 year old laptop. On my beefy windows desktop this runs at 600+ fps now (from ~50)

The downside is that really large VAOs (3M+ triangles) renders significantly slower on older hardware.

There's definitely room for a low level matrix library or something that supports the most basic operations like ``glm``.

**Comment by cprogrammer1994** [comment]
> Matrix math in python is not fast enough for real time rendering when you traverse a scene graph drawing lots of nodes.

I have an experimental module targeting this issue: http://miniglm.readthedocs.io/en/latest/

There are some benchmarks already available.
I was working/testing on windows.

I want to extend this module to support `memoryview` `np.frombuffer` ...
miniglm lacks the ability to directly access numpy arrays from C++

**Comment by einarf** [comment]
Nice! Auto star + follow on that!
